import Erdos390.Full.ContinuumManyLowArithmeticGaugeOrdinary

#print axioms Erdos390.Full.ContinuumCellGraph.ArithmeticGaugeOrdinary.weightedGaugeProjection_norm_le_of_scaled_moment_ratio
#print axioms Erdos390.Full.ContinuumCellGraph.ArithmeticGaugeOrdinary.weightedGaugeProjection_sub_self_norm_le_of_rawWeightDefect
#print axioms Erdos390.Full.ContinuumCellGraph.ArithmeticGaugeOrdinary.IntervalMesh.ordinary_split_arithmetic_projected_raw_bound
