import Erdos390.Full.PaperExactTwoStageTargetSolve

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.bandDPairing_projectedNormalizedTargetBand
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.inner_mainRawSlow_symm_normalizedTarget
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.inner_exactSchurCovarianceOperator_bilinear
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandSchur_fastGauge_eq_projectedTarget
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.fastGauge_eq_inverse_projectedTarget
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.vectorScore_exactSchurResidual_compensatedMainDirection
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.compensatedNormalizedTarget_eq_slow_sub_bandDPairing
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_compensatedNormalizedTarget_le_of_regression_target
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.slow_div_mul_actualTwoStageCompensatedVariance
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.slow_div_eq_compensatedTarget_div_variance
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.fastGauge_paperSharpNorm_le_of_inverse
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_slow_div_le_of_variance_target_bounds
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.effectivePrimeVelocity_norm_le_of_fast_compensated
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.targetFastNuisanceCoefficient_norm_le_of_covarianceVector
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualTwoStageNuisanceCoefficient_norm_le_of_covarianceVector
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exactNuisanceRegression_eq_targetFast_add_twoStage
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exactNuisanceRegression_norm_le_of_twoStage
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exactSchur_solution_component_bounds_of_twoStageTargets
