import Erdos390.Full.PaperExactTwoStageOrdinaryFast

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.sharpBandWeightTotal_eq_centerEnergy
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.sum_harmonicMass_eq_bandReciprocalSum
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_normalizedTargetBandRow_le_of_envelopes
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_normalizedTarget_slow_le_of_envelopes
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.projectRawBandVector_norm_le_of_moment_ratio
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.projectedNormalizedTargetBand_norm_le_of_envelopes
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.projectedNormalizedTargetBand_norm_le_of_envelopes_and_energy
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceCovarianceVector_rawBandRegression_norm_le_of_marked
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.targetFast_nuisanceCovarianceVector_norm_le_of_marked_ordinary
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.twoStage_nuisanceCovarianceRows_le_of_marked
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.twoStage_nuisanceCovarianceRows_le_halfReserves
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_bandDPairing_le_sharp_mul_raw
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.fastGauge_norm_le_of_ordinary_inverse
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_compensatedNormalizedTarget_le_of_regression_ordinaryTarget
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.effectivePrimeVelocity_norm_le_of_ordinaryFast_compensated
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exactSchur_solution_component_bounds_of_ordinaryFast_twoStageTargets
