import Erdos390.Full.PaperFixedIntervalNuisanceSchur
import Erdos390.Full.PaperNuisancePrimeLogRows
import Erdos390.Full.PaperBridgeNuisanceTiltFallback
import Erdos390.Full.PaperBridgePhysicalValuationRow
import Erdos390.Full.PaperActualLemma86NuisanceProfileAssembly

/-! Kernel-axiom audit for the recent exact Lemma 8.6 attachments. -/

#print axioms Erdos390.Full.FiniteProbability.abs_sigmaMixture_covariance_tagFunction_le_of_common_expect
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.primeLogScore_eq_explicit_physical_add_head
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedBandCovarianceRow_inner_nuisance_eq_exactHeadPrimes
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_normalizedBandCovarianceRow_headFunction_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.headFunctionScore_centeredHeadTagFunction
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_tiltedLaw_covariance_nuisanceHead_le_of_pairwise_cell_expect
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_tiltedLaw_covariance_nuisanceCoord_le_of_pairwise_cell_expect
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_tiltedLaw_covariance_le_of_cell_covariance_and_pairwise_expect
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_fullTiltCell_expect_valuation_sub_other_of_power_profiles
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceMarkedRows_le_of_pairwise_cell_valuation_and_physical
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceMarkedRows_le_of_cell_physical_covariance_and_pairwise_valuation
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceCovarianceVector_postBand_norm_le_of_pairwise_cells
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_cellPhysicalTiltScore_le_fixedIntervals
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.hasCovarianceGap_of_fixedIntervals_schur_and_l1
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.cellMediumLaw_expect_valuation_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.tiltedLaw_expect_valuation_le_of_cellMedium
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_tiltedLaw_covariance_nuisanceCoord_le_of_expect
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_nuisanceStatistic_apply_le_fixedIntervals
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_tiltedLaw_covariance_nuisance_valuation_le_of_guardCensus
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_tiltedLaw_covariance_nuisance_valuation_le_explicit
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceMarkedRows_le_explicit
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_guardedCell_fullTilt_expect_valuation_sub_medium_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_guardedCell_fullTilt_expect_valuation_sub_other_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_guardedCell_fullTilt_covariance_valuation_physical_le_of_medium
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.fullTiltCellProfiles_of_medium_stieltjes
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_variance_bounds_of_squarefree_and_pairwise_cells
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_markedRow_bound_of_squarefree_and_pairwise_cells
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_variance_bounds_of_squarefree_and_cell_profiles
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_markedRow_bound_of_squarefree_and_cell_profiles
