import Erdos390.Full.PaperCanonicalPrimeGraphActualSchurSolutionEventuallyStatementAudit

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.paperSharpNorm_le_iff_abs_coordinate_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_unique_actualBandSchur_sharp_solution_of_equiv
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_fineMesh_cutoff_eventually_unique_actualBandSchur_sharp_solution
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_fineMesh_cutoff_eventually_actualBandSchur_coordinate_solution
