import Erdos390.Full.PaperCanonicalActualSchurSharpOrdinaryEventually

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_paperFineMesh_cutoff_eventually_actualBandSchur_sameEquiv_sharp_and_ordinary
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_cutoff_eventually_canonical_ordinary_perturbation_rows
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_paperFineMesh_cutoff_eventually_canonical_momentRatio
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_paperFineMesh_cutoff_eventually_actualBandSchur_sameEquiv_sharp_and_ordinary_of_endpoint_inputs
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandSchur_sameEquiv_ordinary_inverse_of_partition_eq_endpoint_reference
#print axioms Erdos390.Full.RegularMeshPrimeCutoffs.Mesh.one_div_64_le_centerEnergy_of_canonical_anchor
