import Erdos390.Full.PaperActualFullOrdinaryProjectionConnector

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandFullLinearMap_eq_projectedFullBandRow
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandFull_sub_projectedReference_norm_le_ordinary
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandFull_sub_projectedReference_norm_le_of_rows_ordinary
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.projectRawBandVector_referenceBandRow_eq_projectedRawLinearMap
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandFull_sub_projectedArithmeticRaw_norm_le_of_rows_ordinary
