import Erdos390.Full.PaperCanonicalSlowKappa

/-! Statement audit for the fixed canonical slow-direction gap. -/

#check Erdos390.Full.PaperCanonicalSlowKappa.canonicalSlowKappa_pos
#check Erdos390.Full.PaperCanonicalSlowKappa.canonicalSlowKappa_gap
#check Erdos390.Full.PaperCanonicalSlowKappa.canonicalSlowKappa_primeDirichlet_anchor_lower
#check Erdos390.Full.PaperCanonicalSlowKappa.canonicalSlowKappa_primeReference_compensated_lower
#check Erdos390.Full.PaperBridgeFit.BridgeData.actualSquarefree_compensated_lower_canonicalKappa_of_profiles
#check Erdos390.Full.PaperBridgeFit.BridgeData.actualSquarefree_relative_lower_canonicalKappa_of_profiles
