import Erdos390.Full.PaperCanonicalActiveMassBaseline
import Mathlib.Util.AssertNoSorry

/-! Axiom and proof-term audit for the active-mass baseline variant. -/

#print axioms Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline
#print axioms Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_totalMass
#print axioms Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_normalizedCellMass
#print axioms Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_baseWeight
#print axioms Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_baseWeight_sum
#print axioms Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_ne_baseline_of_ne_one
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.q_eq_of_baseline_eq_activeMassBaseline
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.paperMoment_physicalScore_zero_eq_activeMass_mul_mu
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.paperMoment_physicalScore_zero_eq_reserveActiveMass_mul_mu

assert_no_sorry Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline
assert_no_sorry Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_totalMass
assert_no_sorry Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_normalizedCellMass
assert_no_sorry Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_baseWeight
assert_no_sorry Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_baseWeight_sum
assert_no_sorry Erdos390.Full.PaperGuardCensus.BarycentricTarget.activeMassBaseline_ne_baseline_of_ne_one
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.q_eq_of_baseline_eq_activeMassBaseline
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.paperMoment_physicalScore_zero_eq_activeMass_mul_mu
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.paperMoment_physicalScore_zero_eq_reserveActiveMass_mul_mu
