import Erdos390.Full.PaperActualLemma86Assembly

#print axioms Erdos390.Full.ArithmeticBandGeometry.Partition.compensatedCoefficient_three_bounds
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceCoefficientOfScore_norm_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceRegressionLoss_bounds
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.covariance_marked_nuisanceScore_eq_inner
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceCovarianceVector_norm_le_sqrt_card_mul
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_covariance_nuisance_postBandPrimeScore_le_of_marked
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceCovarianceVector_postBand_norm_le_of_marked
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceCovarianceVector_postBand_norm_le_of_marked_and_l1
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualNuisanceCoefficient_markedRow_bound
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandRegression_normalEquation
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.projectRawBandVector_paperSharpNorm_le_two
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandRegressionTarget_sharpNorm_le_of_row
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandRegression_compensatedCoefficient_three_bounds
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualBandRegression_regularMesh_moment_and_coefficient_bounds
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualTwoStageCompensatedScore_orthogonal
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actual_primePower_relative_variance_bound
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actual_primePower_relative_markedRow_bound
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_variance_bounds_of_squarefree
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_variance_bounds_of_squarefree_and_coordinate_rows
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_variance_bounds_of_squarefree_and_marked_nuisance_rows
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_markedRow_bound_of_squarefree
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_markedRow_bound_of_squarefree_and_vector_rows
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_markedRow_bound_of_squarefree_and_coordinate_rows
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualCompensatedScore_markedRow_bound_of_squarefree_and_marked_nuisance_rows
