import Erdos390.Full.PaperProposition87ActiveMassTransport
import Mathlib.Util.AssertNoSorry

/-! Axiom audit for fixed and varying active-mass Proposition 8.7 transport. -/

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_sampleData
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_baseline
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_partition
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_lowBand
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_referenceHead
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_w
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_L
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_q
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.baseWeight_eq_activeMass_mul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.headBaselineMass_eq_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.statistic_eq_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.unnormalizedWeight_eq_activeMass_mul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.partition_eq_activeMass_mul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.probabilityMass_eq_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.covariance_eq_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.activeWeight_eq_activeMass_mul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.paperMoment_eq_activeMass_mul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.vectorMoment_eq_activeMass_smul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.jacobian_eq_activeMass_smul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.jacobian_apply_eq_activeMass_smul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.covarianceOperator_eq_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.targetVector_eq_activeMass_smul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedTarget_eq_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.hasTargetEnvelopes_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_baseWeight_le_div_log
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_q_le_of_activeMass_bound
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_initialMarkedRate
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.jacobian_isInvertible_iff_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.vectorField_eq_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.markedBandResidual_eq_activeMass_mul_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.hasPaperProposition87Conclusion_of_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.canonical_activeMass_proposition87_of_normalizedLawCompanion
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.canonical_proposition87_activeMassLiteralBandBalance
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.canonical_proposition87_varyingActiveMassLiteralBandBalance

assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_sampleData
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_baseline
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_partition
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_lowBand
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_referenceHead
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_w
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_L
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_q
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.baseWeight_eq_activeMass_mul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.headBaselineMass_eq_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.statistic_eq_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.unnormalizedWeight_eq_activeMass_mul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.partition_eq_activeMass_mul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.probabilityMass_eq_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.covariance_eq_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.activeWeight_eq_activeMass_mul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.paperMoment_eq_activeMass_mul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.vectorMoment_eq_activeMass_smul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.jacobian_eq_activeMass_smul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.jacobian_apply_eq_activeMass_smul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.covarianceOperator_eq_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.targetVector_eq_activeMass_smul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedTarget_eq_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.hasTargetEnvelopes_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_baseWeight_le_div_log
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_q_le_of_activeMass_bound
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.normalizedLawCompanion_initialMarkedRate
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.jacobian_isInvertible_iff_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.vectorField_eq_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.markedBandResidual_eq_activeMass_mul_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.hasPaperProposition87Conclusion_of_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.canonical_activeMass_proposition87_of_normalizedLawCompanion
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.canonical_proposition87_activeMassLiteralBandBalance
assert_no_sorry Erdos390.Full.PaperBridgeFit.BridgeData.canonical_proposition87_varyingActiveMassLiteralBandBalance
