import Erdos390.Full.PaperBridgeCanonicalPowerCorrectionTriangle

/-! Axiom audit for the terminal canonical prime-power triangle. -/

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.physicalMediumReferenceLaw_eq_canonicalGuardedMediumReferenceLaw
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actual_powerCorrection_reference_weightedRow_le_of_two_sides
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actual_powerCorrection_canonicalRaw_weightedRow_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_actual_fullSharpRow_sub_squarefreeSharpRow_le_of_canonicalRaw
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_boxIndependent_canonicalRaw_fullSharp_of_physicalInputs
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.boxIndependent_canonicalRaw_fullSharp
