import Erdos390.Full.PaperRawTiltedPrefixRowUnrestricted

#print axioms Erdos390.Full.PaperRawTiltedPrefixRowUnrestricted.exists_uniform_rawCell_tilted_valuation_prefix_rate_unrestricted
#print axioms Erdos390.Full.PaperRawTiltedPrefixRowUnrestricted.exists_uniform_rawCell_tilted_valuation_all_prefix_rate_unrestricted
