import Erdos390.Full.PaperCanonicalActualBandQuadraticTransfer

/-! Statement audit for the fixed-kappa actual band/full/Schur gaps. -/

#check Erdos390.Full.PaperCanonicalActualBandQuadraticTransfer.canonicalSlowKappa_primeReference_band_lower
#check Erdos390.Full.PaperCanonicalActualBandQuadraticTransfer.canonicalSlowKappa_primeReference_physicalResidual_lower
#check Erdos390.Full.PaperCanonicalActualBandQuadraticTransfer.canonicalSlowKappa_primeReference_fullQuotient_lower
#check Erdos390.Full.PaperCanonicalActualBandQuadraticTransfer.subtypeFull_band_lower_canonicalKappa_of_entry_and_row
#check Erdos390.Full.PaperCanonicalActualBandQuadraticTransfer.subtypeFull_physicalResidual_lower_canonicalKappa_of_entry_and_row
#check Erdos390.Full.PaperCanonicalActualBandQuadraticTransfer.subtypeFull_fullQuotient_lower_canonicalKappa_of_entry_and_row
#check Erdos390.Full.PaperBridgeFit.BridgeData.actualFull_bandCovariance_lower_canonicalKappa_of_profiles_and_row
#check Erdos390.Full.PaperBridgeFit.BridgeData.actualFull_physicalResidual_lower_canonicalKappa_of_profiles_and_row
#check Erdos390.Full.PaperBridgeFit.BridgeData.actualFull_fullQuotient_lower_canonicalKappa_of_profiles_and_row
#check Erdos390.Full.PaperBridgeFit.BridgeData.nuisanceRegressionLoss_primeValuationScore_le_of_marked
#check Erdos390.Full.PaperBridgeFit.BridgeData.actualPhysicalResidualSchur_fullQuotient_Dgap_canonicalKappa
#check Erdos390.Full.PaperBridgeFit.BridgeData.actualBandSchur_Dgap_canonicalKappa_of_profiles_rows_marked
