import Erdos390.Full.PaperMovingPrefixMarkedCell

#print axioms Erdos390.Full.PaperMovingPrefixMarkedCell.physicalBound_prefixScale_eq
#print axioms Erdos390.Full.PaperMovingPrefixMarkedCell.prefixScale_mem_compact
#print axioms Erdos390.Full.PaperMovingPrefixMarkedCell.endpointFamilyCoefficient_le_compact
#print axioms Erdos390.Full.PaperMovingPrefixMarkedCell.exists_uniform_movingUpper_markedCell_paper_main_bound
#print axioms Erdos390.Full.PaperMovingPrefixMarkedCell.uniformAverage_divInd_mul_prefix_eq_markedCell_ratio
#print axioms Erdos390.Full.PaperMovingPrefixMarkedCell.exists_uniform_movingPrefix_uniformAverage_divInd_bound
#print axioms Erdos390.Full.PaperMovingPrefixMarkedCell.exists_uniform_movingPrefix_divInd_centered_bound
#print axioms Erdos390.Full.PaperMovingPrefixMarkedCell.exists_uniform_movingPrefix_divInd_covariance_bound
