import Erdos390.Full.PaperCanonicalFullQuotientPaperDistanceEventually

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_paperFineMesh_cutoff_eventually_canonical_actualFullQuotientDistance
