import Erdos390.Full.PaperCanonicalLemma86CompensatedMarkedRowEventually

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_paperFineMesh_cutoff_eventually_canonical_lemma86_compensatedMarkedRow
