import Erdos390.Full.PaperExactSchurFastSlowCoercivity
import Erdos390.Full.PaperExactSchurTwoStageQuadratic
import Erdos390.Full.PaperActualTwoStageRegression
import Erdos390.Full.PaperExactTwoStageTargetSolve

/-!
# Full covariance gap from the exact Lemmas 8.4 and 8.6 outputs

This connector eliminates the `HasCovarianceGap` premise used by the marked
row and ODE modules.  A sharp inverse for the literal actual band Schur map
gives the fast quadratic gap; Lemma 8.6 supplies the compensated slow gap
and regression bound.  The finite fast/slow and nuisance Schur identities
then give the full covariance gap.
-/

namespace Erdos390.Full.PaperBridgeFit

noncomputable section

open ArithmeticBandGeometry PaperWeightedInverseExport
open MovingLowGaugeTransfer

namespace BridgeData

variable {Head Band : Type*} [Fintype Head] [DecidableEq Head]
  [Fintype Band] [DecidableEq Band]
  (B : BridgeData Head Band)

/-- The explicit full-gap constant generated by the two Schur stages. -/
def canonicalTwoStageFullGap
    [Nonempty Head] [Nonempty Band]
    (Cinv gammaSlow Creg gammaNuisance : ℝ) : ℝ :=
  let gammaFast :=
    rawDLowerWeight B.harmonicMass B.bandCenter ^ 2 /
      (sharpWeightTotal B.harmonicMass B.bandCenter * Cinv)
  let gammaMain := min gammaFast gammaSlow /
    (1 + 2 * B.gaugeCenterSquareSum * (1 + Creg ^ 2))
  min gammaMain gammaNuisance /
    (3 + 2 * (B.canonicalCrossBound / gammaNuisance) ^ 2)

/-- Exact full covariance gap, with the fast block derived from the inverse
rather than assumed. -/
theorem hasCovarianceGap_of_sameMap_sharpInverse_and_slow
    [Nonempty Head] [Nonempty Band]
    (xi : B.ParamSpace) {gammaNuisance : ℝ}
    (hgammaNuisance : 0 < gammaNuisance)
    (hGamma : ∀ z, gammaNuisance * ‖z‖ ^ 2 ≤
      inner ℝ z (B.nuisanceCovarianceOperator xi z))
    (e : B.RawBandGauge ≃ₗ[ℝ] B.RawBandGauge)
    (he : ∀ q,
      e q = B.actualBandSchurLinearMap
        xi hgammaNuisance hGamma q)
    {Cinv gammaSlow Creg : ℝ}
    (hCinv : 0 < Cinv) (hgammaSlow : 0 < gammaSlow)
    (hCreg : 0 ≤ Creg)
    (hinv : ∀ v,
      paperSharpNorm B.harmonicMass B.bandCenter
          (B.partition.center_ne_zero B.n_gt_one) (e.symm v) ≤
        Cinv * paperSharpNorm B.harmonicMass B.bandCenter
          (B.partition.center_ne_zero B.n_gt_one) v)
    (hslow : gammaSlow * B.w ^ 2 ≤
      B.actualTwoStageCompensatedVariance
        xi hgammaNuisance hGamma e)
    (hreg : paperSharpNorm B.harmonicMass B.bandCenter
        (B.partition.center_ne_zero B.n_gt_one)
        (B.actualBandRegression xi hgammaNuisance hGamma e) ≤
      Creg * B.w) :
    0 < B.canonicalTwoStageFullGap
        Cinv gammaSlow Creg gammaNuisance ∧
      B.vectorFamily.HasCovarianceGap
        (B.canonicalTwoStageFullGap
          Cinv gammaSlow Creg gammaNuisance) xi := by
  let gammaFast : ℝ :=
    rawDLowerWeight B.harmonicMass B.bandCenter ^ 2 /
      (sharpWeightTotal B.harmonicMass B.bandCenter * Cinv)
  let gammaMain : ℝ := min gammaFast gammaSlow /
    (1 + 2 * B.gaugeCenterSquareSum * (1 + Creg ^ 2))
  have hgammaFast : 0 < gammaFast := by
    dsimp only [gammaFast]
    exact div_pos
      (sq_pos_of_pos (rawDLowerWeight_pos B.harmonicMass B.bandCenter
        B.harmonicMass_pos
        (B.partition.center_ne_zero B.n_gt_one)))
      (mul_pos B.sharpBandWeightTotal_pos hCinv)
  have hcoordDen : 0 <
      1 + 2 * B.gaugeCenterSquareSum * (1 + Creg ^ 2) := by
    have hg := B.gaugeCenterSquareSum_nonneg
    positivity
  have hgammaMain : 0 < gammaMain :=
    div_pos (lt_min hgammaFast hgammaSlow) hcoordDen
  have hfullDen : 0 <
      3 + 2 * (B.canonicalCrossBound / gammaNuisance) ^ 2 := by
    positivity
  have hgammaFull : 0 < B.canonicalTwoStageFullGap
      Cinv gammaSlow Creg gammaNuisance := by
    unfold canonicalTwoStageFullGap
    dsimp only
    exact div_pos (lt_min hgammaMain hgammaNuisance) hfullDen
  have hfast : ∀ q,
      gammaFast *
          paperSharpNorm B.harmonicMass B.bandCenter
            (B.partition.center_ne_zero B.n_gt_one) q ^ 2 ≤
        (B.tiltedLaw xi).covariance
          (B.nuisanceResidualScore xi hgammaNuisance hGamma
            (B.bandRegressionScore q))
          (B.nuisanceResidualScore xi hgammaNuisance hGamma
            (B.bandRegressionScore q)) := by
    intro q
    simpa only [gammaFast] using
      B.actualBandSchur_quadratic_lower_of_inverse_arithmetic
        xi hgammaNuisance hGamma e he hCinv hinv q
  have hslow' : gammaSlow * B.w ^ 2 ≤
      (B.tiltedLaw xi).covariance
        (B.actualTwoStageCompensatedScore
          xi hgammaNuisance hGamma e)
        (B.actualTwoStageCompensatedScore
          xi hgammaNuisance hGamma e) := by
    simpa only [actualTwoStageCompensatedVariance] using hslow
  have hfull := B.hasCovarianceGap_of_fastSlow_of_regressionBound
    xi hgammaNuisance hGamma e he hgammaFast hgammaSlow hCreg
      hfast hslow' hreg
  refine ⟨hgammaFull, ?_⟩
  simpa only [canonicalTwoStageFullGap, gammaFast, gammaMain] using hfull

end BridgeData

end

end Erdos390.Full.PaperBridgeFit
