import Erdos390.Full.PaperActualSquarefreeReference

/-! Axiom audit for the actual-law squarefree reference connector. -/

#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.uniformValuationTilt_expect_divInd_eq_of_finset_eq
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_unguardedCell_mediumScore_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.mediumFallbackExponent_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.cellMediumLaw_squarefree_profiles_of_unguarded
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_boxIndependent_actual_medium_signed_profiles
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualComponent_squarefree_profiles_of_medium
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_boxIndependent_actual_component_signed_profiles
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.sigmaMixture_actualComponentValuationLaw_eq_actualValuationLaw
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_actual_squarefreeSharpRow_sub_arithmeticSharpOperator_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.tendsto_pairCovarianceScale_mul_logL_zero
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.tendsto_squarefreeSharpProfileRemainder
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_actual_squarefreeSharpRow_sub_arithmetic_le_profileRemainder
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_boxIndependent_actual_squarefreeSharp_reference_bound
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualSharpWeightTotal_pos
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualSquarefreeProjectedCLM_sub_arithmetic_le
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_actualSquarefreeProjectedEquiv_of_reference

/-! Full-valuation attachment after the literal Lemma 7.5 transfer. -/
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualFullProjectedCLM_sub_squarefree_le_of_transferBounds
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_actualFullProjectedEquiv_of_squarefree_of_transferBounds
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_actual_fullSharpRow_sub_squarefreeSharpRow_le_of_referenceLaw
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualFullProjectedCLM_sub_squarefree_le_of_referenceLaw
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_actualFullProjectedEquiv_of_squarefree_of_referenceLaw
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.abs_actual_fullSharpRow_sub_squarefreeSharpRow_le_of_referencePowerCorrectionRow
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.actualFullProjectedCLM_sub_squarefree_le_of_referencePowerCorrectionRow
#print axioms Erdos390.Full.PaperBridgeFit.BridgeData.exists_actualFullProjectedEquiv_of_squarefree_of_referencePowerCorrectionRow
