import Erdos390.WholePaper.BankPaperFourFiveRealLastPrimeEndpoint

/-! Expanded statement audit for exact real last-prime endpoints. -/

namespace Erdos390.WholePaper.BankPaperRealization

#check fourFiveRealPrefixProduct
#check fourFiveRealPrefixProduct_pos
#check fourFiveLastPrimeRealLower
#check fourFiveLastPrimeRealUpper
#check floor_fourFiveLastPrimeRealUpper
#check floor_fourFiveLastPrimeRealLower
#check fourFiveLastPrimeRealIntegral
#check fourFiveLastPrimeRealEndpointError
#check fourFiveLastPrimeRealPhysicalIntegral
#check fourFiveLastPrimeRealLower_ge_y
#check fourFiveRealPrefixProduct_mul_realUpper
#check fourFiveRealPrefixProduct_mul_realLower
#check fourFiveLastPrimeRealIntegral_eq_physicalIntegral
#check fourFiveLastPrimeRealPhysicalIntegral_eq_maxIntegral
#check fourFiveOrderedLastPrimeRealIntegralLayer
#check fourFiveOrderedLastPrimeRealPhysicalLayer
#check fourFiveOrderedLastPrimeRealIntegralLayer_eq_physicalLayer
#check abs_fourFiveLastPrimeFiber_card_sub_realIntegral_le
#check fourFiveOrderedLastPrimeRealEndpointErrorLayer
#check fourFivePrimeCoordinateReciprocalMass
#check fourFiveOrderedPrimePrefixReciprocalMass
#check fourFiveOrderedPrimePrefixReciprocalMass_eq_pow
#check fourFivePrimeCoordinateReciprocalMass_nonneg
#check fourFiveLastPrimeRealEndpointError_le_reciprocalWeight
#check fourFiveOrderedLastPrimeRealEndpointErrorLayer_le_prefixMass
#check fourFiveOrderedLastPrimeRealEndpointErrorLayer_le_massPow
#check abs_fourFiveOrderedPrimeLayerMass_sub_realLastPrimeIntegral_le
#check exists_abs_fourFiveOrderedPrimeLayerMass_sub_realLastPrimeIntegral_le

end Erdos390.WholePaper.BankPaperRealization
