import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalFourFiveGeometryPrecursorConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the signed exceptional four/five geometry precursor
-/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms eventually_two_mul_tangentPaperExceptionalCutoff_le_yNat
#print axioms roughCanonicalFourFiveFrozenCoordinate_mem_padded_of_deepCore
#print axioms eventually_roughCanonicalFourFiveFrozenCoordinate_mem_padded_of_deepCore
#print axioms RoughCanonicalSignedExceptionalFourFiveScalarBoundsAt
#print axioms eventually_roughCanonicalSignedExceptionalFourFiveScalarBoundsAt
#print axioms RoughCanonicalSignedExceptionalFourFiveGeometryPrecursorAt
#print axioms RoughCanonicalSignedExceptionalFourFiveGeometryPrecursorAt.variation_coordinates
#print axioms eventually_roughCanonicalSignedExceptionalFourFiveGeometryPrecursorAt

assert_no_sorry eventually_two_mul_tangentPaperExceptionalCutoff_le_yNat
assert_no_sorry roughCanonicalFourFiveFrozenCoordinate_mem_padded_of_deepCore
assert_no_sorry eventually_roughCanonicalFourFiveFrozenCoordinate_mem_padded_of_deepCore
assert_no_sorry RoughCanonicalSignedExceptionalFourFiveScalarBoundsAt
assert_no_sorry eventually_roughCanonicalSignedExceptionalFourFiveScalarBoundsAt
assert_no_sorry RoughCanonicalSignedExceptionalFourFiveGeometryPrecursorAt
assert_no_sorry RoughCanonicalSignedExceptionalFourFiveGeometryPrecursorAt.variation_coordinates
assert_no_sorry eventually_roughCanonicalSignedExceptionalFourFiveGeometryPrecursorAt

end Erdos390.WholePaper.BankPaperRealization
