import Erdos390.WholePaper.BankPaperCanonicalSelectorRoundingCandidateHandoff
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the candidate-parametric selector handoff -/

#print axioms Erdos390.WholePaper.BankPaperCanonicalSelectorRoundingTangentHandoffOnCandidates
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnCandidates_of_selectorInput
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnCandidates_subset_raw
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnCandidates_exists_selectorInput
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnRawCandidates_of_selectorInput
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnRawCandidates_of_legacyHandoff
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnGuardedCandidates_of_selectorInput

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSelectorRoundingTangentHandoffOnCandidates
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnCandidates_of_selectorInput
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnCandidates_subset_raw
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnCandidates_exists_selectorInput
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnRawCandidates_of_selectorInput
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnRawCandidates_of_legacyHandoff
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorRoundingTangentHandoffOnGuardedCandidates_of_selectorInput
