import Erdos390.WholePaper.BankPaperCanonicalTwoZeroHeadCellProducerConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the two-zero-head-cell producer connector

The connector exports twenty public declarations: two definitions and
eighteen theorems.  Both audit blocks below cover all twenty, in source
order.
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_physicalBound_le_two_mul_sub_upperTailLength
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_physicalIntervals_upperBound_le_two_mul_sub_upperTailLength
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadValue_coprime_roughHeadModulus
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadValue_mem_guardedBroadCorrectionPool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadValue_mem_guardedBroadCorrectionPool_of_physicalIntervals
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCells_subset_guardedBroadCorrectionPool_of_physicalIntervals
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightCellMass
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightCellMass_add_self
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalLiteralActiveMass_symmetricHeightRebalance
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightCellMass
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightCellMass_add_self
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalLiteralActiveMass_symmetricInitialAndHeightRebalance
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_symmetricHeight
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricRebalance_apply_of_zeroHeadCell
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightRebalance_apply_of_zeroHeadCell
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightRebalance_apply_of_zeroHeadCell
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightRebalance_nonneg_of_cellMass
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightRebalance_protected_le_one_of_cellMass
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightRebalance_nonneg_of_cellMass
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightRebalance_protected_le_one_of_cellMass

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_physicalBound_le_two_mul_sub_upperTailLength
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_physicalIntervals_upperBound_le_two_mul_sub_upperTailLength
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadValue_coprime_roughHeadModulus
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadValue_mem_guardedBroadCorrectionPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadValue_mem_guardedBroadCorrectionPool_of_physicalIntervals
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCells_subset_guardedBroadCorrectionPool_of_physicalIntervals
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightCellMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightCellMass_add_self
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalLiteralActiveMass_symmetricHeightRebalance
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightCellMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightCellMass_add_self
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalLiteralActiveMass_symmetricInitialAndHeightRebalance
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_symmetricHeight
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricRebalance_apply_of_zeroHeadCell
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightRebalance_apply_of_zeroHeadCell
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightRebalance_apply_of_zeroHeadCell
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightRebalance_nonneg_of_cellMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightRebalance_protected_le_one_of_cellMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightRebalance_nonneg_of_cellMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightRebalance_protected_le_one_of_cellMass
