import Erdos390.WholePaper.BankPaperCanonicalSectionEightAnalyticLedgerReduction
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the reduced Section 8 analytic ledger -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool
#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothBaseMass
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseMass_sub_guarded_eq_guardDeletion
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothResidualAnchorPool
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedTailFiber
#print Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.mk
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.fiber
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.realization
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.certificate
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.extendedGuardedSmoothBaseMass
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.extendedSmoothBaseGuardDeletionCard
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.extendedAnchorIntersectionCard
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothGuardCensusEnvelope
#print axioms Erdos390.WholePaper.BankPaperCanonicalSmoothGuardDeletionCensus
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedSmoothCorrectionEstimate
#print axioms Erdos390.WholePaper.BankPaperCanonicalFrozenBaselineSourceLedger
#print axioms Erdos390.WholePaper.BankPaperCanonicalSectionEightAnalyticSourceLedger
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool_subset_anchors
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool_card_le_anchors
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool_subset_anchorIntersection
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool_card_le_anchorIntersection
#print axioms Erdos390.WholePaper.guardedCentralAnchors_inter_rawSmoothBasePool_subset_smoothResidual
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothResidualAnchorPool_card_le
#print axioms Erdos390.WholePaper.guardedCentralAnchors_inter_rawSmoothBasePool_card_le_yNat
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothGuardCensusEnvelope_nonneg
#print axioms Erdos390.WholePaper.bankPaperCanonical_yNat_sq_isLittleO_secondOrderScale
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothGuardCensusEnvelope_isLittleO
#print axioms Erdos390.WholePaper.guardedCentralAnchors_inter_rawSmoothBasePool_isBigO_envelope
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothGuardDeletionCard_isLittleO
#print axioms Erdos390.WholePaper.bankPaperCanonical_beta_div_L_isBigO_one
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothGuardDeletionMass_isLittleO
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBase_sub_guarded_isLittleO_of_census
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBase_sub_qTilde_isLittleO_of_guardedReduction
#print axioms Erdos390.WholePaper.bankPaperCanonical_one_isBigO_secondOrderScale_div_L
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothQ0_baselineMassError_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothQ0_baselineMassError_mul_L_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothA0Family_isBigO_of_baselineSource
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_sourceLedger
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_literalGuardedSource
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_literalAnchorSource
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_correctionAndBaseline

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothBaseMass
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseMass_sub_guarded_eq_guardDeletion
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothResidualAnchorPool
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedTailFiber
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.mk
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.fiber
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.realization
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.certificate
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.extendedGuardedSmoothBaseMass
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.extendedSmoothBaseGuardDeletionCard
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedTailFamily.extendedAnchorIntersectionCard
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothGuardCensusEnvelope
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSmoothGuardDeletionCensus
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedSmoothCorrectionEstimate
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalFrozenBaselineSourceLedger
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSectionEightAnalyticSourceLedger
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool_subset_anchors
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool_card_le_anchors
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool_subset_anchorIntersection
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothBaseGuardDeletionPool_card_le_anchorIntersection
assert_no_sorry Erdos390.WholePaper.guardedCentralAnchors_inter_rawSmoothBasePool_subset_smoothResidual
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothResidualAnchorPool_card_le
assert_no_sorry Erdos390.WholePaper.guardedCentralAnchors_inter_rawSmoothBasePool_card_le_yNat
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothGuardCensusEnvelope_nonneg
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_yNat_sq_isLittleO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothGuardCensusEnvelope_isLittleO
assert_no_sorry Erdos390.WholePaper.guardedCentralAnchors_inter_rawSmoothBasePool_isBigO_envelope
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothGuardDeletionCard_isLittleO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_beta_div_L_isBigO_one
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothGuardDeletionMass_isLittleO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBase_sub_guarded_isLittleO_of_census
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBase_sub_qTilde_isLittleO_of_guardedReduction
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_one_isBigO_secondOrderScale_div_L
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothQ0_baselineMassError_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothQ0_baselineMassError_mul_L_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothA0Family_isBigO_of_baselineSource
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_sourceLedger
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_literalGuardedSource
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_literalAnchorSource
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_correctionAndBaseline
