import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalFourFiveDeepIntervalEstimateConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for deep exceptional four/five interval estimates
-/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms roughCanonicalFourFiveDeep_shortFreezingEndpointRate_le
#print axioms roughCanonicalFourFiveDeep_broadFreezingEndpointRate_le
#print axioms roughCanonicalFourFiveDeepShortEstimateConstant
#print axioms roughCanonicalFourFiveDeepBroadEstimateConstant
#print axioms roughCanonicalFourFiveDeepShortEstimateConstant_nonneg
#print axioms roughCanonicalFourFiveDeepBroadEstimateConstant_nonneg
#print axioms abs_roughCanonicalExceptionalPhysicalInterval_card_sub_idealFrozen_le_deepShortRate
#print axioms abs_roughCanonicalExceptionalPhysicalInterval_card_sub_idealFrozen_le_deepBroadRate
#print axioms roughCanonicalFourFiveDeep_self_div_core_le_rateScale
#print axioms roughCanonicalFourFiveDeep_shortIdealLength_le
#print axioms roughCanonicalFourFiveDeep_broadEndpointRate_le
#print axioms abs_fourFiveRoughInterval_card_sub_idealFrozen_le_deepBroadRate_of_empty
#print axioms roughCanonicalFourFiveDeepUpperEstimateConstant
#print axioms roughCanonicalFourFiveDeepHighEstimateConstant
#print axioms roughCanonicalFourFiveDeepBroadFinalEstimateConstant
#print axioms roughCanonicalFourFiveDeepUpperEstimateConstant_nonneg
#print axioms roughCanonicalFourFiveDeepHighEstimateConstant_nonneg
#print axioms roughCanonicalFourFiveDeepBroadFinalEstimateConstant_nonneg
#print axioms roughCanonicalSignedExceptionalDeepIntervalEstimate_of_inputs
#print axioms exists_eventually_roughCanonicalSignedExceptionalDeepIntervalEstimates

assert_no_sorry roughCanonicalFourFiveDeep_shortFreezingEndpointRate_le
assert_no_sorry roughCanonicalFourFiveDeep_broadFreezingEndpointRate_le
assert_no_sorry roughCanonicalFourFiveDeepShortEstimateConstant
assert_no_sorry roughCanonicalFourFiveDeepBroadEstimateConstant
assert_no_sorry roughCanonicalFourFiveDeepShortEstimateConstant_nonneg
assert_no_sorry roughCanonicalFourFiveDeepBroadEstimateConstant_nonneg
assert_no_sorry abs_roughCanonicalExceptionalPhysicalInterval_card_sub_idealFrozen_le_deepShortRate
assert_no_sorry abs_roughCanonicalExceptionalPhysicalInterval_card_sub_idealFrozen_le_deepBroadRate
assert_no_sorry roughCanonicalFourFiveDeep_self_div_core_le_rateScale
assert_no_sorry roughCanonicalFourFiveDeep_shortIdealLength_le
assert_no_sorry roughCanonicalFourFiveDeep_broadEndpointRate_le
assert_no_sorry abs_fourFiveRoughInterval_card_sub_idealFrozen_le_deepBroadRate_of_empty
assert_no_sorry roughCanonicalFourFiveDeepUpperEstimateConstant
assert_no_sorry roughCanonicalFourFiveDeepHighEstimateConstant
assert_no_sorry roughCanonicalFourFiveDeepBroadFinalEstimateConstant
assert_no_sorry roughCanonicalFourFiveDeepUpperEstimateConstant_nonneg
assert_no_sorry roughCanonicalFourFiveDeepHighEstimateConstant_nonneg
assert_no_sorry roughCanonicalFourFiveDeepBroadFinalEstimateConstant_nonneg
assert_no_sorry roughCanonicalSignedExceptionalDeepIntervalEstimate_of_inputs
assert_no_sorry exists_eventually_roughCanonicalSignedExceptionalDeepIntervalEstimates

end Erdos390.WholePaper.BankPaperRealization
