import Erdos390.WholePaper.BankPaperCanonicalSectionNineSymmetricHeightLocalInputConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the symmetric-height local-input connector
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightSourceInputsAt
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightP87InputsAt
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightSlackInputsAt
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightCoreInputsAt
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightSourceStateInputsAt
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightDependentInputsAt
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineSymmetricHeightCoreInputsAt_of_sourceInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineSymmetricHeightSourceStateInputsAt_of_sourceInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineSymmetricHeightDependentInputsAt_of_p87_slack
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightRebalance_le_div_log
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNinePostHfitSourceStateLocalInputsAt_of_symmetricHeight
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNinePostHfitLocalInputsAt_of_symmetricHeight

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightSourceInputsAt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightP87InputsAt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightSlackInputsAt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightCoreInputsAt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightSourceStateInputsAt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineSymmetricHeightDependentInputsAt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineSymmetricHeightCoreInputsAt_of_sourceInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineSymmetricHeightSourceStateInputsAt_of_sourceInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineSymmetricHeightDependentInputsAt_of_p87_slack
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightRebalance_le_div_log
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNinePostHfitSourceStateLocalInputsAt_of_symmetricHeight
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNinePostHfitLocalInputsAt_of_symmetricHeight
