import Erdos390.WholePaper.BankPaperCanonicalSectionEightTopFrozenInitialMassConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the frozen-top initial-mass connector

Every public declaration in the isolated integration connector is printed
and checked for proof placeholders.
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalBalancedRawWeight
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_completeLabelMultiplicity_one_eq_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_completeLabelMultiplicity_one_eq_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedSmoothRow_subset_anchors
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_inter_rawSmoothRow_subset_smoothResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedSmoothRow_card_le_yNat
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_sum_roughCanonicalGuardDeletedSmoothRow_balancedRawWeight_le
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_log_three_mul_natCast_le_five_log_yNat
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_yNat_cast_le_secondOrderScale_div_L
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonical_yNat_isBigO_secondOrderScale_div_L
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalBalancedRawSmoothRowDiscrepancy_isBigO
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenBalancedInitialRealization
#print axioms Erdos390.WholePaper.BankPaperRealization.chargedSelectorMass_sub_height_eq_neg_balancedRawDiscrepancy_sub_deleted
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualSelectorMassEstimate_of_topFrozenBalancedInitial
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenBalancedInitialRealization_of_scaledSeed

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalBalancedRawWeight
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_completeLabelMultiplicity_one_eq_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_completeLabelMultiplicity_one_eq_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedSmoothRow_subset_anchors
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_inter_rawSmoothRow_subset_smoothResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedSmoothRow_card_le_yNat
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_sum_roughCanonicalGuardDeletedSmoothRow_balancedRawWeight_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_log_three_mul_natCast_le_five_log_yNat
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_yNat_cast_le_secondOrderScale_div_L
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonical_yNat_isBigO_secondOrderScale_div_L
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalBalancedRawSmoothRowDiscrepancy_isBigO
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenBalancedInitialRealization
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.chargedSelectorMass_sub_height_eq_neg_balancedRawDiscrepancy_sub_deleted
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualSelectorMassEstimate_of_topFrozenBalancedInitial
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenBalancedInitialRealization_of_scaledSeed
