import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightSourceInputAssemblyConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit: mechanical fresh post-height source-input assembly -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.exists_bankPaperCanonicalSectionNinePostHeight_sourceInputsAndPrimitiveGapsAt_of_canonical
#print axioms BankPaperRealization.exists_eventually_bankPaperCanonicalSectionNinePostHeight_sourceInputsAndPrimitiveGapsAt_of_targetResidual

assert_no_sorry BankPaperRealization.exists_bankPaperCanonicalSectionNinePostHeight_sourceInputsAndPrimitiveGapsAt_of_canonical
assert_no_sorry BankPaperRealization.exists_eventually_bankPaperCanonicalSectionNinePostHeight_sourceInputsAndPrimitiveGapsAt_of_targetResidual

end Erdos390.WholePaper
