import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightSourceResidualConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the coherent post-height source residual
-/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonical_scaledActiveSeed_le_divLog_of_cellDensity
#print axioms BankPaperRealization.eventually_bankPaperCanonical_canonicalSample_cellDensityFloor
#print axioms BankPaperRealization.eventually_bankPaperCanonicalTopFrozenRoundedSourceResidualInputsAt_of_coherentTarget

assert_no_sorry BankPaperRealization.bankPaperCanonical_scaledActiveSeed_le_divLog_of_cellDensity
assert_no_sorry BankPaperRealization.eventually_bankPaperCanonical_canonicalSample_cellDensityFloor
assert_no_sorry BankPaperRealization.eventually_bankPaperCanonicalTopFrozenRoundedSourceResidualInputsAt_of_coherentTarget

end Erdos390.WholePaper
