import Erdos390.WholePaper.BankAnchorCollisionFree

/-! # Assumption audit for complete bank/anchor collision freedom -/

#print axioms Erdos390.WholePaper.bankAnchor_yNat_mul_self_le_self
#print axioms Erdos390.WholePaper.bankAnchor_yNat_tendsto_atTop
#print axioms Erdos390.WholePaper.eventually_bankAnchor_fixed_le_yNat
#print axioms Erdos390.WholePaper.yNat_lt_centralAnchorCutoff_of_threshold
#print axioms Erdos390.WholePaper.eventually_yNat_lt_centralAnchorCutoff
#print axioms Erdos390.WholePaper.marker_mul_nonpower_smooth_ne_promotedCentralFactor
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedLargeCentralAnchor_ne_marker_mul_incidentCore
#print axioms Erdos390.WholePaper.BankPaperRealization.anchorGuardIncidentCores_ordinaryMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.anchorGuardLeftCore_ordinaryMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.anchorGuardRightCore_ordinaryMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.anchorGuardIncidentCores_bottomMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.anchorGuardLeftCore_bottomMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.anchorGuardRightCore_bottomMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.ordinaryMarker_mem_allMarkers
#print axioms Erdos390.WholePaper.BankPaperRealization.bottomMarker_mem_allMarkers
#print axioms Erdos390.WholePaper.BankPaperRealization.centralAnchorCutoff_lt_bottomMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.bottomDonor_eq_upperState_or_two_mul_n_lt
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_allComponentOccurrences
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_guardedCentralAnchors_disjoint_allComponentOccurrences

assert_no_sorry Erdos390.WholePaper.bankAnchor_yNat_mul_self_le_self
assert_no_sorry Erdos390.WholePaper.bankAnchor_yNat_tendsto_atTop
assert_no_sorry Erdos390.WholePaper.eventually_bankAnchor_fixed_le_yNat
assert_no_sorry Erdos390.WholePaper.yNat_lt_centralAnchorCutoff_of_threshold
assert_no_sorry Erdos390.WholePaper.eventually_yNat_lt_centralAnchorCutoff
assert_no_sorry Erdos390.WholePaper.marker_mul_nonpower_smooth_ne_promotedCentralFactor
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedLargeCentralAnchor_ne_marker_mul_incidentCore
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.anchorGuardIncidentCores_ordinaryMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.anchorGuardLeftCore_ordinaryMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.anchorGuardRightCore_ordinaryMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.anchorGuardIncidentCores_bottomMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.anchorGuardLeftCore_bottomMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.anchorGuardRightCore_bottomMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.ordinaryMarker_mem_allMarkers
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bottomMarker_mem_allMarkers
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.centralAnchorCutoff_lt_bottomMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bottomDonor_eq_upperState_or_two_mul_n_lt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_allComponentOccurrences
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_guardedCentralAnchors_disjoint_allComponentOccurrences
