import Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenPlacedDominationConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for frozen-top placed domination -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenCoreHeightPlacementSeed
#print axioms BankPaperRealization.bankPaperCanonicalLiteralActiveMass_sectionNineTopFrozenCoreHeightPlacementSeed
#print axioms BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenCoreHeightPlacementSeed_ne_scaledCoreSeed_of_d_ne_zero
#print axioms BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenCoreHeightPlacedPreSelector_coordinateFit
#print axioms BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenCoreHeightPlaced_actualMeasure
#print axioms BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenSymmetricHeightSourceInputsAt_of_coreHeightPlacement

assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenCoreHeightPlacementSeed
assert_no_sorry BankPaperRealization.bankPaperCanonicalLiteralActiveMass_sectionNineTopFrozenCoreHeightPlacementSeed
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenCoreHeightPlacementSeed_ne_scaledCoreSeed_of_d_ne_zero
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenCoreHeightPlacedPreSelector_coordinateFit
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenCoreHeightPlaced_actualMeasure
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenSymmetricHeightSourceInputsAt_of_coreHeightPlacement

end Erdos390.WholePaper
