import Erdos390.WholePaper.BankPaperPrechargeCapacityEventually
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.exists_eventually_bankPaperPrechargedTailTarget
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.prechargeBaseStateProduct_factorization_add_retained_le_prechargedTailTarget
#print axioms Erdos390.WholePaper.exists_eventually_bankPaperPrechargedTailTarget_with_twelfthReserve

assert_no_sorry Erdos390.WholePaper.exists_eventually_bankPaperPrechargedTailTarget
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.prechargeBaseStateProduct_factorization_add_retained_le_prechargedTailTarget
assert_no_sorry Erdos390.WholePaper.exists_eventually_bankPaperPrechargedTailTarget_with_twelfthReserve
