import Erdos390.WholePaper.BankPaperCanonicalRatioCellGeometry
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for canonical exponent bands and ratio cells

All 39 public declarations in the geometry module (13 definitions or
abbreviations and 26 theorems) are printed and checked by `assert_no_sorry`
in source order.
-/

#print axioms Erdos390.WholePaper.tangentMultiplicativeRatioCutoff
#print axioms Erdos390.WholePaper.tangentMultiplicativeRatioCutoff_zero
#print axioms Erdos390.WholePaper.tangentMultiplicativeRatioCutoff_mono
#print axioms Erdos390.WholePaper.exists_label_le_tangentMultiplicativeRatioCutoff_succ
#print axioms Erdos390.WholePaper.tangentMultiplicativeRawCellIndex
#print axioms Erdos390.WholePaper.label_le_tangentMultiplicativeRatioCutoff_rawCell_succ
#print axioms Erdos390.WholePaper.tangentMultiplicativeRatioCutoff_rawCell_lt_label
#print axioms Erdos390.WholePaper.tangentMultiplicativeRawCellIndex_mono
#print axioms Erdos390.WholePaper.tangentMultiplicativeRawCellIndex_eq_of_mem
#print axioms Erdos390.WholePaper.tangentMultiplicativeRawCell_real_lower_lt
#print axioms Erdos390.WholePaper.tangentMultiplicativeRawCell_real_upper
#print axioms Erdos390.WholePaper.tangentMergedRatioCellIndex
#print axioms Erdos390.WholePaper.tangentMergedRatioLastCell
#print axioms Erdos390.WholePaper.tangentMergedRatioCellIndex_le_lastCell
#print axioms Erdos390.WholePaper.tangentMergedRatioCellIndex_le_raw
#print axioms Erdos390.WholePaper.tangentMergedRatioCellIndex_eq_self
#print axioms Erdos390.WholePaper.tangentMergedRatioCellIndex_lastRaw
#print axioms Erdos390.WholePaper.raw_le_tangentMergedRatioCellIndex_add_one
#print axioms Erdos390.WholePaper.tangentMergedRatioCellIndex_mono
#print axioms Erdos390.WholePaper.rawCellIndices_within_two_of_merged_sameOrAdjacent
#print axioms Erdos390.WholePaper.tangentMultiplicativeRawCell_ratio_lt_cube
#print axioms Erdos390.WholePaper.BankPaperCanonicalExponentBand
#print axioms Erdos390.WholePaper.bankPaperCanonicalExponentBandOf
#print axioms Erdos390.WholePaper.bankPaperCanonicalExponentBandLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalExponentBandUpper
#print axioms Erdos390.WholePaper.bankPaperCanonicalExponentBandOf_mem_interval
#print axioms Erdos390.WholePaper.bankPaperCanonicalExponentBandLower_pos
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawRatioCellIndex
#print axioms Erdos390.WholePaper.bankPaperCanonicalLastRawRatioCell
#print axioms Erdos390.WholePaper.bankPaperCanonicalLastRatioCell
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellIndex
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawRatioCellIndex_le_lastRaw
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellIndex_le_lastCell
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellIndex_mono_of_sameBand
#print axioms Erdos390.WholePaper.bankPaperCanonical_sameOrAdjacentRatioCell_ratio_lt_cube
#print axioms Erdos390.WholePaper.bankPaperCanonical_tangentRatioCellGeometry
#print axioms Erdos390.WholePaper.TangentFixedRatioPrimeIntervalOccupied
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCell_occupied_of_fixedRatioPrimeInterval
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellGeometry_spec

assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRatioCutoff
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRatioCutoff_zero
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRatioCutoff_mono
assert_no_sorry Erdos390.WholePaper.exists_label_le_tangentMultiplicativeRatioCutoff_succ
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRawCellIndex
assert_no_sorry Erdos390.WholePaper.label_le_tangentMultiplicativeRatioCutoff_rawCell_succ
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRatioCutoff_rawCell_lt_label
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRawCellIndex_mono
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRawCellIndex_eq_of_mem
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRawCell_real_lower_lt
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRawCell_real_upper
assert_no_sorry Erdos390.WholePaper.tangentMergedRatioCellIndex
assert_no_sorry Erdos390.WholePaper.tangentMergedRatioLastCell
assert_no_sorry Erdos390.WholePaper.tangentMergedRatioCellIndex_le_lastCell
assert_no_sorry Erdos390.WholePaper.tangentMergedRatioCellIndex_le_raw
assert_no_sorry Erdos390.WholePaper.tangentMergedRatioCellIndex_eq_self
assert_no_sorry Erdos390.WholePaper.tangentMergedRatioCellIndex_lastRaw
assert_no_sorry Erdos390.WholePaper.raw_le_tangentMergedRatioCellIndex_add_one
assert_no_sorry Erdos390.WholePaper.tangentMergedRatioCellIndex_mono
assert_no_sorry Erdos390.WholePaper.rawCellIndices_within_two_of_merged_sameOrAdjacent
assert_no_sorry Erdos390.WholePaper.tangentMultiplicativeRawCell_ratio_lt_cube
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalExponentBand
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalExponentBandOf
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalExponentBandLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalExponentBandUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalExponentBandOf_mem_interval
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalExponentBandLower_pos
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawRatioCellIndex
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLastRawRatioCell
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLastRatioCell
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellIndex
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawRatioCellIndex_le_lastRaw
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellIndex_le_lastCell
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellIndex_mono_of_sameBand
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_sameOrAdjacentRatioCell_ratio_lt_cube
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_tangentRatioCellGeometry
assert_no_sorry Erdos390.WholePaper.TangentFixedRatioPrimeIntervalOccupied
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCell_occupied_of_fixedRatioPrimeInterval
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellGeometry_spec
