import Erdos390.WholePaper.BankPaperCanonicalSmoothSourceGuardedRateClosure
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the exact smooth source-to-guarded reduction -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalRawSmoothBasePool_eq_zeroHeadStructuredCell
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedSmoothBasePool_eq_zeroHeadStructuredCell_sdiff
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalLiteralActiveMass_scaledGuardedSmoothBase_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalScaledActiveValuationMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothBaseValuationMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenNearestIntegerValuationMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedActiveSeed_mul_valuation_eq_scaled_add_nearestInteger
#print axioms Erdos390.WholePaper.BankPaperRealization.not_roughCanonicalExceptionalLabel_one
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalTopFrozenRoundedSmoothSourceToGuardedValuationDefect_eq_roundedActive_sub_guardedBase
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalTopFrozenRoundedSmoothSourceToGuardedValuationDefect_eq_scaled_sub_guardedBase_add_nearestInteger

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalRawSmoothBasePool_eq_zeroHeadStructuredCell
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedSmoothBasePool_eq_zeroHeadStructuredCell_sdiff
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalLiteralActiveMass_scaledGuardedSmoothBase_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalScaledActiveValuationMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothBaseValuationMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenNearestIntegerValuationMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedActiveSeed_mul_valuation_eq_scaled_add_nearestInteger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.not_roughCanonicalExceptionalLabel_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalTopFrozenRoundedSmoothSourceToGuardedValuationDefect_eq_roundedActive_sub_guardedBase
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalTopFrozenRoundedSmoothSourceToGuardedValuationDefect_eq_scaled_sub_guardedBase_add_nearestInteger
