import Erdos390.WholePaper.BankPaperFourFiveSignedCoreErrorAdapter

/-! # Independent statement-shape audit: signed FourFive error adapter -/

namespace Erdos390.WholePaper.BankPaperRealization

#check fourFiveEndpointFactorialMassPolynomial
#check fourFiveTransferFactorialMassPolynomial
#check fourFiveSignedCoreAssemblyLogCubeConstant
#check fourFiveEndpointFactorialMassPolynomial_nonneg
#check fourFiveTransferFactorialMassPolynomial_nonneg
#check fourFiveSignedCoreAssemblyLogCubeConstant_nonneg
#check fourFiveRealEndpointFullyBoundedAssemblyError_le_logCube
#check abs_fourFiveRoughInterval_card_sub_mixtureIntegral_le_paperRate
#check abs_fourFiveContinuumMixtureKernel_sub_le_of_C1
#check intervalIntegrable_fourFiveContinuumMixtureKernel_of_paperRange
#check abs_fourFiveContinuumMixtureIntegralMain_sub_frozen_le
#check abs_natQuotientIntervalLength_sub_realLength_le_one
#check abs_count_sub_idealFrozen_le
#check roughHeadBalancedAlpha_succ_div_core_normalization
#check abs_balanced_three_interval_sub_periodic_frozen_le
#check abs_balanced_three_interval_sub_periodic_frozen_le_paperRate
#check abs_balanced_three_interval_cutoff_le_paperRate

end Erdos390.WholePaper.BankPaperRealization
