import Erdos390.WholePaper.BankPaperFourFiveMovingSimplexCellIdentification
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveRealMovingSimplexKernelOne
#print axioms fourFiveRealMovingSimplexKernelTwo
#print axioms fourFiveRealMovingSimplexKernelThree
#print axioms fourFiveMovingSimplexRightEndpointProductTwo
#print axioms fourFiveMovingSimplexHybridCellProductTwo
#print axioms fourFiveMovingSimplexIteratedRealCellProductTwo
#print axioms fourFiveMovingSimplexRightEndpointProductThree
#print axioms fourFiveMovingSimplexTwoIntegratedHybridThree
#print axioms fourFiveMovingSimplexIteratedRealCellProductThree
#print axioms fourFiveMovingSimplexActivePhysicalIntegralTwo
#print axioms fourFiveMovingSimplexActivePhysicalIntegralThree
#print axioms fourFiveRealMovingSimplexKernelTwo_eq_face_first
#print axioms fourFiveRealMovingSimplexKernelTwo_eq_face_second
#print axioms fourFiveRealMovingSimplexKernelTwo_natCast
#print axioms fourFiveRealMovingSimplexKernelTwo_nonneg_le_one
#print axioms measurable_fourFiveRealMovingSimplexKernelTwo
#print axioms fourFiveRealMovingSimplexKernelThree_eq_face_third
#print axioms fourFiveRealMovingSimplexKernelThree_eq_two_shift
#print axioms fourFiveRealMovingSimplexKernelThree_eq_two_shift_first
#print axioms fourFiveMovingSimplexKernelThree_eq_two_shift
#print axioms fourFiveRealMovingSimplexKernelThree_natCast
#print axioms fourFiveMovingFaceKernel_shift
#print axioms fourFiveRealMovingFaceKernel_shift
#print axioms fourFiveMovingFaceLebesgueCellDefectSum_shift
#print axioms fourFiveMovingSimplexRightEndpointProductTwo_sub_hybrid
#print axioms fourFiveMovingSimplexHybridCellProductTwo_sub_iterated
#print axioms fourFiveMovingSimplexRightEndpointProductTwo_sub_iterated_eq_telescope
#print axioms abs_fourFiveMovingSimplexRightEndpointProductTwo_sub_iterated_le
#print axioms fourFiveMovingSimplexRightEndpointProductThree_eq_sum_two
#print axioms fourFiveMovingSimplexRightEndpointProductThree_sub_twoIntegrated
#print axioms fourFiveRealMovingSimplexKernelThree_nonneg_le_one
#print axioms measurable_fourFiveRealMovingSimplexKernelThree
#print axioms fourFiveMovingSimplexTwoIntegratedHybridThree_eq_explicit
#print axioms fourFiveMovingSimplex_lastCellDefect_identity
#print axioms fourFiveMovingSimplexTwoIntegratedHybridThree_sub_iterated
#print axioms fourFiveMovingSimplexRightEndpointProductThree_sub_iterated_eq_telescope
#print axioms abs_fourFiveMovingSimplexRightEndpointProductThree_sub_iterated_le
#print axioms fourFiveMovingFaceRealCellIntegralSum_eq_interval
#print axioms fourFiveMovingSimplexIteratedRealCellProductTwo_eq_activePhysical
#print axioms fourFiveMovingSimplexIteratedRealCellProductThree_eq_activePhysical
#print axioms integrableOn_fourFiveRealMovingSimplexDensityTwo_activeBox
#print axioms integrableOn_fourFiveRealMovingSimplexDensityThree_activeBox

assert_no_sorry fourFiveRealMovingSimplexKernelOne
assert_no_sorry fourFiveRealMovingSimplexKernelTwo
assert_no_sorry fourFiveRealMovingSimplexKernelThree
assert_no_sorry fourFiveMovingSimplexRightEndpointProductTwo
assert_no_sorry fourFiveMovingSimplexHybridCellProductTwo
assert_no_sorry fourFiveMovingSimplexIteratedRealCellProductTwo
assert_no_sorry fourFiveMovingSimplexRightEndpointProductThree
assert_no_sorry fourFiveMovingSimplexTwoIntegratedHybridThree
assert_no_sorry fourFiveMovingSimplexIteratedRealCellProductThree
assert_no_sorry fourFiveMovingSimplexActivePhysicalIntegralTwo
assert_no_sorry fourFiveMovingSimplexActivePhysicalIntegralThree
assert_no_sorry fourFiveRealMovingSimplexKernelTwo_eq_face_first
assert_no_sorry fourFiveRealMovingSimplexKernelTwo_eq_face_second
assert_no_sorry fourFiveRealMovingSimplexKernelTwo_natCast
assert_no_sorry fourFiveRealMovingSimplexKernelTwo_nonneg_le_one
assert_no_sorry measurable_fourFiveRealMovingSimplexKernelTwo
assert_no_sorry fourFiveRealMovingSimplexKernelThree_eq_face_third
assert_no_sorry fourFiveRealMovingSimplexKernelThree_eq_two_shift
assert_no_sorry fourFiveRealMovingSimplexKernelThree_eq_two_shift_first
assert_no_sorry fourFiveMovingSimplexKernelThree_eq_two_shift
assert_no_sorry fourFiveRealMovingSimplexKernelThree_natCast
assert_no_sorry fourFiveMovingFaceKernel_shift
assert_no_sorry fourFiveRealMovingFaceKernel_shift
assert_no_sorry fourFiveMovingFaceLebesgueCellDefectSum_shift
assert_no_sorry fourFiveMovingSimplexRightEndpointProductTwo_sub_hybrid
assert_no_sorry fourFiveMovingSimplexHybridCellProductTwo_sub_iterated
assert_no_sorry fourFiveMovingSimplexRightEndpointProductTwo_sub_iterated_eq_telescope
assert_no_sorry abs_fourFiveMovingSimplexRightEndpointProductTwo_sub_iterated_le
assert_no_sorry fourFiveMovingSimplexRightEndpointProductThree_eq_sum_two
assert_no_sorry fourFiveMovingSimplexRightEndpointProductThree_sub_twoIntegrated
assert_no_sorry fourFiveRealMovingSimplexKernelThree_nonneg_le_one
assert_no_sorry measurable_fourFiveRealMovingSimplexKernelThree
assert_no_sorry fourFiveMovingSimplexTwoIntegratedHybridThree_eq_explicit
assert_no_sorry fourFiveMovingSimplex_lastCellDefect_identity
assert_no_sorry fourFiveMovingSimplexTwoIntegratedHybridThree_sub_iterated
assert_no_sorry fourFiveMovingSimplexRightEndpointProductThree_sub_iterated_eq_telescope
assert_no_sorry abs_fourFiveMovingSimplexRightEndpointProductThree_sub_iterated_le
assert_no_sorry fourFiveMovingFaceRealCellIntegralSum_eq_interval
assert_no_sorry fourFiveMovingSimplexIteratedRealCellProductTwo_eq_activePhysical
assert_no_sorry fourFiveMovingSimplexIteratedRealCellProductThree_eq_activePhysical
assert_no_sorry integrableOn_fourFiveRealMovingSimplexDensityTwo_activeBox
assert_no_sorry integrableOn_fourFiveRealMovingSimplexDensityThree_activeBox

end Erdos390.WholePaper.BankPaperRealization
