import Erdos390.WholePaper.BankPaperCanonicalGuardCapacityReduction
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for canonical guard-capacity reduction -/

#print axioms Erdos390.WholePaper.prime_dvd_completeRoughLabel_of_cutoff_lt
#print axioms Erdos390.WholePaper.completeRoughLabel_promotedCentralFactor_eq_one_of_base_le
#print axioms Erdos390.WholePaper.fullCentralAnchors_completeRoughLabel_injective_of_ne_one
#print axioms Erdos390.WholePaper.completeRoughRowFiber_inter_guardedCentralAnchors_card_le_one
#print axioms Erdos390.WholePaper.BankPaperRealization.paperMarker_prime
#print axioms Erdos390.WholePaper.BankPaperRealization.yNat_lt_paperMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonor_completeRoughSignature_eq_marker
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBase_completeRoughSignature_eq_marker
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeAlternate_completeRoughSignature_eq_marker
#print axioms Erdos390.WholePaper.BankPaperRealization.completeRoughLabel_paperMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBase_completeRoughLabel_eq_marker
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeAlternate_completeRoughLabel_eq_marker
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBase_completeRoughLabel_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeAlternate_completeRoughLabel_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.completeRoughRowFiber_inter_prechargeBaseState_card_le_one
#print axioms Erdos390.WholePaper.BankPaperRealization.completeRoughRowFiber_inter_prechargeAlternateState_card_le_one
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalCensusBound_three_of_ne_one
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalCensusBound_three_of_active
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadPoolCapacity_of_raw_surplus
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget_le_upperTarget
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowCapacity_of_guardedBroadPoolCapacity
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalActiveRawBroadSurplus
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonical_active_guard_capacity_inputs_of_rawBroadSurplus

assert_no_sorry Erdos390.WholePaper.prime_dvd_completeRoughLabel_of_cutoff_lt
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_promotedCentralFactor_eq_one_of_base_le
assert_no_sorry Erdos390.WholePaper.fullCentralAnchors_completeRoughLabel_injective_of_ne_one
assert_no_sorry Erdos390.WholePaper.completeRoughRowFiber_inter_guardedCentralAnchors_card_le_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperMarker_prime
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.yNat_lt_paperMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonor_completeRoughSignature_eq_marker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBase_completeRoughSignature_eq_marker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeAlternate_completeRoughSignature_eq_marker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeRoughLabel_paperMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBase_completeRoughLabel_eq_marker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeAlternate_completeRoughLabel_eq_marker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBase_completeRoughLabel_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeAlternate_completeRoughLabel_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeRoughRowFiber_inter_prechargeBaseState_card_le_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeRoughRowFiber_inter_prechargeAlternateState_card_le_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalCensusBound_three_of_ne_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalCensusBound_three_of_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadPoolCapacity_of_raw_surplus
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget_le_upperTarget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowCapacity_of_guardedBroadPoolCapacity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalActiveRawBroadSurplus
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonical_active_guard_capacity_inputs_of_rawBroadSurplus
