import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightHeadMarginAlgebra
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit: finite post-height head-margin algebra -/

namespace Erdos390.WholePaper

#print axioms bankPaperCanonicalSectionNinePostHeightHeadCoordinateFloor_pos
#print axioms bankPaperCanonicalSectionNinePostHeightHeadCoordinateFloor_le
#print axioms bankPaperCanonicalSectionNinePostHeightHeadMargin_pos
#print axioms exists_bankPaperCanonicalSectionNinePostHeight_headExponent_large
#print axioms bankPaperCanonicalSectionNinePostHeight_headMargins_of_linearBounds
#print axioms bankPaperCanonicalSectionNinePostHeight_sourceAndPostHeadMargins_of_linearBounds

assert_no_sorry bankPaperCanonicalSectionNinePostHeightHeadCoordinateFloor_pos
assert_no_sorry bankPaperCanonicalSectionNinePostHeightHeadCoordinateFloor_le
assert_no_sorry bankPaperCanonicalSectionNinePostHeightHeadMargin_pos
assert_no_sorry exists_bankPaperCanonicalSectionNinePostHeight_headExponent_large
assert_no_sorry bankPaperCanonicalSectionNinePostHeight_headMargins_of_linearBounds
assert_no_sorry bankPaperCanonicalSectionNinePostHeight_sourceAndPostHeadMargins_of_linearBounds

end Erdos390.WholePaper
