import Erdos390.WholePaper.BankPaperCanonicalSmoothProtectedAdditiveRefinement
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the smooth protected additive refinement -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_apply_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_apply_of_not_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_pos_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_eq_rawWeight_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadCompatibleRawWeight_eq_protected_add_active_of_mem_guardedSmoothPool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_apply_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_apply_of_not_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_sub_base
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_guardedSmoothRow_additiveRefinement_sub_base_eq_pool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_additiveRefinement_of_rowChange
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_eq_base_on_nonsmoothPool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActiveSeedAmbientWeight_le_of_headPatternsSeparated
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_le_div_log
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_le_of_cellDensity
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_protectedReserve
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_frozenAmbientWeight_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_protectedWindow
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_bankPaperCanonicalGuardedSmoothAdditiveRefinement_endpointSlackLayers

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_apply_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_apply_of_not_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_pos_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_eq_rawWeight_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadCompatibleRawWeight_eq_protected_add_active_of_mem_guardedSmoothPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_apply_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_apply_of_not_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_sub_base
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_guardedSmoothRow_additiveRefinement_sub_base_eq_pool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_additiveRefinement_of_rowChange
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_eq_base_on_nonsmoothPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActiveSeedAmbientWeight_le_of_headPatternsSeparated
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_le_div_log
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_le_of_cellDensity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_protectedReserve
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_frozenAmbientWeight_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_protectedWindow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_bankPaperCanonicalGuardedSmoothAdditiveRefinement_endpointSlackLayers
