import Erdos390.WholePaper.BankPaperCanonicalFourFiveKernelVariation
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for frozen four/five kernel variation
-/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalFourFiveFrozenCoordinate
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalFourFiveFrozenKernelWeight
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_fourFiveContinuumMixtureKernel_sub_le_of_C1_bound
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalFourFiveFrozenCoordinate_sub_succ
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalFourFiveFrozenCoordinate_sub_succ_le
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCoreDiscreteVariation_le_two_mul_div_of_reciprocalSteps
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCoreDiscreteVariation_fourFiveFrozenKernelWeight_le
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCoreDiscreteVariation_fourFiveFrozenKernelWeight_primePower_le
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_roughCanonicalFourFiveFrozenKernelVariationConstant
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_roughCanonicalFourFiveFrozenKernelPrimePowerVariationConstant

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalFourFiveFrozenCoordinate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalFourFiveFrozenKernelWeight
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_fourFiveContinuumMixtureKernel_sub_le_of_C1_bound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalFourFiveFrozenCoordinate_sub_succ
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalFourFiveFrozenCoordinate_sub_succ_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCoreDiscreteVariation_le_two_mul_div_of_reciprocalSteps
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCoreDiscreteVariation_fourFiveFrozenKernelWeight_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCoreDiscreteVariation_fourFiveFrozenKernelWeight_primePower_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_roughCanonicalFourFiveFrozenKernelVariationConstant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_roughCanonicalFourFiveFrozenKernelPrimePowerVariationConstant
