import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalFourFiveCutoffIntervalPrecursorConnector

/-!
# Statement audit for the cutoff-interval precursor
-/

namespace Erdos390.WholePaper

namespace BankPaperRealization

#check roughCanonicalExceptional_clippedPhysicalEndpoint_span_le
#check roughCanonicalExceptional_self_div_core_le_physicalRateScale
#check fourFiveRoughInterval_card_le_arithmetic_add_fixedEndpointFreezing
#check roughCanonicalExceptional_shortClippedSpan_div_log_le
#check roughCanonicalExceptional_broadClippedSpan_div_log_le
#check roughCanonicalExceptional_paperRate_le_cutoffSqRate
#check roughCanonicalExceptional_paperRate_le_cutoffBroadRate
#check roughCanonicalFourFiveCutoffUpperEstimateConstant
#check roughCanonicalFourFiveCutoffHighEstimateConstant
#check roughCanonicalFourFiveCutoffBroadEstimateConstant
#check roughCanonicalFourFiveCutoffUpperEstimateConstant_nonneg
#check roughCanonicalFourFiveCutoffHighEstimateConstant_nonneg
#check roughCanonicalFourFiveCutoffBroadEstimateConstant_nonneg
#check roughCanonicalSignedExceptionalCutoffIntervalEstimate_of_geometry_or_empty
#check exists_eventually_roughCanonicalSignedExceptionalCutoffIntervalEstimates

end BankPaperRealization

end Erdos390.WholePaper
