import Erdos390.WholePaper.BankPaperCanonicalPostHfitSlackConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the Post-Hfit endpoint/slack connector

All six public declarations are audited below in source order.
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitBalancedAlpha
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitGlobalSourceSelector
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitGuardedSlackPackage
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_bankPaperCanonicalPostHfitGuardedSlackPackage_of_sourceState
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_bankPaperCanonicalPostHfitGuardedSlackPackage

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitBalancedAlpha
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitGlobalSourceSelector
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitGuardedSlackPackage
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_bankPaperCanonicalPostHfitGuardedSlackPackage_of_sourceState
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_bankPaperCanonicalPostHfitGuardedSlackPackage
