import Erdos390.WholePaper.BankPaperCanonicalSmoothSourceGuardedSharpRoundedValuationRateConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the sharp rounded smooth-source valuation connector -/

#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalGuardedSmoothBaseMass_le_abs_mul_secondOrderScale
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTopFrozenNearestIntegerCellMass_le_quarter
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTopFrozenNearestIntegerValuationMoment_le
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_topFrozenRoundedSmoothSourceToGuardedValuationDefectBound_paperRate

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalGuardedSmoothBaseMass_le_abs_mul_secondOrderScale
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTopFrozenNearestIntegerCellMass_le_quarter
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTopFrozenNearestIntegerValuationMoment_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_topFrozenRoundedSmoothSourceToGuardedValuationDefectBound_paperRate
