import Erdos390.WholePaper.BankPaperAnchorGuards
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.BankPaperRealization.centralChangedMarkers_subset_largeCentralPrimes
#print axioms Erdos390.WholePaper.BankPaperRealization.centralChangedMarkers_subset_allMarkers
#print axioms Erdos390.WholePaper.BankPaperRealization.centralChangedMarkers_card_le
#print axioms Erdos390.WholePaper.BankPaperRealization.anchorGuardIncidentCores_of_ordinary
#print axioms Erdos390.WholePaper.BankPaperRealization.anchorGuardIncidentCores_of_bottom
#print axioms Erdos390.WholePaper.BankPaperRealization.centralChangedMarker_le_n
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_two_mul_upperEndpoint_le_five_mul
#print axioms Erdos390.WholePaper.BankPaperRealization.centralChangedMarker_rowOne_avoids_three

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.centralChangedMarkers_subset_largeCentralPrimes
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.centralChangedMarkers_subset_allMarkers
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.centralChangedMarkers_card_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.anchorGuardIncidentCores_of_ordinary
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.anchorGuardIncidentCores_of_bottom
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.centralChangedMarker_le_n
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_two_mul_upperEndpoint_le_five_mul
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.centralChangedMarker_rowOne_avoids_three
