import Erdos390.WholePaper.BankPaperCanonicalDistributedTangentBridge
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the canonical distributed tangent bridge -/

#print axioms Erdos390.WholePaper.tangentDistributedSupportCount_canonical_le_yNat_sq
#print axioms Erdos390.WholePaper.tangentDistributed_yNat_cubed_div_self_tendsto_zero
#print axioms Erdos390.WholePaper.tangentDistributedPaperCeilingBudget_canonical_le_yNat_cubic
#print axioms Erdos390.WholePaper.tangentDistributedPaperCeilingBudget_canonical_tendsto_zero
#print axioms Erdos390.WholePaper.eventually_tangentDistributedPaperCeilingBudget_canonical_le
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellEarthmover_positiveEdge_locality
#print axioms Erdos390.WholePaper.BankPaperCanonicalDistributedTangentSplitRequest
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedTangentRequestSource
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedTangentRequestTarget
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedTangentLowerCard
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedTangentUpdatedSelector
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedSplitRequest_boundary_eq_selectorDeficit
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_distributedBoundary
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorRowIntegral_and_distributedBoundary
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellCutTraffic_le_prefixUpper
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellCutTraffic_le_tailPointwiseUpper
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_weightedResidual_le_pointwiseUpper
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_weightedPortLoad_le_pointwisePortUpper
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellEarthmover_spec
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellEarthmover_positiveIncident
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellDistributedBoundary

assert_no_sorry Erdos390.WholePaper.tangentDistributedSupportCount_canonical_le_yNat_sq
assert_no_sorry Erdos390.WholePaper.tangentDistributed_yNat_cubed_div_self_tendsto_zero
assert_no_sorry Erdos390.WholePaper.tangentDistributedPaperCeilingBudget_canonical_le_yNat_cubic
assert_no_sorry Erdos390.WholePaper.tangentDistributedPaperCeilingBudget_canonical_tendsto_zero
assert_no_sorry Erdos390.WholePaper.eventually_tangentDistributedPaperCeilingBudget_canonical_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellEarthmover_positiveEdge_locality
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalDistributedTangentSplitRequest
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedTangentRequestSource
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedTangentRequestTarget
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedTangentLowerCard
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedTangentUpdatedSelector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedSplitRequest_boundary_eq_selectorDeficit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_distributedBoundary
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorRowIntegral_and_distributedBoundary
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellCutTraffic_le_prefixUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellCutTraffic_le_tailPointwiseUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_weightedResidual_le_pointwiseUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_weightedPortLoad_le_pointwisePortUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellEarthmover_spec
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellEarthmover_positiveIncident
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelector_ratioCellDistributedBoundary
