import Erdos390.WholePaper.BankPaperFourFivePrimeEndpoint
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveLogIntegralIncrement_eq_integral_inv_log
#print axioms fourFivePrimeCounting_sub_logIntegralIncrement_eq_thetaError
#print axioms fourFivePrimeCounting_sub_integral_inv_log_eq_thetaError
#print axioms abs_fourFivePrimeCounting_sub_logIntegralIncrement_le
#print axioms abs_fourFivePrimeCounting_sub_integral_inv_log_le
#print axioms exists_abs_fourFivePrimeCounting_sub_logIntegralIncrement_le
#print axioms exists_abs_fourFivePrimeCounting_sub_integral_inv_log_le

assert_no_sorry fourFiveLogIntegralIncrement_eq_integral_inv_log
assert_no_sorry fourFivePrimeCounting_sub_logIntegralIncrement_eq_thetaError
assert_no_sorry fourFivePrimeCounting_sub_integral_inv_log_eq_thetaError
assert_no_sorry abs_fourFivePrimeCounting_sub_logIntegralIncrement_le
assert_no_sorry abs_fourFivePrimeCounting_sub_integral_inv_log_le
assert_no_sorry exists_abs_fourFivePrimeCounting_sub_logIntegralIncrement_le
assert_no_sorry exists_abs_fourFivePrimeCounting_sub_integral_inv_log_le

end Erdos390.WholePaper.BankPaperRealization
