import Erdos390.WholePaper.BankPaperCanonicalDirectOrdinaryLogRateConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the direct ordinary-log rate connector
-/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelector_ordinaryLogCompatibleUpTo_of_pointwisePaperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelector_ordinaryLogCompatibleUpTo_meshScale_of_pointwisePaperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_ordinaryLogCompatibleUpTo_of_pointwisePaperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_target_sub_primeLogMoment_abs_le_of_pointwisePaperRate

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelector_ordinaryLogCompatibleUpTo_of_pointwisePaperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelector_ordinaryLogCompatibleUpTo_meshScale_of_pointwisePaperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_ordinaryLogCompatibleUpTo_of_pointwisePaperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_target_sub_primeLogMoment_abs_le_of_pointwisePaperRate
