import Erdos390.WholePaper.BankPaperCanonicalTopFrozenSmoothFeasibilityConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for frozen-top smooth-row feasibility -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonicalStructuredValue_mem_roughBroadLowerBlock_of_physicalIntervals
#print axioms BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_eq_rawWeight_of_mem_smoothBroadRow
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_smoothRow_feasible_of_scaledSeedCapacity
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_feasible_of_scaledSeedCapacity_of_active
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_feasible_of_scaledSeedDivLog_of_twoSidedSlack

assert_no_sorry BankPaperRealization.bankPaperCanonicalStructuredValue_mem_roughBroadLowerBlock_of_physicalIntervals
assert_no_sorry BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_eq_rawWeight_of_mem_smoothBroadRow
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_smoothRow_feasible_of_scaledSeedCapacity
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_feasible_of_scaledSeedCapacity_of_active
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_feasible_of_scaledSeedDivLog_of_twoSidedSlack

end Erdos390.WholePaper
