import Erdos390.WholePaper.BankPaperCanonicalMediumPrimeStructuredPlacementMomentRateConnector
import Mathlib.Util.AssertNoSorry

/-! Transitive axiom and sorry-freedom audit for the placement-moment rate. -/

#print axioms Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalUniformCellIncrement_mul_valuation_eq_mass_mul_guardedCellProbability_expect
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacementValuationMoment_twoZeroHeadCells_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalGlobalCorrectedStructuredPlacementValuationMoment_twoZeroHeadCells_le_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPlacementValuationMoment_twoZeroHeadCells_le_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitMediumPrimeImplementationRateInputs_of_twoZeroHeadCellMean

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalUniformCellIncrement_mul_valuation_eq_mass_mul_guardedCellProbability_expect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacementValuationMoment_twoZeroHeadCells_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalGlobalCorrectedStructuredPlacementValuationMoment_twoZeroHeadCells_le_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPlacementValuationMoment_twoZeroHeadCells_le_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitMediumPrimeImplementationRateInputs_of_twoZeroHeadCellMean
