import Erdos390.WholePaper.BankPaperCanonicalGlobalCorrectedSourceSelector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the global corrected source selector -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActiveSeedAmbientWeight_eq_of_value_of_headPatternsSeparated
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedOutsideSelector
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedOutsideSelector_eq_ambient_of_mem_smoothRow
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool_not_mem_smoothRow_of_ne_one
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedOutsideSelector_eq_corrected_of_mem_nonsmoothPool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_apply_of_mem_smoothPool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_apply_of_mem_nonsmoothPool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_prebridgeMomentLedger_twoZeroHeadCells
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacementSelector_twoZeroHeadCells_feasible_of_source
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredAdditivePlacement_twoZeroHeadCells_of_sourceState
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredAdditivePlacement_twoZeroHeadCells_of_roundedSource
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActiveSeedAmbientWeight_le_of_pointwise
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacement_hpreNonsmooth
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacement_hpreUpper
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacement_slackInputs

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActiveSeedAmbientWeight_eq_of_value_of_headPatternsSeparated
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedOutsideSelector
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedOutsideSelector_eq_ambient_of_mem_smoothRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool_not_mem_smoothRow_of_ne_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedOutsideSelector_eq_corrected_of_mem_nonsmoothPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_apply_of_mem_smoothPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_apply_of_mem_nonsmoothPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_prebridgeMomentLedger_twoZeroHeadCells
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacementSelector_twoZeroHeadCells_feasible_of_source
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredAdditivePlacement_twoZeroHeadCells_of_sourceState
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredAdditivePlacement_twoZeroHeadCells_of_roundedSource
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActiveSeedAmbientWeight_le_of_pointwise
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacement_hpreNonsmooth
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacement_hpreUpper
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedStructuredPlacement_slackInputs
