import Erdos390.WholePaper.BankPaperPrechargeExactificationBridge
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.bankPaperIndexedPathComponentRequest_surjective
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateZeroValue_eq_prechargeBaseStateValue
#print axioms Erdos390.WholePaper.BankPaperRealization.baseExactificationBank_eq_prechargeBaseState
#print axioms Erdos390.WholePaper.BankPaperRealization.baseExactificationBank_prod_eq_prechargeBaseStateProduct
#print axioms Erdos390.WholePaper.BankPaperRealization.baseExactificationBank_prod_eq_prechargeComponentProduct
#print axioms Erdos390.WholePaper.BankPaperRealization.fixed_mul_baseExactificationBank_prod_eq_precharge

assert_no_sorry Erdos390.WholePaper.bankPaperIndexedPathComponentRequest_surjective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateZeroValue_eq_prechargeBaseStateValue
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.baseExactificationBank_eq_prechargeBaseState
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.baseExactificationBank_prod_eq_prechargeBaseStateProduct
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.baseExactificationBank_prod_eq_prechargeComponentProduct
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fixed_mul_baseExactificationBank_prod_eq_precharge
