import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalPhysicalReindex
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the exact signed exceptional physical reindex -/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms roughCanonicalRealExceptionalRoughCutoff
#print axioms roughCanonicalRealExceptionalRoughCutoff_lt_iff
#print axioms roughCanonicalExceptionalClippedRoughInterval
#print axioms roughCanonicalExceptionalUpperPhysicalRoughInterval
#print axioms roughCanonicalExceptionalHighPhysicalRoughInterval
#print axioms roughCanonicalExceptionalBroadPhysicalRoughInterval
#print axioms mem_roughCanonicalExceptionalClippedRoughInterval
#print axioms roughCanonicalExceptionalPhysicalSmoothFiber
#print axioms mem_roughCanonicalExceptionalPhysicalSmoothFiber
#print axioms completeSmoothPart_mul_eq_of_isCompleteRoughLabel_of_smooth
#print axioms roughCanonicalExceptionalPhysicalSmoothFiber_card_eq_clippedRoughInterval
#print axioms paperExceptionalSmoothFiber_eq_physicalSmoothFiber
#print axioms paperExceptionalSmoothFiber_card_eq_upperPhysicalRoughInterval
#print axioms roughCanonicalExceptionalRawLowerSmoothFiber_eq_physical_union
#print axioms roughCanonicalExceptionalPhysicalSmoothFiber_high_disjoint_broad
#print axioms coprime_roughHeadModulus_iff_completeSmoothPart
#print axioms roughHeadCompatibleRawWeight_eq_highCoreCoefficient
#print axioms roughHeadCompatibleRawWeight_eq_broadCoreCoefficient
#print axioms sum_roughCanonicalExceptionalRawLowerSmoothFiber_rawWeight_eq_twoPhysicalIntervals
#print axioms roughCanonicalSignedExceptionalCoreMass_eq_threePhysicalIntervals
#print axioms smooth_of_mem_exceptionalCorePrefix
#print axioms roughCanonicalSignedExceptionalCoreMass_eq_threePhysicalIntervals_of_mem_prefix
#print axioms roughCanonicalSignedExceptionalCoreMass_paper_K0_succ_eq_threePhysicalIntervals

assert_no_sorry roughCanonicalRealExceptionalRoughCutoff
assert_no_sorry roughCanonicalRealExceptionalRoughCutoff_lt_iff
assert_no_sorry roughCanonicalExceptionalClippedRoughInterval
assert_no_sorry roughCanonicalExceptionalUpperPhysicalRoughInterval
assert_no_sorry roughCanonicalExceptionalHighPhysicalRoughInterval
assert_no_sorry roughCanonicalExceptionalBroadPhysicalRoughInterval
assert_no_sorry mem_roughCanonicalExceptionalClippedRoughInterval
assert_no_sorry roughCanonicalExceptionalPhysicalSmoothFiber
assert_no_sorry mem_roughCanonicalExceptionalPhysicalSmoothFiber
assert_no_sorry completeSmoothPart_mul_eq_of_isCompleteRoughLabel_of_smooth
assert_no_sorry roughCanonicalExceptionalPhysicalSmoothFiber_card_eq_clippedRoughInterval
assert_no_sorry paperExceptionalSmoothFiber_eq_physicalSmoothFiber
assert_no_sorry paperExceptionalSmoothFiber_card_eq_upperPhysicalRoughInterval
assert_no_sorry roughCanonicalExceptionalRawLowerSmoothFiber_eq_physical_union
assert_no_sorry roughCanonicalExceptionalPhysicalSmoothFiber_high_disjoint_broad
assert_no_sorry coprime_roughHeadModulus_iff_completeSmoothPart
assert_no_sorry roughHeadCompatibleRawWeight_eq_highCoreCoefficient
assert_no_sorry roughHeadCompatibleRawWeight_eq_broadCoreCoefficient
assert_no_sorry sum_roughCanonicalExceptionalRawLowerSmoothFiber_rawWeight_eq_twoPhysicalIntervals
assert_no_sorry roughCanonicalSignedExceptionalCoreMass_eq_threePhysicalIntervals
assert_no_sorry smooth_of_mem_exceptionalCorePrefix
assert_no_sorry roughCanonicalSignedExceptionalCoreMass_eq_threePhysicalIntervals_of_mem_prefix
assert_no_sorry roughCanonicalSignedExceptionalCoreMass_paper_K0_succ_eq_threePhysicalIntervals

end Erdos390.WholePaper.BankPaperRealization
