import Erdos390.WholePaper.BankPaperCanonicalTopFrozenImplementationRateReductionConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for literal frozen-top implementation-rate reductions -/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeSourceGuardedRowValuationDefectAtLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceToGuardedCorrectionValuationDefect_eq_sum_postchargeRowDefects
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeSourceGuardedRowValuationDefectAtLabel_eq_zero_of_active
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeSourceGuardedRowValuationDefectAtLabel_eq_zero_of_exceptional
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSmoothSourceToGuardedValuationDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceToGuardedCorrectionValuationDefect_eq_smooth_of_nonsmooth

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalTopFrozenRoundedSmoothSourceToGuardedValuationDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalTopFrozenRoundedSourceToGuardedCorrectionValuationDefect_eq_smooth
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalTopFrozenRoundedSmoothSourceToGuardedValuationDefectBound
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalTopFrozenRoundedSourceToGuardedCorrectionValuationDefect_le_of_smooth
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenRoundedTwoImplementationDefectRateInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs_of_defectReductions
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs_of_smooth_aggregateGuardedRaw_and_placement

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellSourceStructuredPlacementValuationMoment_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTwoZeroHeadCellSourceStructuredPlacementValuationMoment_le_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenRoundedPlacementOutsideCompatibility
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenSmoothTopInvisibleOnStructuredActive
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPlacementOutsideCompatibility_of_topInvisible
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedStructuredPlacementValuationMoment_twoZeroHeadCells_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTopFrozenRoundedStructuredPlacementValuationMoment_twoZeroHeadCells_le_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs_of_defectReductions_and_twoZeroHeadCellMean

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeSourceGuardedRowValuationDefectAtLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceToGuardedCorrectionValuationDefect_eq_sum_postchargeRowDefects
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeSourceGuardedRowValuationDefectAtLabel_eq_zero_of_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeSourceGuardedRowValuationDefectAtLabel_eq_zero_of_exceptional
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSmoothSourceToGuardedValuationDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceToGuardedCorrectionValuationDefect_eq_smooth_of_nonsmooth

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalTopFrozenRoundedSmoothSourceToGuardedValuationDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalTopFrozenRoundedSourceToGuardedCorrectionValuationDefect_eq_smooth
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalTopFrozenRoundedSmoothSourceToGuardedValuationDefectBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalTopFrozenRoundedSourceToGuardedCorrectionValuationDefect_le_of_smooth
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenRoundedTwoImplementationDefectRateInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs_of_defectReductions
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs_of_smooth_aggregateGuardedRaw_and_placement

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellSourceStructuredPlacementValuationMoment_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTwoZeroHeadCellSourceStructuredPlacementValuationMoment_le_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenRoundedPlacementOutsideCompatibility
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenSmoothTopInvisibleOnStructuredActive
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPlacementOutsideCompatibility_of_topInvisible
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedStructuredPlacementValuationMoment_twoZeroHeadCells_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTopFrozenRoundedStructuredPlacementValuationMoment_twoZeroHeadCells_le_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs_of_defectReductions_and_twoZeroHeadCellMean
