import Erdos390.WholePaper.BankPaperComponents
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the combined bank realization -/

#print Erdos390.WholePaper.BankPaperRealization
#print axioms Erdos390.WholePaper.BankPaperRealization.mk
#print axioms Erdos390.WholePaper.BankPaperRealization.marker
#print axioms Erdos390.WholePaper.BankPaperRealization.ordinaryMarker_lt_bottomMarker
#print axioms Erdos390.WholePaper.BankPaperRealization.marker_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.ordinaryMarkers_disjoint_bottomMarkers
#print axioms Erdos390.WholePaper.BankPaperRealization.allMarkers_card
#print axioms Erdos390.WholePaper.BankPaperRealization.ordinaryOccurrence_ne_bottomCarrier
#print axioms Erdos390.WholePaper.BankPaperRealization.ordinaryComponent_disjoint_bottomComponent
#print axioms Erdos390.WholePaper.BankPaperRealization.ordinaryComponentOccurrences_disjoint_bottomComponentOccurrences
#print axioms Erdos390.WholePaper.BankPaperRealization.ordinaryComponentOccurrences_card_le
#print axioms Erdos390.WholePaper.BankPaperRealization.allComponentOccurrences_card_le
#print axioms Erdos390.WholePaper.eventually_exists_bankPaperRealization

/-! Existing component APIs retained by the combined realization. -/

#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrence_mem_factorInterval
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.state_donor_completeRoughSignature_eq
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.occurrenceValue_ne_of_request_ne
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrences_disjoint
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrence_mem_factorInterval
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrence_completeRoughSignature
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.occurrenceValue_ne_of_request_ne
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.carrierValueSets_disjoint_of_request_ne
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrences_disjoint_of_request_ne

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mk
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.marker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.ordinaryMarker_lt_bottomMarker
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.marker_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.ordinaryMarkers_disjoint_bottomMarkers
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.allMarkers_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.ordinaryOccurrence_ne_bottomCarrier
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.ordinaryComponent_disjoint_bottomComponent
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.ordinaryComponentOccurrences_disjoint_bottomComponentOccurrences
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.ordinaryComponentOccurrences_card_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.allComponentOccurrences_card_le
assert_no_sorry Erdos390.WholePaper.eventually_exists_bankPaperRealization

assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrence_mem_factorInterval
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.state_donor_completeRoughSignature_eq
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.occurrenceValue_ne_of_request_ne
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrences_disjoint
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrence_mem_factorInterval
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrence_completeRoughSignature
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.occurrenceValue_ne_of_request_ne
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.carrierValueSets_disjoint_of_request_ne
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrences_disjoint_of_request_ne
