import Erdos390.WholePaper.BankPaperCanonicalBalancedRawSignedValuationResidualBoundConnector

/-! Transitive axiom and sorry-freedom audit for the balanced raw connector. -/

#print axioms Erdos390.WholePaper.BankPaperRealization.factorization_cast_eq_sum_primeExponentIndicators
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_factorization_cast_eq_sum_primePowerDivisorCounts
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_weight_mul_factorization_cast_eq_sum_primePowerIndicators
#print axioms Erdos390.WholePaper.BankPaperRealization.Ioc_filter_dvd_card_sub_realLengthDiv_abs_lt_one
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawPrimePowerColumnResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_roughHeadCompatibleRawWeight_mul_primePowerIndicator
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawSignedValuationResidual_eq_sum_primePowerColumns
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalRawPrimePowerColumnResidual_le
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalRawSignedValuationResidual_le_log_mul_columnBound
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawPrimePowerColumnConstant
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawPrimePowerColumnConstant_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawSignedValuationConstant
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawSignedValuationConstant_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_yNat_sq_le_secondOrderScale_div_L
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_balancedRaw_primePowerColumnBound_le_constant
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalBalancedRawSignedValuationResidualBound
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_eventually_roughCanonicalBalancedRawSignedValuationResidualBound

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.factorization_cast_eq_sum_primeExponentIndicators
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_factorization_cast_eq_sum_primePowerDivisorCounts
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_weight_mul_factorization_cast_eq_sum_primePowerIndicators
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.Ioc_filter_dvd_card_sub_realLengthDiv_abs_lt_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawPrimePowerColumnResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_roughHeadCompatibleRawWeight_mul_primePowerIndicator
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawSignedValuationResidual_eq_sum_primePowerColumns
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalRawPrimePowerColumnResidual_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalRawSignedValuationResidual_le_log_mul_columnBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawPrimePowerColumnConstant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawPrimePowerColumnConstant_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawSignedValuationConstant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawSignedValuationConstant_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_yNat_sq_le_secondOrderScale_div_L
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_balancedRaw_primePowerColumnBound_le_constant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalBalancedRawSignedValuationResidualBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_eventually_roughCanonicalBalancedRawSignedValuationResidualBound
