import Erdos390.WholePaper.BankPaperGuardedUpperProductAssembly
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the concrete guarded final assembly -/

#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_exactificationResidualFactorSet
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_exactificationResidualFactorSet_of_candidateUniverse
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchor_exactificationResidualGuards_of_candidateUniverse
#print axioms Erdos390.WholePaper.BankPaperRealization.exactificationResidualFactorSet_subset_factorInterval
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedComplementFactorSet_subset_factorInterval
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedComplementFactorSet_prod
#print axioms Erdos390.WholePaper.BankPaperRealization.isAdmissibleEndpoint_of_exactificationResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedExactification_finalAssembly

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_exactificationResidualFactorSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_exactificationResidualFactorSet_of_candidateUniverse
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchor_exactificationResidualGuards_of_candidateUniverse
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exactificationResidualFactorSet_subset_factorInterval
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedComplementFactorSet_subset_factorInterval
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedComplementFactorSet_prod
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.isAdmissibleEndpoint_of_exactificationResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedExactification_finalAssembly
