import Erdos390.WholePaper.BankPaperSelectorTailTarget
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.BankPaperRealization.selectorTailCharge_eq_fixed_mul_prechargeBaseStateProduct
#print axioms Erdos390.WholePaper.BankPaperRealization.selectorTailCharge_pos
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.selectorTailTarget_pos
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.selectorTailTarget_mul_selectorTailCharge
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.selectorTailTarget_factorization_eq_sub
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.valuationCertificate_iff_selectorTailTarget

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.selectorTailCharge_eq_fixed_mul_prechargeBaseStateProduct
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.selectorTailCharge_pos
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.selectorTailTarget_pos
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.selectorTailTarget_mul_selectorTailCharge
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.selectorTailTarget_factorization_eq_sub
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.valuationCertificate_iff_selectorTailTarget
