import Erdos390.WholePaper.BankPaperCanonicalArbitrarySourceSelectorDeficitPaperRateClosureConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the arbitrary-source selector-deficit closure -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceToGuardedCorrectionValuationDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceRawCorrectionValuationDefect_eq_sourceToGuarded_add_guardedRaw
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalParameterizedCompleteSignedResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalParameterizedCompleteSignedResidual_eq_balanced
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment_of_chargeDvd
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalMediumPrimeImplementationRateInputsOfSource
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_le_scale_of_complete_and_implementation
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitStructuredPreSelector_deficit_eq_balancedCompleteSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTopFrozenRoundedPostHfitStructuredPreSelector_deficit_le_scale_of_balancedComplete_and_implementation

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceToGuardedCorrectionValuationDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceRawCorrectionValuationDefect_eq_sourceToGuarded_add_guardedRaw
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalParameterizedCompleteSignedResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalParameterizedCompleteSignedResidual_eq_balanced
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment_of_chargeDvd
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalMediumPrimeImplementationRateInputsOfSource
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_le_scale_of_complete_and_implementation
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitStructuredPreSelector_deficit_eq_balancedCompleteSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalTopFrozenRoundedPostHfitStructuredPreSelector_deficit_le_scale_of_balancedComplete_and_implementation
