import Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSynchronizedAnalyticCompletionConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the top-frozen synchronized analytic completion
-/

#print axioms Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSynchronizedAnalyticCompletion
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalSectionNineParameterSynchronizedFinalPayload_of_topFrozenSynchronizedAnalyticCompletion

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSynchronizedAnalyticCompletion
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalSectionNineParameterSynchronizedFinalPayload_of_topFrozenSynchronizedAnalyticCompletion
