import Erdos390.WholePaper.BankPaperCombinedChargeTerminal
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the combined-charge terminal -/

#print axioms Erdos390.WholePaper.paperCombinedChargeDeltaStar_spec
#print axioms Erdos390.WholePaper.paperCombinedChargeDeltaStar_pos
#print axioms Erdos390.WholePaper.paperCombinedChargeDeltaStar_lt_one_eighteenth
#print axioms Erdos390.WholePaper.eventually_paperFixedExceptionalFactors_charge_le_combinedReserve
#print axioms Erdos390.WholePaper.exists_eventually_bankPaperCombinedChargeTerminal_of_deltaStar
#print axioms Erdos390.WholePaper.exists_eventually_bankPaperCombinedChargeTerminal

assert_no_sorry Erdos390.WholePaper.paperCombinedChargeDeltaStar_spec
assert_no_sorry Erdos390.WholePaper.paperCombinedChargeDeltaStar_pos
assert_no_sorry Erdos390.WholePaper.paperCombinedChargeDeltaStar_lt_one_eighteenth
assert_no_sorry Erdos390.WholePaper.eventually_paperFixedExceptionalFactors_charge_le_combinedReserve
assert_no_sorry Erdos390.WholePaper.exists_eventually_bankPaperCombinedChargeTerminal_of_deltaStar
assert_no_sorry Erdos390.WholePaper.exists_eventually_bankPaperCombinedChargeTerminal
