import Erdos390.WholePaper.BankPaperCapacityAwareMainAsymptoticReduction
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the capacity-aware main-asymptotic reduction

All six public declarations are printed and checked by `assert_no_sorry`.
-/

#print axioms Erdos390.WholePaper.bankPaperCapacitySelectedDepth
#print axioms Erdos390.WholePaper.bankPaperCapacitySelectedDepth_spec
#print axioms Erdos390.WholePaper.mainNormalizedLimit_of_capacityAwareCanonicalPostTangentContinuation
#print axioms Erdos390.WholePaper.mainAsymptotic_of_capacityAwareCanonicalPostTangentContinuation
#print axioms Erdos390.WholePaper.mainNormalizedLimit_of_sharpSaiasDefect_and_capacityAwareSelectorGeometryContinuation
#print axioms Erdos390.WholePaper.mainAsymptotic_of_sharpSaiasDefect_and_capacityAwareSelectorGeometryContinuation

assert_no_sorry Erdos390.WholePaper.bankPaperCapacitySelectedDepth
assert_no_sorry Erdos390.WholePaper.bankPaperCapacitySelectedDepth_spec
assert_no_sorry Erdos390.WholePaper.mainNormalizedLimit_of_capacityAwareCanonicalPostTangentContinuation
assert_no_sorry Erdos390.WholePaper.mainAsymptotic_of_capacityAwareCanonicalPostTangentContinuation
assert_no_sorry Erdos390.WholePaper.mainNormalizedLimit_of_sharpSaiasDefect_and_capacityAwareSelectorGeometryContinuation
assert_no_sorry Erdos390.WholePaper.mainAsymptotic_of_sharpSaiasDefect_and_capacityAwareSelectorGeometryContinuation
