import Erdos390.WholePaper.BankPaperCanonicalDistributedCandidateSet
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for guarded-candidate distributed Section 9 -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedGuardedCandidates
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedGuardedCandidates_subset_raw
#print axioms Erdos390.WholePaper.tangentSplitCleanMultiplier_endpoints_mem_guardedCandidates
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributed_cleanEndpoints_mem_guardedCandidates
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_canonicalDistributedPostTangentOutput_of_multiplier_on_candidates
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_canonicalDistributedSectionNinePostTangentOutput_of_paperBudgets_on_candidates

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedGuardedCandidates
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedGuardedCandidates_subset_raw
assert_no_sorry Erdos390.WholePaper.tangentSplitCleanMultiplier_endpoints_mem_guardedCandidates
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributed_cleanEndpoints_mem_guardedCandidates
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_canonicalDistributedPostTangentOutput_of_multiplier_on_candidates
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_canonicalDistributedSectionNinePostTangentOutput_of_paperBudgets_on_candidates
