import Erdos390.WholePaper.BankPaperCanonicalHeadActiveMassEventually
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the eventual head active-mass bridge -/

#print axioms Erdos390.WholePaper.BankPaperCanonicalActiveMassPaperScaleLower
#print axioms Erdos390.WholePaper.BankPaperCanonicalHeadActiveMassPaperScaleLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalSubunitHeadSimplexReserve
#print axioms Erdos390.WholePaper.bankPaperCanonicalSubunitHeadSimplexReserve_activeMass
#print axioms Erdos390.WholePaper.bankPaperCanonicalSubunitHeadSimplexReserve_not_one_le
#print axioms Erdos390.WholePaper.exists_headSimplexReserve_pos_activeMass_not_one_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveMass_tendsto_atTop_of_paperScaleLower
#print axioms Erdos390.WholePaper.eventually_const_le_bankPaperCanonicalActiveMass_of_paperScaleLower
#print axioms Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalActiveMass_of_paperScaleLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalHeadActiveMass_tendsto_atTop_of_paperScaleLower
#print axioms Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalHeadActiveMass
#print axioms Erdos390.WholePaper.secondOrderScale_div_L_isLittleO_secondOrderScale
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveMassPaperScaleLower_sub_of_isLittleO
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveMassPaperScaleLower_sub_of_logScale_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalHeadActiveMassPaperScaleLower_of_heightCenter
#print axioms Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalHeadActiveMass_of_heightCenter
#print axioms Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_scaledFamily_tendsto_atTop
#print axioms Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalLiteralQMass_scaledFamily
#print axioms Erdos390.WholePaper.eventually_bankPaperCanonicalActualActiveMeasureConstructor_self
#print axioms Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalPaperDataActiveSeedMass
#print axioms Erdos390.WholePaper.eventually_bankPaperCanonicalPaperDataActualActiveMeasureConstructor_self

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActiveMassPaperScaleLower
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalHeadActiveMassPaperScaleLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSubunitHeadSimplexReserve
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSubunitHeadSimplexReserve_activeMass
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSubunitHeadSimplexReserve_not_one_le
assert_no_sorry Erdos390.WholePaper.exists_headSimplexReserve_pos_activeMass_not_one_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveMass_tendsto_atTop_of_paperScaleLower
assert_no_sorry Erdos390.WholePaper.eventually_const_le_bankPaperCanonicalActiveMass_of_paperScaleLower
assert_no_sorry Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalActiveMass_of_paperScaleLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalHeadActiveMass_tendsto_atTop_of_paperScaleLower
assert_no_sorry Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalHeadActiveMass
assert_no_sorry Erdos390.WholePaper.secondOrderScale_div_L_isLittleO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveMassPaperScaleLower_sub_of_isLittleO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveMassPaperScaleLower_sub_of_logScale_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalHeadActiveMassPaperScaleLower_of_heightCenter
assert_no_sorry Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalHeadActiveMass_of_heightCenter
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_scaledFamily_tendsto_atTop
assert_no_sorry Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalLiteralQMass_scaledFamily
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonicalActualActiveMeasureConstructor_self
assert_no_sorry Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalPaperDataActiveSeedMass
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonicalPaperDataActualActiveMeasureConstructor_self
