import Erdos390.WholePaper.BankPaperCanonicalTopFrozenSourceFeasibilityReductionConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for frozen-top source feasibility reduction -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight_mem_unitInterval_of_twoSidedSlack
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_feasible_of_smooth_of_active
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_feasible_of_smooth_of_active
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_feasible_of_smooth_of_twoSidedSlack
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_feasible_of_smooth_of_twoSidedSlack

assert_no_sorry BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight_mem_unitInterval_of_twoSidedSlack
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_feasible_of_smooth_of_active
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_feasible_of_smooth_of_active
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_feasible_of_smooth_of_twoSidedSlack
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_feasible_of_smooth_of_twoSidedSlack

end Erdos390.WholePaper
