import Erdos390.WholePaper.BankPaperCanonicalSectionNineFixedComponentCollision
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the fixed/component collision closure

Every public declaration introduced by the production module is printed and
checked for proof placeholders in source order.
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineBottomStateCollisionExclusions
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineFixedComponentCollisionFree_iff_bottomStateExclusions
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineFixedComponentCollisionFree_of_scaledEndpoint_narrow
#print axioms Erdos390.WholePaper.eventually_bankPaperCanonicalSectionNineFixedComponentCollisionFree

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineBottomStateCollisionExclusions
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineFixedComponentCollisionFree_iff_bottomStateExclusions
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineFixedComponentCollisionFree_of_scaledEndpoint_narrow
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonicalSectionNineFixedComponentCollisionFree
