import Erdos390.WholePaper.BankPaperFourFiveMovingFaceBV
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveRightDiscreteBVNorm_congr
#print axioms fourFiveRightDiscreteBVNorm_cutoffSequence_le_two
#print axioms fourFiveLogCoordinate_mono
#print axioms fourFiveMovingFace_active_iff_le_cutoff
#print axioms fourFiveMovingFaceKernel_eq_cutoffSequence
#print axioms fourFiveMovingFaceMonotoneExtension_certificate
#print axioms fourFiveRightDiscreteBVNorm_movingFace_le_two
#print axioms fourFiveCompactReciprocalMass_pos
#print axioms fourFiveAnchoredReciprocalPrimeAtom_nonneg
#print axioms fourFiveAnchoredLogLogCellAtom_nonneg
#print axioms sum_Ioc_fourFiveAnchoredReciprocalPrimeAtom
#print axioms sum_Ioc_fourFiveAnchoredLogLogCellAtom
#print axioms sum_abs_fourFiveAnchoredReciprocalPrimeAtom
#print axioms sum_abs_fourFiveAnchoredLogLogCellAtom
#print axioms fourFive_actual_and_continuum_mass_le_compact
#print axioms fourFiveMovingSimplexKernelTwo_eq_face_first
#print axioms fourFiveMovingSimplexKernelTwo_eq_face_second
#print axioms fourFiveRightDiscreteBVNorm_movingSimplexTwo_first_le_two
#print axioms fourFiveRightDiscreteBVNorm_movingSimplexTwo_second_le_two
#print axioms fourFiveMovingSimplexKernelThree_eq_face_first
#print axioms fourFiveMovingSimplexKernelThree_eq_face_second
#print axioms fourFiveMovingSimplexKernelThree_eq_face_third
#print axioms fourFiveRightDiscreteBVNorm_movingSimplexThree_first_le_two
#print axioms fourFiveRightDiscreteBVNorm_movingSimplexThree_second_le_two
#print axioms fourFiveRightDiscreteBVNorm_movingSimplexThree_third_le_two
#print axioms abs_fourFiveMovingSimplexProductOne_sub_continuum_le
#print axioms abs_fourFiveMovingSimplexProductTwo_sub_continuum_le
#print axioms abs_fourFiveMovingSimplexProductThree_sub_continuum_le

assert_no_sorry fourFiveRightDiscreteBVNorm_congr
assert_no_sorry fourFiveRightDiscreteBVNorm_cutoffSequence_le_two
assert_no_sorry fourFiveLogCoordinate_mono
assert_no_sorry fourFiveMovingFace_active_iff_le_cutoff
assert_no_sorry fourFiveMovingFaceKernel_eq_cutoffSequence
assert_no_sorry fourFiveMovingFaceMonotoneExtension_certificate
assert_no_sorry fourFiveRightDiscreteBVNorm_movingFace_le_two
assert_no_sorry fourFiveCompactReciprocalMass_pos
assert_no_sorry fourFiveAnchoredReciprocalPrimeAtom_nonneg
assert_no_sorry fourFiveAnchoredLogLogCellAtom_nonneg
assert_no_sorry sum_Ioc_fourFiveAnchoredReciprocalPrimeAtom
assert_no_sorry sum_Ioc_fourFiveAnchoredLogLogCellAtom
assert_no_sorry sum_abs_fourFiveAnchoredReciprocalPrimeAtom
assert_no_sorry sum_abs_fourFiveAnchoredLogLogCellAtom
assert_no_sorry fourFive_actual_and_continuum_mass_le_compact
assert_no_sorry fourFiveMovingSimplexKernelTwo_eq_face_first
assert_no_sorry fourFiveMovingSimplexKernelTwo_eq_face_second
assert_no_sorry fourFiveRightDiscreteBVNorm_movingSimplexTwo_first_le_two
assert_no_sorry fourFiveRightDiscreteBVNorm_movingSimplexTwo_second_le_two
assert_no_sorry fourFiveMovingSimplexKernelThree_eq_face_first
assert_no_sorry fourFiveMovingSimplexKernelThree_eq_face_second
assert_no_sorry fourFiveMovingSimplexKernelThree_eq_face_third
assert_no_sorry fourFiveRightDiscreteBVNorm_movingSimplexThree_first_le_two
assert_no_sorry fourFiveRightDiscreteBVNorm_movingSimplexThree_second_le_two
assert_no_sorry fourFiveRightDiscreteBVNorm_movingSimplexThree_third_le_two
assert_no_sorry abs_fourFiveMovingSimplexProductOne_sub_continuum_le
assert_no_sorry abs_fourFiveMovingSimplexProductTwo_sub_continuum_le
assert_no_sorry abs_fourFiveMovingSimplexProductThree_sub_continuum_le

end Erdos390.WholePaper.BankPaperRealization
