import Erdos390.WholePaper.BankPaperFourFiveSignedCoreErrorAdapter
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit: signed FourFive error adapter -/

#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveEndpointFactorialMassPolynomial
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveTransferFactorialMassPolynomial
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveSignedCoreAssemblyLogCubeConstant
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveEndpointFactorialMassPolynomial_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveTransferFactorialMassPolynomial_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveSignedCoreAssemblyLogCubeConstant_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRealEndpointFullyBoundedAssemblyError_le_logCube
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughInterval_card_sub_mixtureIntegral_le_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_fourFiveContinuumMixtureKernel_sub_le_of_C1
#print axioms Erdos390.WholePaper.BankPaperRealization.intervalIntegrable_fourFiveContinuumMixtureKernel_of_paperRange
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_fourFiveContinuumMixtureIntegralMain_sub_frozen_le
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_natQuotientIntervalLength_sub_realLength_le_one
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_count_sub_idealFrozen_le
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadBalancedAlpha_succ_div_core_normalization
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_balanced_three_interval_sub_periodic_frozen_le
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_balanced_three_interval_sub_periodic_frozen_le_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_balanced_three_interval_cutoff_le_paperRate

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveEndpointFactorialMassPolynomial
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveTransferFactorialMassPolynomial
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveSignedCoreAssemblyLogCubeConstant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveEndpointFactorialMassPolynomial_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveTransferFactorialMassPolynomial_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveSignedCoreAssemblyLogCubeConstant_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRealEndpointFullyBoundedAssemblyError_le_logCube
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughInterval_card_sub_mixtureIntegral_le_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_fourFiveContinuumMixtureKernel_sub_le_of_C1
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.intervalIntegrable_fourFiveContinuumMixtureKernel_of_paperRange
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_fourFiveContinuumMixtureIntegralMain_sub_frozen_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_natQuotientIntervalLength_sub_realLength_le_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_count_sub_idealFrozen_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadBalancedAlpha_succ_div_core_normalization
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_balanced_three_interval_sub_periodic_frozen_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_balanced_three_interval_sub_periodic_frozen_le_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_balanced_three_interval_cutoff_le_paperRate
