import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalFourFiveChamberConnector

/-!
# Statement audit for the signed exceptional four/five chamber connector
-/

open Filter Topology

namespace Erdos390.WholePaper

open Erdos390.Full.ArithmeticModel
open Erdos390.Full.Scale

namespace BankPaperRealization

#check roughCanonicalExceptionalPhysicalRateScale
#check roughCanonicalFourFiveIntervalPaperRateConstant
#check roughCanonicalFourFiveIntervalPaperRateConstant_nonneg
#check eventually_log_yNat_cube_le_yNat
#check abs_roughCanonicalExceptionalPhysicalInterval_card_sub_mixtureIntegral_le_paperRate
#check exists_eventually_roughCanonicalExceptionalPhysicalInterval_paperRate
#check abs_roughCanonicalExceptionalPhysicalInterval_card_sub_idealFrozen_le
#check abs_roughCanonicalExceptionalPhysicalEndpoint_length_sub_ideal_le_one
#check roughCanonicalExceptional_threePhysicalInterval_quotient_lengths
#check RoughCanonicalSignedExceptionalDeepIntervalEstimate
#check RoughCanonicalSignedExceptionalCutoffIntervalEstimate
#check roughCanonicalExceptionalPhysicalRateScale_div_L_cube_add_one_le
#check roughCanonicalExceptionalPhysicalRateScale_div_L_sq_add_one_le
#check roughCanonicalFourFiveSignedExceptionalCoreError
#check roughCanonicalFourFiveDeepCoreConstant
#check roughCanonicalFourFiveCutoffCoreConstant
#check roughCanonicalFourFiveDeepCoreConstant_nonneg
#check roughCanonicalFourFiveCutoffCoreConstant_nonneg
#check abs_roughCanonicalFourFiveSignedExceptionalCoreError_le_paperRate
#check abs_roughCanonicalSignedExceptionalCoreMass_le_cutoffPaperRate
#check RoughCanonicalSignedExceptionalFourFiveChamberInputAt
#check RoughCanonicalSignedExceptionalFourFiveRemainingInputs
#check roughCanonicalSignedExceptionalCoreChamberEstimate_of_fourFiveInput
#check exists_roughCanonicalSignedExceptionalCoreChamberEventually_of_fourFiveInputs
#check exists_eventually_roughCanonicalSignedExceptionalResidualBound_of_fourFiveInputs

end BankPaperRealization

end Erdos390.WholePaper
