import Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenPreRoundingActivePlacementSplitConnector
import Mathlib

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms BankPaperCanonicalSectionNineTopFrozenSymmetricHeightSourceInputsAt.verifiedPlacement
#print axioms bankPaperCanonicalScaledActiveSeed_le_protected_add_symmetricRebalance
#print axioms bankPaperCanonicalActualActiveMeasureConstructor_preRounding_of_symmetricPlacement
#print axioms bankPaperCanonicalSectionNineTopFrozen_preRoundingActive_postRoundingPlacement_masses
#print axioms bankPaperCanonicalActualActiveMeasureConstructor_sectionNineTopFrozen_preRounding

assert_no_sorry BankPaperCanonicalSectionNineTopFrozenSymmetricHeightSourceInputsAt.verifiedPlacement
assert_no_sorry bankPaperCanonicalScaledActiveSeed_le_protected_add_symmetricRebalance
assert_no_sorry bankPaperCanonicalActualActiveMeasureConstructor_preRounding_of_symmetricPlacement
assert_no_sorry bankPaperCanonicalSectionNineTopFrozen_preRoundingActive_postRoundingPlacement_masses
assert_no_sorry bankPaperCanonicalActualActiveMeasureConstructor_sectionNineTopFrozen_preRounding

end Erdos390.WholePaper.BankPaperRealization
