import Erdos390.WholePaper.BankPaperCanonicalPrefixAdapter
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the canonical prefix adapter -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentResidual_abs_prefixMass_le_tailPointwiseUpper
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelectorTangentInput_of_tailPointwiseMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRoundedSelectorTangentInput_of_balance_pointwise

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentResidual_abs_prefixMass_le_tailPointwiseUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelectorTangentInput_of_tailPointwiseMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRoundedSelectorTangentInput_of_balance_pointwise
