import Erdos390.WholePaper.BankPaperCanonicalSectionEightTwoZeroOneShotConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the Section 8 two-zero-cell one-shot connector -/

#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalTwoZeroHeadCell_scalarCapacity_of_asymptoticMass
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightCellMassFamily
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightCellMassFamily_isLittleO
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSymmetricHeight_twoZeroHeadCell_scalarCapacity
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSymmetricHeight_twoZeroHeadCell_rebalance_capacity
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActiveSeedAmbientWeight_eq_of_value
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_twoZeroHeadCells_feasible_of_source
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacement_symmetricHeight_of_roundedSource
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_symmetricHeight_of_source
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_initialSource_of_rowIntegral
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_ambientSource_initial
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_symmetricHeight_of_initialQuota
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_symmetricHeight_of_roundedSource
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_mul_upperTailLength_le_self
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionEight_twoZeroHeadCell_geometryInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSectionEight_twoZeroHeadCell_oneShot
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSectionEight_twoZeroHeadCell_oneShot_relevantLedgerFamily

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalTwoZeroHeadCell_scalarCapacity_of_asymptoticMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightCellMassFamily
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricHeightCellMassFamily_isLittleO
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSymmetricHeight_twoZeroHeadCell_scalarCapacity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSymmetricHeight_twoZeroHeadCell_rebalance_capacity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActiveSeedAmbientWeight_eq_of_value
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_twoZeroHeadCells_feasible_of_source
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacement_symmetricHeight_of_roundedSource
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_symmetricHeight_of_source
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_initialSource_of_rowIntegral
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_ambientSource_initial
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_symmetricHeight_of_initialQuota
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_symmetricHeight_of_roundedSource
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_mul_upperTailLength_le_self
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionEight_twoZeroHeadCell_geometryInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSectionEight_twoZeroHeadCell_oneShot
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSectionEight_twoZeroHeadCell_oneShot_relevantLedgerFamily
