import Erdos390.WholePaper.BankPaperFourFiveOrderedLastPrimeExpansion
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms mem_fourFivePrimeCoordinateBand
#print axioms mem_fourFiveOrderedPrimeTupleSet
#print axioms map_fourFiveOrderedPrimeTupleSet_eq_factorLists
#print axioms fourFiveOrderedPrimeTupleSet_card_eq_layerMass
#print axioms mem_fourFiveOrderedPrimePrefixSet
#print axioms mem_fourFiveLastPrimeFiber
#print axioms mem_fourFiveLastPrimeSplitSet
#print axioms map_fourFiveLastPrimeSplitSet_eq_tupleSet
#print axioms fourFiveLastPrimeSplitSet_card_eq_sum_fibers
#print axioms fourFiveOrderedPrimeLayerMass_eq_sum_lastPrimeFibers
#print axioms fourFiveLastPrimeFiber_eq_primeInterval
#print axioms fourFiveOrderedPrimePrefix_prod_pos
#print axioms fourFiveLastPrimeFiber_card_eq_primeCounting_sub
#print axioms fourFiveLastPrimeLower_ge_y
#print axioms abs_fourFiveLastPrimeFiber_card_sub_integral_le
#print axioms abs_fourFiveOrderedPrimeLayerMass_sub_lastPrimeIntegral_le
#print axioms exists_abs_fourFiveOrderedPrimeLayerMass_sub_lastPrimeIntegral_le

assert_no_sorry mem_fourFivePrimeCoordinateBand
assert_no_sorry mem_fourFiveOrderedPrimeTupleSet
assert_no_sorry map_fourFiveOrderedPrimeTupleSet_eq_factorLists
assert_no_sorry fourFiveOrderedPrimeTupleSet_card_eq_layerMass
assert_no_sorry mem_fourFiveOrderedPrimePrefixSet
assert_no_sorry mem_fourFiveLastPrimeFiber
assert_no_sorry mem_fourFiveLastPrimeSplitSet
assert_no_sorry map_fourFiveLastPrimeSplitSet_eq_tupleSet
assert_no_sorry fourFiveLastPrimeSplitSet_card_eq_sum_fibers
assert_no_sorry fourFiveOrderedPrimeLayerMass_eq_sum_lastPrimeFibers
assert_no_sorry fourFiveLastPrimeFiber_eq_primeInterval
assert_no_sorry fourFiveOrderedPrimePrefix_prod_pos
assert_no_sorry fourFiveLastPrimeFiber_card_eq_primeCounting_sub
assert_no_sorry fourFiveLastPrimeLower_ge_y
assert_no_sorry abs_fourFiveLastPrimeFiber_card_sub_integral_le
assert_no_sorry abs_fourFiveOrderedPrimeLayerMass_sub_lastPrimeIntegral_le
assert_no_sorry exists_abs_fourFiveOrderedPrimeLayerMass_sub_lastPrimeIntegral_le

end Erdos390.WholePaper.BankPaperRealization
