import Erdos390.WholePaper.BankPaperCanonicalGuardedPostchargeCorrectionRateClosure

/-! # Statement audit for guarded postcharge correction-rate closure -/

open Filter

namespace Erdos390.WholePaper.BankPaperRealization

#check roughCanonicalUniformGuardedPostchargeCorrectionDensityConstant
#check roughCanonicalUniformGuardedPostchargeCorrectionDensityConstant_pos
#check eventually_roughCanonicalUniformGuardedPostchargeCorrectionDensityBound
#check sum_activeGuardedPostchargeCorrectionPool_factorization_le_four_mul_div_prime
#check abs_roughCanonicalAggregateGuardedPostchargeRowCorrection_le_uniformDensity
#check eventually_abs_roughCanonicalAggregateGuardedPostchargeRowCorrection_le_strictScale
#check eventually_abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_strictScale

end Erdos390.WholePaper.BankPaperRealization
