import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightOrdinaryLogLedgerConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the exact post-height ordinary-log ledger -/

namespace Erdos390.WholePaper

#print axioms bankPaperCanonicalSelectorLogSupport
#print axioms bankPaperCanonical_log_target_eq_sum_factorization_on_selectorLogSupport
#print axioms bankPaperCanonical_log_candidate_eq_sum_factorization_on_selectorLogSupport
#print axioms bankPaperCanonical_selectorLogDefect_eq_sum_log_mul_deficit
#print axioms bankPaperCanonical_selectorWeightedResidual_eq_selectorLogDefect_div
#print axioms bankPaperCanonicalSelector_ordinaryLogCompatible_of_selectorLog
#print axioms sum_bankPaperCanonicalActiveSeedAmbientWeight_mul
#print axioms bankPaperCanonicalActualFrozenLogMass_add_activeOrdinaryLog_eq
#print axioms bankPaperCanonical_log_finset_prod_id
#print axioms GuardedCentralAnchorCertificate.selectorTailTarget_log_charge
#print axioms bankPaperCanonicalSectionNinePostHeight_activeSeed_ordinaryLogMoment_eq_logY_sub_Lambda0
#print axioms bankPaperCanonicalSectionNinePostHeight_selectorLog_eq_target
#print axioms bankPaperCanonicalSectionNinePostHeight_selectorLog_eq_target_of_prechargedTail
#print axioms bankPaperCanonicalSectionNinePostHeight_initialSelector_ordinaryLogCompatible
#print axioms bankPaperCanonicalSectionNinePostHeight_weightedActiveTarget_sub_primeLogMoment_eq_zero

assert_no_sorry bankPaperCanonicalSelectorLogSupport
assert_no_sorry bankPaperCanonical_log_target_eq_sum_factorization_on_selectorLogSupport
assert_no_sorry bankPaperCanonical_log_candidate_eq_sum_factorization_on_selectorLogSupport
assert_no_sorry bankPaperCanonical_selectorLogDefect_eq_sum_log_mul_deficit
assert_no_sorry bankPaperCanonical_selectorWeightedResidual_eq_selectorLogDefect_div
assert_no_sorry bankPaperCanonicalSelector_ordinaryLogCompatible_of_selectorLog
assert_no_sorry sum_bankPaperCanonicalActiveSeedAmbientWeight_mul
assert_no_sorry bankPaperCanonicalActualFrozenLogMass_add_activeOrdinaryLog_eq
assert_no_sorry bankPaperCanonical_log_finset_prod_id
assert_no_sorry GuardedCentralAnchorCertificate.selectorTailTarget_log_charge
assert_no_sorry bankPaperCanonicalSectionNinePostHeight_activeSeed_ordinaryLogMoment_eq_logY_sub_Lambda0
assert_no_sorry bankPaperCanonicalSectionNinePostHeight_selectorLog_eq_target
assert_no_sorry bankPaperCanonicalSectionNinePostHeight_selectorLog_eq_target_of_prechargedTail
assert_no_sorry bankPaperCanonicalSectionNinePostHeight_initialSelector_ordinaryLogCompatible
assert_no_sorry bankPaperCanonicalSectionNinePostHeight_weightedActiveTarget_sub_primeLogMoment_eq_zero

end Erdos390.WholePaper
