import Erdos390.WholePaper.BankPaperFixedExceptionalValuationFibers
import Mathlib.Util.AssertNoSorry

/-! # Transitive axiom audit for the fixed exceptional valuation fibres -/

#print axioms Erdos390.WholePaper.mem_paperExceptionalSmoothParts
#print axioms Erdos390.WholePaper.mem_paperExceptionalSmoothFiber
#print axioms Erdos390.WholePaper.mem_paperExceptionalRoughCandidates
#print axioms Erdos390.WholePaper.paperExceptionalUpperFactors_pos
#print axioms Erdos390.WholePaper.paperExceptionalUpperFactors_prod_factorization_eq_smoothFiberSum
#print axioms Erdos390.WholePaper.completeRoughLabel_injOn_paperExceptionalSmoothFiber
#print axioms Erdos390.WholePaper.completeRoughLabel_mem_paperExceptionalRoughCandidates
#print axioms Erdos390.WholePaper.paperExceptionalSmoothFiber_card_le_roughCandidates
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_factorization_le_smoothFiberSum
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_factorization_le_roughCandidateSum
#print axioms Erdos390.WholePaper.eventually_paperExceptionalRoughCandidates_card_le_canonicalLambdaSquare
#print axioms Erdos390.WholePaper.eventually_paperExceptionalSmoothFiber_card_le_canonicalLambdaSquare

assert_no_sorry Erdos390.WholePaper.mem_paperExceptionalSmoothParts
assert_no_sorry Erdos390.WholePaper.mem_paperExceptionalSmoothFiber
assert_no_sorry Erdos390.WholePaper.mem_paperExceptionalRoughCandidates
assert_no_sorry Erdos390.WholePaper.paperExceptionalUpperFactors_pos
assert_no_sorry Erdos390.WholePaper.paperExceptionalUpperFactors_prod_factorization_eq_smoothFiberSum
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_injOn_paperExceptionalSmoothFiber
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_mem_paperExceptionalRoughCandidates
assert_no_sorry Erdos390.WholePaper.paperExceptionalSmoothFiber_card_le_roughCandidates
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_factorization_le_smoothFiberSum
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_factorization_le_roughCandidateSum
assert_no_sorry Erdos390.WholePaper.eventually_paperExceptionalRoughCandidates_card_le_canonicalLambdaSquare
assert_no_sorry Erdos390.WholePaper.eventually_paperExceptionalSmoothFiber_card_le_canonicalLambdaSquare
