import Erdos390.WholePaper.BankPaperCanonicalSelectorDeficitPaperRateClosureConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the canonical selector-deficit paper-rate closure -/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceToGuardedCorrectionValuationDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitSourceToGuardedCorrectionValuationReindex_iff_defect_eq_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceRawCorrectionValuationDefect_eq_sourceToGuarded_add_guardedRaw
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment_of_chargeDvd
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalBalancedRawSignedValuationResidualBound
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitMediumPrimeImplementationRateInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_sub_sub_sub_le_scale
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPreSelector_deficit_le_scale_of_complete_and_implementation
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPreSelector_deficit_le_scale_of_complete_and_implementation_of_chargeDvd
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPreSelector_deficit_le_scale_of_components
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedCompleteSignedResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitCompleteSignedResidual_eq_balanced
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_eventually_roughCanonicalBalancedCompleteSignedResidualBound_of_raw

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceToGuardedCorrectionValuationDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitSourceToGuardedCorrectionValuationReindex_iff_defect_eq_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceRawCorrectionValuationDefect_eq_sourceToGuarded_add_guardedRaw
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment_of_chargeDvd
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalBalancedRawSignedValuationResidualBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitMediumPrimeImplementationRateInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_sub_sub_sub_le_scale
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPreSelector_deficit_le_scale_of_complete_and_implementation
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPreSelector_deficit_le_scale_of_complete_and_implementation_of_chargeDvd
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalPostHfitStructuredPreSelector_deficit_le_scale_of_components
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedCompleteSignedResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitCompleteSignedResidual_eq_balanced
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_eventually_roughCanonicalBalancedCompleteSignedResidualBound_of_raw
