import Erdos390.WholePaper.BankPaperCanonicalRawBroadSurplusAsymptotic
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit: eventual raw broad-pool surplus

All 19 public theorems, together with the proof-valued row constructor, are
printed and checked for proof gaps.
-/

#print axioms Erdos390.WholePaper.roughCanonicalPoolDickmanFloor_pos
#print axioms Erdos390.WholePaper.roughCanonicalPoolDickmanFloor_le_rho
#print axioms Erdos390.WholePaper.roughCanonical_dickmanEndpointMain_sub_lower
#print axioms Erdos390.WholePaper.roughCanonical_smoothInterval_card_lower
#print axioms Erdos390.WholePaper.roughHead_sum_moebius_div_eq_density
#print axioms Erdos390.WholePaper.roughCanonical_smoothInterval_divisorShift_error
#print axioms Erdos390.WholePaper.roughCanonical_headFreeSmoothInterval_lower_of_shift
#print axioms Erdos390.WholePaper.roughCanonical_headFreeSmoothInterval_card_lower
#print axioms Erdos390.WholePaper.roughCanonicalRawBroadPoolDensity_pos
#print axioms Erdos390.WholePaper.roughCanonicalBroadCorrectionPool_card_eq_headFreeSmoothInterval
#print axioms Erdos390.WholePaper.roughCanonicalBroadCorrectionPool_card_eq_headFreeSmoothInterval_of_isCompleteRoughLabel
#print axioms Erdos390.WholePaper.roughUpperCompleteRoughRowTarget_le_div_add_one
#print axioms Erdos390.WholePaper.BankPaperRealization.rawCanonicalRowOfGuardedLabel
#print axioms Erdos390.WholePaper.roughCanonical_activeLabel_div_scale_lower
#print axioms Erdos390.WholePaper.roughCanonical_activeLabel_three_mul_le_half
#print axioms Erdos390.WholePaper.eventually_roughCanonical_activeRawBroadPool_linear_lower
#print axioms Erdos390.WholePaper.eventually_roughCanonicalActiveIntrinsicRawBroadSurplus
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalActiveRawBroadSurplus
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonical_active_intrinsic_guard_capacity_inputs
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonical_active_guard_capacity_inputs

assert_no_sorry Erdos390.WholePaper.roughCanonicalPoolDickmanFloor_pos
assert_no_sorry Erdos390.WholePaper.roughCanonicalPoolDickmanFloor_le_rho
assert_no_sorry Erdos390.WholePaper.roughCanonical_dickmanEndpointMain_sub_lower
assert_no_sorry Erdos390.WholePaper.roughCanonical_smoothInterval_card_lower
assert_no_sorry Erdos390.WholePaper.roughHead_sum_moebius_div_eq_density
assert_no_sorry Erdos390.WholePaper.roughCanonical_smoothInterval_divisorShift_error
assert_no_sorry Erdos390.WholePaper.roughCanonical_headFreeSmoothInterval_lower_of_shift
assert_no_sorry Erdos390.WholePaper.roughCanonical_headFreeSmoothInterval_card_lower
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawBroadPoolDensity_pos
assert_no_sorry Erdos390.WholePaper.roughCanonicalBroadCorrectionPool_card_eq_headFreeSmoothInterval
assert_no_sorry Erdos390.WholePaper.roughCanonicalBroadCorrectionPool_card_eq_headFreeSmoothInterval_of_isCompleteRoughLabel
assert_no_sorry Erdos390.WholePaper.roughUpperCompleteRoughRowTarget_le_div_add_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.rawCanonicalRowOfGuardedLabel
assert_no_sorry Erdos390.WholePaper.roughCanonical_activeLabel_div_scale_lower
assert_no_sorry Erdos390.WholePaper.roughCanonical_activeLabel_three_mul_le_half
assert_no_sorry Erdos390.WholePaper.eventually_roughCanonical_activeRawBroadPool_linear_lower
assert_no_sorry Erdos390.WholePaper.eventually_roughCanonicalActiveIntrinsicRawBroadSurplus
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalActiveRawBroadSurplus
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonical_active_intrinsic_guard_capacity_inputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonical_active_guard_capacity_inputs
