import Erdos390.WholePaper.BankPaperCanonicalRatioCellTraffic
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for canonical ratio-cell traffic envelopes -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTailLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTailUpper
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTailLower_le_upper
#print axioms Erdos390.WholePaper.bankPaperCanonical_fixedCutoff_le_exponentBandLower
#print axioms Erdos390.WholePaper.bankPaperCanonical_fixedCutoff_le_ratioCellTailLower
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellTail_mem_interval
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTailMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellTail_harmonic_le_majorant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTailMajorant_nonneg
#print axioms Erdos390.WholePaper.TangentFixedRatioPrimeCountLower
#print axioms Erdos390.WholePaper.exists_fixedRatioPrimeCountLower_cutoff
#print axioms Erdos390.WholePaper.exists_fixedRatioPrimeCountLower_and_Mertens_cutoff
#print axioms Erdos390.WholePaper.bankPaperCanonical_lastRawRatioCutoff_lt_bandUpper
#print axioms Erdos390.WholePaper.bankPaperCanonical_fixedRatioPrimeCounting_le_ratioCellCard
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellCard_PNT_lower
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellCutEnvelope
#print axioms Erdos390.WholePaper.bankPaperCanonicalHarmonicResidualL1Envelope
#print axioms Erdos390.WholePaper.bankPaperCanonicalHarmonicResidualL1Majorant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTotalTrafficEnvelope
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTotalTrafficMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonical_weightedResidual_le_harmonicScale
#print axioms Erdos390.WholePaper.bankPaperCanonicalHarmonicResidualL1Envelope_le_majorant
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellCutTraffic_le_envelope
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellTotalTraffic_le_envelope
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellTotalTraffic_le_majorant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellPortNumeratorEnvelope
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellTail_eq_zero_of_lastRaw_eq_zero
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellPointwisePortUpper_eq_zero_of_lastRaw_eq_zero
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellPointwisePortUpper_le_envelope_div_card
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellPNTDenominator
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellPNTDenominator_pos
#print axioms Erdos390.WholePaper.bankPaperCanonical_weightedRatioCellPointwisePortUpper_le_PNTEnvelope
#print axioms Erdos390.WholePaper.bankPaperCanonical_weightedRatioCellUniformPortLoad_le_PNTEnvelope

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTailLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTailUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTailLower_le_upper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_fixedCutoff_le_exponentBandLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_fixedCutoff_le_ratioCellTailLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellTail_mem_interval
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTailMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellTail_harmonic_le_majorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTailMajorant_nonneg
assert_no_sorry Erdos390.WholePaper.TangentFixedRatioPrimeCountLower
assert_no_sorry Erdos390.WholePaper.exists_fixedRatioPrimeCountLower_cutoff
assert_no_sorry Erdos390.WholePaper.exists_fixedRatioPrimeCountLower_and_Mertens_cutoff
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_lastRawRatioCutoff_lt_bandUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_fixedRatioPrimeCounting_le_ratioCellCard
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellCard_PNT_lower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellCutEnvelope
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalHarmonicResidualL1Envelope
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalHarmonicResidualL1Majorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTotalTrafficEnvelope
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTotalTrafficMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_weightedResidual_le_harmonicScale
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalHarmonicResidualL1Envelope_le_majorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellCutTraffic_le_envelope
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellTotalTraffic_le_envelope
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellTotalTraffic_le_majorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellPortNumeratorEnvelope
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellTail_eq_zero_of_lastRaw_eq_zero
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellPointwisePortUpper_eq_zero_of_lastRaw_eq_zero
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellPointwisePortUpper_le_envelope_div_card
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellPNTDenominator
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellPNTDenominator_pos
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_weightedRatioCellPointwisePortUpper_le_PNTEnvelope
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_weightedRatioCellUniformPortLoad_le_PNTEnvelope
