import Erdos390.WholePaper.BankPaperCanonicalPostHfitBalancedAlphaEventually
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for eventual Post-Hfit balanced-alpha feasibility -/

#print axioms Erdos390.WholePaper.roughHeadBalancedAlpha_mem_Icc_of_tail_lower
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitBalancedAlpha_mem_Icc_of_paperBounds
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalPostHfitBalancedAlpha_mem_Icc
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_K0_eventually_bankPaperCanonicalPostHfitBalancedAlpha_mem_Icc_of_paperBeta
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_paperParameters_eventually_bankPaperCanonicalPostHfitBalancedAlpha_mem_Icc

assert_no_sorry Erdos390.WholePaper.roughHeadBalancedAlpha_mem_Icc_of_tail_lower
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitBalancedAlpha_mem_Icc_of_paperBounds
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalPostHfitBalancedAlpha_mem_Icc
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_K0_eventually_bankPaperCanonicalPostHfitBalancedAlpha_mem_Icc_of_paperBeta
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_paperParameters_eventually_bankPaperCanonicalPostHfitBalancedAlpha_mem_Icc
