import Erdos390.WholePaper.BankPaperCanonicalUpperConstructionEventually
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the eventual canonical upper connector -/

#print axioms Erdos390.WholePaper.BankPaperCanonicalPostTangentContinuationAtDepth
#print axioms Erdos390.WholePaper.exists_depth_bankPaper_f_le_upperEndpoint_of_canonicalPostTangentContinuation
#print axioms Erdos390.WholePaper.eventually_bankPaper_f_le_upperEndpoint_of_canonicalPostTangentContinuation

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalPostTangentContinuationAtDepth
assert_no_sorry Erdos390.WholePaper.exists_depth_bankPaper_f_le_upperEndpoint_of_canonicalPostTangentContinuation
assert_no_sorry Erdos390.WholePaper.eventually_bankPaper_f_le_upperEndpoint_of_canonicalPostTangentContinuation
