import Erdos390.WholePaper.BankPaperCanonicalSectionNineActiveLedgerConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the Section 9 active-ledger density connector -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedCellDensityFloor
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedCellDensityFloor_pos
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedCellDensityFloor_le
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonical_activeLedger_of_scaledSeed_cellDensity
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_eventually_bankPaperCanonical_activeLedger_of_q0_isBigO

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedCellDensityFloor
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedCellDensityFloor_pos
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedCellDensityFloor_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonical_activeLedger_of_scaledSeed_cellDensity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_eventually_bankPaperCanonical_activeLedger_of_q0_isBigO
