import Erdos390.WholePaper.BankPaperCanonicalGuardedSectionNineContinuation
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the guarded Section 9 continuation

All eight public declarations are printed and checked for `sorry`.
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet_eq_distributedGuardedCandidates
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet_cleanEndpoints
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalGuardedSmoothFlexibleQuota
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_eq_intCast
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalGuardedSectionNineContinuation
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSectionNineContinuation_capacityInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSectionNineContinuation_exists_assemblyFrontEnd
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSectionNineContinuation_selectorHandoff

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet_eq_distributedGuardedCandidates
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet_cleanEndpoints
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalGuardedSmoothFlexibleQuota
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_eq_intCast
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalGuardedSectionNineContinuation
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSectionNineContinuation_capacityInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSectionNineContinuation_exists_assemblyFrontEnd
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSectionNineContinuation_selectorHandoff
