import Erdos390.WholePaper.BankPaperCanonicalArbitrarySourceSelectorDeficitPaperRateClosureConnector

/-!
# Statement audit for the arbitrary-source selector-deficit closure

The audited interface keeps the supplied source literal and exposes the
two implementation defects separately before specializing to the rounded
frozen-top source.
-/

namespace Erdos390.WholePaper

open Erdos390.Full
open Erdos390.Full.ArithmeticModel
open Erdos390.Full.PaperBridgeFit

noncomputable section

namespace BankPaperRealization

#check roughCanonicalSourceToGuardedCorrectionValuationDefect
#check roughCanonicalSourceRawCorrectionValuationDefect_eq_sourceToGuarded_add_guardedRaw
#check roughCanonicalParameterizedCompleteSignedResidual
#check roughCanonicalParameterizedCompleteSignedResidual_eq_balanced
#check bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment
#check bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_eq_completeSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment_of_chargeDvd
#check BankPaperCanonicalMediumPrimeImplementationRateInputsOfSource
#check abs_bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_deficit_le_scale_of_complete_and_implementation
#check bankPaperCanonicalTopFrozenRoundedPostHfitStructuredPreSelector_deficit_eq_balancedCompleteSignedResidual_sub_sourceToGuardedDefect_sub_guardedRawDefect_sub_moment
#check BankPaperCanonicalTopFrozenRoundedMediumPrimeImplementationRateInputs
#check abs_bankPaperCanonicalTopFrozenRoundedPostHfitStructuredPreSelector_deficit_le_scale_of_balancedComplete_and_implementation

end BankPaperRealization

end

end Erdos390.WholePaper
