import Erdos390.WholePaper.BankPaperPrechargeUniformCapacityAsymptotic
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for uniform precharge capacity -/

#print axioms Erdos390.WholePaper.eventually_bankPaperPrecharge_perPrimeCapacity
#print axioms Erdos390.WholePaper.bankPaperPrechargeCubicLogMajorant_normalized_tendsto_zero
#print axioms Erdos390.WholePaper.bankPaperPrechargeUniformCapacityMajorant_normalized_tendsto_zero
#print axioms Erdos390.WholePaper.eventually_bankPaperPrechargeUniformCapacityCost_le_majorant
#print axioms Erdos390.WholePaper.bankPaperPrechargeUniformCapacityCost_normalized_tendsto_zero
#print axioms Erdos390.WholePaper.eventually_bankPaperPrecharge_uniformMovingPrimeCapacity

assert_no_sorry Erdos390.WholePaper.eventually_bankPaperPrecharge_perPrimeCapacity
assert_no_sorry Erdos390.WholePaper.bankPaperPrechargeCubicLogMajorant_normalized_tendsto_zero
assert_no_sorry Erdos390.WholePaper.bankPaperPrechargeUniformCapacityMajorant_normalized_tendsto_zero
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperPrechargeUniformCapacityCost_le_majorant
assert_no_sorry Erdos390.WholePaper.bankPaperPrechargeUniformCapacityCost_normalized_tendsto_zero
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperPrecharge_uniformMovingPrimeCapacity
