import Erdos390.WholePaper.BankPaperCanonicalSectionNineSynchronizedPostHfitProducer
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper

namespace BankPaperRealization

#print axioms BankPaperCanonicalSectionNinePostHfitLocalInputsAt
#print axioms BankPaperCanonicalSectionNinePostHfitSourceStateLocalInputsAt
#print axioms
  bankPaperCanonicalSectionNinePostHfitSourceStateLocalInputsAt_of_localInputs
#print axioms BankPaperCanonicalSectionNinePostHfitLocalSupplier
#print axioms BankPaperCanonicalSectionNinePostHfitSourceStateLocalSupplier
#print axioms
  bankPaperCanonicalSectionNineSynchronizedPostHfitInputAt_of_sourceStateLocalInputs
#print axioms
  bankPaperCanonicalSectionNineSynchronizedPostHfitInputAt_of_localInputs
#print axioms
  bankPaperCanonicalSectionNineSynchronizedPostHfitInput_of_combinedChargeTerminal
#print axioms
  bankPaperCanonicalSectionNineSynchronizedPostHfitInput_of_combinedChargeTerminal_sourceStateLocalSupplier

assert_no_sorry BankPaperCanonicalSectionNinePostHfitLocalInputsAt
assert_no_sorry BankPaperCanonicalSectionNinePostHfitSourceStateLocalInputsAt
assert_no_sorry
  bankPaperCanonicalSectionNinePostHfitSourceStateLocalInputsAt_of_localInputs
assert_no_sorry BankPaperCanonicalSectionNinePostHfitLocalSupplier
assert_no_sorry BankPaperCanonicalSectionNinePostHfitSourceStateLocalSupplier
assert_no_sorry
  bankPaperCanonicalSectionNineSynchronizedPostHfitInputAt_of_sourceStateLocalInputs
assert_no_sorry
  bankPaperCanonicalSectionNineSynchronizedPostHfitInputAt_of_localInputs
assert_no_sorry
  bankPaperCanonicalSectionNineSynchronizedPostHfitInput_of_combinedChargeTerminal
assert_no_sorry
  bankPaperCanonicalSectionNineSynchronizedPostHfitInput_of_combinedChargeTerminal_sourceStateLocalSupplier

end BankPaperRealization

end Erdos390.WholePaper
