import Erdos390.WholePaper.BankPaperCanonicalStructuredPrebridgeLedgerConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the structured prebridge ledger connector -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellAmbientSourceSelector
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellAmbientSourceSelector_apply_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellAmbientSourceSelector_apply_of_not_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellRebalance_ambient_sub_eq_zero_of_not_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalOutsideSelector_eq_scaledActiveSeedAmbientWeight_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_twoZeroHeadCells_sub_source_of_active
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_twoZeroHeadCells_sub_source
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells_of_active
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells_scaled
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells_scaled_of_physicalIntervals
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells_of_physicalIntervals

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellAmbientSourceSelector
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellAmbientSourceSelector_apply_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellAmbientSourceSelector_apply_of_not_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTwoZeroHeadCellRebalance_ambient_sub_eq_zero_of_not_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalOutsideSelector_eq_scaledActiveSeedAmbientWeight_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_twoZeroHeadCells_sub_source_of_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_twoZeroHeadCells_sub_source
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells_of_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells_scaled
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells_scaled_of_physicalIntervals
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePrebridgeMomentLedger_twoZeroHeadCells_of_physicalIntervals
