import Erdos390.WholePaper.BankPaperCanonicalSectionNineAssembly
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the canonical Section 9 assembly -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentEdges
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentEdgeFlow
#print axioms Erdos390.WholePaper.BankPaperCanonicalTangentSplitRequest
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentRequestSource
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentRequestTarget
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentLowerCard
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentUpdatedSelector
#print axioms Erdos390.WholePaper.tangentSplitCleanMultiplier_pos
#print axioms Erdos390.WholePaper.tangentSplitCleanMultiplier_endpoints_mem_roughRawCandidateSet
#print axioms Erdos390.WholePaper.tangentSplitEndpoints_completeRoughLabel_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_canonicalSectionNinePostTangentOutput_of_cleanListLower
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_exists_canonicalSectionNinePostTangentOutput
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_canonicalSectionNineCleanListLower
#print axioms Erdos390.WholePaper.BankPaperRealization.canonicalPostTangentContinuationData_of_output

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentEdges
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentEdgeFlow
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalTangentSplitRequest
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentRequestSource
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentRequestTarget
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentLowerCard
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentUpdatedSelector
assert_no_sorry Erdos390.WholePaper.tangentSplitCleanMultiplier_pos
assert_no_sorry Erdos390.WholePaper.tangentSplitCleanMultiplier_endpoints_mem_roughRawCandidateSet
assert_no_sorry Erdos390.WholePaper.tangentSplitEndpoints_completeRoughLabel_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_canonicalSectionNinePostTangentOutput_of_cleanListLower
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_exists_canonicalSectionNinePostTangentOutput
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_canonicalSectionNineCleanListLower
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.canonicalPostTangentContinuationData_of_output
