import Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminal
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the distributed Section 9 terminal

All eight public declarations are printed and checked for proof placeholders
in source order.
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineFinalPayload_to_outputData
#print axioms Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminalAtDepth
#print axioms Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminalAtDepth.to_canonicalCapacityAtDepth
#print axioms Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminalAtDepth.to_postTangentContinuationAtDepth
#print axioms Erdos390.WholePaper.eventually_bankPaper_f_le_upperEndpoint_of_canonicalDistributedSectionNineTerminalAtDepth
#print axioms Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminal
#print axioms Erdos390.WholePaper.mainNormalizedLimit_of_canonicalDistributedSectionNineTerminal
#print axioms Erdos390.WholePaper.mainAsymptotic_of_canonicalDistributedSectionNineTerminal

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineFinalPayload_to_outputData
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminalAtDepth
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminalAtDepth.to_canonicalCapacityAtDepth
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminalAtDepth.to_postTangentContinuationAtDepth
assert_no_sorry Erdos390.WholePaper.eventually_bankPaper_f_le_upperEndpoint_of_canonicalDistributedSectionNineTerminalAtDepth
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalDistributedSectionNineTerminal
assert_no_sorry Erdos390.WholePaper.mainNormalizedLimit_of_canonicalDistributedSectionNineTerminal
assert_no_sorry Erdos390.WholePaper.mainAsymptotic_of_canonicalDistributedSectionNineTerminal
