import Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSymmetricHeightLocalInputConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the frozen-top symmetric-height finite input
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineTopFrozenSymmetricHeightSourceInputsAt
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineTopFrozenSymmetricHeightDependentInputsAt
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_bankPaperCanonicalTopFrozenRoundedPostHfitGuardedSlackPackage_of_symmetricHeightInputs

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineTopFrozenSymmetricHeightSourceInputsAt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineTopFrozenSymmetricHeightDependentInputsAt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_bankPaperCanonicalTopFrozenRoundedPostHfitGuardedSlackPackage_of_symmetricHeightInputs
