import Erdos390.WholePaper.BankPaperCanonicalSignedResidualSelectorIdentification
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for exact signed-residual selector identification -/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawSignedValuationResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSignedResidualTargetLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSignedResidualSelectorLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalNonexceptionalGuardedCandidateSet
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalNonexceptionalGuardedCandidateSet
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_raw_sub_exceptional_sub_nonexceptionalDeleted_eq_guardedNonexceptional
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceValuationCorrectionMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceRawCorrectionValuationDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSignedResidualSelectorLedger_iff_correctionMoment_eq_raw
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSignedResidualSelectorLedger_iff_sourceRawCorrectionDefect_eq_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_bankPaperConstantPoolCorrection_mul_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeCorrectionDensity_eq_rawLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_guardedPostchargeRowCorrectedWeight_mul_factorization_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedPostchargeRowCorrection
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_apply_of_mem_nonsmoothRow
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_apply_of_mem_exceptionalNonsmoothRow
#print axioms Erdos390.WholePaper.BankPaperRealization.paperExceptionalUpperFactors_eq_fixed_union_exceptionalDonors
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSignedResidualTargetLedger_of_chargeDvd
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_eq_completeSignedResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_eq_completeSignedResidual_sub_sourceDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_eq_completeSignedResidual_of_chargeDvd
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredPreSelector_deficit_eq_completeSignedResidual_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceDefect_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredPreSelector_deficit_eq_completeSignedResidual_of_moment_eq_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitCompleteSignedResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceValuationCorrectionMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceRawCorrectionValuationDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitSourceToGuardedCorrectionValuationReindex
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitGuardedToRawCorrectionValuationReindex
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitGlobalSourceSignedResidualSelectorLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitGlobalSourceSignedResidualSelectorLedger_iff_correctionMoment_eq_raw
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitGlobalSourceSignedResidualSelectorLedger_of_reindexes
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceDefect_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceDefect_sub_moment_of_chargeDvd
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_moment_of_chargeDvd
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_of_moment_eq_zero

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawSignedValuationResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSignedResidualTargetLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSignedResidualSelectorLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalNonexceptionalGuardedCandidateSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalNonexceptionalGuardedCandidateSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_raw_sub_exceptional_sub_nonexceptionalDeleted_eq_guardedNonexceptional
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceValuationCorrectionMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceRawCorrectionValuationDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSignedResidualSelectorLedger_iff_correctionMoment_eq_raw
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSignedResidualSelectorLedger_iff_sourceRawCorrectionDefect_eq_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_bankPaperConstantPoolCorrection_mul_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeCorrectionDensity_eq_rawLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_guardedPostchargeRowCorrectedWeight_mul_factorization_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedPostchargeRowCorrection
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_apply_of_mem_nonsmoothRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelector_apply_of_mem_exceptionalNonsmoothRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperExceptionalUpperFactors_eq_fixed_union_exceptionalDonors
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSignedResidualTargetLedger_of_chargeDvd
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_eq_completeSignedResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_eq_completeSignedResidual_sub_sourceDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_eq_completeSignedResidual_of_chargeDvd
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredPreSelector_deficit_eq_completeSignedResidual_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceDefect_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredPreSelector_deficit_eq_completeSignedResidual_of_moment_eq_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitCompleteSignedResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceValuationCorrectionMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceRawCorrectionValuationDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitSourceToGuardedCorrectionValuationReindex
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitGuardedToRawCorrectionValuationReindex
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitGlobalSourceSignedResidualSelectorLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitGlobalSourceSignedResidualSelectorLedger_iff_correctionMoment_eq_raw
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitGlobalSourceSignedResidualSelectorLedger_of_reindexes
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceDefect_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_sourceDefect_sub_moment_of_chargeDvd
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_sub_moment_of_chargeDvd
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelector_deficit_eq_completeSignedResidual_of_moment_eq_zero
