import Erdos390.WholePaper.BankPaperCanonicalSectionNineLedgerBackedWitnesswiseFinalPayloadConnector
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper

#print axioms
  BankPaperCanonicalSectionNineLedgerBackedWitnesswiseAnalyticCompletion
#print axioms
  BankPaperCanonicalSectionNineLedgerBackedSourceStateWitnesswiseAnalyticCompletion
#print axioms
  bankPaperCanonicalSectionNineWitnesswiseAnalyticCompletion_of_ledgerBacked
#print axioms
  exists_bankPaperCanonicalSectionNineParameterSynchronizedFinalPayload_of_ledgerBackedWitnesswiseAnalyticCompletion
#print axioms
  exists_bankPaperCanonicalSectionNineParameterSynchronizedFinalPayload_of_ledgerBackedSourceStateWitnesswiseAnalyticCompletion
#print axioms
  mainAsymptotic_of_ledgerBackedSourceStateWitnesswiseAnalyticCompletion

assert_no_sorry
  BankPaperCanonicalSectionNineLedgerBackedWitnesswiseAnalyticCompletion
assert_no_sorry
  BankPaperCanonicalSectionNineLedgerBackedSourceStateWitnesswiseAnalyticCompletion
assert_no_sorry
  bankPaperCanonicalSectionNineWitnesswiseAnalyticCompletion_of_ledgerBacked
assert_no_sorry
  exists_bankPaperCanonicalSectionNineParameterSynchronizedFinalPayload_of_ledgerBackedWitnesswiseAnalyticCompletion
assert_no_sorry
  exists_bankPaperCanonicalSectionNineParameterSynchronizedFinalPayload_of_ledgerBackedSourceStateWitnesswiseAnalyticCompletion
assert_no_sorry
  mainAsymptotic_of_ledgerBackedSourceStateWitnesswiseAnalyticCompletion

end Erdos390.WholePaper
