import Erdos390.WholePaper.BankPaperFourFiveReciprocalPrimeBV
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveReciprocalBVSafeCutoff_ge_uniformCutoff
#print axioms fourFiveReciprocalBVSafeCutoff_ge_two
#print axioms sum_range_fourFiveReciprocalPrimeAtom
#print axioms sum_range_fourFiveAnchoredReciprocalPrimeAtom
#print axioms sum_range_fourFiveAnchoredLogLogCellAtom
#print axioms sum_range_fourFiveReciprocalPrimeSignedCell
#print axioms fourFiveReciprocalPrimeBVDefect_eq_prime_sub_logLogCells
#print axioms fourFiveFiniteBV_by_parts
#print axioms abs_sum_Ioc_mul_le_prefixBound_mul_rightDiscreteBVNorm
#print axioms abs_fourFiveReciprocalPrimeDiscrepancy_le_uniform
#print axioms abs_fourFiveReciprocalPrimeBVDefect_le_uniform
#print axioms abs_fourFiveWeightedReciprocalPrimeSum_sub_logLogCells_le_uniform

assert_no_sorry fourFiveReciprocalBVSafeCutoff_ge_uniformCutoff
assert_no_sorry fourFiveReciprocalBVSafeCutoff_ge_two
assert_no_sorry sum_range_fourFiveReciprocalPrimeAtom
assert_no_sorry sum_range_fourFiveAnchoredReciprocalPrimeAtom
assert_no_sorry sum_range_fourFiveAnchoredLogLogCellAtom
assert_no_sorry sum_range_fourFiveReciprocalPrimeSignedCell
assert_no_sorry fourFiveReciprocalPrimeBVDefect_eq_prime_sub_logLogCells
assert_no_sorry fourFiveFiniteBV_by_parts
assert_no_sorry abs_sum_Ioc_mul_le_prefixBound_mul_rightDiscreteBVNorm
assert_no_sorry abs_fourFiveReciprocalPrimeDiscrepancy_le_uniform
assert_no_sorry abs_fourFiveReciprocalPrimeBVDefect_le_uniform
assert_no_sorry abs_fourFiveWeightedReciprocalPrimeSum_sub_logLogCells_le_uniform

end Erdos390.WholePaper.BankPaperRealization
