import Erdos390.WholePaper.BankPaperCanonicalTopFrozenRoundedSourceStateEventualConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the eventual frozen-top rounded source state -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonicalSymmetricInitialCellMassFamily
#print axioms BankPaperRealization.bankPaperCanonicalSymmetricInitialCellMassFamily_isLittleO
#print axioms BankPaperRealization.eventually_bankPaperCanonicalSymmetricInitial_twoZeroHeadCell_rebalance_capacity
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_sub_qTildeSource_eq_ambient_sub
#print axioms BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedSourceSelector_mul_headValuation_eq_qTilde
#print axioms BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedSourceSelector_mul_factorization_eq_qTilde_of_yNat_lt
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_deficitSupportedOnPrimeBand_of_qTilde
#print axioms BankPaperRealization.BankPaperCanonicalTopFrozenRoundedSourceResidualInputsAt
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSelectorSourceState_of_qTildeSource
#print axioms BankPaperRealization.eventually_bankPaperCanonicalTopFrozenRoundedSelectorSourceState_of_residualInputs

assert_no_sorry BankPaperRealization.bankPaperCanonicalSymmetricInitialCellMassFamily
assert_no_sorry BankPaperRealization.bankPaperCanonicalSymmetricInitialCellMassFamily_isLittleO
assert_no_sorry BankPaperRealization.eventually_bankPaperCanonicalSymmetricInitial_twoZeroHeadCell_rebalance_capacity
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_sub_qTildeSource_eq_ambient_sub
assert_no_sorry BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedSourceSelector_mul_headValuation_eq_qTilde
assert_no_sorry BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedSourceSelector_mul_factorization_eq_qTilde_of_yNat_lt
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_deficitSupportedOnPrimeBand_of_qTilde
assert_no_sorry BankPaperRealization.BankPaperCanonicalTopFrozenRoundedSourceResidualInputsAt
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSelectorSourceState_of_qTildeSource
assert_no_sorry BankPaperRealization.eventually_bankPaperCanonicalTopFrozenRoundedSelectorSourceState_of_residualInputs

end Erdos390.WholePaper
