import Erdos390.WholePaper.BankPaperFourFiveRoughChamberReduction

/-! Public statement audit for the finite four-to-five rough-chamber reduction. -/

open Erdos390.WholePaper.BankPaperRealization

#check fourFiveRoughInterval
#check fourFiveRoughOmegaLayer
#check fourFiveRoughRepeatedInterval
#check fourFiveRoughRepeatedOmegaLayer
#check mem_fourFiveRoughInterval
#check mem_fourFiveRoughOmegaLayer
#check mem_fourFiveRoughRepeatedInterval
#check mem_fourFiveRoughRepeatedOmegaLayer
#check fourFiveRoughRepeatedOmegaLayer_eq_filter_not_squarefree
#check fourFiveRough_cardFactors_le_four
#check fourFiveRoughInterval_eq_biUnion_omegaLayers
#check fourFiveRoughInterval_card_eq_sum_omegaLayers
#check fourFiveRoughRepeatedInterval_card_eq_sum_omegaLayers
#check fourFiveOrderedPrimeMultiplicity
#check fourFiveOrderedPrimeFactorLists
#check fourFiveOrderedPrimeLayerMass
#check fourFiveOrderedPrimeMultiplicity_le_factorial
#check fourFiveOrderedPrimeMultiplicity_eq_factorial_of_squarefree
#check mem_fourFiveOrderedPrimeFactorLists
#check mem_fourFiveOrderedPrimeFactorLists_iff
#check fourFiveOrderedPrimeFactorListFibers_pairwiseDisjoint
#check fourFiveOrderedPrimeFactorLists_card
#check fourFiveOrderedPrimeLayerMass_le_factorial_mul_card
#check factorial_mul_card_le_orderedPrimeLayerMass_add_repeated
#check fourFiveOrderedPrimeLayerRatio_le_card
#check abs_fourFiveRoughOmegaLayer_card_sub_orderedRatio_le_repeated
#check fourFiveOrderedPrimeMixture
#check abs_fourFiveRoughInterval_card_sub_orderedPrimeMixture_le_repeated
#check fourFiveRepeatedPrimeSquareSet
#check fourFiveSquareMultiples
#check mem_fourFiveRepeatedPrimeSquareSet
#check mem_fourFiveSquareMultiples
#check fourFiveRoughRepeatedInterval_subset_repeatedPrimeSquareSet
#check fourFiveRepeatedPrimeSquareSet_subset_biUnion_squareMultiples
#check fourFiveSquareMultiples_card
#check fourFiveRepeatedPrimeSquareSet_card_le_div
#check fourFiveRoughRepeatedInterval_card_le_div
#check FourFiveOrderedPrimeMixtureEstimate
#check abs_fourFiveRoughInterval_card_sub_mainTerm_le_of_orderedEstimate
#check abs_fourFiveRoughInterval_card_sub_mainTerm_le_div_add_error
#check abs_sum_weighted_fourFiveRoughInterval_sub_mainTerm_le
