import Erdos390.WholePaper.BankPaperCanonicalTopFrozenSelectorTailSupportReductionConnector

/-! # Statement audit for frozen-top selector-tail support reduction -/

namespace Erdos390.WholePaper

namespace BankPaperRealization

#check roughHeadCompatibleRawWeight_mul_factorization_eq_zero_of_headPrime
#check factorization_eq_zero_of_mem_guardedBroadCorrectionPool_of_headPrime_label
#check roughCanonicalGuardedPostchargeRowCorrectedWeight_mul_factorization_eq_zero_of_headPrime
#check bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_mul_factorization_eq_ambient_of_headPrime
#check sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_mul_factorization_eq_headTarget
#check bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_selectorValuationDeficit_eq_zero_of_headPrime
#check sum_mul_factorization_eq_sum_rowSum_mul_labelFactorization_of_labelSet_subset
#check sum_factorization_cast_eq_sum_completeLabelMultiplicity_mul_of_labelSet_subset
#check sum_chargedSelector_eq_postchargeRowTarget_of_mem_labelSet_of_ne_one
#check selectorTailTarget_factorization_eq_upper_sub_fixed_sub_base_of_signedTargetLedger
#check bankPaperCanonicalSelectorValuationDeficit_eq_zero_of_chargedRows_of_yNat_lt
#check bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_deficitSupportedOnPrimeBand
#check bankPaperCanonicalTopFrozenRoundedSourceSelector_deficitSupportedOnPrimeBand

end BankPaperRealization

end Erdos390.WholePaper
