import Erdos390.WholePaper.BankPaperFourFiveOrderedMixtureAssembly
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveContinuumOrderedMixtureMain_eq_mixtureIntegralMain_of_intervalIntegrable
#print axioms fourFiveContinuumOrderedMixtureMain_eq_mixtureIntegralMain_of_paperRange
#print axioms fourFiveOrderedPrimeMixture_eq_explicitLayers
#print axioms fourFiveOrderedPrimeMixtureEstimate_of_layerBounds
#print axioms fourFiveOrderedPrimeMixtureEstimate_of_lastPrime_continuumBridge
#print axioms exists_fourFiveOrderedPrimeMixtureEstimate_of_continuumBridge

assert_no_sorry fourFiveContinuumOrderedMixtureMain_eq_mixtureIntegralMain_of_intervalIntegrable
assert_no_sorry fourFiveContinuumOrderedMixtureMain_eq_mixtureIntegralMain_of_paperRange
assert_no_sorry fourFiveOrderedPrimeMixture_eq_explicitLayers
assert_no_sorry fourFiveOrderedPrimeMixtureEstimate_of_layerBounds
assert_no_sorry fourFiveOrderedPrimeMixtureEstimate_of_lastPrime_continuumBridge
assert_no_sorry exists_fourFiveOrderedPrimeMixtureEstimate_of_continuumBridge

end Erdos390.WholePaper.BankPaperRealization
