import Erdos390.WholePaper.BankPaperFourFiveFixedSimplexKernel
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms isClosed_fourFiveClosedSimplex
#print axioms fourFiveClosedSimplex_subset_Icc
#print axioms isCompact_fourFiveClosedSimplex
#print axioms fourFiveSimplexDenominator_pos
#print axioms continuousOn_fourFiveFixedSimplexIntegrand
#print axioms continuousOn_fourFiveFixedSimplexIntegrandDerivative
#print axioms hasDerivAt_fourFiveFixedSimplexIntegrand
#print axioms hasDerivAt_fourFiveFixedSimplexKernel
#print axioms continuousOn_fourFiveFixedSimplexKernelDerivative
#print axioms continuousOn_fourFiveFixedSimplexKernel
#print axioms hasDerivAt_fourFiveContinuumKernelOne
#print axioms hasDerivAt_fourFiveContinuumKernelTwo
#print axioms hasDerivAt_fourFiveContinuumKernelThree
#print axioms hasDerivAt_fourFiveContinuumKernelFour
#print axioms hasDerivAt_fourFiveContinuumMixtureKernel
#print axioms continuousOn_fourFiveContinuumMixtureKernel
#print axioms continuousOn_fourFiveContinuumMixtureKernelDerivative
#print axioms exists_fourFiveContinuumMixtureKernel_uniform_C1_bound

assert_no_sorry isClosed_fourFiveClosedSimplex
assert_no_sorry fourFiveClosedSimplex_subset_Icc
assert_no_sorry isCompact_fourFiveClosedSimplex
assert_no_sorry fourFiveSimplexDenominator_pos
assert_no_sorry continuousOn_fourFiveFixedSimplexIntegrand
assert_no_sorry continuousOn_fourFiveFixedSimplexIntegrandDerivative
assert_no_sorry hasDerivAt_fourFiveFixedSimplexIntegrand
assert_no_sorry hasDerivAt_fourFiveFixedSimplexKernel
assert_no_sorry continuousOn_fourFiveFixedSimplexKernelDerivative
assert_no_sorry continuousOn_fourFiveFixedSimplexKernel
assert_no_sorry hasDerivAt_fourFiveContinuumKernelOne
assert_no_sorry hasDerivAt_fourFiveContinuumKernelTwo
assert_no_sorry hasDerivAt_fourFiveContinuumKernelThree
assert_no_sorry hasDerivAt_fourFiveContinuumKernelFour
assert_no_sorry hasDerivAt_fourFiveContinuumMixtureKernel
assert_no_sorry continuousOn_fourFiveContinuumMixtureKernel
assert_no_sorry continuousOn_fourFiveContinuumMixtureKernelDerivative
assert_no_sorry exists_fourFiveContinuumMixtureKernel_uniform_C1_bound

end Erdos390.WholePaper.BankPaperRealization
