import Erdos390.WholePaper.BankPaperFourFiveLastPrimeContinuumDecomposition
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFivePrefixProductReal_pos
#print axioms fourFiveLastPrimeIntegral_eq_physicalIntegral
#print axioms fourFiveOrderedLastPrimeIntegralLayer_eq_physicalLayer
#print axioms fourFivePhysicalContinuumCellLayer_zero_eq_lebesgue
#print axioms fourFivePhysicalContinuumCellLayer_one_eq_lebesgue
#print axioms fourFivePhysicalContinuumCellLayer_two_eq_lebesgue
#print axioms fourFivePhysicalContinuumCellLayer_three_eq_lebesgue
#print axioms abs_fourFivePhysicalMovingProductOne_sub_cell_le
#print axioms abs_fourFivePhysicalMovingProductTwo_sub_cell_le
#print axioms abs_fourFivePhysicalMovingProductThree_sub_cell_le
#print axioms fourFiveLastPrimePhysicalChangeError_eq_commonDomainError
#print axioms fourFivePhysicalActualMovingLayer_zero_eq_fixed
#print axioms fourFivePhysicalProductReplacementError_zero
#print axioms fourFiveLebesgueCellAggregationError_zero
#print axioms fourFiveMovingToFixedSimplexError_zero
#print axioms fourFivePhysicalProductBudgetOverrun_zero
#print axioms fourFiveExactContinuumBridgeCellError_zero
#print axioms fourFivePhysicalProductReplacementError_le_budget_add_overrun
#print axioms abs_fourFiveLastPrimeIntegralLayer_sub_fixedContinuumLayer_le_exact
#print axioms fourFiveLastPrimeToContinuumBridge_exactDecomposition
#print axioms fourFiveOrderedPrimeMixtureEstimate_of_exactContinuumDecomposition

assert_no_sorry fourFivePrefixProductReal_pos
assert_no_sorry fourFiveLastPrimeIntegral_eq_physicalIntegral
assert_no_sorry fourFiveOrderedLastPrimeIntegralLayer_eq_physicalLayer
assert_no_sorry fourFivePhysicalContinuumCellLayer_zero_eq_lebesgue
assert_no_sorry fourFivePhysicalContinuumCellLayer_one_eq_lebesgue
assert_no_sorry fourFivePhysicalContinuumCellLayer_two_eq_lebesgue
assert_no_sorry fourFivePhysicalContinuumCellLayer_three_eq_lebesgue
assert_no_sorry abs_fourFivePhysicalMovingProductOne_sub_cell_le
assert_no_sorry abs_fourFivePhysicalMovingProductTwo_sub_cell_le
assert_no_sorry abs_fourFivePhysicalMovingProductThree_sub_cell_le
assert_no_sorry fourFiveLastPrimePhysicalChangeError_eq_commonDomainError
assert_no_sorry fourFivePhysicalActualMovingLayer_zero_eq_fixed
assert_no_sorry fourFivePhysicalProductReplacementError_zero
assert_no_sorry fourFiveLebesgueCellAggregationError_zero
assert_no_sorry fourFiveMovingToFixedSimplexError_zero
assert_no_sorry fourFivePhysicalProductBudgetOverrun_zero
assert_no_sorry fourFiveExactContinuumBridgeCellError_zero
assert_no_sorry fourFivePhysicalProductReplacementError_le_budget_add_overrun
assert_no_sorry abs_fourFiveLastPrimeIntegralLayer_sub_fixedContinuumLayer_le_exact
assert_no_sorry fourFiveLastPrimeToContinuumBridge_exactDecomposition
assert_no_sorry fourFiveOrderedPrimeMixtureEstimate_of_exactContinuumDecomposition

end Erdos390.WholePaper.BankPaperRealization
