import Erdos390.WholePaper.BankPaperPrechargeAsymptotic
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the precharge asymptotic layer -/

#print axioms Erdos390.WholePaper.bankPaperPrechargeCubicNormalizedCost_eq
#print axioms Erdos390.WholePaper.bankPaperPrechargeCubicNormalizedCost_tendsto_zero
#print axioms Erdos390.WholePaper.y_cubed_mul_L_isLittleO_secondOrderScale
#print axioms Erdos390.WholePaper.bankPaperPrecharge_yNat_isBigO_y
#print axioms Erdos390.WholePaper.natLog_two_three_mul_isBigO_L
#print axioms Erdos390.WholePaper.yNat_cubed_mul_natLog_isLittleO_secondOrderScale
#print axioms Erdos390.WholePaper.bankPaperPrechargeSmallPrimeCost_isLittleO_secondOrderScale
#print axioms Erdos390.WholePaper.bankPaperPrechargeSmallPrimeCost_normalized_tendsto_zero
#print axioms Erdos390.WholePaper.bankPaperPrechargeSmallPrimeCostMajorant_normalized_tendsto_zero
#print axioms Erdos390.WholePaper.normalized_tendsto_zero_of_eventually_le_prechargeSmallPrimeCost
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeSmallPrimeValuationCost_le
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeSmallPrimeValuationCost_le_majorant
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeSmallPrimeValuationCost_le_majorant_at_upperEndpoint

assert_no_sorry Erdos390.WholePaper.bankPaperPrechargeCubicNormalizedCost_eq
assert_no_sorry Erdos390.WholePaper.bankPaperPrechargeCubicNormalizedCost_tendsto_zero
assert_no_sorry Erdos390.WholePaper.y_cubed_mul_L_isLittleO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.bankPaperPrecharge_yNat_isBigO_y
assert_no_sorry Erdos390.WholePaper.natLog_two_three_mul_isBigO_L
assert_no_sorry Erdos390.WholePaper.yNat_cubed_mul_natLog_isLittleO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.bankPaperPrechargeSmallPrimeCost_isLittleO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.bankPaperPrechargeSmallPrimeCost_normalized_tendsto_zero
assert_no_sorry Erdos390.WholePaper.bankPaperPrechargeSmallPrimeCostMajorant_normalized_tendsto_zero
assert_no_sorry Erdos390.WholePaper.normalized_tendsto_zero_of_eventually_le_prechargeSmallPrimeCost
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeSmallPrimeValuationCost_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeSmallPrimeValuationCost_le_majorant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeSmallPrimeValuationCost_le_majorant_at_upperEndpoint
