import Erdos390.WholePaper.BankPaperCanonicalFixedDepthCapacityBridge
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the fixed-depth capacity bridge

All seven public declarations are audited below in source order.
-/

#print axioms Erdos390.WholePaper.BankPaperCanonicalCapacityAtDepth
#print axioms Erdos390.WholePaper.BankPaperCombinedChargeTerminalAtDepth.to_canonicalCapacityAtDepth
#print axioms Erdos390.WholePaper.eventually_bankPaper_f_le_upperEndpoint_of_fixedDepthCapacity
#print axioms Erdos390.WholePaper.eventually_bankPaper_f_le_upperEndpoint_of_combinedChargeTerminalAtDepth
#print axioms Erdos390.WholePaper.exists_depth_bankPaperCombinedChargeTerminal_uniform_deltaStar_with_upperEndpointBridge
#print axioms Erdos390.WholePaper.mainNormalizedLimit_of_depthFirstCombinedChargePostTangentContinuation
#print axioms Erdos390.WholePaper.mainAsymptotic_of_depthFirstCombinedChargePostTangentContinuation

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalCapacityAtDepth
assert_no_sorry Erdos390.WholePaper.BankPaperCombinedChargeTerminalAtDepth.to_canonicalCapacityAtDepth
assert_no_sorry Erdos390.WholePaper.eventually_bankPaper_f_le_upperEndpoint_of_fixedDepthCapacity
assert_no_sorry Erdos390.WholePaper.eventually_bankPaper_f_le_upperEndpoint_of_combinedChargeTerminalAtDepth
assert_no_sorry Erdos390.WholePaper.exists_depth_bankPaperCombinedChargeTerminal_uniform_deltaStar_with_upperEndpointBridge
assert_no_sorry Erdos390.WholePaper.mainNormalizedLimit_of_depthFirstCombinedChargePostTangentContinuation
assert_no_sorry Erdos390.WholePaper.mainAsymptotic_of_depthFirstCombinedChargePostTangentContinuation
