import Erdos390.WholePaper.BankPaperCanonicalSmoothSourceGuardedSharpValuationRateClosureFinal

/-! # Statement audit for the sharp smooth-source valuation closure -/

namespace Erdos390.WholePaper

open Erdos390.Full

noncomputable section

namespace BankPaperRealization

#check exists_uniform_rawStructuredCell_valuation_mean_profile_paperRate
#check exists_uniform_fixedFinite_rawStructuredCell_valuation_mean_profiles_paperRate
#check abs_uniformOnFinset_sdiff_expect_sub_uniformOnFinset_expect_le
#check exists_uniform_guardedRawCell_valuation_mean_profiles_paperRate
#check exists_uniform_bridge_guardedCell_valuation_mean_profiles_paperRate
#check uniformAverage_movingPrefix_indicator_eq_card_ratio
#check uniformAverage_movingPrefix_divInd_eq_joint_div_prefixMass
#check exists_uniform_movingPrefix_uniformAverage_divInd_paper_bound_of_fraction
#check exists_uniform_movingPrefix_density_lower_bound_of_fraction
#check exists_uniform_movingPrefix_divInd_fallback_of_fraction
#check exists_uniform_movingPrefix_valuation_mean_profile_paperRate_of_fraction
#check exists_uniform_rawSmoothBasePool_valuation_mean_profile_paperRate
#check exists_uniform_guardedSmoothBasePool_valuation_mean_profile_paperRate
#check bankPaperCanonicalScaledActiveValuationMoment_eq_q_mul_cellMeans
#check bankPaperCanonicalGuardedSmoothBaseValuationMoment_eq_mass_mul_poolMean
#check bankPaperCanonicalScaledActiveValuationMoment_sub_guardedSmoothBase_eq_mass_mul_meanDefect
#check abs_bankPaperCanonicalScaledActiveValuationMoment_sub_guardedSmoothBase_le_of_commonProfile
#check exists_uniform_scaledActive_sub_guardedSmoothBase_valuationMoment_paperRate

end BankPaperRealization

end

end Erdos390.WholePaper
