import Erdos390.WholePaper.BankPaperFourFiveRealCommonDomainIdentification
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveRealPrefixCutoffKernel
#print axioms fourFivePrimePrefixMovingTerm
#print axioms fourFiveLastPrimeRealPhysicalChangeError
#print axioms fourFivePhysicalOuterScaledBVError
#print axioms fourFiveRealEndpointFullyBoundedAssemblyError
#print axioms fourFiveLastPrimeRealPhysicalIntegral_eq_cutoffIntegral
#print axioms intervalIntegrable_fourFivePrimePrefixMovingTerm
#print axioms fourFiveLastPrimeRealPhysicalIntegral_eq_prefixMovingTerm
#print axioms fourFiveOrderedLastPrimeRealPhysicalLayer_zero_eq_physicalActualMoving
#print axioms fourFiveOrderedLastPrimeRealPhysicalLayer_one_eq_physicalActualMoving
#print axioms fourFiveOrderedLastPrimeRealPhysicalLayer_two_eq_physicalActualMoving
#print axioms fourFiveOrderedLastPrimeRealPhysicalLayer_three_eq_physicalActualMoving
#print axioms fourFiveOrderedLastPrimeRealPhysicalLayer_eq_physicalActualMovingLayer
#print axioms abs_fourFiveOrderedLastPrimeRealPhysicalLayer_sub_physicalActualMovingLayer
#print axioms fourFiveLastPrimeRealPhysicalChangeError_eq_zero
#print axioms fourFivePhysicalProductReplacementError_one_le_outer
#print axioms fourFivePhysicalProductReplacementError_two_le_outer
#print axioms fourFivePhysicalProductReplacementError_three_le_outer
#print axioms fourFivePhysicalProductReplacementError_le_movingFaceBudget
#print axioms fourFivePhysicalProductBudgetOverrun_eq_zero_outerScaled
#print axioms abs_fourFiveRealLastPrimeIntegralLayer_sub_fixed_le_fullyBounded
#print axioms fourFiveOrderedPrimeMixtureEstimate_realEndpoint_fullyBounded
#print axioms fourFiveOrderedPrimeMixtureEstimate_realEndpoint_fullyBounded_mixtureIntegral

assert_no_sorry fourFiveRealPrefixCutoffKernel
assert_no_sorry fourFivePrimePrefixMovingTerm
assert_no_sorry fourFiveLastPrimeRealPhysicalChangeError
assert_no_sorry fourFivePhysicalOuterScaledBVError
assert_no_sorry fourFiveRealEndpointFullyBoundedAssemblyError
assert_no_sorry fourFiveLastPrimeRealPhysicalIntegral_eq_cutoffIntegral
assert_no_sorry intervalIntegrable_fourFivePrimePrefixMovingTerm
assert_no_sorry fourFiveLastPrimeRealPhysicalIntegral_eq_prefixMovingTerm
assert_no_sorry fourFiveOrderedLastPrimeRealPhysicalLayer_zero_eq_physicalActualMoving
assert_no_sorry fourFiveOrderedLastPrimeRealPhysicalLayer_one_eq_physicalActualMoving
assert_no_sorry fourFiveOrderedLastPrimeRealPhysicalLayer_two_eq_physicalActualMoving
assert_no_sorry fourFiveOrderedLastPrimeRealPhysicalLayer_three_eq_physicalActualMoving
assert_no_sorry fourFiveOrderedLastPrimeRealPhysicalLayer_eq_physicalActualMovingLayer
assert_no_sorry abs_fourFiveOrderedLastPrimeRealPhysicalLayer_sub_physicalActualMovingLayer
assert_no_sorry fourFiveLastPrimeRealPhysicalChangeError_eq_zero
assert_no_sorry fourFivePhysicalProductReplacementError_one_le_outer
assert_no_sorry fourFivePhysicalProductReplacementError_two_le_outer
assert_no_sorry fourFivePhysicalProductReplacementError_three_le_outer
assert_no_sorry fourFivePhysicalProductReplacementError_le_movingFaceBudget
assert_no_sorry fourFivePhysicalProductBudgetOverrun_eq_zero_outerScaled
assert_no_sorry abs_fourFiveRealLastPrimeIntegralLayer_sub_fixed_le_fullyBounded
assert_no_sorry fourFiveOrderedPrimeMixtureEstimate_realEndpoint_fullyBounded
assert_no_sorry fourFiveOrderedPrimeMixtureEstimate_realEndpoint_fullyBounded_mixtureIntegral

end Erdos390.WholePaper.BankPaperRealization
