import Erdos390.WholePaper.BankPaperCanonicalRatioCellMomentTraffic
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for canonical ratio-cell moment traffic -/

#print axioms Erdos390.WholePaper.tangentRatioCell_sum_tailPointwiseUpper_eq_indexMoment
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellIndex_le_logGap_div_logRho
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellIndex_le_coordinateGap
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellCoordinateMoment
#print axioms Erdos390.WholePaper.bankPaperCanonical_fiber_shiftedCoordinate_eq
#print axioms Erdos390.WholePaper.bankPaperCanonical_sum_shiftedCoordinate_eq_coordinateMoment
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellFloorLoss
#print axioms Erdos390.WholePaper.bankPaperCanonical_positive_shiftedCoordinate_le
#print axioms Erdos390.WholePaper.bankPaperCanonical_low_shiftedCoordinate_le
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellCoordinateMoment_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellMomentCutMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellMomentTotalTrafficMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellIndexMoment_le_coordinateMoment
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellCutTraffic_le_momentMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellTotalTraffic_le_momentMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTrafficConstant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTrafficErrorCoefficient
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellMomentTotalTrafficMajorant_paperScale
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellCurrentLower
#print axioms Erdos390.WholePaper.bankPaperCanonical_fixedCutoff_le_ratioCellCurrentLower
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellCurrentLower_lt_label
#print axioms Erdos390.WholePaper.bankPaperCanonical_label_le_two_mul_rho_sq_mul_currentLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalHarmonicTailMajorant_mono_lower
#print axioms Erdos390.WholePaper.bankPaperCanonical_log_mul_logLogGap_le_logGap
#print axioms Erdos390.WholePaper.bankPaperCanonical_logCurrentLower_mul_portNumerator_le
#print axioms Erdos390.WholePaper.bankPaperCanonical_weightedPNTEnvelope_le_logGap
#print axioms Erdos390.WholePaper.bankPaperCanonical_exponentBand_logWidth_le
#print axioms Erdos390.WholePaper.bankPaperCanonical_currentLower_bandUpper_logGap_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellUniformPortMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonical_weightedPNTEnvelope_le_uniformPortMajorant
#print axioms Erdos390.WholePaper.bankPaperCanonical_weightedRatioCellUniformPortLoad_le_majorant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellPortConstant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellIncidentConstant
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellIncidentErrorCoefficient
#print axioms Erdos390.WholePaper.bankPaperCanonical_incidentMajorant_paperScale
#print axioms Erdos390.WholePaper.tendsto_bankPaperCanonicalRatioCellIncidentErrorCoefficient_zero
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellTrafficErrorUpperCoefficient
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellTrafficErrorCoefficient_le_upper
#print axioms Erdos390.WholePaper.tendsto_bankPaperCanonicalRatioCellTrafficErrorUpperCoefficient_zero
#print axioms Erdos390.WholePaper.bankPaperCanonical_yNat_tendsto_atTop
#print axioms Erdos390.WholePaper.eventually_bankPaperCanonical_ratioCellErrorCoefficients_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellMainCoefficient
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellMainCoefficient_pos
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellPaperWidthChoice
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellPaperWidthChoice_pos
#print axioms Erdos390.WholePaper.bankPaperCanonical_paperMainBudget_widthChoice_eq
#print axioms Erdos390.WholePaper.bankPaperCanonical_paperMainBudget_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalRatioCellPaperErrorChoice
#print axioms Erdos390.WholePaper.bankPaperCanonical_ratioCellPaperErrorChoice_pos
#print axioms Erdos390.WholePaper.bankPaperCanonical_paperErrorBudget_choice_eq
#print axioms Erdos390.WholePaper.eventually_bankPaperCanonical_paperErrorBudget_le

assert_no_sorry Erdos390.WholePaper.tangentRatioCell_sum_tailPointwiseUpper_eq_indexMoment
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellIndex_le_logGap_div_logRho
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellIndex_le_coordinateGap
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellCoordinateMoment
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_fiber_shiftedCoordinate_eq
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_sum_shiftedCoordinate_eq_coordinateMoment
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellFloorLoss
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_positive_shiftedCoordinate_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_low_shiftedCoordinate_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellCoordinateMoment_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellMomentCutMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellMomentTotalTrafficMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellIndexMoment_le_coordinateMoment
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellCutTraffic_le_momentMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellTotalTraffic_le_momentMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTrafficConstant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTrafficErrorCoefficient
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellMomentTotalTrafficMajorant_paperScale
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellCurrentLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_fixedCutoff_le_ratioCellCurrentLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellCurrentLower_lt_label
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_label_le_two_mul_rho_sq_mul_currentLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalHarmonicTailMajorant_mono_lower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_log_mul_logLogGap_le_logGap
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_logCurrentLower_mul_portNumerator_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_weightedPNTEnvelope_le_logGap
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_exponentBand_logWidth_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_currentLower_bandUpper_logGap_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellUniformPortMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_weightedPNTEnvelope_le_uniformPortMajorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_weightedRatioCellUniformPortLoad_le_majorant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellPortConstant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellIncidentConstant
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellIncidentErrorCoefficient
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_incidentMajorant_paperScale
assert_no_sorry Erdos390.WholePaper.tendsto_bankPaperCanonicalRatioCellIncidentErrorCoefficient_zero
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellTrafficErrorUpperCoefficient
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellTrafficErrorCoefficient_le_upper
assert_no_sorry Erdos390.WholePaper.tendsto_bankPaperCanonicalRatioCellTrafficErrorUpperCoefficient_zero
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_yNat_tendsto_atTop
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonical_ratioCellErrorCoefficients_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellMainCoefficient
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellMainCoefficient_pos
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellPaperWidthChoice
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellPaperWidthChoice_pos
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_paperMainBudget_widthChoice_eq
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_paperMainBudget_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRatioCellPaperErrorChoice
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_ratioCellPaperErrorChoice_pos
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_paperErrorBudget_choice_eq
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonical_paperErrorBudget_le
