import Erdos390.WholePaper.BankPaperCanonicalActualActiveMeasureConstruction
import Mathlib.Util.AssertNoSorry

/-!
# Assumption audit for the actual active-measure construction

Every public declaration is printed and checked for `sorry`.  The minimized
coordinate-fit object is a definition, not an asserted existence axiom.
-/

#print axioms Erdos390.WholePaper.bankPaperCanonicalScaledActiveSeed
#print axioms Erdos390.WholePaper.bankPaperCanonicalScaledActiveSeed_nonneg
#print axioms Erdos390.WholePaper.bankPaperCanonicalScaledActiveSeed_pos
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_scaled_nonneg
#print axioms Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_scaledActiveSeed
#print axioms Erdos390.WholePaper.bankPaperCanonicalStructuredActiveValues
#print axioms Erdos390.WholePaper.mem_bankPaperCanonicalStructuredActiveValues
#print axioms Erdos390.WholePaper.bankPaperCanonicalScaledActivePreSelector
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_self
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalActualActiveMeasureConstructor
#print axioms Erdos390.WholePaper.BankPaperCanonicalActualActivePlacement
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_scaled_iff
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_scaled_eq_of_value
#print axioms Erdos390.WholePaper.BankPaperCanonicalActualCoordinateFit
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActivePlacement_of_coordinateFit
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActivePlacement_iff_coordinateFit
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_iff_coordinateFit
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_of_coordinateFit
#print axioms Erdos390.WholePaper.bankPaperCanonicalZeroPreSelector_not_coordinateFit
#print axioms Erdos390.WholePaper.bankPaperCanonicalStructuredValue_mem_guardedCandidates
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_guarded_of_coordinateFit
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalActualActiveMeasureConstructor_of_guardedBridge
#print axioms Erdos390.WholePaper.bankPaperCanonicalPaperDataActiveSeed
#print axioms Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_paperDataActiveSeed

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalScaledActiveSeed
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalScaledActiveSeed_nonneg
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalScaledActiveSeed_pos
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_scaled_nonneg
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_scaledActiveSeed
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalStructuredActiveValues
assert_no_sorry Erdos390.WholePaper.mem_bankPaperCanonicalStructuredActiveValues
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalScaledActivePreSelector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_self
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalActualActiveMeasureConstructor
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActualActivePlacement
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_scaled_iff
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_scaled_eq_of_value
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActualCoordinateFit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActivePlacement_of_coordinateFit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActivePlacement_iff_coordinateFit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_iff_coordinateFit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_of_coordinateFit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalZeroPreSelector_not_coordinateFit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalStructuredValue_mem_guardedCandidates
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActiveMeasureConstructor_guarded_of_coordinateFit
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalActualActiveMeasureConstructor_of_guardedBridge
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalPaperDataActiveSeed
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_paperDataActiveSeed
