import Erdos390.WholePaper.BankBottomPaperComponents
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the actual bottom-bank component realization -/

#print axioms Erdos390.WholePaper.bankBottom_relevant_union_unused
#print axioms Erdos390.WholePaper.bankBottomRelevantMoves_three
#print axioms Erdos390.WholePaper.bankBottomPaperRequestOfMove_mem_relevant
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.ofMatching
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.marker_mem
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.states_donor_mem_factorInterval
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.n_lt_three_mul_marker
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.three_mul_marker_le_M
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.marker_le_n
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.donorOccurrence_eq_upperStateOccurrence_of_terminalMove
#print axioms Erdos390.WholePaper.bankBottomPathChange_eq_neg_unit_five_of_five_le
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.realizedComponentChange_eq_signedMoveChange
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.realizedSlotChange_eq_signedBottomPathChange
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.realizedSlotChange_eq_signedUnit_five_of_five_le
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.realizedSlotChange_eq_signedUnit_three
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.realizedSlotChange_eq_signedUnit_two
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrence_completeRoughSignature
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrence_mem_factorInterval
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.occurrenceValue_ne_of_request_ne
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.carrierValueSets_disjoint_of_request_ne
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrences_disjoint_of_request_ne
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.card_relevantMarkers
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.card_relevantMarkers_le_demand
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.relevantMarkerMap_injective
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.relevantMarker_existsUnique_request
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.marker_requestForRelevantMarker
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.requestForRelevantMarker_unique
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.relevantMarkerIncidentStateCores_of_request
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.relevant_marker_incident_data_unique
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.card_relevantComponentOccurrences_le_demand
#print axioms Erdos390.WholePaper.BankBottomPaperRealization.relevantMarkers_disjoint_relevantComponentOccurrences
#print axioms Erdos390.WholePaper.eventually_bankBottom_six_le_yNat
#print axioms Erdos390.WholePaper.eventually_bankBottom_three_mul_yNat_le_self
#print axioms Erdos390.WholePaper.eventually_exists_bankBottomPaper_component_realization

assert_no_sorry Erdos390.WholePaper.bankBottom_relevant_union_unused
assert_no_sorry Erdos390.WholePaper.bankBottomRelevantMoves_three
assert_no_sorry Erdos390.WholePaper.bankBottomPaperRequestOfMove_mem_relevant
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.ofMatching
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.marker_mem
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.states_donor_mem_factorInterval
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.n_lt_three_mul_marker
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.three_mul_marker_le_M
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.marker_le_n
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.donorOccurrence_eq_upperStateOccurrence_of_terminalMove
assert_no_sorry Erdos390.WholePaper.bankBottomPathChange_eq_neg_unit_five_of_five_le
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.realizedComponentChange_eq_signedMoveChange
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.realizedSlotChange_eq_signedBottomPathChange
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.realizedSlotChange_eq_signedUnit_five_of_five_le
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.realizedSlotChange_eq_signedUnit_three
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.realizedSlotChange_eq_signedUnit_two
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrence_completeRoughSignature
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrence_mem_factorInterval
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.occurrenceValue_ne_of_request_ne
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.carrierValueSets_disjoint_of_request_ne
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.componentOccurrences_disjoint_of_request_ne
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.card_relevantMarkers
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.card_relevantMarkers_le_demand
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.relevantMarkerMap_injective
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.relevantMarker_existsUnique_request
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.marker_requestForRelevantMarker
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.requestForRelevantMarker_unique
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.relevantMarkerIncidentStateCores_of_request
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.relevant_marker_incident_data_unique
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.card_relevantComponentOccurrences_le_demand
assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.relevantMarkers_disjoint_relevantComponentOccurrences
assert_no_sorry Erdos390.WholePaper.eventually_bankBottom_six_le_yNat
assert_no_sorry Erdos390.WholePaper.eventually_bankBottom_three_mul_yNat_le_self
assert_no_sorry Erdos390.WholePaper.eventually_exists_bankBottomPaper_component_realization
