import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalFourFiveCutoffIntervalPrecursorConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the cutoff-interval precursor
-/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms roughCanonicalExceptional_clippedPhysicalEndpoint_span_le
#print axioms roughCanonicalExceptional_self_div_core_le_physicalRateScale
#print axioms fourFiveRoughInterval_card_le_arithmetic_add_fixedEndpointFreezing
#print axioms roughCanonicalExceptional_shortClippedSpan_div_log_le
#print axioms roughCanonicalExceptional_broadClippedSpan_div_log_le
#print axioms roughCanonicalExceptional_paperRate_le_cutoffSqRate
#print axioms roughCanonicalExceptional_paperRate_le_cutoffBroadRate
#print axioms roughCanonicalFourFiveCutoffUpperEstimateConstant
#print axioms roughCanonicalFourFiveCutoffHighEstimateConstant
#print axioms roughCanonicalFourFiveCutoffBroadEstimateConstant
#print axioms roughCanonicalFourFiveCutoffUpperEstimateConstant_nonneg
#print axioms roughCanonicalFourFiveCutoffHighEstimateConstant_nonneg
#print axioms roughCanonicalFourFiveCutoffBroadEstimateConstant_nonneg
#print axioms roughCanonicalSignedExceptionalCutoffIntervalEstimate_of_geometry_or_empty
#print axioms exists_eventually_roughCanonicalSignedExceptionalCutoffIntervalEstimates

assert_no_sorry roughCanonicalExceptional_clippedPhysicalEndpoint_span_le
assert_no_sorry roughCanonicalExceptional_self_div_core_le_physicalRateScale
assert_no_sorry fourFiveRoughInterval_card_le_arithmetic_add_fixedEndpointFreezing
assert_no_sorry roughCanonicalExceptional_shortClippedSpan_div_log_le
assert_no_sorry roughCanonicalExceptional_broadClippedSpan_div_log_le
assert_no_sorry roughCanonicalExceptional_paperRate_le_cutoffSqRate
assert_no_sorry roughCanonicalExceptional_paperRate_le_cutoffBroadRate
assert_no_sorry roughCanonicalFourFiveCutoffUpperEstimateConstant
assert_no_sorry roughCanonicalFourFiveCutoffHighEstimateConstant
assert_no_sorry roughCanonicalFourFiveCutoffBroadEstimateConstant
assert_no_sorry roughCanonicalFourFiveCutoffUpperEstimateConstant_nonneg
assert_no_sorry roughCanonicalFourFiveCutoffHighEstimateConstant_nonneg
assert_no_sorry roughCanonicalFourFiveCutoffBroadEstimateConstant_nonneg
assert_no_sorry roughCanonicalSignedExceptionalCutoffIntervalEstimate_of_geometry_or_empty
assert_no_sorry exists_eventually_roughCanonicalSignedExceptionalCutoffIntervalEstimates

end Erdos390.WholePaper.BankPaperRealization
