import Erdos390.WholePaper.BankPaperFourFiveMovingFixedSimplexIdentification
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveSimplexAffineMap
#print axioms fourFiveSimplexAffineDerivative
#print axioms hasFDerivAt_fourFiveSimplexAffineMap
#print axioms fourFiveSimplexAffineMap_injective
#print axioms abs_det_fourFiveSimplexAffineDerivative
#print axioms sum_fourFiveSimplexAffineMap
#print axioms image_fourFiveClosedSimplex_affine_eq_movingSimplex
#print axioms fourFive_movingSimplexIntegrand_affine
#print axioms fourFiveLogarithmicMovingSimplexKernel_eq_fixedSimplexKernel
#print axioms fourFivePhysicalMovingSimplexLayer_zero_eq_fixed
#print axioms fourFivePhysicalMovingSimplexLayer_one_eq_fixed
#print axioms fourFivePhysicalMovingSimplexLayer_two_eq_fixed
#print axioms fourFivePhysicalMovingSimplexLayer_three_eq_fixed
#print axioms fourFiveMovingToFixedSimplexError_one_eq_zero
#print axioms fourFiveMovingToFixedSimplexError_two_eq_zero
#print axioms fourFiveMovingToFixedSimplexError_three_eq_zero

assert_no_sorry fourFiveSimplexAffineMap
assert_no_sorry fourFiveSimplexAffineDerivative
assert_no_sorry hasFDerivAt_fourFiveSimplexAffineMap
assert_no_sorry fourFiveSimplexAffineMap_injective
assert_no_sorry abs_det_fourFiveSimplexAffineDerivative
assert_no_sorry sum_fourFiveSimplexAffineMap
assert_no_sorry image_fourFiveClosedSimplex_affine_eq_movingSimplex
assert_no_sorry fourFive_movingSimplexIntegrand_affine
assert_no_sorry fourFiveLogarithmicMovingSimplexKernel_eq_fixedSimplexKernel
assert_no_sorry fourFivePhysicalMovingSimplexLayer_zero_eq_fixed
assert_no_sorry fourFivePhysicalMovingSimplexLayer_one_eq_fixed
assert_no_sorry fourFivePhysicalMovingSimplexLayer_two_eq_fixed
assert_no_sorry fourFivePhysicalMovingSimplexLayer_three_eq_fixed
assert_no_sorry fourFiveMovingToFixedSimplexError_one_eq_zero
assert_no_sorry fourFiveMovingToFixedSimplexError_two_eq_zero
assert_no_sorry fourFiveMovingToFixedSimplexError_three_eq_zero

end Erdos390.WholePaper.BankPaperRealization
