import Erdos390.WholePaper.BankPaperCanonicalTopFrozenSelectorTailSupportReductionConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for frozen-top selector-tail support reduction -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.roughHeadCompatibleRawWeight_mul_factorization_eq_zero_of_headPrime
#print axioms BankPaperRealization.factorization_eq_zero_of_mem_guardedBroadCorrectionPool_of_headPrime_label
#print axioms BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight_mul_factorization_eq_zero_of_headPrime
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_mul_factorization_eq_ambient_of_headPrime
#print axioms BankPaperRealization.sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_mul_factorization_eq_headTarget
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_selectorValuationDeficit_eq_zero_of_headPrime
#print axioms BankPaperRealization.sum_mul_factorization_eq_sum_rowSum_mul_labelFactorization_of_labelSet_subset
#print axioms BankPaperRealization.sum_factorization_cast_eq_sum_completeLabelMultiplicity_mul_of_labelSet_subset
#print axioms BankPaperRealization.sum_chargedSelector_eq_postchargeRowTarget_of_mem_labelSet_of_ne_one
#print axioms BankPaperRealization.selectorTailTarget_factorization_eq_upper_sub_fixed_sub_base_of_signedTargetLedger
#print axioms BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_eq_zero_of_chargedRows_of_yNat_lt
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_deficitSupportedOnPrimeBand
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_deficitSupportedOnPrimeBand

assert_no_sorry BankPaperRealization.roughHeadCompatibleRawWeight_mul_factorization_eq_zero_of_headPrime
assert_no_sorry BankPaperRealization.factorization_eq_zero_of_mem_guardedBroadCorrectionPool_of_headPrime_label
assert_no_sorry BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight_mul_factorization_eq_zero_of_headPrime
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_mul_factorization_eq_ambient_of_headPrime
assert_no_sorry BankPaperRealization.sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_mul_factorization_eq_headTarget
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_selectorValuationDeficit_eq_zero_of_headPrime
assert_no_sorry BankPaperRealization.sum_mul_factorization_eq_sum_rowSum_mul_labelFactorization_of_labelSet_subset
assert_no_sorry BankPaperRealization.sum_factorization_cast_eq_sum_completeLabelMultiplicity_mul_of_labelSet_subset
assert_no_sorry BankPaperRealization.sum_chargedSelector_eq_postchargeRowTarget_of_mem_labelSet_of_ne_one
assert_no_sorry BankPaperRealization.selectorTailTarget_factorization_eq_upper_sub_fixed_sub_base_of_signedTargetLedger
assert_no_sorry BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_eq_zero_of_chargedRows_of_yNat_lt
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_deficitSupportedOnPrimeBand
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_deficitSupportedOnPrimeBand

end Erdos390.WholePaper
