import Erdos390.WholePaper.BankPaperCanonicalTwoZeroHeadCellOuterCapacityConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the outer two-zero-head-cell capacity connector -/

#print axioms Erdos390.WholePaper.BankPaperRealization.secondOrderScale_isLittleO_natCast
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonical_marginFloor_le_baseline_cellMass
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonical_baseline_cellMass_le_one
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightCellMassFamily
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightCellMassFamily_isLittleO
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadCellDensityFloor
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadCellDensityFloor_pos
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadCellDensityFloor_le
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSymmetricInitialAndHeight_twoZeroHeadCell_scalarCapacity
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSymmetricInitialAndHeight_twoZeroHeadCell_rebalance_capacity

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.secondOrderScale_isLittleO_natCast
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonical_marginFloor_le_baseline_cellMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonical_baseline_cellMass_le_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightCellMassFamily
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSymmetricInitialAndHeightCellMassFamily_isLittleO
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadCellDensityFloor
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadCellDensityFloor_pos
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalZeroHeadCellDensityFloor_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSymmetricInitialAndHeight_twoZeroHeadCell_scalarCapacity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalSymmetricInitialAndHeight_twoZeroHeadCell_rebalance_capacity
