import Erdos390.WholePaper.BankPaperCanonicalImplementationDefectRateReductionConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the two implementation-defect reductions -/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceGuardedRowValuationDefectAtLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.completeRoughRowFiber_nonexceptionalGuarded_eq_guardedRow
#print axioms Erdos390.WholePaper.BankPaperRealization.completeRoughRowFiber_nonexceptionalGuarded_eq_empty
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceValuationCorrectionMoment_sub_guardedCorrection_eq_sum_rowDefects
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitSourceGuardedRowValuationDefectAtLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceToGuardedCorrectionValuationDefect_eq_sum_rowDefects
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitSourceGuardedRowValuationDefectAtLabel_eq_zero_of_active
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitSourceGuardedRowValuationDefectAtLabel_eq_zero_of_exceptional
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitSmoothSourceToGuardedValuationDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceToGuardedCorrectionValuationDefect_eq_smooth
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalPostHfitSmoothSourceToGuardedValuationDefectBound
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalPostHfitGlobalSourceToGuardedCorrectionValuationDefect_le_of_smooth

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBroadCorrectionPoolGuardDeleted
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBroadCorrectionPoolGuardDeleted_card_le_three
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawPoolValuationMomentCrossNumerator
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawPoolValuationMomentCrossNumerator_eq_deleted
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedNormalizedValuationMoment_sub_raw_eq_crossNumerator_div
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRaw_and_guardedBroadCorrectionPool_card_ne_zero_of_linear_lower
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationMajorantAtLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationMajorantAtLabel_eq_crossNumerator
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalGuardedRawRowCorrectionValuationDefectAtLabel_le_majorant
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_rowwiseMajorant
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardedRawCorrectionValuationRowwiseBound
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardedRawPoolMomentChangeContributionBound
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardedRawNumeratorShiftContributionBound
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_of_splitContributions
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_of_rowwise
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalGuardedPostchargeRawNumeratorShift_le_fixed

#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitTwoImplementationDefectRateInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitMediumPrimeImplementationRateInputs_of_defectReductions
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalPostHfitMediumPrimeImplementationRateInputs_of_defectReductions

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceGuardedRowValuationDefectAtLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeRoughRowFiber_nonexceptionalGuarded_eq_guardedRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeRoughRowFiber_nonexceptionalGuarded_eq_empty
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSourceValuationCorrectionMoment_sub_guardedCorrection_eq_sum_rowDefects
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitSourceGuardedRowValuationDefectAtLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceToGuardedCorrectionValuationDefect_eq_sum_rowDefects
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitSourceGuardedRowValuationDefectAtLabel_eq_zero_of_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitSourceGuardedRowValuationDefectAtLabel_eq_zero_of_exceptional
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitSmoothSourceToGuardedValuationDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostHfitGlobalSourceToGuardedCorrectionValuationDefect_eq_smooth
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalPostHfitSmoothSourceToGuardedValuationDefectBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalPostHfitGlobalSourceToGuardedCorrectionValuationDefect_le_of_smooth

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBroadCorrectionPoolGuardDeleted
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBroadCorrectionPoolGuardDeleted_card_le_three
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawPoolValuationMomentCrossNumerator
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawPoolValuationMomentCrossNumerator_eq_deleted
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedNormalizedValuationMoment_sub_raw_eq_crossNumerator_div
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRaw_and_guardedBroadCorrectionPool_card_ne_zero_of_linear_lower
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationMajorantAtLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationMajorantAtLabel_eq_crossNumerator
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalGuardedRawRowCorrectionValuationDefectAtLabel_le_majorant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_rowwiseMajorant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardedRawCorrectionValuationRowwiseBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardedRawPoolMomentChangeContributionBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardedRawNumeratorShiftContributionBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_of_splitContributions
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_of_rowwise
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalGuardedPostchargeRawNumeratorShift_le_fixed

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalPostHfitTwoImplementationDefectRateInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitMediumPrimeImplementationRateInputs_of_defectReductions
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_bankPaperCanonicalPostHfitMediumPrimeImplementationRateInputs_of_defectReductions
