import Erdos390.WholePaper.BankPaperCanonicalSignedGuardResidual
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the signed exceptional/guard residual ledger -/

#print axioms Erdos390.WholePaper.BankPaperRealization.sum_factorization_cast_le_card_mul_log_two
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_sum_weight_mul_factorization_le_sum_factorization
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_factorization_union_le
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSet
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalExceptionalRawLowerSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_paperExceptionalUpperFactors_factorization_eq_prod
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalSignedExceptionalResidual_le_positive_parts
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalNonexceptionalGuardDeletedSet
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalNonexceptionalGuardDeletedSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDonorSet
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalExceptionalDonorSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDonorSet_subset_prechargeDonorSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalNonexceptionalGuardDeletedSet_subset_support
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardResidual_le_components
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_guardedCentralAnchors_factorization_le_two_mul_log_two
#print axioms Erdos390.WholePaper.BankPaperRealization.precharge_guard_state_factorization_bounds
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualMajorant
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualMajorant_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardResidual_le_majorant
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperGuardCubicNormalizedCost
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperGuardCubicNormalizedCost_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperGuardCubicNormalizedCost_tendsto_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.y_cubed_mul_L_sq_isLittleO_secondOrderScale
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualMajorant_scaled_isLittleO
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualMajorant_scaled_tendsto_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalAggregateGuardResidualMajorant_le_strictScale
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalActiveRawCorrectionLabels
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalActiveRawCorrectionLabels
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawCorrectionDensityAtLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrection
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawCorrectionDensityAtLabel_eq_quotaError_div
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrection_eq_density_mul_valuationSum
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateRawRowCorrection_le_rowwise
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_activeRawCorrectionPool_factorization_le_four_mul_div_prime
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateRawRowCorrection_le_uniformDensity
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateRawRowCorrection_le_strictScale_of_density
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalCompleteSignedResidual
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalCompleteSignedResidual_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalCompleteSignedResidual_le
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalSignedExceptionalResidualBound
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalAggregateGuardResidualBound
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalAggregateRawRowCorrectionBound
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalUniformRawRowCorrectionDensityBound
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalResidualBound_of_positive_parts
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualBound_of_majorant
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrectionBound_of_rowwise
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrectionBound_of_uniformDensity
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrectionBound_strictScale_of_uniformDensity
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalAggregateGuardResidualBound
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalCompleteSignedResidual_le_scale

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_factorization_cast_le_card_mul_log_two
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_sum_weight_mul_factorization_le_sum_factorization
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_factorization_union_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalExceptionalRawLowerSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_paperExceptionalUpperFactors_factorization_eq_prod
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalSignedExceptionalResidual_le_positive_parts
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalNonexceptionalGuardDeletedSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalNonexceptionalGuardDeletedSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDonorSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalExceptionalDonorSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDonorSet_subset_prechargeDonorSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalNonexceptionalGuardDeletedSet_subset_support
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardResidual_le_components
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_guardedCentralAnchors_factorization_le_two_mul_log_two
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.precharge_guard_state_factorization_bounds
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualMajorant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualMajorant_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardResidual_le_majorant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperGuardCubicNormalizedCost
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperGuardCubicNormalizedCost_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperGuardCubicNormalizedCost_tendsto_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.y_cubed_mul_L_sq_isLittleO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualMajorant_scaled_isLittleO
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualMajorant_scaled_tendsto_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalAggregateGuardResidualMajorant_le_strictScale
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalActiveRawCorrectionLabels
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalActiveRawCorrectionLabels
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawCorrectionDensityAtLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrection
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawCorrectionDensityAtLabel_eq_quotaError_div
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrection_eq_density_mul_valuationSum
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateRawRowCorrection_le_rowwise
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_activeRawCorrectionPool_factorization_le_four_mul_div_prime
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateRawRowCorrection_le_uniformDensity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateRawRowCorrection_le_strictScale_of_density
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalCompleteSignedResidual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalCompleteSignedResidual_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalCompleteSignedResidual_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalSignedExceptionalResidualBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalAggregateGuardResidualBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalAggregateRawRowCorrectionBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalUniformRawRowCorrectionDensityBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalResidualBound_of_positive_parts
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardResidualBound_of_majorant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrectionBound_of_rowwise
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrectionBound_of_uniformDensity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateRawRowCorrectionBound_strictScale_of_uniformDensity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalAggregateGuardResidualBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalCompleteSignedResidual_le_scale
