import Erdos390.WholePaper.BankPaperCanonicalSmoothQuotaHeightAsymptotic
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the analytic Section 8 quota/height bridge -/

#print axioms Erdos390.WholePaper.eventually_bankPaperCanonicalRawSmoothBasePool_linear_lower
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseMass_paperScaleLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseMass_isBigO
#print axioms Erdos390.WholePaper.BankPaperCanonicalSectionEightAnalyticLedger
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothQ0Family_sub_qTilde_isLittleO
#print axioms Erdos390.WholePaper.bankPaperCanonicalPostGuardSmoothMass_paperScaleLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothQ0Family_paperScaleLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalPostGuardSmoothMass_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothQ0Family_isBigO
#print axioms Erdos390.WholePaper.secondOrderScale_div_L_tendsto_atTop
#print axioms Erdos390.WholePaper.bankPaperCanonical_inv_L_add_mu_isBigO_inv_L
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustment_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEight_q0_paperScaleLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEight_d_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEight_finalActiveMass_paperScaleLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEight_physicalMeanError_isBigO
#print axioms Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalSectionEight_finalActiveMass
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEight_headActiveMass_paperScaleLower
#print axioms Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalSectionEight_headActiveMass

assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonicalRawSmoothBasePool_linear_lower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseMass_paperScaleLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseMass_isBigO
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSectionEightAnalyticLedger
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothQ0Family_sub_qTilde_isLittleO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalPostGuardSmoothMass_paperScaleLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothQ0Family_paperScaleLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalPostGuardSmoothMass_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothQ0Family_isBigO
assert_no_sorry Erdos390.WholePaper.secondOrderScale_div_L_tendsto_atTop
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_inv_L_add_mu_isBigO_inv_L
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustment_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEight_q0_paperScaleLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEight_d_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEight_finalActiveMass_paperScaleLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEight_physicalMeanError_isBigO
assert_no_sorry Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalSectionEight_finalActiveMass
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEight_headActiveMass_paperScaleLower
assert_no_sorry Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalSectionEight_headActiveMass
