import Erdos390.WholePaper.BankOrdinaryPoolMatching

/-! # Assumption audit for actual ordinary pool assignment -/

#print axioms Erdos390.WholePaper.bankOrdinaryAvailablePairs_disjoint
#print axioms Erdos390.WholePaper.bankOrdinaryAvailablePairs_subset_eligible
#print axioms Erdos390.WholePaper.bankOrdinaryPoolCapacity_ge_half_markerCount
#print axioms Erdos390.WholePaper.eventually_bankOrdinary_allPoolDemands_le_capacity
#print axioms Erdos390.WholePaper.mem_bankOrdinaryEligibleRelation
#print axioms Erdos390.WholePaper.BankOrdinaryPoolMatching.matchedPair_mem_available
#print axioms Erdos390.WholePaper.BankOrdinaryPoolMatching.matchedPair_injective
#print axioms Erdos390.WholePaper.BankOrdinaryPoolMatching.matchedPair_eligible
#print axioms Erdos390.WholePaper.eventually_exists_bankOrdinaryPaper_injective_assignment

assert_no_sorry Erdos390.WholePaper.bankOrdinaryAvailablePairs_disjoint
assert_no_sorry Erdos390.WholePaper.bankOrdinaryAvailablePairs_subset_eligible
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPoolCapacity_ge_half_markerCount
assert_no_sorry Erdos390.WholePaper.eventually_bankOrdinary_allPoolDemands_le_capacity
assert_no_sorry Erdos390.WholePaper.mem_bankOrdinaryEligibleRelation
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPoolMatching.matchedPair_mem_available
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPoolMatching.matchedPair_injective
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPoolMatching.matchedPair_eligible
assert_no_sorry Erdos390.WholePaper.eventually_exists_bankOrdinaryPaper_injective_assignment
