import Erdos390.WholePaper.BankBottomMarkerPoolScale
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the bottom-pool scale facts -/

#print axioms Erdos390.WholePaper.bankBottomMarkerGap_bounds
#print axioms Erdos390.WholePaper.bankBottomMarkerGap_normalized_tendsto
#print axioms Erdos390.WholePaper.bankBottomOrientationCut_ratio_tendsto
#print axioms Erdos390.WholePaper.bankBottomOrientedMarkerGap_bounds
#print axioms Erdos390.WholePaper.bankBottomOrientedMarkerGap_normalized_tendsto
#print axioms Erdos390.WholePaper.bankBottomOrientedMarkerPrimes_card_div_bankBottomPrimeScale_tendsto

#print axioms Erdos390.WholePaper.bankBottomMarkerPrimes_card_div_secondOrderScale_tendsto_zero
#print axioms Erdos390.WholePaper.bankBottomOrientedMarkerPrimes_card_div_secondOrderScale_tendsto_zero
#print axioms Erdos390.WholePaper.eventually_bankBottom_scaledEndpoint_narrow

assert_no_sorry Erdos390.WholePaper.bankBottomMarkerGap_bounds
assert_no_sorry Erdos390.WholePaper.bankBottomMarkerGap_normalized_tendsto
assert_no_sorry Erdos390.WholePaper.bankBottomOrientationCut_ratio_tendsto
assert_no_sorry Erdos390.WholePaper.bankBottomOrientedMarkerGap_bounds
assert_no_sorry Erdos390.WholePaper.bankBottomOrientedMarkerGap_normalized_tendsto
assert_no_sorry Erdos390.WholePaper.bankBottomOrientedMarkerPrimes_card_div_bankBottomPrimeScale_tendsto

assert_no_sorry Erdos390.WholePaper.bankBottomMarkerPrimes_card_div_secondOrderScale_tendsto_zero
assert_no_sorry Erdos390.WholePaper.bankBottomOrientedMarkerPrimes_card_div_secondOrderScale_tendsto_zero
assert_no_sorry Erdos390.WholePaper.eventually_bankBottom_scaledEndpoint_narrow
