import Erdos390.WholePaper.BankPaperPrechargeCapacityAlgebra
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for numerical precharge capacity -/

#print axioms Erdos390.WholePaper.centralTailProduct_factorization_ge_of_cross_capacity
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_factorization_le_anchorMarkerBudget_log2_three_mul
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.precharge_fixedSupport_factorization_add_retainedReserve_le_upperTailValuation
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.precharge_fixedSupport_factorization_add_twelfthReserve_le_upperTailValuation
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.precharge_lowPrime_factorization_le_centralTailProduct
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.mul_prechargeBaseStateProduct_dvd_centralTailProduct_of_capacity

assert_no_sorry Erdos390.WholePaper.centralTailProduct_factorization_ge_of_cross_capacity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_factorization_le_anchorMarkerBudget_log2_three_mul
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.precharge_fixedSupport_factorization_add_retainedReserve_le_upperTailValuation
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.precharge_fixedSupport_factorization_add_twelfthReserve_le_upperTailValuation
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.precharge_lowPrime_factorization_le_centralTailProduct
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.mul_prechargeBaseStateProduct_dvd_centralTailProduct_of_capacity
