import Erdos390.WholePaper.BankBottomConcreteDemand
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the concrete bottom-bank demand and allocation chain -/

#print axioms Erdos390.WholePaper.roundingErrorBox_le_bankRoundingBeta
#print axioms Erdos390.WholePaper.bankRoundingDepth_eq_paperCeil
#print axioms Erdos390.WholePaper.bankRoundingBeta_eq_paperCeil
#print axioms Erdos390.WholePaper.bankBottomPaperPoolDemand_eq
#print axioms Erdos390.WholePaper.bankBottomPaperDemand_le_majorant
#print axioms Erdos390.WholePaper.bankBottomPaperDemand_isBigO_yNat
#print axioms Erdos390.WholePaper.bankBottomPaperDemand_div_bankBottomPrimeScale_tendsto_zero
#print axioms Erdos390.WholePaper.eventually_bankBottomPaper_poolDemand_le_capacity
#print axioms Erdos390.WholePaper.eventually_bankBottomPaper_all_poolDemands_le_capacity
#print axioms Erdos390.WholePaper.eventually_exists_bankBottomPaper_injective_assignment

assert_no_sorry Erdos390.WholePaper.roundingErrorBox_le_bankRoundingBeta
assert_no_sorry Erdos390.WholePaper.bankRoundingDepth_eq_paperCeil
assert_no_sorry Erdos390.WholePaper.bankRoundingBeta_eq_paperCeil
assert_no_sorry Erdos390.WholePaper.bankBottomPaperPoolDemand_eq
assert_no_sorry Erdos390.WholePaper.bankBottomPaperDemand_le_majorant
assert_no_sorry Erdos390.WholePaper.bankBottomPaperDemand_isBigO_yNat
assert_no_sorry Erdos390.WholePaper.bankBottomPaperDemand_div_bankBottomPrimeScale_tendsto_zero
assert_no_sorry Erdos390.WholePaper.eventually_bankBottomPaper_poolDemand_le_capacity
assert_no_sorry Erdos390.WholePaper.eventually_bankBottomPaper_all_poolDemands_le_capacity
assert_no_sorry Erdos390.WholePaper.eventually_exists_bankBottomPaper_injective_assignment
