import Erdos390.WholePaper.BankOrdinaryDonorSupply

/-! # Axiom audit for ordinary-bank analytic supply -/

#print axioms Erdos390.WholePaper.exists_primeInterval_card_lower_from_cumulativePNT
#print axioms Erdos390.WholePaper.exists_eventually_bankOrdinarySmoothBulkDonors_lower
#print axioms Erdos390.WholePaper.exists_eventually_bankOrdinaryPrimeChoices_lower
#print axioms Erdos390.WholePaper.exists_eventually_bankOrdinary_occurrenceTotal_lower
#print axioms Erdos390.WholePaper.eventually_bankOrdinary_occurrenceCeilDiv_le_markerCount
#print axioms Erdos390.WholePaper.exists_eventually_bankOrdinary_markerCount_lower
#print axioms Erdos390.WholePaper.bankOrdinary_smallScale_occurrenceTotal_lower
#print axioms Erdos390.WholePaper.bankOrdinary_smallScale_markerCount_lower

assert_no_sorry Erdos390.WholePaper.exists_primeInterval_card_lower_from_cumulativePNT
assert_no_sorry Erdos390.WholePaper.exists_eventually_bankOrdinarySmoothBulkDonors_lower
assert_no_sorry Erdos390.WholePaper.exists_eventually_bankOrdinaryPrimeChoices_lower
assert_no_sorry Erdos390.WholePaper.exists_eventually_bankOrdinary_occurrenceTotal_lower
assert_no_sorry Erdos390.WholePaper.eventually_bankOrdinary_occurrenceCeilDiv_le_markerCount
assert_no_sorry Erdos390.WholePaper.exists_eventually_bankOrdinary_markerCount_lower
assert_no_sorry Erdos390.WholePaper.bankOrdinary_smallScale_occurrenceTotal_lower
assert_no_sorry Erdos390.WholePaper.bankOrdinary_smallScale_markerCount_lower
