import Erdos390.WholePaper.BankPaperFixedExceptionalBacking
import Mathlib.Util.AssertNoSorry

/-! # Transitive axiom audit for the literal fixed exceptional backing -/

#print axioms Erdos390.WholePaper.mem_paperExceptionalUpperFactors
#print axioms Erdos390.WholePaper.paperExceptionalUpperFactors_subset_upperBlock
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_paperFixedExceptionalFactors
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_subset_upperBlock
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_subset_tail
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_disjoint_prechargeDonorSet
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalBacking_subset_tail
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalBacking_prod_dvd_centralTailProduct
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_mul_prechargeDonorSet_prod
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_selectorTailCharge_factorization_eq_backing
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_selectorTailCharge_factorization_le

assert_no_sorry Erdos390.WholePaper.mem_paperExceptionalUpperFactors
assert_no_sorry Erdos390.WholePaper.paperExceptionalUpperFactors_subset_upperBlock
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_paperFixedExceptionalFactors
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_subset_upperBlock
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_subset_tail
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_disjoint_prechargeDonorSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalBacking_subset_tail
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalBacking_prod_dvd_centralTailProduct
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_mul_prechargeDonorSet_prod
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_selectorTailCharge_factorization_eq_backing
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_selectorTailCharge_factorization_le
