import Erdos390.WholePaper.BankPaperFourFiveMovingSimplexCellTelescope
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveLogLogCellTelescopeTwo
#print axioms fourFiveLogLogCellTelescopeThree
#print axioms fourFiveLogLogCellTelescopeThreeRightOrdered
#print axioms fourFiveMovingFaceInteriorConditionalDefect
#print axioms fourFiveMovingFaceStrictConditionalDefect
#print axioms fourFiveMovingSimplexCellInteriorTelescopeTwo
#print axioms fourFiveMovingSimplexCellStrictTelescopeTwo
#print axioms fourFiveMovingSimplexCellTelescopeTwo
#print axioms fourFiveMovingSimplexCellInteriorTelescopeThree
#print axioms fourFiveMovingSimplexCellStrictTelescopeThree
#print axioms fourFiveMovingSimplexCellTelescopeThree
#print axioms sum_abs_fourFiveLogLogLebesgueCellAtom_eq_logLogIncrement
#print axioms sum_abs_fourFiveLogLogLebesgueCellAtom_le_compact
#print axioms abs_fourFiveLogLogCellTelescopeTwo_le
#print axioms abs_fourFiveLogLogCellTelescopeThree_le
#print axioms abs_fourFiveLogLogCellTelescopeThreeRightOrdered_le
#print axioms abs_fourFiveMovingSimplexCellInteriorTelescopeTwo_le
#print axioms abs_fourFiveMovingSimplexCellStrictTelescopeTwo_le
#print axioms abs_fourFiveMovingSimplexCellTelescopeTwo_le
#print axioms abs_fourFiveMovingSimplexCellInteriorTelescopeThree_le
#print axioms abs_fourFiveMovingSimplexCellStrictTelescopeThree_le
#print axioms abs_fourFiveMovingSimplexCellTelescopeThree_le
#print axioms abs_fourFiveMovingSimplexCellTelescopeTwo_le_compact
#print axioms abs_fourFiveMovingSimplexCellTelescopeThree_le_compact

assert_no_sorry fourFiveLogLogCellTelescopeTwo
assert_no_sorry fourFiveLogLogCellTelescopeThree
assert_no_sorry fourFiveLogLogCellTelescopeThreeRightOrdered
assert_no_sorry fourFiveMovingFaceInteriorConditionalDefect
assert_no_sorry fourFiveMovingFaceStrictConditionalDefect
assert_no_sorry fourFiveMovingSimplexCellInteriorTelescopeTwo
assert_no_sorry fourFiveMovingSimplexCellStrictTelescopeTwo
assert_no_sorry fourFiveMovingSimplexCellTelescopeTwo
assert_no_sorry fourFiveMovingSimplexCellInteriorTelescopeThree
assert_no_sorry fourFiveMovingSimplexCellStrictTelescopeThree
assert_no_sorry fourFiveMovingSimplexCellTelescopeThree
assert_no_sorry sum_abs_fourFiveLogLogLebesgueCellAtom_eq_logLogIncrement
assert_no_sorry sum_abs_fourFiveLogLogLebesgueCellAtom_le_compact
assert_no_sorry abs_fourFiveLogLogCellTelescopeTwo_le
assert_no_sorry abs_fourFiveLogLogCellTelescopeThree_le
assert_no_sorry abs_fourFiveLogLogCellTelescopeThreeRightOrdered_le
assert_no_sorry abs_fourFiveMovingSimplexCellInteriorTelescopeTwo_le
assert_no_sorry abs_fourFiveMovingSimplexCellStrictTelescopeTwo_le
assert_no_sorry abs_fourFiveMovingSimplexCellTelescopeTwo_le
assert_no_sorry abs_fourFiveMovingSimplexCellInteriorTelescopeThree_le
assert_no_sorry abs_fourFiveMovingSimplexCellStrictTelescopeThree_le
assert_no_sorry abs_fourFiveMovingSimplexCellTelescopeThree_le
assert_no_sorry abs_fourFiveMovingSimplexCellTelescopeTwo_le_compact
assert_no_sorry abs_fourFiveMovingSimplexCellTelescopeThree_le_compact

end Erdos390.WholePaper.BankPaperRealization
