import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightFrozenLogInvarianceConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for post-height frozen-log invariance -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacement_actualFrozenWeight_eq_source_of_arbitrarySeedReplacement
#print axioms BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacement_frozenAmbientWeight_eq_source_of_arbitrarySeedReplacement
#print axioms BankPaperRealization.sum_bankPaperCanonicalGuardedStructuredAdditivePlacement_actualFrozenWeight_mul_log_eq_source_of_arbitrarySeedReplacement
#print axioms BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacement_actualFrozenLogMass_eq_source_of_arbitrarySeedReplacement
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlaced_actualFrozenWeight_eq_roundedSource
#print axioms BankPaperRealization.sum_bankPaperCanonicalSectionNinePostHeightPlaced_actualFrozenWeight_mul_log_eq_roundedSource
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlaced_actualFrozenLogMass_eq_roundedSource

assert_no_sorry BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacement_actualFrozenWeight_eq_source_of_arbitrarySeedReplacement
assert_no_sorry BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacement_frozenAmbientWeight_eq_source_of_arbitrarySeedReplacement
assert_no_sorry BankPaperRealization.sum_bankPaperCanonicalGuardedStructuredAdditivePlacement_actualFrozenWeight_mul_log_eq_source_of_arbitrarySeedReplacement
assert_no_sorry BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacement_actualFrozenLogMass_eq_source_of_arbitrarySeedReplacement
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlaced_actualFrozenWeight_eq_roundedSource
assert_no_sorry BankPaperRealization.sum_bankPaperCanonicalSectionNinePostHeightPlaced_actualFrozenWeight_mul_log_eq_roundedSource
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlaced_actualFrozenLogMass_eq_roundedSource

end Erdos390.WholePaper
