import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalClippedIntervalGeometry
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for signed exceptional clipped-interval geometry -/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms roughCanonicalExceptionalPhysicalLowerEndpoint
#print axioms roughCanonicalExceptionalPhysicalUpperEndpoint
#print axioms roughCanonicalExceptionalClippedRoughInterval_eq_endpoints
#print axioms RoughCanonicalExceptionalPhysicalIntervalGeometry
#print axioms RoughCanonicalExceptionalCommonEndpointGeometry
#print axioms RoughCanonicalExceptionalPhysicalIntervalGeometry.counting_inputs
#print axioms fourFiveRoughInterval_eq_empty_of_upper_le_lower
#print axioms roughCanonicalExceptionalClippedRoughInterval_eq_empty
#print axioms roughCanonicalExceptionalClippedRoughInterval_card_eq_zero
#print axioms roughCanonicalExceptionalClippedInterval_geometry
#print axioms roughCanonicalExceptionalClippedInterval_geometry_or_empty
#print axioms roughCanonicalExceptional_threePhysicalIntervals_geometry_or_empty
#print axioms rpow_one_sub_le_roughCanonicalRealExceptionalRoughCutoff
#print axioms one_le_roughCanonicalRealExceptionalRoughCutoff
#print axioms yNat_le_roughCanonicalRealExceptionalRoughCutoff
#print axioms roughCanonicalExceptionalPaddedLogThreshold
#print axioms roughCanonicalExceptional_common_padded_log_range
#print axioms three_mul_lt_yNat_succ_pow_five
#print axioms roughCanonicalExceptionalCommonEndpointGeometry_of_bounds
#print axioms eventually_roughCanonicalExceptionalCommonEndpointGeometry
#print axioms eventually_roughCanonicalExceptional_threePhysicalIntervals_geometry_or_empty

assert_no_sorry roughCanonicalExceptionalPhysicalLowerEndpoint
assert_no_sorry roughCanonicalExceptionalPhysicalUpperEndpoint
assert_no_sorry roughCanonicalExceptionalClippedRoughInterval_eq_endpoints
assert_no_sorry RoughCanonicalExceptionalPhysicalIntervalGeometry
assert_no_sorry RoughCanonicalExceptionalCommonEndpointGeometry
assert_no_sorry RoughCanonicalExceptionalPhysicalIntervalGeometry.counting_inputs
assert_no_sorry fourFiveRoughInterval_eq_empty_of_upper_le_lower
assert_no_sorry roughCanonicalExceptionalClippedRoughInterval_eq_empty
assert_no_sorry roughCanonicalExceptionalClippedRoughInterval_card_eq_zero
assert_no_sorry roughCanonicalExceptionalClippedInterval_geometry
assert_no_sorry roughCanonicalExceptionalClippedInterval_geometry_or_empty
assert_no_sorry roughCanonicalExceptional_threePhysicalIntervals_geometry_or_empty
assert_no_sorry rpow_one_sub_le_roughCanonicalRealExceptionalRoughCutoff
assert_no_sorry one_le_roughCanonicalRealExceptionalRoughCutoff
assert_no_sorry yNat_le_roughCanonicalRealExceptionalRoughCutoff
assert_no_sorry roughCanonicalExceptionalPaddedLogThreshold
assert_no_sorry roughCanonicalExceptional_common_padded_log_range
assert_no_sorry three_mul_lt_yNat_succ_pow_five
assert_no_sorry roughCanonicalExceptionalCommonEndpointGeometry_of_bounds
assert_no_sorry eventually_roughCanonicalExceptionalCommonEndpointGeometry
assert_no_sorry eventually_roughCanonicalExceptional_threePhysicalIntervals_geometry_or_empty

end Erdos390.WholePaper.BankPaperRealization
