import Erdos390.WholePaper.BankPaperCanonicalTopFrozenRoundedSourceStateConnector
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenSmoothFrozenMass
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedActiveMass
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenNearestIntegerCellMass
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenNearestIntegerCellMass_eq_symmetricInitial
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedActiveSeed
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_eq_of_mem_nonsmoothRow
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_apply_of_mem_nonsmoothRow
#print axioms BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_apply_of_mem_exceptionalNonsmoothRow
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_eq_qTildeSource_of_mem_nonsmoothRow
#print axioms BankPaperRealization.bankPaperCanonicalLiteralActiveMass_topFrozenRoundedActiveSeed
#print axioms BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedActiveSeed_mul_headValuation_eq_qTilde
#print axioms BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedAmbient_mul_headValuation_eq_qTilde
#print axioms BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedSourceSelector_smoothRow
#print axioms BankPaperRealization.bankPaperCanonicalChargedNonsmoothRowRealization_topFrozenRounded_of_qTilde
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_feasible_of_qTildeSource
#print axioms BankPaperRealization.bankPaperCanonicalSelectorRowIntegral_of_chargedNonsmoothRows_of_smoothQuota
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_rowIntegral
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSelectorSourceState

assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenSmoothFrozenMass
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedActiveMass
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenNearestIntegerCellMass
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenNearestIntegerCellMass_eq_symmetricInitial
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedActiveSeed
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_eq_of_mem_nonsmoothRow
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_apply_of_mem_nonsmoothRow
assert_no_sorry BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_apply_of_mem_exceptionalNonsmoothRow
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_eq_qTildeSource_of_mem_nonsmoothRow
assert_no_sorry BankPaperRealization.bankPaperCanonicalLiteralActiveMass_topFrozenRoundedActiveSeed
assert_no_sorry BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedActiveSeed_mul_headValuation_eq_qTilde
assert_no_sorry BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedAmbient_mul_headValuation_eq_qTilde
assert_no_sorry BankPaperRealization.sum_bankPaperCanonicalTopFrozenRoundedSourceSelector_smoothRow
assert_no_sorry BankPaperRealization.bankPaperCanonicalChargedNonsmoothRowRealization_topFrozenRounded_of_qTilde
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_feasible_of_qTildeSource
assert_no_sorry BankPaperRealization.bankPaperCanonicalSelectorRowIntegral_of_chargedNonsmoothRows_of_smoothQuota
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_rowIntegral
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSelectorSourceState

end Erdos390.WholePaper
