import Erdos390.WholePaper.BankPaperCanonicalSaiasUpperReduction
import Mathlib.Util.AssertNoSorry

#print Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput
#print axioms Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.mk
#print axioms Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.selector
#print axioms Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.feasible
#print axioms Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.rowIntegral
#print axioms Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.valuationCertificate
#print axioms Erdos390.WholePaper.bankPaper_activeRoughRowQuota_and_isAdmissibleEndpoint_of_canonicalSaiasHandoff

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.mk
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.selector
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.feasible
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.rowIntegral
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalPostTangentOutput.valuationCertificate
assert_no_sorry Erdos390.WholePaper.bankPaper_activeRoughRowQuota_and_isAdmissibleEndpoint_of_canonicalSaiasHandoff
