import Erdos390.WholePaper.BankPaperCanonicalP87ApproximateOrdinaryLogTargetEnvelopeConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for approximate ordinary-log target envelopes
-/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperCanonicalSelectorOrdinaryLogCompatibleUpTo
#print axioms Erdos390.WholePaper.BankPaperCanonicalSelectorOrdinaryLogCompatibleUpTo.of_exact
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_ordinaryLogCompatibleUpTo
#print axioms Erdos390.WholePaper.BankPaperCanonicalSelectorOrdinaryLogCompatibleUpTo.of_eq_normalizedHeightRoundingDefect
#print axioms Erdos390.WholePaper.bankPaperCanonicalBandCenterResidual_eq_primeDeviationResidual_add_ordinaryDefect
#print axioms Erdos390.WholePaper.bankPaperCanonicalHasTargetEnvelopes_seven_add_of_primeResidual
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualInitialHasTargetEnvelopes_of_selectorDeficit_of_approximateOrdinaryLog
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothNormalizedHeightRoundingDefect
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothNormalizedHeightRoundingDefect_abs_le
#print axioms Erdos390.WholePaper.eventually_bankPaperCanonicalSmoothNormalizedHeightRoundingDefect_abs_le_nine_halves
#print axioms Erdos390.WholePaper.eventually_constant_le_activeMass_div_L_mul_mesh
#print axioms Erdos390.WholePaper.eventually_bankPaperCanonicalSmoothNormalizedHeightRoundingDefect_abs_le_activeMass_div_L_mul_mesh

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSelectorOrdinaryLogCompatibleUpTo
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSelectorOrdinaryLogCompatibleUpTo.of_exact
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_ordinaryLogCompatibleUpTo
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSelectorOrdinaryLogCompatibleUpTo.of_eq_normalizedHeightRoundingDefect
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBandCenterResidual_eq_primeDeviationResidual_add_ordinaryDefect
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalHasTargetEnvelopes_seven_add_of_primeResidual
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualInitialHasTargetEnvelopes_of_selectorDeficit_of_approximateOrdinaryLog
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothNormalizedHeightRoundingDefect
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothNormalizedHeightRoundingDefect_abs_le
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonicalSmoothNormalizedHeightRoundingDefect_abs_le_nine_halves
assert_no_sorry Erdos390.WholePaper.eventually_constant_le_activeMass_div_L_mul_mesh
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonicalSmoothNormalizedHeightRoundingDefect_abs_le_activeMass_div_L_mul_mesh
