import Erdos390.WholePaper.BankPaperCanonicalSmoothSourceGuardedSharpValuationRateClosureFinal
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the sharp smooth-source valuation closure -/

#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_rawStructuredCell_valuation_mean_profile_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_guardedRawCell_valuation_mean_profiles_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_bridge_guardedCell_valuation_mean_profiles_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_movingPrefix_uniformAverage_divInd_paper_bound_of_fraction
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_movingPrefix_divInd_fallback_of_fraction
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_movingPrefix_valuation_mean_profile_paperRate_of_fraction
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_rawSmoothBasePool_valuation_mean_profile_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_guardedSmoothBasePool_valuation_mean_profile_paperRate
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalScaledActiveValuationMoment_sub_guardedSmoothBase_le_of_commonProfile
#print axioms Erdos390.WholePaper.BankPaperRealization.exists_uniform_scaledActive_sub_guardedSmoothBase_valuationMoment_paperRate

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_rawStructuredCell_valuation_mean_profile_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_guardedRawCell_valuation_mean_profiles_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_bridge_guardedCell_valuation_mean_profiles_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_movingPrefix_uniformAverage_divInd_paper_bound_of_fraction
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_movingPrefix_divInd_fallback_of_fraction
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_movingPrefix_valuation_mean_profile_paperRate_of_fraction
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_rawSmoothBasePool_valuation_mean_profile_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_guardedSmoothBasePool_valuation_mean_profile_paperRate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_bankPaperCanonicalScaledActiveValuationMoment_sub_guardedSmoothBase_le_of_commonProfile
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exists_uniform_scaledActive_sub_guardedSmoothBase_valuationMoment_paperRate
