import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightSourceFirstEventualPostHfitConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the source-first eventual Post-Hfit connector
-/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.BankPaperCanonicalSectionNinePostHeightSourceFirstSpecializedLocalP87At
#print axioms BankPaperRealization.BankPaperCanonicalSectionNinePostHeightSourceFirstSpecializedEventualLocalP87Callback
#print axioms BankPaperRealization.BankPaperCanonicalSectionNinePostHeightSourceFirstSpecializedEventualLocalP87Factory
#print axioms BankPaperRealization.exists_bankPaperCanonicalSectionNinePostHeight_sourceFirstEventualPostHfitInput

assert_no_sorry BankPaperRealization.BankPaperCanonicalSectionNinePostHeightSourceFirstSpecializedLocalP87At
assert_no_sorry BankPaperRealization.BankPaperCanonicalSectionNinePostHeightSourceFirstSpecializedEventualLocalP87Callback
assert_no_sorry BankPaperRealization.BankPaperCanonicalSectionNinePostHeightSourceFirstSpecializedEventualLocalP87Factory
assert_no_sorry BankPaperRealization.exists_bankPaperCanonicalSectionNinePostHeight_sourceFirstEventualPostHfitInput

end Erdos390.WholePaper
