import Erdos390.WholePaper.BankPaperCanonicalSectionEightActualDataConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the actual-data Section 8 connector -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMass
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenLogMass
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMassFamily
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenLogMassFamily
#print axioms Erdos390.WholePaper.bankPaperCanonicalUpperTailHeight
#print axioms Erdos390.WholePaper.bankPaperCanonicalCentralTailLogTarget
#print axioms Erdos390.WholePaper.BankPaperCanonicalActualFrozenIntervalGeometry
#print axioms Erdos390.WholePaper.BankPaperCanonicalActualSelectorMassEstimate
#print axioms Erdos390.WholePaper.BankPaperCanonicalChargedNonsmoothRowRealization
#print axioms Erdos390.WholePaper.bankPaperCanonicalChargedLabelSet
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalInitialSmoothFrozenMass
#print axioms Erdos390.WholePaper.BankPaperCanonicalActualGuardedSmoothMassEstimate
#print axioms Erdos390.WholePaper.BankPaperCanonicalActualFrozenBaselineEstimates
#print axioms Erdos390.WholePaper.BankPaperCanonicalSectionEightActualDataSourceLedger
#print axioms Erdos390.WholePaper.BankPaperCanonicalSectionEightScaledActualDataSourceLedger
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMass_eq
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMass_add_literalActiveMass_eq
#print axioms Erdos390.WholePaper.bankPaperCanonicalCentralTailLog_eq_sum
#print axioms Erdos390.WholePaper.bankPaperCanonicalCentralTailLog_sub_height_mul_L_eq_sum
#print axioms Erdos390.WholePaper.bankPaperCanonicalFactorLog_sub_L_mem_Icc
#print axioms Erdos390.WholePaper.bankPaperCanonicalUpperTailHeight_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalCentralTailLogTarget_sub_height_mul_L_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenWeight_nonneg
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMass_nonneg
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenLogMass_sub_total_mul
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualSelectorMassEstimate_of_frozenBaselineSource
#print axioms Erdos390.WholePaper.sum_eq_sum_completeRoughRowFibers_of_labelSet_subset
#print axioms Erdos390.WholePaper.card_cast_eq_sum_completeLabelMultiplicity_of_labelSet_subset
#print axioms Erdos390.WholePaper.bankPaperCanonical_chargedSelectorMass_sub_height_eq_neg_smoothDiscrepancy
#print axioms Erdos390.WholePaper.bankPaperCanonical_chargedSelectorMass_sub_height_eq_rawSmoothLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSmoothPreinitialMismatch_eq_neg_chargedMassError
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSectionNineContinuation_exists_chargedMassIdentity
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowDiscrepancy_eq_constructedSmoothLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalPostchargeRowDiscrepancy_le_of_constructedSmoothQuota
#check @Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualSelectorMassEstimate_of_constructedSmoothQuota
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualSelectorMassEstimate_of_constructedSmoothQuota
#print axioms Erdos390.WholePaper.bankPaperCanonical_secondOrderScale_div_L_isBigO_secondOrderScale
#print axioms Erdos390.WholePaper.bankPaperAnchorMarkerBudget_isBigO_secondOrderScale_div_L
-- These two declarations now expose generic bank-base sequence interfaces.
#check @Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_card_family_isBigO_secondOrderScale_div_L
#check @Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_logMassFamily_isBigO_secondOrderScale
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_card_family_isBigO_secondOrderScale_div_L
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_logMassFamily_isBigO_secondOrderScale
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMassFamily_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenLogMassFamily_centered_isBigO
#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothCorrectionEstimate_of_actualData
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualGuardedSmoothMassEstimate_scaledActiveSeed
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenBaselineEstimates_of_intervalGeometry
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightScaledActualDataSourceLedger_of_intervalGeometry
#print axioms Erdos390.WholePaper.bankPaperCanonicalFrozenBaselineSourceLedger_of_actualData
-- These five declarations now expose the guarded tail-family interface.
#check @Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_actualData
#check @Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_scaledActualData
#check @Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_scaledActualData_intervalGeometry
#check @Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_constructedSmoothQuota_selectorMass_intervalGeometry
#check @Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_constructedSmoothQuota_intervalGeometry
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_actualData
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_scaledActualData
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_scaledActualData_intervalGeometry
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_constructedSmoothQuota_selectorMass_intervalGeometry
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_constructedSmoothQuota_intervalGeometry

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMass
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenLogMass
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMassFamily
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenLogMassFamily
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalUpperTailHeight
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalCentralTailLogTarget
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActualFrozenIntervalGeometry
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActualSelectorMassEstimate
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalChargedNonsmoothRowRealization
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalChargedLabelSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalInitialSmoothFrozenMass
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActualGuardedSmoothMassEstimate
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActualFrozenBaselineEstimates
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSectionEightActualDataSourceLedger
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSectionEightScaledActualDataSourceLedger
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMass_eq
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMass_add_literalActiveMass_eq
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalCentralTailLog_eq_sum
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalCentralTailLog_sub_height_mul_L_eq_sum
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalFactorLog_sub_L_mem_Icc
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalUpperTailHeight_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalCentralTailLogTarget_sub_height_mul_L_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenWeight_nonneg
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMass_nonneg
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenLogMass_sub_total_mul
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualSelectorMassEstimate_of_frozenBaselineSource
assert_no_sorry Erdos390.WholePaper.sum_eq_sum_completeRoughRowFibers_of_labelSet_subset
assert_no_sorry Erdos390.WholePaper.card_cast_eq_sum_completeLabelMultiplicity_of_labelSet_subset
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_chargedSelectorMass_sub_height_eq_neg_smoothDiscrepancy
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_chargedSelectorMass_sub_height_eq_rawSmoothLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSmoothPreinitialMismatch_eq_neg_chargedMassError
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSectionNineContinuation_exists_chargedMassIdentity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowDiscrepancy_eq_constructedSmoothLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalPostchargeRowDiscrepancy_le_of_constructedSmoothQuota
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualSelectorMassEstimate_of_constructedSmoothQuota
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_secondOrderScale_div_L_isBigO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.bankPaperAnchorMarkerBudget_isBigO_secondOrderScale_div_L
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_card_family_isBigO_secondOrderScale_div_L
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_logMassFamily_isBigO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenTotalMassFamily_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenLogMassFamily_centered_isBigO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothCorrectionEstimate_of_actualData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualGuardedSmoothMassEstimate_scaledActiveSeed
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenBaselineEstimates_of_intervalGeometry
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightScaledActualDataSourceLedger_of_intervalGeometry
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalFrozenBaselineSourceLedger_of_actualData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_actualData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_scaledActualData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_scaledActualData_intervalGeometry
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_constructedSmoothQuota_selectorMass_intervalGeometry
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionEightAnalyticLedger_of_constructedSmoothQuota_intervalGeometry
