import Erdos390.WholePaper.BankPaperCanonicalGuardedRawCorrectionMomentDefectConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the guarded-versus-raw correction-moment defect -/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawBroadCorrectionPoolNormalizedValuationMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPoolNormalizedValuationMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRawNumeratorShift
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRawNumeratorShift_eq_of_active
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawCorrectionDensityAtLabel_eq_rawDiscrepancy_div
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeCorrectionDensity_eq_rawDiscrepancy_add_shift_div
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawRowCorrectionValuationMomentAtLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectionValuationMomentAtLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationDefectAtLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationDefectAtLabel_eq_explicit
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationDefectAtLabel_eq_explicit_of_active
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect_eq_sum_rowDefects
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect_eq_sum_explicit
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect_eq_sum_explicit_active
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedPostchargeRowCorrection_eq_raw_iff_defect_eq_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitGuardedToRawCorrectionValuationReindex_iff_guardedRawDefect_eq_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect_eq_zero_of_rowwise

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawBroadCorrectionPoolNormalizedValuationMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPoolNormalizedValuationMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRawNumeratorShift
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRawNumeratorShift_eq_of_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawCorrectionDensityAtLabel_eq_rawDiscrepancy_div
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeCorrectionDensity_eq_rawDiscrepancy_add_shift_div
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawRowCorrectionValuationMomentAtLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectionValuationMomentAtLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationDefectAtLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationDefectAtLabel_eq_explicit
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRawRowCorrectionValuationDefectAtLabel_eq_explicit_of_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect_eq_sum_rowDefects
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect_eq_sum_explicit
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect_eq_sum_explicit_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedPostchargeRowCorrection_eq_raw_iff_defect_eq_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalPostHfitGuardedToRawCorrectionValuationReindex_iff_guardedRawDefect_eq_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalAggregateGuardedRawCorrectionValuationDefect_eq_zero_of_rowwise
