import Erdos390.WholePaper.BankPaperCanonicalSmoothAdditiveRefinementTangentTransport
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for smooth additive refinement tangent transport -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinementValuationMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalGuardedSmoothAdditiveRefinementZeroMomentLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinementValuationMoment_eq_zero_of_not_prime
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinementValuationMoment_eq_zero_of_yNat_lt
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_sub_base_at_scaledActiveValue
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_guardedCandidates_additiveRefinement_factorization_sub_base_eq_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_additiveRefinement_eq_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTangentResidual_additiveRefinement_eq_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_tangentResidual_additiveRefinement_eq_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentRatioCellPrefixMass_additiveRefinement_eq_sub_moment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_eq_base_on_guardedRow
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_guardedRow_additiveRefinement_eq_base_of_label_ne_one
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_guardedSmoothRow_additiveRefinement_eq_base_of_zeroMomentLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_additiveRefinement_of_zeroMomentLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_additiveRefinement_eq_base_of_zeroMomentLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTangentResidual_additiveRefinement_eq_base_of_zeroMomentLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorRowIntegral_additiveRefinement_of_zeroMomentLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalRoundedSelectorTangentInput_additiveRefinement_of_zeroMomentLedger

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinementValuationMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalGuardedSmoothAdditiveRefinementZeroMomentLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinementValuationMoment_eq_zero_of_not_prime
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinementValuationMoment_eq_zero_of_yNat_lt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_sub_base_at_scaledActiveValue
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_guardedCandidates_additiveRefinement_factorization_sub_base_eq_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_additiveRefinement_eq_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTangentResidual_additiveRefinement_eq_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_tangentResidual_additiveRefinement_eq_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentRatioCellPrefixMass_additiveRefinement_eq_sub_moment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_eq_base_on_guardedRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_guardedRow_additiveRefinement_eq_base_of_label_ne_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_guardedSmoothRow_additiveRefinement_eq_base_of_zeroMomentLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothFlexibleQuota_additiveRefinement_of_zeroMomentLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorValuationDeficit_additiveRefinement_eq_base_of_zeroMomentLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTangentResidual_additiveRefinement_eq_base_of_zeroMomentLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSelectorRowIntegral_additiveRefinement_of_zeroMomentLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalRoundedSelectorTangentInput_additiveRefinement_of_zeroMomentLedger
