import Erdos390.WholePaper.BankPaperCanonicalTangentSlackIntegration
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the canonical tangent-slack integration

All five public definitions and all ten public theorems are printed and
checked by `assert_no_sorry`.
-/

#print axioms Erdos390.WholePaper.IsPaperCombinedTangentDeltaStar
#print axioms Erdos390.WholePaper.paperCombinedTangentDeltaStar
#print axioms Erdos390.WholePaper.paperCombinedTangentDeltaStar_spec
#print axioms Erdos390.WholePaper.paperCombinedTangentDeltaStar_chargeSpec
#print axioms Erdos390.WholePaper.paperCombinedTangentDeltaStar_cleanListInputs
#print axioms Erdos390.WholePaper.exists_eventually_bankPaperCombinedChargeTerminal_for_tangentChoice
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeCorrectionDensity
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight_apply_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight_twoSidedSlack
#print axioms Erdos390.WholePaper.BankPaperRealization.canonicalDistributedCleanMultiplier_guardedBroadEndpoints
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalGuardedEndpointSlackConstruction
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedEndpointSlackConstruction_twoSidedSlack_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedEndpointSlackConstruction_cleanMultiplierSlack
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedEndpointSlackConstruction_candidateSetEndpointInputs

assert_no_sorry Erdos390.WholePaper.IsPaperCombinedTangentDeltaStar
assert_no_sorry Erdos390.WholePaper.paperCombinedTangentDeltaStar
assert_no_sorry Erdos390.WholePaper.paperCombinedTangentDeltaStar_spec
assert_no_sorry Erdos390.WholePaper.paperCombinedTangentDeltaStar_chargeSpec
assert_no_sorry Erdos390.WholePaper.paperCombinedTangentDeltaStar_cleanListInputs
assert_no_sorry Erdos390.WholePaper.exists_eventually_bankPaperCombinedChargeTerminal_for_tangentChoice
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeCorrectionDensity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight_apply_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeRowCorrectedWeight_twoSidedSlack
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.canonicalDistributedCleanMultiplier_guardedBroadEndpoints
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalGuardedEndpointSlackConstruction
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedEndpointSlackConstruction_twoSidedSlack_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedEndpointSlackConstruction_cleanMultiplierSlack
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedEndpointSlackConstruction_candidateSetEndpointInputs
