import Erdos390.WholePaper.BankPaperFourFiveRealCommonDomainIdentification

/-! Statement audit for the exact real-endpoint common-domain bridge and
the fully bounded real-endpoint assembly. -/

namespace Erdos390.WholePaper.BankPaperRealization

#check fourFiveRealPrefixCutoffKernel
#check fourFiveLastPrimeRealPhysicalIntegral_eq_cutoffIntegral
#check fourFivePrimePrefixMovingTerm
#check intervalIntegrable_fourFivePrimePrefixMovingTerm
#check fourFiveLastPrimeRealPhysicalIntegral_eq_prefixMovingTerm
#check fourFiveOrderedLastPrimeRealPhysicalLayer_zero_eq_physicalActualMoving
#check fourFiveOrderedLastPrimeRealPhysicalLayer_one_eq_physicalActualMoving
#check fourFiveOrderedLastPrimeRealPhysicalLayer_two_eq_physicalActualMoving
#check fourFiveOrderedLastPrimeRealPhysicalLayer_three_eq_physicalActualMoving
#check fourFiveOrderedLastPrimeRealPhysicalLayer_eq_physicalActualMovingLayer
#check abs_fourFiveOrderedLastPrimeRealPhysicalLayer_sub_physicalActualMovingLayer
#check fourFiveLastPrimeRealPhysicalChangeError
#check fourFiveLastPrimeRealPhysicalChangeError_eq_zero
#check fourFivePhysicalOuterScaledBVError
#check fourFivePhysicalProductReplacementError_one_le_outer
#check fourFivePhysicalProductReplacementError_two_le_outer
#check fourFivePhysicalProductReplacementError_three_le_outer
#check fourFivePhysicalProductReplacementError_le_movingFaceBudget
#check fourFivePhysicalProductBudgetOverrun_eq_zero_outerScaled
#check abs_fourFiveRealLastPrimeIntegralLayer_sub_fixed_le_fullyBounded
#check fourFiveRealEndpointFullyBoundedAssemblyError
#check fourFiveOrderedPrimeMixtureEstimate_realEndpoint_fullyBounded
#check fourFiveOrderedPrimeMixtureEstimate_realEndpoint_fullyBounded_mixtureIntegral

end Erdos390.WholePaper.BankPaperRealization
