import Erdos390.WholePaper.BankPaperCanonicalSmoothQuotaHeightLedger
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the exact Section 8 smooth quota/height ledger -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseWeight_eq_roughRawWeight
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalRawSmoothBaseWeight
#print axioms Erdos390.WholePaper.isCompleteRoughLabel_one
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBasePool_card_eq_headFreeSmoothInterval
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseMass_eq_headFreeSmoothInterval
#print axioms Erdos390.WholePaper.bankPaperNearestIntegerTieLower_eq_iff
#print axioms Erdos390.WholePaper.bankPaperNearestIntegerTieLower_intCast
#print axioms Erdos390.WholePaper.bankPaperNearestIntegerTieLower_add_half
#print axioms Erdos390.WholePaper.bankPaperNearestIntegerTieLower_abs_sub_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothInitialQuota_eq_of_total_eq_intCast
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothInitialActiveMass_sub_actual
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothInitialActiveMass_abs_sub_actual_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothActiveMassAt_eq_q0_sub
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothQuotaAt_cast_eq_frozen_add_active
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothQuotaAt_exact_ledger
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothFlexibleQuotaAt_exact_ledger
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothActiveHeightAt_eq_defect_add
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustment_abs_sub_center_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustedActiveMass_eq_q0_sub_d
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothHeightCenter_exact_residual
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustment_centered_residual_bound
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothHeightCenter_exact_mean_error
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustment_mean_error_bound
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothActiveHeight_centered_residual
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothFinalActiveMassFamily_eq_q0_sub_d
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothQ0Family_abs_sub_qTilde_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothDRealFamily_abs_sub_dStar_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalSmoothPhysicalMeanErrorFamily_bound

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseWeight_eq_roughRawWeight
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalRawSmoothBaseWeight
assert_no_sorry Erdos390.WholePaper.isCompleteRoughLabel_one
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBasePool_card_eq_headFreeSmoothInterval
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBaseMass_eq_headFreeSmoothInterval
assert_no_sorry Erdos390.WholePaper.bankPaperNearestIntegerTieLower_eq_iff
assert_no_sorry Erdos390.WholePaper.bankPaperNearestIntegerTieLower_intCast
assert_no_sorry Erdos390.WholePaper.bankPaperNearestIntegerTieLower_add_half
assert_no_sorry Erdos390.WholePaper.bankPaperNearestIntegerTieLower_abs_sub_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothInitialQuota_eq_of_total_eq_intCast
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothInitialActiveMass_sub_actual
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothInitialActiveMass_abs_sub_actual_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothActiveMassAt_eq_q0_sub
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothQuotaAt_cast_eq_frozen_add_active
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothQuotaAt_exact_ledger
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothFlexibleQuotaAt_exact_ledger
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothActiveHeightAt_eq_defect_add
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustment_abs_sub_center_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustedActiveMass_eq_q0_sub_d
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothHeightCenter_exact_residual
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustment_centered_residual_bound
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothHeightCenter_exact_mean_error
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothHeightAdjustment_mean_error_bound
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothActiveHeight_centered_residual
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothFinalActiveMassFamily_eq_q0_sub_d
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothQ0Family_abs_sub_qTilde_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothDRealFamily_abs_sub_dStar_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSmoothPhysicalMeanErrorFamily_bound
