import Erdos390.WholePaper.BankPaperCanonicalTopFrozenRoundedSourceStateConnector

/-! # Statement audit for the frozen-top nearest-integer source state -/

namespace Erdos390.WholePaper

open Erdos390.Full
open Erdos390.Full.ArithmeticModel
open Erdos390.Full.PaperBridgeFit
open Erdos390.Full.PaperGuardCensus

noncomputable section

namespace BankPaperRealization

#check bankPaperCanonicalTopFrozenSmoothFrozenMass
#check bankPaperCanonicalTopFrozenRoundedActiveMass
#check bankPaperCanonicalTopFrozenNearestIntegerCellMass
#check bankPaperCanonicalTopFrozenNearestIntegerCellMass_eq_symmetricInitial
#check bankPaperCanonicalTopFrozenRoundedActiveSeed
#check bankPaperCanonicalTopFrozenRoundedSourceSelector
#check bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_eq_of_mem_nonsmoothRow
#check bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_apply_of_mem_nonsmoothRow
#check bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_apply_of_mem_exceptionalNonsmoothRow
#check bankPaperCanonicalTopFrozenRoundedSourceSelector_eq_qTildeSource_of_mem_nonsmoothRow
#check bankPaperCanonicalLiteralActiveMass_topFrozenRoundedActiveSeed
#check sum_bankPaperCanonicalTopFrozenRoundedActiveSeed_mul_headValuation_eq_qTilde
#check sum_bankPaperCanonicalTopFrozenRoundedAmbient_mul_headValuation_eq_qTilde
#check sum_bankPaperCanonicalTopFrozenRoundedSourceSelector_smoothRow
#check bankPaperCanonicalChargedNonsmoothRowRealization_topFrozenRounded_of_qTilde
#check bankPaperCanonicalTopFrozenRoundedSourceSelector_feasible_of_qTildeSource
#check bankPaperCanonicalSelectorRowIntegral_of_chargedNonsmoothRows_of_smoothQuota
#check bankPaperCanonicalTopFrozenRoundedSourceSelector_rowIntegral
#check bankPaperCanonicalTopFrozenRoundedSelectorSourceState

end BankPaperRealization

end

end Erdos390.WholePaper
