import Erdos390.WholePaper.BankPaperCanonicalRoughRowCorrection
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for finite canonical row correction -/

#print axioms Erdos390.WholePaper.bankPaperConstantPoolCorrectionDensity
#print axioms Erdos390.WholePaper.bankPaperConstantPoolCorrection
#print axioms Erdos390.WholePaper.bankPaperConstantPoolCorrection_apply_of_mem
#print axioms Erdos390.WholePaper.bankPaperConstantPoolCorrection_apply_of_not_mem
#print axioms Erdos390.WholePaper.sum_bankPaperConstantPoolCorrection_eq_target
#print axioms Erdos390.WholePaper.bankPaperConstantPoolCorrection_mem_unitInterval
#print axioms Erdos390.WholePaper.bankPaperConstantPoolCorrection_mem_unitInterval_of_abs_density_le
#print axioms Erdos390.WholePaper.roughCanonicalBroadCorrectionPool
#print axioms Erdos390.WholePaper.roughCanonicalBroadCorrectionPool_subset_rawRow
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawWeight_eq_broad_of_mem_correctionPool
#print axioms Erdos390.WholePaper.roughCanonicalRawRowCorrectedWeight
#print axioms Erdos390.WholePaper.roughCanonicalRawRowCorrectionDensity_eq_quotaError_div
#print axioms Erdos390.WholePaper.sum_roughCanonicalRawRowCorrectedWeight_eq_upperTarget
#print axioms Erdos390.WholePaper.roughCanonicalRawRowCorrectedWeight_mem_unitInterval
#print axioms Erdos390.WholePaper.roughCanonicalRawRowCorrection_exact_and_feasible
#print axioms Erdos390.WholePaper.roughCanonicalRawCorrectedSelector
#print axioms Erdos390.WholePaper.roughCanonicalRawCorrectedSelector_eq_rowCorrected_of_mem
#print axioms Erdos390.WholePaper.sum_roughCanonicalRawCorrectedSelector_eq_upperTarget
#print axioms Erdos390.WholePaper.roughCanonicalRawCorrectedSelector_mem_unitInterval
#print axioms Erdos390.WholePaper.roughCanonicalRawCorrectedSelector_rowSums_integer
#print axioms Erdos390.WholePaper.roughCanonicalRawCorrectedSelector_finiteState
#print axioms Erdos390.WholePaper.roughCanonicalCappedUpperQuota
#print axioms Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector
#print axioms Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_apply_of_mem
#print axioms Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_apply_of_not_mem
#print axioms Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_mem_unitInterval
#print axioms Erdos390.WholePaper.sum_roughCanonicalCappedUpperQuotaSelector_eq_cappedQuota
#print axioms Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_rowSums_integer
#print axioms Erdos390.WholePaper.roughCanonicalCappedUpperQuota_eq_upperTarget_of_capacity
#print axioms Erdos390.WholePaper.sum_roughCanonicalCappedUpperQuotaSelector_eq_upperTarget_of_capacity
#print axioms Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_finiteState

assert_no_sorry Erdos390.WholePaper.bankPaperConstantPoolCorrectionDensity
assert_no_sorry Erdos390.WholePaper.bankPaperConstantPoolCorrection
assert_no_sorry Erdos390.WholePaper.bankPaperConstantPoolCorrection_apply_of_mem
assert_no_sorry Erdos390.WholePaper.bankPaperConstantPoolCorrection_apply_of_not_mem
assert_no_sorry Erdos390.WholePaper.sum_bankPaperConstantPoolCorrection_eq_target
assert_no_sorry Erdos390.WholePaper.bankPaperConstantPoolCorrection_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.bankPaperConstantPoolCorrection_mem_unitInterval_of_abs_density_le
assert_no_sorry Erdos390.WholePaper.roughCanonicalBroadCorrectionPool
assert_no_sorry Erdos390.WholePaper.roughCanonicalBroadCorrectionPool_subset_rawRow
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawWeight_eq_broad_of_mem_correctionPool
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowCorrectedWeight
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowCorrectionDensity_eq_quotaError_div
assert_no_sorry Erdos390.WholePaper.sum_roughCanonicalRawRowCorrectedWeight_eq_upperTarget
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowCorrectedWeight_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowCorrection_exact_and_feasible
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawCorrectedSelector
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawCorrectedSelector_eq_rowCorrected_of_mem
assert_no_sorry Erdos390.WholePaper.sum_roughCanonicalRawCorrectedSelector_eq_upperTarget
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawCorrectedSelector_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawCorrectedSelector_rowSums_integer
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawCorrectedSelector_finiteState
assert_no_sorry Erdos390.WholePaper.roughCanonicalCappedUpperQuota
assert_no_sorry Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector
assert_no_sorry Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_apply_of_mem
assert_no_sorry Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_apply_of_not_mem
assert_no_sorry Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.sum_roughCanonicalCappedUpperQuotaSelector_eq_cappedQuota
assert_no_sorry Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_rowSums_integer
assert_no_sorry Erdos390.WholePaper.roughCanonicalCappedUpperQuota_eq_upperTarget_of_capacity
assert_no_sorry Erdos390.WholePaper.sum_roughCanonicalCappedUpperQuotaSelector_eq_upperTarget_of_capacity
assert_no_sorry Erdos390.WholePaper.roughCanonicalCappedUpperQuotaSelector_finiteState
