import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightSourceFirstMassAlgebra
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the source-first post-height mass algebra
-/

namespace Erdos390.WholePaper

#print axioms eventually_bankPaperCanonical_fixedHalfScaleLower_sub_of_isLittleO
#print axioms eventually_bankPaperCanonical_fixedHalfScaleLower_sub_of_logScale_isBigO
#print axioms eventually_bankPaperCanonicalSectionNinePostHeight_finalActiveMass_ge_quarter_sourceCoefficient
#print axioms exists_eventually_bankPaperCanonicalSectionNinePostHeight_preledgerSourceMassExponent

assert_no_sorry eventually_bankPaperCanonical_fixedHalfScaleLower_sub_of_isLittleO
assert_no_sorry eventually_bankPaperCanonical_fixedHalfScaleLower_sub_of_logScale_isBigO
assert_no_sorry eventually_bankPaperCanonicalSectionNinePostHeight_finalActiveMass_ge_quarter_sourceCoefficient
assert_no_sorry exists_eventually_bankPaperCanonicalSectionNinePostHeight_preledgerSourceMassExponent

end Erdos390.WholePaper
