import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalFourFiveDeepEndpointErrorConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for deep exceptional endpoint-length errors
-/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms abs_clippedNatIntervalLength_sub_ideal_le
#print axioms roughCanonicalRealExceptionalRoughCutoff_le_natQuotient_of_real_le
#print axioms roughCanonicalFourFiveDeepUpperHigh_noClipping_of_scale
#print axioms roughCanonicalFourFiveDeepUpperEndpointLengthError_le_one
#print axioms roughCanonicalFourFiveDeepHighEndpointLengthError_le_one
#print axioms roughCanonicalFourFiveDeepBroadClippingExcess_le
#print axioms roughCanonicalFourFiveDeepBroadEndpointLengthError_le
#print axioms RoughCanonicalFourFiveDeepEndpointLengthErrorsAt
#print axioms roughCanonicalFourFiveDeepEndpointLengthErrorsAt_of_scale
#print axioms RoughCanonicalFourFiveDeepEndpointLengthErrorsAt.upper_adapter_inputs
#print axioms RoughCanonicalFourFiveDeepEndpointLengthErrorsAt.high_adapter_inputs
#print axioms RoughCanonicalFourFiveDeepEndpointLengthErrorsAt.broad_adapter_inputs
#print axioms eventually_deepEndpointError_L_le_rpow
#print axioms eventually_roughCanonicalFourFiveDeepUpperHigh_noClipping
#print axioms eventually_roughCanonicalFourFiveDeepEndpointLengthErrorsAt

assert_no_sorry abs_clippedNatIntervalLength_sub_ideal_le
assert_no_sorry roughCanonicalRealExceptionalRoughCutoff_le_natQuotient_of_real_le
assert_no_sorry roughCanonicalFourFiveDeepUpperHigh_noClipping_of_scale
assert_no_sorry roughCanonicalFourFiveDeepUpperEndpointLengthError_le_one
assert_no_sorry roughCanonicalFourFiveDeepHighEndpointLengthError_le_one
assert_no_sorry roughCanonicalFourFiveDeepBroadClippingExcess_le
assert_no_sorry roughCanonicalFourFiveDeepBroadEndpointLengthError_le
assert_no_sorry RoughCanonicalFourFiveDeepEndpointLengthErrorsAt
assert_no_sorry roughCanonicalFourFiveDeepEndpointLengthErrorsAt_of_scale
assert_no_sorry RoughCanonicalFourFiveDeepEndpointLengthErrorsAt.upper_adapter_inputs
assert_no_sorry RoughCanonicalFourFiveDeepEndpointLengthErrorsAt.high_adapter_inputs
assert_no_sorry RoughCanonicalFourFiveDeepEndpointLengthErrorsAt.broad_adapter_inputs
assert_no_sorry eventually_deepEndpointError_L_le_rpow
assert_no_sorry eventually_roughCanonicalFourFiveDeepUpperHigh_noClipping
assert_no_sorry eventually_roughCanonicalFourFiveDeepEndpointLengthErrorsAt

end Erdos390.WholePaper.BankPaperRealization
