import Erdos390.WholePaper.BankPaperPrecharge
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the actual precharge layer -/

#print axioms Erdos390.WholePaper.BankBottomPaperRealization.two_mul_n_lt_donorFactor
#print axioms Erdos390.WholePaper.BankPaperRealization.precharge_completeRoughSignature_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBase_donor_factorization_eq_of_yNat_lt
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeComponentOccurrences_disjoint
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorValue_ne_endpointValue_of_request_ne
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateValue_ne_alternateStateValue
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeStateOccurrence_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateValue_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeAlternateStateValue_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorValue_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBottomTerminalDonor_eq_endpoint
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorSet_subset_tail
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorSet_prod_dvd_centralTailProduct
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_disjoint_prechargeAlternateState
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorSet_card
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorBaseEquiv
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorToBase_completeRoughSignature
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_eq_componentProduct
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorSet_prod_eq_componentProduct
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_factorization_eq_donorSet_prod
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_factorization_le
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_factorization_le_anchorMarkerBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.card_bankPaperMarkerRequest_le_anchorMarkerBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeComponentCount_isBigO_yNat_sq

assert_no_sorry Erdos390.WholePaper.BankBottomPaperRealization.two_mul_n_lt_donorFactor
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.precharge_completeRoughSignature_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBase_donor_factorization_eq_of_yNat_lt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeComponentOccurrences_disjoint
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorValue_ne_endpointValue_of_request_ne
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateValue_ne_alternateStateValue
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeStateOccurrence_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateValue_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeAlternateStateValue_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorValue_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBottomTerminalDonor_eq_endpoint
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorSet_subset_tail
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorSet_prod_dvd_centralTailProduct
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_disjoint_prechargeAlternateState
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorSet_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorBaseEquiv
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorToBase_completeRoughSignature
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_eq_componentProduct
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorSet_prod_eq_componentProduct
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_factorization_eq_donorSet_prod
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_factorization_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseStateProduct_factorization_le_anchorMarkerBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.card_bankPaperMarkerRequest_le_anchorMarkerBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeComponentCount_isBigO_yNat_sq
