import Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenEventStepConnector
import Mathlib.Util.AssertNoSorry

/-! Transitive axiom and sorry-freedom audit for the frozen-top event step. -/

#print axioms Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSynchronizedPostHfitInputAt
#print axioms Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSynchronizedPostHfitInput
#print axioms Erdos390.WholePaper.bankPaperCanonicalSectionNineTopFrozenFinalPayload_eventStep
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedSectionNineTerminalAtDepth_of_topFrozenSynchronizedPostHfit

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSynchronizedPostHfitInputAt
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSynchronizedPostHfitInput
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSectionNineTopFrozenFinalPayload_eventStep
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedSectionNineTerminalAtDepth_of_topFrozenSynchronizedPostHfit
