import Erdos390.WholePaper.BankPaperFourFiveActiveLogCoordinate
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveStrictLogarithmicMovingSimplex
#print axioms fourFivePhysicalActiveMovingSimplex
#print axioms fourFivePhysicalActiveMovingSimplexIntegrand
#print axioms fourFivePhysicalActiveMovingSimplexKernel
#print axioms fourFivePhysicalActiveMovingSimplexOne
#print axioms fourFivePhysicalActiveMovingSimplexTwo
#print axioms fourFivePhysicalActiveMovingSimplexThree
#print axioms fourFivePhysicalActiveIntegrandOne
#print axioms fourFivePhysicalActiveIntegrandTwo
#print axioms fourFivePhysicalActiveIntegrandThree
#print axioms fourFiveFinThreeArrow
#print axioms fourFiveCoordinateSumCLM
#print axioms fourFiveLogCoordinateExpMap
#print axioms fourFiveLogCoordinateExpDerivative
#print axioms measurableSet_fourFivePhysicalActiveMovingSimplex
#print axioms measurableSet_fourFivePhysicalActiveMovingSimplexOne
#print axioms measurableSet_fourFivePhysicalActiveMovingSimplexTwo
#print axioms measurableSet_fourFivePhysicalActiveMovingSimplexThree
#print axioms fourFiveFinThreeArrow_apply
#print axioms fourFiveFinThreeArrow_measurePreserving
#print axioms fourFiveFinThreeArrow_symm_apply_zero
#print axioms fourFiveFinThreeArrow_symm_apply_one
#print axioms fourFiveFinThreeArrow_symm_apply_two
#print axioms image_fourFivePhysicalActiveMovingSimplex_finOne
#print axioms image_fourFivePhysicalActiveMovingSimplex_finTwo
#print axioms image_fourFivePhysicalActiveMovingSimplex_finThree
#print axioms fourFivePhysicalActiveMovingSimplexKernel_one_eq_setIntegral
#print axioms fourFivePhysicalActiveMovingSimplexKernel_two_eq_setIntegral
#print axioms fourFivePhysicalActiveMovingSimplexKernel_three_eq_setIntegral
#print axioms fourFivePhysicalActiveMovingSimplexOne_subset_Ioc
#print axioms fourFivePhysicalActiveMovingSimplexTwo_subset_box
#print axioms fourFivePhysicalActiveMovingSimplexThree_subset_box
#print axioms fourFiveStrictLogarithmicMovingSimplex_subset_closed
#print axioms isOpen_fourFiveStrictLogarithmicMovingSimplex
#print axioms isClosed_fourFiveLogarithmicMovingSimplex
#print axioms convex_fourFiveLogarithmicMovingSimplex
#print axioms fourFiveCoordinateSumCLM_apply
#print axioms fourFiveCoordinateSumCLM_surjective
#print axioms interior_fourFiveLogarithmicMovingSimplex_subset_strict
#print axioms fourFiveStrictLogarithmicMovingSimplex_ae_eq_closed
#print axioms fourFiveStrictLogarithmicMovingSimplexKernel_eq_closed
#print axioms hasFDerivAt_fourFiveLogCoordinateExpMap
#print axioms det_fourFiveLogCoordinateExpDerivative
#print axioms fourFiveLogCoordinateExpMap_injective
#print axioms fourFiveRealLogCoordinate_expMap
#print axioms image_fourFiveStrictLogarithmicSimplex_exp_eq_physical
#print axioms abs_det_fourFiveLogCoordinateExpDerivative
#print axioms fourFive_expJacobian_mul_physicalIntegrand
#print axioms fourFivePhysicalActiveMovingSimplexKernel_eq_logarithmic
#print axioms fourFiveMovingFaceRealCellIntegralSum_eq_physicalActiveKernel
#print axioms fourFiveMovingSimplexActivePhysicalIntegralTwo_eq_physicalActiveKernel
#print axioms fourFiveMovingSimplexActivePhysicalIntegralThree_eq_physicalActiveKernel
#print axioms fourFiveMovingFaceRealCellIntegralSum_eq_logarithmicKernel
#print axioms fourFiveMovingSimplexIteratedRealCellProductTwo_eq_logarithmicKernel
#print axioms fourFiveMovingSimplexIteratedRealCellProductThree_eq_logarithmicKernel

assert_no_sorry fourFiveStrictLogarithmicMovingSimplex
assert_no_sorry fourFivePhysicalActiveMovingSimplex
assert_no_sorry fourFivePhysicalActiveMovingSimplexIntegrand
assert_no_sorry fourFivePhysicalActiveMovingSimplexKernel
assert_no_sorry fourFivePhysicalActiveMovingSimplexOne
assert_no_sorry fourFivePhysicalActiveMovingSimplexTwo
assert_no_sorry fourFivePhysicalActiveMovingSimplexThree
assert_no_sorry fourFivePhysicalActiveIntegrandOne
assert_no_sorry fourFivePhysicalActiveIntegrandTwo
assert_no_sorry fourFivePhysicalActiveIntegrandThree
assert_no_sorry fourFiveFinThreeArrow
assert_no_sorry fourFiveCoordinateSumCLM
assert_no_sorry fourFiveLogCoordinateExpMap
assert_no_sorry fourFiveLogCoordinateExpDerivative
assert_no_sorry measurableSet_fourFivePhysicalActiveMovingSimplex
assert_no_sorry measurableSet_fourFivePhysicalActiveMovingSimplexOne
assert_no_sorry measurableSet_fourFivePhysicalActiveMovingSimplexTwo
assert_no_sorry measurableSet_fourFivePhysicalActiveMovingSimplexThree
assert_no_sorry fourFiveFinThreeArrow_apply
assert_no_sorry fourFiveFinThreeArrow_measurePreserving
assert_no_sorry fourFiveFinThreeArrow_symm_apply_zero
assert_no_sorry fourFiveFinThreeArrow_symm_apply_one
assert_no_sorry fourFiveFinThreeArrow_symm_apply_two
assert_no_sorry image_fourFivePhysicalActiveMovingSimplex_finOne
assert_no_sorry image_fourFivePhysicalActiveMovingSimplex_finTwo
assert_no_sorry image_fourFivePhysicalActiveMovingSimplex_finThree
assert_no_sorry fourFivePhysicalActiveMovingSimplexKernel_one_eq_setIntegral
assert_no_sorry fourFivePhysicalActiveMovingSimplexKernel_two_eq_setIntegral
assert_no_sorry fourFivePhysicalActiveMovingSimplexKernel_three_eq_setIntegral
assert_no_sorry fourFivePhysicalActiveMovingSimplexOne_subset_Ioc
assert_no_sorry fourFivePhysicalActiveMovingSimplexTwo_subset_box
assert_no_sorry fourFivePhysicalActiveMovingSimplexThree_subset_box
assert_no_sorry fourFiveStrictLogarithmicMovingSimplex_subset_closed
assert_no_sorry isOpen_fourFiveStrictLogarithmicMovingSimplex
assert_no_sorry isClosed_fourFiveLogarithmicMovingSimplex
assert_no_sorry convex_fourFiveLogarithmicMovingSimplex
assert_no_sorry fourFiveCoordinateSumCLM_apply
assert_no_sorry fourFiveCoordinateSumCLM_surjective
assert_no_sorry interior_fourFiveLogarithmicMovingSimplex_subset_strict
assert_no_sorry fourFiveStrictLogarithmicMovingSimplex_ae_eq_closed
assert_no_sorry fourFiveStrictLogarithmicMovingSimplexKernel_eq_closed
assert_no_sorry hasFDerivAt_fourFiveLogCoordinateExpMap
assert_no_sorry det_fourFiveLogCoordinateExpDerivative
assert_no_sorry fourFiveLogCoordinateExpMap_injective
assert_no_sorry fourFiveRealLogCoordinate_expMap
assert_no_sorry image_fourFiveStrictLogarithmicSimplex_exp_eq_physical
assert_no_sorry abs_det_fourFiveLogCoordinateExpDerivative
assert_no_sorry fourFive_expJacobian_mul_physicalIntegrand
assert_no_sorry fourFivePhysicalActiveMovingSimplexKernel_eq_logarithmic
assert_no_sorry fourFiveMovingFaceRealCellIntegralSum_eq_physicalActiveKernel
assert_no_sorry fourFiveMovingSimplexActivePhysicalIntegralTwo_eq_physicalActiveKernel
assert_no_sorry fourFiveMovingSimplexActivePhysicalIntegralThree_eq_physicalActiveKernel
assert_no_sorry fourFiveMovingFaceRealCellIntegralSum_eq_logarithmicKernel
assert_no_sorry fourFiveMovingSimplexIteratedRealCellProductTwo_eq_logarithmicKernel
assert_no_sorry fourFiveMovingSimplexIteratedRealCellProductThree_eq_logarithmicKernel

end Erdos390.WholePaper.BankPaperRealization
