import Erdos390.WholePaper.BankPaperCanonicalRawRowCorrectionRateClosure
import Mathlib.Util.AssertNoSorry

open Erdos390.WholePaper

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalUniformRawRowCorrectionDensityConstant
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalUniformRawRowCorrectionDensityConstant_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalUniformRawRowCorrectionDensityBound
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalAggregateRawRowCorrectionBound_strictScale

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalUniformRawRowCorrectionDensityConstant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalUniformRawRowCorrectionDensityConstant_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalUniformRawRowCorrectionDensityBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalAggregateRawRowCorrectionBound_strictScale
