import Erdos390.WholePaper.BankPaperAnchorChangeBudget
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.bankPaperAnchorMarkerBudget_isBigO_yNat_sq
#print axioms Erdos390.WholePaper.bankPaperAnchorMarkerBudget_isLittleO_secondOrderScale
#print axioms Erdos390.WholePaper.bankPaperAnchorChangeCost_normalized_tendsto_zero
#print axioms Erdos390.WholePaper.eventually_bankPaper_centralChangedMarkers_changeCost_le
#print axioms Erdos390.WholePaper.eventually_bankPaper_changeCost_le_sixth_reserve

assert_no_sorry Erdos390.WholePaper.bankPaperAnchorMarkerBudget_isBigO_yNat_sq
assert_no_sorry Erdos390.WholePaper.bankPaperAnchorMarkerBudget_isLittleO_secondOrderScale
assert_no_sorry Erdos390.WholePaper.bankPaperAnchorChangeCost_normalized_tendsto_zero
assert_no_sorry Erdos390.WholePaper.eventually_bankPaper_centralChangedMarkers_changeCost_le
assert_no_sorry Erdos390.WholePaper.eventually_bankPaper_changeCost_le_sixth_reserve
