import Erdos390.WholePaper.BankPaperCanonicalActualP87RatioCellTrafficConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the actual-P87 ratio-cell traffic connector

Every public theorem is printed and checked for `sorry`.
-/

#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87PointwiseUpper_eq_harmonicScale
#print axioms Erdos390.WholePaper.bankPaperCanonicalHarmonicPointwiseUpper_mono_scale
#print axioms Erdos390.WholePaper.bankPaperCanonical_actualP87Scale_le_paperScale_of_normalized
#print axioms Erdos390.WholePaper.bankPaperCanonical_actualP87RatioCellMomentTraffic
#print axioms Erdos390.WholePaper.bankPaperCanonical_actualP87RatioCellPaperTraffic_of_scale_le
#print axioms Erdos390.WholePaper.eventually_bankPaperCanonical_actualP87RatioCellMomentTraffic

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87PointwiseUpper_eq_harmonicScale
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalHarmonicPointwiseUpper_mono_scale
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_actualP87Scale_le_paperScale_of_normalized
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_actualP87RatioCellMomentTraffic
assert_no_sorry Erdos390.WholePaper.bankPaperCanonical_actualP87RatioCellPaperTraffic_of_scale_le
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperCanonical_actualP87RatioCellMomentTraffic
