import Erdos390.WholePaper.BankPaperFourFiveMovingSimplexCellTelescope

namespace Erdos390.WholePaper.BankPaperRealization

#check sum_abs_fourFiveLogLogLebesgueCellAtom_eq_logLogIncrement
#check sum_abs_fourFiveLogLogLebesgueCellAtom_le_compact
#check fourFiveLogLogCellTelescopeTwo
#check fourFiveLogLogCellTelescopeThree
#check fourFiveLogLogCellTelescopeThreeRightOrdered
#check abs_fourFiveLogLogCellTelescopeTwo_le
#check abs_fourFiveLogLogCellTelescopeThree_le
#check abs_fourFiveLogLogCellTelescopeThreeRightOrdered_le
#check fourFiveMovingFaceInteriorConditionalDefect
#check fourFiveMovingFaceStrictConditionalDefect
#check fourFiveMovingSimplexCellInteriorTelescopeTwo
#check fourFiveMovingSimplexCellStrictTelescopeTwo
#check fourFiveMovingSimplexCellTelescopeTwo
#check fourFiveMovingSimplexCellInteriorTelescopeThree
#check fourFiveMovingSimplexCellStrictTelescopeThree
#check fourFiveMovingSimplexCellTelescopeThree
#check abs_fourFiveMovingSimplexCellInteriorTelescopeTwo_le
#check abs_fourFiveMovingSimplexCellStrictTelescopeTwo_le
#check abs_fourFiveMovingSimplexCellTelescopeTwo_le
#check abs_fourFiveMovingSimplexCellInteriorTelescopeThree_le
#check abs_fourFiveMovingSimplexCellStrictTelescopeThree_le
#check abs_fourFiveMovingSimplexCellTelescopeThree_le
#check abs_fourFiveMovingSimplexCellTelescopeTwo_le_compact
#check abs_fourFiveMovingSimplexCellTelescopeThree_le_compact

end Erdos390.WholePaper.BankPaperRealization
