import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightPhysicalMarginAlgebra
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the explicit post-height physical margin
-/

namespace Erdos390.WholePaper

#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalMu
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalIntervals
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_lower_minus
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_upper_minus
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_lower_plus
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_upper_plus
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_lower_one
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_upper_two
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalMu_pos
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalGap
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalGap_pos
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalEta
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalEta_pos
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalEta_le_minus_gap
#print axioms bankPaperCanonicalSectionNinePostHeightPhysicalEta_le_plus_gap
#print axioms bankPaperCanonicalSectionNinePostHeightFixedPhysicalTarget
#print axioms bankPaperCanonicalSectionNinePostHeightFixedPhysicalTarget_mu
#print axioms bankPaperCanonicalSectionNinePostHeightFixedPhysicalTarget_eta
#print axioms bankPaperCanonical_L_div_secondOrderScale_tendsto_zero
#print axioms eventually_bankPaperCanonicalSectionNinePostHeight_physicalMean_has_margin_of_error_isBigO
#print axioms eventually_bankPaperCanonicalSectionNinePostHeight_fixedPhysicalMean_has_margin
#print axioms eventually_bankPaperCanonicalSectionNinePostHeight_smoothPhysicalMean_has_fixed_margin
#print axioms eventually_bankPaperCanonicalSectionNinePostHeight_smoothPhysicalMean_has_fixed_margin_of_analyticLedger

assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalMu
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalIntervals
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_lower_minus
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_upper_minus
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_lower_plus
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_upper_plus
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_lower_one
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalIntervals_upper_two
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalMu_pos
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalGap
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalGap_pos
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalEta
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalEta_pos
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalEta_le_minus_gap
assert_no_sorry bankPaperCanonicalSectionNinePostHeightPhysicalEta_le_plus_gap
assert_no_sorry bankPaperCanonicalSectionNinePostHeightFixedPhysicalTarget
assert_no_sorry bankPaperCanonicalSectionNinePostHeightFixedPhysicalTarget_mu
assert_no_sorry bankPaperCanonicalSectionNinePostHeightFixedPhysicalTarget_eta
assert_no_sorry bankPaperCanonical_L_div_secondOrderScale_tendsto_zero
assert_no_sorry eventually_bankPaperCanonicalSectionNinePostHeight_physicalMean_has_margin_of_error_isBigO
assert_no_sorry eventually_bankPaperCanonicalSectionNinePostHeight_fixedPhysicalMean_has_margin
assert_no_sorry eventually_bankPaperCanonicalSectionNinePostHeight_smoothPhysicalMean_has_fixed_margin
assert_no_sorry eventually_bankPaperCanonicalSectionNinePostHeight_smoothPhysicalMean_has_fixed_margin_of_analyticLedger

end Erdos390.WholePaper
