import Erdos390.WholePaper.BankPaperCanonicalTopFrozenOrdinaryLogHeightReductionConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the frozen-top ordinary-log height reduction
-/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_weightedResidual_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_ordinaryLogCompatibleUpTo_of_target_sub_primeLogMoment
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_weightedResidual_eq_normalizedHeightRoundingDefect
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_ordinaryLogCompatibleUpTo_of_heightLedger

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_weightedResidual_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_ordinaryLogCompatibleUpTo_of_target_sub_primeLogMoment
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_weightedResidual_eq_normalizedHeightRoundingDefect
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitInitialSelector_ordinaryLogCompatibleUpTo_of_heightLedger
