import Erdos390.WholePaper.BankPaperFourFiveLebesgueCellAggregationBound

/-! Statement audit for the explicit Lebesgue-cell aggregation residual. -/

namespace Erdos390.WholePaper.BankPaperRealization

#check fourFiveActivePhysicalProxyOne
#check fourFiveActivePhysicalProxyTwo
#check fourFiveActivePhysicalProxyThree
#check measurable_fourFiveActivePhysicalProxyOne
#check measurable_fourFiveActivePhysicalProxyTwo
#check measurable_fourFiveActivePhysicalProxyThree
#check fourFiveLebesgueCellEndpointOne
#check fourFiveLebesgueCellEndpointTwo
#check fourFiveLebesgueCellEndpointThree
#check measurable_fourFiveLebesgueCellEndpointOne
#check measurable_fourFiveLebesgueCellEndpointTwo
#check measurable_fourFiveLebesgueCellEndpointThree
#check abs_fourFiveLebesgueCellEndpointOne_le_mass
#check abs_fourFiveLebesgueCellEndpointTwo_le_mass_sq
#check abs_fourFiveLebesgueCellEndpointThree_le_mass_cu
#check fourFiveActivePhysicalProxyOne_eq_realCellIntegralSum
#check fourFiveActivePhysicalProxyTwo_eq_iteratedRealCellProduct
#check fourFiveActivePhysicalProxyThree_eq_iteratedRealCellProduct
#check fourFiveActivePhysicalProxyOne_eq_logarithmicKernel
#check fourFiveActivePhysicalProxyTwo_eq_logarithmicKernel
#check fourFiveActivePhysicalProxyThree_eq_logarithmicKernel
#check abs_fourFiveLebesgueCellEndpointOne_sub_proxy_le
#check abs_fourFiveLebesgueCellEndpointTwo_sub_proxy_le
#check abs_fourFiveLebesgueCellEndpointThree_sub_proxy_le
#check intervalIntegrable_fourFiveLebesgueCellEndpointOne
#check intervalIntegrable_fourFiveLebesgueCellEndpointTwo
#check intervalIntegrable_fourFiveLebesgueCellEndpointThree
#check intervalIntegrable_fourFiveActivePhysicalProxyOne
#check intervalIntegrable_fourFiveActivePhysicalProxyTwo
#check intervalIntegrable_fourFiveActivePhysicalProxyThree
#check intervalIntegrable_fourFiveLogarithmicMovingSimplexKernel_one_outer
#check intervalIntegrable_fourFiveLogarithmicMovingSimplexKernel_two_outer
#check intervalIntegrable_fourFiveLogarithmicMovingSimplexKernel_three_outer
#check fourFiveLebesgueCellAggregationBudget
#check fourFiveLebesgueCellAggregationError_one_le
#check fourFiveLebesgueCellAggregationError_two_le
#check fourFiveLebesgueCellAggregationError_three_le
#check fourFiveLebesgueCellAggregationError_le_budget
#check fourFiveContinuumBridgeCellBudgetAfterAggregation
#check fourFiveExactContinuumBridgeCellError_zero_le_afterAggregation
#check fourFiveExactContinuumBridgeCellError_one_le_afterAggregation
#check fourFiveExactContinuumBridgeCellError_two_le_afterAggregation
#check fourFiveExactContinuumBridgeCellError_three_le_afterAggregation
#check fourFiveLastPrimeToContinuumBridge_afterAggregation
#check fourFiveOrderedPrimeMixtureEstimate_afterAggregation

end Erdos390.WholePaper.BankPaperRealization
