import Erdos390.WholePaper.BankPaperCanonicalP87OrdinaryLogCompatibilityConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for exact P87 ordinary-log propagation
-/

/-! ## Transitive axiom dependencies -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalPaperMoment_primeLogScore_eq_sum_markedValuation
#print axioms Erdos390.WholePaper.bankPaperCanonicalWeightedActiveResidual_eq_target_sub_primeLogMoment
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_weightedResidual_eq
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualInitialSelector_weightedResidual_eq
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_weightedResidual_eq_initial
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_ordinaryLogCompatible
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_ordinaryLogCompatible_of_path

/-! ## Sorry-freedom -/

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalPaperMoment_primeLogScore_eq_sum_markedValuation
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalWeightedActiveResidual_eq_target_sub_primeLogMoment
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_weightedResidual_eq
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualInitialSelector_weightedResidual_eq
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_weightedResidual_eq_initial
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_ordinaryLogCompatible
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_ordinaryLogCompatible_of_path
