import Erdos390.WholePaper.BankPaperFixedExceptionalChargeAsymptotic
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the fixed exceptional charge asymptotics -/

#print axioms Erdos390.WholePaper.paperExceptionalTheta_pos
#print axioms Erdos390.WholePaper.paperExceptionalSelbergMainConstant_pos
#print axioms Erdos390.WholePaper.paperExceptionalSelbergRemainderConstant_pos
#print axioms Erdos390.WholePaper.paperExceptionalChargeConstant_pos
#print axioms Erdos390.WholePaper.paperExceptionalChargeEpsilon_nonneg
#print axioms Erdos390.WholePaper.paperExceptionalQuotientLength_cast_le
#print axioms Erdos390.WholePaper.paperExceptionalFiniteRemainder_eq_epsilon_mul_scale
#print axioms Erdos390.WholePaper.eventually_paperExceptionalChargeEpsilon_le_power
#print axioms Erdos390.WholePaper.paperExceptionalChargeEpsilon_tendsto_zero
#print axioms Erdos390.WholePaper.eventually_upperTailLength_cast_le_two_mul_secondOrderScale
#print axioms Erdos390.WholePaper.eventually_one_add_log_two_mul_exceptionalCutoff_le
#print axioms Erdos390.WholePaper.paperExceptionalFiniteChargeMain_le_paperReserve
#print axioms Erdos390.WholePaper.eventually_paperExceptionalFiniteChargeMajorant_le
#print axioms Erdos390.WholePaper.completeSmoothPart_cast_lt_two_mul_realExceptionalCutoff
#print axioms Erdos390.WholePaper.completeSmoothPart_lt_two_mul_exceptionalCutoff
#print axioms Erdos390.WholePaper.paperExceptionalSmoothParts_subset_Icc_two_mul_cutoff
#print axioms Erdos390.WholePaper.eventually_paperFixedExceptionalFactors_charge_le_finiteMajorant
#print axioms Erdos390.WholePaper.paperFixedExceptionalCharge_asymptoticPackage
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_factorization_eq_zero_of_realCutoff
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_factorization_eq_zero
#print axioms Erdos390.WholePaper.eventually_paperFixedExceptionalFactors_prod_factorization_eq_zero_of_realCutoff
#print axioms Erdos390.WholePaper.eventually_paperFixedExceptionalFactors_prod_factorization_eq_zero

assert_no_sorry Erdos390.WholePaper.paperExceptionalTheta_pos
assert_no_sorry Erdos390.WholePaper.paperExceptionalSelbergMainConstant_pos
assert_no_sorry Erdos390.WholePaper.paperExceptionalSelbergRemainderConstant_pos
assert_no_sorry Erdos390.WholePaper.paperExceptionalChargeConstant_pos
assert_no_sorry Erdos390.WholePaper.paperExceptionalChargeEpsilon_nonneg
assert_no_sorry Erdos390.WholePaper.paperExceptionalQuotientLength_cast_le
assert_no_sorry Erdos390.WholePaper.paperExceptionalFiniteRemainder_eq_epsilon_mul_scale
assert_no_sorry Erdos390.WholePaper.eventually_paperExceptionalChargeEpsilon_le_power
assert_no_sorry Erdos390.WholePaper.paperExceptionalChargeEpsilon_tendsto_zero
assert_no_sorry Erdos390.WholePaper.eventually_upperTailLength_cast_le_two_mul_secondOrderScale
assert_no_sorry Erdos390.WholePaper.eventually_one_add_log_two_mul_exceptionalCutoff_le
assert_no_sorry Erdos390.WholePaper.paperExceptionalFiniteChargeMain_le_paperReserve
assert_no_sorry Erdos390.WholePaper.eventually_paperExceptionalFiniteChargeMajorant_le
assert_no_sorry Erdos390.WholePaper.completeSmoothPart_cast_lt_two_mul_realExceptionalCutoff
assert_no_sorry Erdos390.WholePaper.completeSmoothPart_lt_two_mul_exceptionalCutoff
assert_no_sorry Erdos390.WholePaper.paperExceptionalSmoothParts_subset_Icc_two_mul_cutoff
assert_no_sorry Erdos390.WholePaper.eventually_paperFixedExceptionalFactors_charge_le_finiteMajorant
assert_no_sorry Erdos390.WholePaper.paperFixedExceptionalCharge_asymptoticPackage
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_factorization_eq_zero_of_realCutoff
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_prod_factorization_eq_zero
assert_no_sorry Erdos390.WholePaper.eventually_paperFixedExceptionalFactors_prod_factorization_eq_zero_of_realCutoff
assert_no_sorry Erdos390.WholePaper.eventually_paperFixedExceptionalFactors_prod_factorization_eq_zero
