import Erdos390.WholePaper.BankPaperPrechargedTailTarget
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.prechargedTailTarget_pos
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.prechargedTailTarget_mul_centralAnchorDivisor
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.prechargeBaseStateProduct_dvd_prechargedTailTarget
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.baseExactificationBank_prod_dvd_prechargedTailTarget

assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.prechargedTailTarget_pos
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.prechargedTailTarget_mul_centralAnchorDivisor
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.prechargeBaseStateProduct_dvd_prechargedTailTarget
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.baseExactificationBank_prod_dvd_prechargedTailTarget
