import Erdos390.WholePaper.BankPaperProposition87EndpointSelector
import Mathlib.Util.AssertNoSorry

/-! Axiom and proof-term audit for the Proposition 8.7 endpoint selector. -/

#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveMassBridgeData
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveMassBridgeData_sampleData
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveMassBridgeData_baseline
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveMassBridgeData_q
#print axioms Erdos390.WholePaper.bankPaperProposition87SelectorSupport
#print axioms Erdos390.WholePaper.bankPaperProposition87SelectorAt
#print axioms Erdos390.WholePaper.bankPaperProposition87EndpointSelector
#print axioms Erdos390.WholePaper.fixedValue_mem_bankPaperProposition87SelectorSupport
#print axioms Erdos390.WholePaper.sampleValue_mem_bankPaperProposition87SelectorSupport
#print axioms Erdos390.WholePaper.bankPaperProposition87SelectorAt_eq_zero_of_not_mem_support
#print axioms Erdos390.WholePaper.sum_bankPaperProposition87SelectorAt_mul
#print axioms Erdos390.WholePaper.sum_bankPaperProposition87SelectorAt
#print axioms Erdos390.WholePaper.bankPaperProposition87FullMarkedTarget
#print axioms Erdos390.WholePaper.bankPaperProposition87FullMarkedResidual
#print axioms Erdos390.WholePaper.bankPaperProposition87FullMarkedResidual_eq_activeResidual
#print axioms Erdos390.WholePaper.bankPaperProposition87FullMarkedResidual_band_sum_eq_zero
#print axioms Erdos390.WholePaper.abs_bankPaperProposition87FullMarkedResidual_le
#print axioms Erdos390.WholePaper.bankPaperProposition87EndpointSelector_mem_Icc_of_path
#print axioms Erdos390.WholePaper.sum_bankPaperProposition87EndpointSelector_eq_quota_of_path
#print axioms Erdos390.WholePaper.bankPaperProposition87Selector_lowPrimeMoment_preserved_of_path
#print axioms Erdos390.WholePaper.exists_bankPaperProposition87EndpointSelector

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveMassBridgeData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveMassBridgeData_sampleData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveMassBridgeData_baseline
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveMassBridgeData_q
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87SelectorSupport
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87SelectorAt
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87EndpointSelector
assert_no_sorry Erdos390.WholePaper.fixedValue_mem_bankPaperProposition87SelectorSupport
assert_no_sorry Erdos390.WholePaper.sampleValue_mem_bankPaperProposition87SelectorSupport
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87SelectorAt_eq_zero_of_not_mem_support
assert_no_sorry Erdos390.WholePaper.sum_bankPaperProposition87SelectorAt_mul
assert_no_sorry Erdos390.WholePaper.sum_bankPaperProposition87SelectorAt
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87FullMarkedTarget
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87FullMarkedResidual
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87FullMarkedResidual_eq_activeResidual
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87FullMarkedResidual_band_sum_eq_zero
assert_no_sorry Erdos390.WholePaper.abs_bankPaperProposition87FullMarkedResidual_le
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87EndpointSelector_mem_Icc_of_path
assert_no_sorry Erdos390.WholePaper.sum_bankPaperProposition87EndpointSelector_eq_quota_of_path
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87Selector_lowPrimeMoment_preserved_of_path
assert_no_sorry Erdos390.WholePaper.exists_bankPaperProposition87EndpointSelector
