import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalFourFiveChamberConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the signed exceptional four/five chamber connector
-/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms roughCanonicalExceptionalPhysicalRateScale
#print axioms roughCanonicalFourFiveIntervalPaperRateConstant
#print axioms roughCanonicalFourFiveIntervalPaperRateConstant_nonneg
#print axioms eventually_log_yNat_cube_le_yNat
#print axioms abs_roughCanonicalExceptionalPhysicalInterval_card_sub_mixtureIntegral_le_paperRate
#print axioms exists_eventually_roughCanonicalExceptionalPhysicalInterval_paperRate
#print axioms abs_roughCanonicalExceptionalPhysicalInterval_card_sub_idealFrozen_le
#print axioms abs_roughCanonicalExceptionalPhysicalEndpoint_length_sub_ideal_le_one
#print axioms roughCanonicalExceptional_threePhysicalInterval_quotient_lengths
#print axioms RoughCanonicalSignedExceptionalDeepIntervalEstimate
#print axioms RoughCanonicalSignedExceptionalCutoffIntervalEstimate
#print axioms roughCanonicalExceptionalPhysicalRateScale_div_L_cube_add_one_le
#print axioms roughCanonicalExceptionalPhysicalRateScale_div_L_sq_add_one_le
#print axioms roughCanonicalFourFiveSignedExceptionalCoreError
#print axioms roughCanonicalFourFiveDeepCoreConstant
#print axioms roughCanonicalFourFiveCutoffCoreConstant
#print axioms roughCanonicalFourFiveDeepCoreConstant_nonneg
#print axioms roughCanonicalFourFiveCutoffCoreConstant_nonneg
#print axioms abs_roughCanonicalFourFiveSignedExceptionalCoreError_le_paperRate
#print axioms abs_roughCanonicalSignedExceptionalCoreMass_le_cutoffPaperRate
#print axioms RoughCanonicalSignedExceptionalFourFiveChamberInputAt
#print axioms RoughCanonicalSignedExceptionalFourFiveRemainingInputs
#print axioms roughCanonicalSignedExceptionalCoreChamberEstimate_of_fourFiveInput
#print axioms exists_roughCanonicalSignedExceptionalCoreChamberEventually_of_fourFiveInputs
#print axioms exists_eventually_roughCanonicalSignedExceptionalResidualBound_of_fourFiveInputs

assert_no_sorry roughCanonicalExceptionalPhysicalRateScale
assert_no_sorry roughCanonicalFourFiveIntervalPaperRateConstant
assert_no_sorry roughCanonicalFourFiveIntervalPaperRateConstant_nonneg
assert_no_sorry eventually_log_yNat_cube_le_yNat
assert_no_sorry abs_roughCanonicalExceptionalPhysicalInterval_card_sub_mixtureIntegral_le_paperRate
assert_no_sorry exists_eventually_roughCanonicalExceptionalPhysicalInterval_paperRate
assert_no_sorry abs_roughCanonicalExceptionalPhysicalInterval_card_sub_idealFrozen_le
assert_no_sorry abs_roughCanonicalExceptionalPhysicalEndpoint_length_sub_ideal_le_one
assert_no_sorry roughCanonicalExceptional_threePhysicalInterval_quotient_lengths
assert_no_sorry RoughCanonicalSignedExceptionalDeepIntervalEstimate
assert_no_sorry RoughCanonicalSignedExceptionalCutoffIntervalEstimate
assert_no_sorry roughCanonicalExceptionalPhysicalRateScale_div_L_cube_add_one_le
assert_no_sorry roughCanonicalExceptionalPhysicalRateScale_div_L_sq_add_one_le
assert_no_sorry roughCanonicalFourFiveSignedExceptionalCoreError
assert_no_sorry roughCanonicalFourFiveDeepCoreConstant
assert_no_sorry roughCanonicalFourFiveCutoffCoreConstant
assert_no_sorry roughCanonicalFourFiveDeepCoreConstant_nonneg
assert_no_sorry roughCanonicalFourFiveCutoffCoreConstant_nonneg
assert_no_sorry abs_roughCanonicalFourFiveSignedExceptionalCoreError_le_paperRate
assert_no_sorry abs_roughCanonicalSignedExceptionalCoreMass_le_cutoffPaperRate
assert_no_sorry RoughCanonicalSignedExceptionalFourFiveChamberInputAt
assert_no_sorry RoughCanonicalSignedExceptionalFourFiveRemainingInputs
assert_no_sorry roughCanonicalSignedExceptionalCoreChamberEstimate_of_fourFiveInput
assert_no_sorry exists_roughCanonicalSignedExceptionalCoreChamberEventually_of_fourFiveInputs
assert_no_sorry exists_eventually_roughCanonicalSignedExceptionalResidualBound_of_fourFiveInputs

end Erdos390.WholePaper.BankPaperRealization
