import Erdos390.WholePaper.BankOrdinaryPaperComponents
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for realized ordinary components -/

#print Erdos390.WholePaper.BankOrdinaryPaperRealization
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.mk
#print axioms Erdos390.WholePaper.bankOrdinaryPrimeCoreSources_card_le
#print axioms Erdos390.WholePaper.bankOrdinarySignedSlots_card_eq_two_mul_demand
#print axioms Erdos390.WholePaper.bankOrdinaryPaperRequests_card_le_two_mul_yNat_mul_demand
#print axioms Erdos390.WholePaper.bankOrdinaryPaperRequests_card_isBigO_yNat_sq
#print axioms Erdos390.WholePaper.yNat_sq_div_secondOrderScale_tendsto_zero
#print axioms Erdos390.WholePaper.primeMarker_mul_smooth_pair_eq
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.marker_injective
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.markerDonorPair_injective
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.three_mul_marker_lt_n
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.markers_card_eq_paperRequests_card
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.marker_requestForMarker
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.requestForMarker_unique
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.markerSourceCore_of_request
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.sourceCore_eq_of_marker_eq
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.state_donor_completeRoughSignature_eq
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrences_card
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrence_mem_factorInterval
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrences_disjoint
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.occurrenceValue_ne_of_pool_ne
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.occurrenceValue_eq_marker_implies_request_eq
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.factorMoveChange_mul_left
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.realizedComponentChange_eq
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.realizedSlotChange_eq_signedFinitePathChange
#print axioms Erdos390.WholePaper.BankOrdinaryPaperRealization.realizedSlotChange_eq_signedPrimeToFiveChange
#print axioms Erdos390.WholePaper.eventually_exists_bankOrdinaryPaperRealization

assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.mk
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPrimeCoreSources_card_le
assert_no_sorry Erdos390.WholePaper.bankOrdinarySignedSlots_card_eq_two_mul_demand
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPaperRequests_card_le_two_mul_yNat_mul_demand
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPaperRequests_card_isBigO_yNat_sq
assert_no_sorry Erdos390.WholePaper.yNat_sq_div_secondOrderScale_tendsto_zero
assert_no_sorry Erdos390.WholePaper.primeMarker_mul_smooth_pair_eq
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.marker_injective
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.markerDonorPair_injective
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.three_mul_marker_lt_n
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.markers_card_eq_paperRequests_card
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.marker_requestForMarker
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.requestForMarker_unique
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.markerSourceCore_of_request
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.sourceCore_eq_of_marker_eq
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.state_donor_completeRoughSignature_eq
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrences_card
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrence_mem_factorInterval
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.componentOccurrences_disjoint
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.occurrenceValue_ne_of_pool_ne
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.occurrenceValue_eq_marker_implies_request_eq
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.factorMoveChange_mul_left
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.realizedComponentChange_eq
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.realizedSlotChange_eq_signedFinitePathChange
assert_no_sorry Erdos390.WholePaper.BankOrdinaryPaperRealization.realizedSlotChange_eq_signedPrimeToFiveChange
assert_no_sorry Erdos390.WholePaper.eventually_exists_bankOrdinaryPaperRealization
