import Erdos390.WholePaper.BankPaperFourFiveRealLastPrimeEndpoint
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveRealPrefixProduct_pos
#print axioms floor_fourFiveLastPrimeRealUpper
#print axioms floor_fourFiveLastPrimeRealLower
#print axioms fourFiveLastPrimeRealLower_ge_y
#print axioms fourFiveRealPrefixProduct_mul_realUpper
#print axioms fourFiveRealPrefixProduct_mul_realLower
#print axioms fourFiveLastPrimeRealIntegral_eq_physicalIntegral
#print axioms fourFiveLastPrimeRealPhysicalIntegral_eq_maxIntegral
#print axioms fourFiveOrderedLastPrimeRealIntegralLayer_eq_physicalLayer
#print axioms abs_fourFiveLastPrimeFiber_card_sub_realIntegral_le
#print axioms fourFiveOrderedPrimePrefixReciprocalMass_eq_pow
#print axioms fourFivePrimeCoordinateReciprocalMass_nonneg
#print axioms fourFiveLastPrimeRealEndpointError_le_reciprocalWeight
#print axioms fourFiveOrderedLastPrimeRealEndpointErrorLayer_le_prefixMass
#print axioms fourFiveOrderedLastPrimeRealEndpointErrorLayer_le_massPow
#print axioms abs_fourFiveOrderedPrimeLayerMass_sub_realLastPrimeIntegral_le
#print axioms exists_abs_fourFiveOrderedPrimeLayerMass_sub_realLastPrimeIntegral_le

assert_no_sorry fourFiveRealPrefixProduct_pos
assert_no_sorry floor_fourFiveLastPrimeRealUpper
assert_no_sorry floor_fourFiveLastPrimeRealLower
assert_no_sorry fourFiveLastPrimeRealLower_ge_y
assert_no_sorry fourFiveRealPrefixProduct_mul_realUpper
assert_no_sorry fourFiveRealPrefixProduct_mul_realLower
assert_no_sorry fourFiveLastPrimeRealIntegral_eq_physicalIntegral
assert_no_sorry fourFiveLastPrimeRealPhysicalIntegral_eq_maxIntegral
assert_no_sorry fourFiveOrderedLastPrimeRealIntegralLayer_eq_physicalLayer
assert_no_sorry abs_fourFiveLastPrimeFiber_card_sub_realIntegral_le
assert_no_sorry fourFiveOrderedPrimePrefixReciprocalMass_eq_pow
assert_no_sorry fourFivePrimeCoordinateReciprocalMass_nonneg
assert_no_sorry fourFiveLastPrimeRealEndpointError_le_reciprocalWeight
assert_no_sorry fourFiveOrderedLastPrimeRealEndpointErrorLayer_le_prefixMass
assert_no_sorry fourFiveOrderedLastPrimeRealEndpointErrorLayer_le_massPow
assert_no_sorry abs_fourFiveOrderedPrimeLayerMass_sub_realLastPrimeIntegral_le
assert_no_sorry exists_abs_fourFiveOrderedPrimeLayerMass_sub_realLastPrimeIntegral_le

end Erdos390.WholePaper.BankPaperRealization
