import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalOrderedMixtureConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the exceptional ordered-mixture connector -/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveReciprocalBVError_le_one_of_log_large
#print axioms fourFiveLogLogPrimitive_sub_le_log_twentyfour_fifths_of_paperRange
#print axioms fourFiveOrderedPrimeMixtureEstimate_realEndpoint_compact_of_paperRange
#print axioms roughCanonicalExceptional_yNat_tendsto_atTop
#print axioms roughCanonicalExceptional_log_yNat_tendsto_atTop
#print axioms exists_eventually_roughCanonicalExceptionalPhysicalInterval_orderedMixtureEstimate

assert_no_sorry fourFiveReciprocalBVError_le_one_of_log_large
assert_no_sorry fourFiveLogLogPrimitive_sub_le_log_twentyfour_fifths_of_paperRange
assert_no_sorry fourFiveOrderedPrimeMixtureEstimate_realEndpoint_compact_of_paperRange
assert_no_sorry roughCanonicalExceptional_yNat_tendsto_atTop
assert_no_sorry roughCanonicalExceptional_log_yNat_tendsto_atTop
assert_no_sorry exists_eventually_roughCanonicalExceptionalPhysicalInterval_orderedMixtureEstimate

end Erdos390.WholePaper.BankPaperRealization
