import Erdos390.WholePaper.BankPaperCanonicalActualActiveMeasureAdditiveRefinement
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the additive actual-active-measure connector -/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_coordinateFit
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_of_additiveRefinement
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredValue_bounds_of_physicalIntervals
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredActiveValues_subset_guardedSmoothRow_of_physicalIntervals
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredActiveValues_subset_guardedSmoothRow
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_apply_of_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_apply_of_not_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_eq_refinement_of_mem_pool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_eq_base_outside_smoothRow
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_scaled_apply_of_value
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_scaled_apply_of_value_of_not_mem_pool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_frozenAmbientWeight_eq_of_mem_pool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_frozenAmbientWeight_eq_zero_of_value_of_not_mem_pool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_frozenAmbientWeight_eq_of_value
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_coordinateFit
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalStructuredAdditivePlacementCapacity
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_mem_Icc
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredAdditivePlacementCapacity_of_div_log_bound
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredAdditivePlacementCapacity_of_cellDensity
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_of_structuredAdditivePlacement
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_and_feasible_of_structuredAdditivePlacement
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_and_feasible_of_structuredAdditivePlacement_physicalIntervals
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_and_feasible_of_structuredAdditivePlacement_cellDensity

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_coordinateFit
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothAdditiveRefinement_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_of_additiveRefinement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredValue_bounds_of_physicalIntervals
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredActiveValues_subset_guardedSmoothRow_of_physicalIntervals
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredActiveValues_subset_guardedSmoothRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_apply_of_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_apply_of_not_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_eq_refinement_of_mem_pool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_eq_base_outside_smoothRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedSmoothProtectedLayer_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_scaled_apply_of_value
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_scaled_apply_of_value_of_not_mem_pool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_frozenAmbientWeight_eq_of_mem_pool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_frozenAmbientWeight_eq_zero_of_value_of_not_mem_pool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_frozenAmbientWeight_eq_of_value
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_coordinateFit
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalStructuredAdditivePlacementCapacity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGuardedStructuredAdditivePlacementSelector_mem_Icc
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredAdditivePlacementCapacity_of_div_log_bound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalStructuredAdditivePlacementCapacity_of_cellDensity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_of_structuredAdditivePlacement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_and_feasible_of_structuredAdditivePlacement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_and_feasible_of_structuredAdditivePlacement_physicalIntervals
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalActualActiveMeasureConstructor_and_feasible_of_structuredAdditivePlacement_cellDensity
