import Erdos390.WholePaper.BankPaperCanonicalTangentResidualBridge
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the canonical tangent residual bridge -/

#print axioms Erdos390.WholePaper.BankPaperCanonicalTangentPrime
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentPrimeLabel
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorValuationDeficit
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentResidual
#print axioms Erdos390.WholePaper.BankPaperCanonicalPostRoundingPrimeBandBalance
#print axioms Erdos390.WholePaper.BankPaperCanonicalSelectorDeficitSupportedOnPrimeBand
#print axioms Erdos390.WholePaper.BankPaperCanonicalSelectorRowIntegral
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentPrimeLabel_injective
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentPrimeLabel_prime
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentPrimeLabel_le_yNat
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorValuationDeficit_eq_zero_of_not_prime
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalTangentResidual_eq_zero
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalTangentPrime_factorization
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalTangentResidual_mul_factorization_eq_deficit
#print axioms Erdos390.WholePaper.bankPaperCanonicalTangentStarSplitRequest_boundary_eq_selectorDeficit
#print axioms Erdos390.WholePaper.bankPaperCanonicalSelectorRowIntegral_and_tangentStarBoundary

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalTangentPrime
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentPrimeLabel
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorValuationDeficit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentResidual
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalPostRoundingPrimeBandBalance
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSelectorDeficitSupportedOnPrimeBand
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalSelectorRowIntegral
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentPrimeLabel_injective
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentPrimeLabel_prime
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentPrimeLabel_le_yNat
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorValuationDeficit_eq_zero_of_not_prime
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalTangentResidual_eq_zero
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalTangentPrime_factorization
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalTangentResidual_mul_factorization_eq_deficit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalTangentStarSplitRequest_boundary_eq_selectorDeficit
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalSelectorRowIntegral_and_tangentStarBoundary
