import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightSourceFirstFiniteExportedFields
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the source-first finite exported fields
-/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_roundedFrozenAmbientWeight_eq_protectedLayer
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_roundedFrozenLedger_of_sourceInputs
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_guardedBroadCorrectionPool_nonempty_of_sourceInputs
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_q0_eq_smoothQ0Family_of_primitiveGaps
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_d_eq_smoothDRealFamily_of_primitiveGaps

assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_roundedFrozenAmbientWeight_eq_protectedLayer
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_roundedFrozenLedger_of_sourceInputs
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_guardedBroadCorrectionPool_nonempty_of_sourceInputs
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_q0_eq_smoothQ0Family_of_primitiveGaps
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeight_d_eq_smoothDRealFamily_of_primitiveGaps

end Erdos390.WholePaper
