import Erdos390.WholePaper.BankPaperProposition87ActualDataConnector
import Mathlib.Util.AssertNoSorry

/-!
# Assumption audit for the actual Proposition 8.7 paper-data connector

Every public declaration in the connector is printed and checked for `sorry`.
The literal active-measure constructor remains a definition of the remaining
paper-faithful input predicate, not an axiom asserting its realization.
-/

#print axioms Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight
#print axioms Erdos390.WholePaper.BankPaperCanonicalActualActiveMeasureConstructor
#print axioms Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_one_le
#print axioms Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_pos
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeed_eq_mass_mul_baseline
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeed_value_mem_candidates
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeed_nonneg
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_le_preSelector
#print axioms Erdos390.WholePaper.bankPaperCanonicalLiteralQMass
#print axioms Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalLiteralQMass
#print axioms Erdos390.WholePaper.canonical_proposition87_actualPaperData
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualBridgeData
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualBridgeData_sampleData
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualBridgeData_q
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualBridgeData_baseWeight
#print axioms Erdos390.WholePaper.BankPaperCanonicalActualFrozenIndex
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenValue
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenWeight
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_nonneg
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_eq_zero_of_not_mem
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalActiveSeedAmbientWeight_eq_activeMass
#print axioms Erdos390.WholePaper.frozenAmbientWeight_eq_bankPaperCanonicalActualFrozenWeight
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFrozenWeight_mem_Icc
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalActualFrozenWeight
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalActualP87IntegerQuota
#print axioms Erdos390.WholePaper.BridgeData.activeCoordinateWeight_zero_eq_baseline
#print axioms Erdos390.WholePaper.BridgeData.ambientActiveWeight_zero_eq_activeSeedAmbient
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualSelectorAt_zero_eq_preSelector
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87SelectorSupport_eq_candidates
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActiveMarkedTarget
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualFullMarkedTarget_eq_selectorTailTarget
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualEndpoint_deficit_eq_activeResidual
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualInitial_deficit_eq_activeResidual
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_eq_zero_of_not_mem
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualActiveValues_subset_smoothRow
#print axioms Erdos390.WholePaper.StructuredSampleData.valuation_eq_zero_of_yNat_lt
#print axioms Erdos390.WholePaper.BridgeData.paperMoment_markedValuation_eq_zero_of_yNat_lt
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalActiveSeedAmbientWeight_eq_activeMass_of_subset
#print axioms Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_eq_zero_of_not_value
#print axioms Erdos390.WholePaper.BridgeData.sum_ambientActiveWeight_eq_q_of_values_mem
#print axioms Erdos390.WholePaper.BridgeData.q_eq_literalActiveMass_of_baseWeight_eq_seed
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_eq
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalActualP87EndpointSelector_row_eq_preSelector
#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothFlexibleQuota_actualP87Endpoint
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_rowIntegral
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87PointwiseUpper
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_deficitSupportedOnPrimeBand
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_bandBalance
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_primeBandBalance
#print axioms Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_pointwise
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalActualP87EndpointSelector
#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedContinuation_with_actualPrebridge

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActualActiveMeasureConstructor
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_one_le
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLiteralActiveMass_pos
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeed_eq_mass_mul_baseline
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeed_value_mem_candidates
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeed_nonneg
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_le_preSelector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalLiteralQMass
assert_no_sorry Erdos390.WholePaper.eventually_one_le_bankPaperCanonicalLiteralQMass
assert_no_sorry Erdos390.WholePaper.canonical_proposition87_actualPaperData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualBridgeData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualBridgeData_sampleData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualBridgeData_q
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualBridgeData_baseWeight
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalActualFrozenIndex
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenValue
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenWeight
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_nonneg
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_eq_zero_of_not_mem
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalActiveSeedAmbientWeight_eq_activeMass
assert_no_sorry Erdos390.WholePaper.frozenAmbientWeight_eq_bankPaperCanonicalActualFrozenWeight
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFrozenWeight_mem_Icc
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalActualFrozenWeight
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalActualP87IntegerQuota
assert_no_sorry Erdos390.WholePaper.BridgeData.activeCoordinateWeight_zero_eq_baseline
assert_no_sorry Erdos390.WholePaper.BridgeData.ambientActiveWeight_zero_eq_activeSeedAmbient
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualSelectorAt_zero_eq_preSelector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87SelectorSupport_eq_candidates
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActiveMarkedTarget
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualFullMarkedTarget_eq_selectorTailTarget
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualEndpoint_deficit_eq_activeResidual
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualInitial_deficit_eq_activeResidual
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_eq_zero_of_not_mem
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualActiveValues_subset_smoothRow
assert_no_sorry Erdos390.WholePaper.StructuredSampleData.valuation_eq_zero_of_yNat_lt
assert_no_sorry Erdos390.WholePaper.BridgeData.paperMoment_markedValuation_eq_zero_of_yNat_lt
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalActiveSeedAmbientWeight_eq_activeMass_of_subset
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActiveSeedAmbientWeight_eq_zero_of_not_value
assert_no_sorry Erdos390.WholePaper.BridgeData.sum_ambientActiveWeight_eq_q_of_values_mem
assert_no_sorry Erdos390.WholePaper.BridgeData.q_eq_literalActiveMass_of_baseWeight_eq_seed
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_eq
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalActualP87EndpointSelector_row_eq_preSelector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothFlexibleQuota_actualP87Endpoint
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_rowIntegral
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87PointwiseUpper
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_deficitSupportedOnPrimeBand
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_bandBalance
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_primeBandBalance
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalActualP87EndpointSelector_pointwise
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalActualP87EndpointSelector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedContinuation_with_actualPrebridge
