import Erdos390.WholePaper.BankPaperCanonicalGuardedBridgeConnector
import Mathlib.Util.AssertNoSorry

/-!
# Assumption audit for the guarded Section 8/9 bridge connector

Every public declaration is printed and checked for `sorry`.  The selector
constructor itself is a definition of an explicit existential proposition,
not an axiom or theorem asserting that the selector exists.
-/

#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeData
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeData_sampleData
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeData_baseline
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeData_partition
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeData_lowBand
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeData_w
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeData_q
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeActiveValues
#print axioms Erdos390.WholePaper.mem_bankPaperCanonicalBridgeActiveValues
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalSmoothQuota_of_rowIntegral
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalTotalQuota_of_rowIntegral
#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedBridgeSelectorConstructor
#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedBridgeSelectorConstructor_exists_fields
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeActiveValues_subset_guardedSmoothRow
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeActiveValues_subset_guardedCandidates
#print axioms Erdos390.WholePaper.paperFixedExceptionalFactors_disjoint_bridgeActiveValues
#print axioms Erdos390.WholePaper.paperFixedExceptionalFactors_disjoint_guardedCandidates
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenSupport
#print axioms Erdos390.WholePaper.BankPaperCanonicalBridgeFrozenIndex
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenValue
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenCoordinateWeight
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenWeight
#print axioms Erdos390.WholePaper.frozenAmbientWeight_eq_bankPaperCanonicalBridgeFrozenWeight
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenWeight_mem_Icc
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenWeight_eq_zero_on_sample
#print axioms Erdos390.WholePaper.sum_selector_bridgeActiveValues_eq_q
#print axioms Erdos390.WholePaper.sum_bankPaperCanonicalBridgeFrozenCoordinateWeight
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalBridgeIntegerQuota
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridge_combinedBaselineSlack
#print axioms Erdos390.WholePaper.exists_bankPaperCanonicalGuardedBridgeConnector
#print axioms Erdos390.WholePaper.bankPaperCanonicalBridge_ambientCombinedWeight_mem_Icc

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeData_sampleData
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeData_baseline
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeData_partition
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeData_lowBand
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeData_w
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeData_q
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeActiveValues
assert_no_sorry Erdos390.WholePaper.mem_bankPaperCanonicalBridgeActiveValues
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalSmoothQuota_of_rowIntegral
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalTotalQuota_of_rowIntegral
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedBridgeSelectorConstructor
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedBridgeSelectorConstructor_exists_fields
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeActiveValues_subset_guardedSmoothRow
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeActiveValues_subset_guardedCandidates
assert_no_sorry Erdos390.WholePaper.paperFixedExceptionalFactors_disjoint_bridgeActiveValues
assert_no_sorry Erdos390.WholePaper.paperFixedExceptionalFactors_disjoint_guardedCandidates
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenSupport
assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalBridgeFrozenIndex
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenValue
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenCoordinateWeight
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenWeight
assert_no_sorry Erdos390.WholePaper.frozenAmbientWeight_eq_bankPaperCanonicalBridgeFrozenWeight
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenWeight_mem_Icc
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridgeFrozenWeight_eq_zero_on_sample
assert_no_sorry Erdos390.WholePaper.sum_selector_bridgeActiveValues_eq_q
assert_no_sorry Erdos390.WholePaper.sum_bankPaperCanonicalBridgeFrozenCoordinateWeight
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalBridgeIntegerQuota
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridge_combinedBaselineSlack
assert_no_sorry Erdos390.WholePaper.exists_bankPaperCanonicalGuardedBridgeConnector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalBridge_ambientCombinedWeight_mem_Icc
