import Erdos390.WholePaper.BankPaperSharpCensus
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the sharp actual-bank census -/

#print axioms Erdos390.WholePaper.card_bankOrdinaryPaperRequests_eq_weightedPathDemand
#print axioms Erdos390.WholePaper.bankOrdinaryScaleIndex_mono_of_five_le
#print axioms Erdos390.WholePaper.one_le_bankOrdinaryComponentScaleIndex_of_mem
#print axioms Erdos390.WholePaper.bankOrdinaryComponentScaleIndex_le_yNatScaleIndex_of_six_le
#print axioms Erdos390.WholePaper.bankOrdinaryCoreSources_subset_smallLargePathFibers
#print axioms Erdos390.WholePaper.bankOrdinaryCoreSources_card_le_pathComponentBudget
#print axioms Erdos390.WholePaper.bankOrdinaryWeightedPathDemand_le
#print axioms Erdos390.WholePaper.card_bankOrdinaryPaperRequests_le_sharp
#print axioms Erdos390.WholePaper.card_bankPaperMarkerRequest_eq_weightedPathLedger
#print axioms Erdos390.WholePaper.card_bankPaperMarkerRequest_le_sharpMarkerBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeComponentCount_le_sharpMarkerBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperBankRows_card_le_sharpMarkerBudget
#print axioms Erdos390.WholePaper.bankOrdinaryScaleIndex_yNat_le_log
#print axioms Erdos390.WholePaper.bankOrdinaryPathComponentBudget_isBigO_L
#print axioms Erdos390.WholePaper.bankPaperSharpMarkerBudget_isBigO_yNat_mul_L_of_demand
#print axioms Erdos390.WholePaper.bankPaperSharpMarkerBudget_isBigO_yNat_mul_L
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperNumericalGuardSet_card_le_sharpMarkerBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperPairNumericalGuards_card_le_sharpMarkerBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.card_tangentEndpointGuardDeletedMultipliers_numericalGuardSet_le_sharp
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperCommonMultiplier_sharp_finite_deletion_ledger

assert_no_sorry Erdos390.WholePaper.card_bankOrdinaryPaperRequests_eq_weightedPathDemand
assert_no_sorry Erdos390.WholePaper.bankOrdinaryScaleIndex_mono_of_five_le
assert_no_sorry Erdos390.WholePaper.one_le_bankOrdinaryComponentScaleIndex_of_mem
assert_no_sorry Erdos390.WholePaper.bankOrdinaryComponentScaleIndex_le_yNatScaleIndex_of_six_le
assert_no_sorry Erdos390.WholePaper.bankOrdinaryCoreSources_subset_smallLargePathFibers
assert_no_sorry Erdos390.WholePaper.bankOrdinaryCoreSources_card_le_pathComponentBudget
assert_no_sorry Erdos390.WholePaper.bankOrdinaryWeightedPathDemand_le
assert_no_sorry Erdos390.WholePaper.card_bankOrdinaryPaperRequests_le_sharp
assert_no_sorry Erdos390.WholePaper.card_bankPaperMarkerRequest_eq_weightedPathLedger
assert_no_sorry Erdos390.WholePaper.card_bankPaperMarkerRequest_le_sharpMarkerBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeComponentCount_le_sharpMarkerBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperBankRows_card_le_sharpMarkerBudget
assert_no_sorry Erdos390.WholePaper.bankOrdinaryScaleIndex_yNat_le_log
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPathComponentBudget_isBigO_L
assert_no_sorry Erdos390.WholePaper.bankPaperSharpMarkerBudget_isBigO_yNat_mul_L_of_demand
assert_no_sorry Erdos390.WholePaper.bankPaperSharpMarkerBudget_isBigO_yNat_mul_L
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperNumericalGuardSet_card_le_sharpMarkerBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperPairNumericalGuards_card_le_sharpMarkerBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.card_tangentEndpointGuardDeletedMultipliers_numericalGuardSet_le_sharp
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperCommonMultiplier_sharp_finite_deletion_ledger
