import Erdos390.WholePaper.BankPaperFourFiveRoughChamberReduction
import Mathlib.Util.AssertNoSorry

/-! Axiom and `sorry` audit for the finite four-to-five rough-chamber reduction. -/

#print axioms Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRoughInterval
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRoughOmegaLayer
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRoughRepeatedInterval
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRoughRepeatedOmegaLayer
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRoughRepeatedOmegaLayer_eq_filter_not_squarefree
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRough_cardFactors_le_four
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRoughInterval_eq_biUnion_omegaLayers
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRoughInterval_card_eq_sum_omegaLayers
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRoughRepeatedInterval_card_eq_sum_omegaLayers
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeMultiplicity_le_factorial
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeMultiplicity_eq_factorial_of_squarefree
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_fourFiveOrderedPrimeFactorLists
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_fourFiveOrderedPrimeFactorLists_iff
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeFactorListFibers_pairwiseDisjoint
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeFactorLists_card
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeLayerMass_le_factorial_mul_card
#print axioms Erdos390.WholePaper.BankPaperRealization.factorial_mul_card_le_orderedPrimeLayerMass_add_repeated
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeLayerRatio_le_card
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughOmegaLayer_card_sub_orderedRatio_le_repeated
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughInterval_card_sub_orderedPrimeMixture_le_repeated
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRepeatedPrimeSquareSet
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_fourFiveSquareMultiples
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRoughRepeatedInterval_subset_repeatedPrimeSquareSet
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRepeatedPrimeSquareSet_subset_biUnion_squareMultiples
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveSquareMultiples_card
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRepeatedPrimeSquareSet_card_le_div
#print axioms Erdos390.WholePaper.BankPaperRealization.fourFiveRoughRepeatedInterval_card_le_div
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughInterval_card_sub_mainTerm_le_of_orderedEstimate
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughInterval_card_sub_mainTerm_le_div_add_error
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_sum_weighted_fourFiveRoughInterval_sub_mainTerm_le

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRoughInterval
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRoughOmegaLayer
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRoughRepeatedInterval
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRoughRepeatedOmegaLayer
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRoughRepeatedOmegaLayer_eq_filter_not_squarefree
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRough_cardFactors_le_four
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRoughInterval_eq_biUnion_omegaLayers
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRoughInterval_card_eq_sum_omegaLayers
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRoughRepeatedInterval_card_eq_sum_omegaLayers
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeMultiplicity_le_factorial
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeMultiplicity_eq_factorial_of_squarefree
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_fourFiveOrderedPrimeFactorLists
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_fourFiveOrderedPrimeFactorLists_iff
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeFactorListFibers_pairwiseDisjoint
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeFactorLists_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeLayerMass_le_factorial_mul_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.factorial_mul_card_le_orderedPrimeLayerMass_add_repeated
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveOrderedPrimeLayerRatio_le_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughOmegaLayer_card_sub_orderedRatio_le_repeated
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughInterval_card_sub_orderedPrimeMixture_le_repeated
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_fourFiveRepeatedPrimeSquareSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_fourFiveSquareMultiples
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRoughRepeatedInterval_subset_repeatedPrimeSquareSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRepeatedPrimeSquareSet_subset_biUnion_squareMultiples
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveSquareMultiples_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRepeatedPrimeSquareSet_card_le_div
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.fourFiveRoughRepeatedInterval_card_le_div
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughInterval_card_sub_mainTerm_le_of_orderedEstimate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_fourFiveRoughInterval_card_sub_mainTerm_le_div_add_error
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_sum_weighted_fourFiveRoughInterval_sub_mainTerm_le
