import Erdos390.WholePaper.BankPaperCanonicalGuardLocalRowLedger
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the guard-local rough-row ledger

All 39 public declarations are printed and checked for `sorry`.
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRow
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedRow
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorBaseRowEquiv
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalExceptionalLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalActiveNonexceptionalLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTargetInt
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawRowDiscrepancy
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowDiscrepancy
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardLocalCensusBound
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardedBroadPoolCapacity
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalPostchargeRowCapacity
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet_subset_rawCandidateSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet_disjoint_guardSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool_subset_broadPool
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool_subset_guardedRow
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRow_eq_rawRow_sdiff_guardSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRow_disjoint_guardDeletedRow
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRow_union_guardDeletedRow
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_roughCanonicalGuardedRow_add_sum_guardDeletedRow
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeDonorBaseEquiv_completeRoughLabel
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_completeLabelMultiplicity_eq_donorSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonical_activeNonexceptional_or_exceptional
#print axioms Erdos390.WholePaper.BankPaperRealization.completeLabelMultiplicity_mono
#print axioms Erdos390.WholePaper.BankPaperRealization.completeLabelMultiplicity_union_of_disjoint
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_union_prechargeDonor_multiplicity_eq_upperTarget_of_exceptional
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_add_prechargeBase_multiplicity_eq_upperTarget_of_exceptional
#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_add_prechargeBase_multiplicity_le_upperTarget
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget_eq_intCast
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTargetInt_eq_zero_of_exceptional
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget_eq_zero_of_exceptional
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalDiscrepancyLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.roughRawCandidateSet_disjoint_paperFixedExceptionalFactors
#print axioms Erdos390.WholePaper.BankPaperRealization.roughRawCandidateSet_disjoint_prechargeDonorSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedRow_subset_anchors_union_bankStates

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorBaseRowEquiv
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalExceptionalLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalActiveNonexceptionalLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTargetInt
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawRowDiscrepancy
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowDiscrepancy
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardLocalCensusBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalGuardedBroadPoolCapacity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalPostchargeRowCapacity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet_subset_rawCandidateSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedCandidateSet_disjoint_guardSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool_subset_broadPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool_subset_guardedRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRow_eq_rawRow_sdiff_guardSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRow_disjoint_guardDeletedRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedRow_union_guardDeletedRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_roughCanonicalGuardedRow_add_sum_guardDeletedRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeDonorBaseEquiv_completeRoughLabel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_completeLabelMultiplicity_eq_donorSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonical_activeNonexceptional_or_exceptional
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeLabelMultiplicity_mono
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeLabelMultiplicity_union_of_disjoint
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_union_prechargeDonor_multiplicity_eq_upperTarget_of_exceptional
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_add_prechargeBase_multiplicity_eq_upperTarget_of_exceptional
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptional_add_prechargeBase_multiplicity_le_upperTarget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget_eq_intCast
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTargetInt_eq_zero_of_exceptional
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget_eq_zero_of_exceptional
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalPostchargeRowTarget_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalDiscrepancyLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughRawCandidateSet_disjoint_paperFixedExceptionalFactors
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughRawCandidateSet_disjoint_prechargeDonorSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedRow_subset_anchors_union_bankStates
