import Erdos390.WholePaper.BankPaperCanonicalSectionNineTopFrozenSymmetricHeightEventualConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the frozen-top same-witness handoff
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineTopFrozenSymmetricHeightLocalSupplier
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenSynchronizedPostHfitInputAt_of_symmetricHeightInputs
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenSynchronizedPostHfitInput_of_combinedChargeTerminal_symmetricHeight
#print axioms Erdos390.WholePaper.bankPaperCanonicalDistributedSectionNineTerminalAtDepth_of_topFrozenSymmetricHeightLocalSupplier

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalSectionNineTopFrozenSymmetricHeightLocalSupplier
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenSynchronizedPostHfitInputAt_of_symmetricHeightInputs
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSectionNineTopFrozenSynchronizedPostHfitInput_of_combinedChargeTerminal_symmetricHeight
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalDistributedSectionNineTerminalAtDepth_of_topFrozenSymmetricHeightLocalSupplier
