import Erdos390.WholePaper.BankPaperFourFiveCellLebesgueIdentification
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms hasDerivAt_fourFiveLogLogPrimitiveReal
#print axioms continuousOn_fourFiveLogLogLebesgueDensity
#print axioms integral_fourFiveLogLogLebesgueDensity
#print axioms fourFiveLogLogCell_eq_lebesgueCell
#print axioms fourFiveAnchoredLogLogCellAtom_eq_lebesgueCell
#print axioms fourFiveWeightedLogLogCellSum_eq_lebesgueCells
#print axioms fourFiveContinuumLogLogProductOne_eq_lebesgueCells
#print axioms fourFiveContinuumLogLogProductTwo_eq_lebesgueCells
#print axioms fourFiveContinuumLogLogProductThree_eq_lebesgueCells

assert_no_sorry hasDerivAt_fourFiveLogLogPrimitiveReal
assert_no_sorry continuousOn_fourFiveLogLogLebesgueDensity
assert_no_sorry integral_fourFiveLogLogLebesgueDensity
assert_no_sorry fourFiveLogLogCell_eq_lebesgueCell
assert_no_sorry fourFiveAnchoredLogLogCellAtom_eq_lebesgueCell
assert_no_sorry fourFiveWeightedLogLogCellSum_eq_lebesgueCells
assert_no_sorry fourFiveContinuumLogLogProductOne_eq_lebesgueCells
assert_no_sorry fourFiveContinuumLogLogProductTwo_eq_lebesgueCells
assert_no_sorry fourFiveContinuumLogLogProductThree_eq_lebesgueCells

end Erdos390.WholePaper.BankPaperRealization
