import Erdos390.WholePaper.BankPaperCanonicalSectionEightPrechargedLogConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the Section 8 precharged-log connector -/

namespace Erdos390.WholePaper

#print axioms BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget
#print axioms BankPaperCanonicalGuardedTailFamily.extendedCentralAnchorDivisorLog
#print axioms BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget_eq
#print axioms BankPaperCanonicalGuardedTailFamily.extendedCentralAnchorDivisorLog_eq
#print axioms BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget_add_anchorLog_of_tail
#print axioms BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget_add_extendedCentralAnchorDivisorLog
#print axioms GuardedCentralAnchorCertificate.centralAnchorDivisor_factorization_le_upperTailValuation
#print axioms GuardedCentralAnchorCertificate.centralAnchorDivisorLog_eq_sum_primesUpTo
#print axioms eventually_upperTailValuation_le_add_one_mul_secondOrderScale_on_primesUpTo
#print axioms bankPaperCanonicalAnchorLogBigOConstant
#print axioms bankPaperCanonicalAnchorLogBigOConstant_nonneg
#print axioms BankPaperCanonicalGuardedTailFamily.extendedCentralAnchorDivisorLog_isBigO_secondOrderScale
#print axioms BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget_sub_height_mul_L_isBigO
#print axioms bankPaperCanonicalSectionEightAnalyticLedger_precharged_of_centralTail

assert_no_sorry BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget
assert_no_sorry BankPaperCanonicalGuardedTailFamily.extendedCentralAnchorDivisorLog
assert_no_sorry BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget_eq
assert_no_sorry BankPaperCanonicalGuardedTailFamily.extendedCentralAnchorDivisorLog_eq
assert_no_sorry BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget_add_anchorLog_of_tail
assert_no_sorry BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget_add_extendedCentralAnchorDivisorLog
assert_no_sorry GuardedCentralAnchorCertificate.centralAnchorDivisor_factorization_le_upperTailValuation
assert_no_sorry GuardedCentralAnchorCertificate.centralAnchorDivisorLog_eq_sum_primesUpTo
assert_no_sorry eventually_upperTailValuation_le_add_one_mul_secondOrderScale_on_primesUpTo
assert_no_sorry bankPaperCanonicalAnchorLogBigOConstant
assert_no_sorry bankPaperCanonicalAnchorLogBigOConstant_nonneg
assert_no_sorry BankPaperCanonicalGuardedTailFamily.extendedCentralAnchorDivisorLog_isBigO_secondOrderScale
assert_no_sorry BankPaperCanonicalGuardedTailFamily.extendedPrechargedTailLogTarget_sub_height_mul_L_isBigO
assert_no_sorry bankPaperCanonicalSectionEightAnalyticLedger_precharged_of_centralTail

end Erdos390.WholePaper
