import Erdos390.WholePaper.BankPaperMainAsymptoticReduction
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the final main-asymptotic reduction -/

#print axioms Erdos390.WholePaper.normalized_f_sub_two_mul_eq_div_secondOrderScale
#print axioms Erdos390.WholePaper.eventually_normalized_f_sub_two_mul_le_upperScaledEndpoint_excess
#print axioms Erdos390.WholePaper.mainNormalizedLimit_of_eventually_f_le_upperScaledEndpoint
#print axioms Erdos390.WholePaper.mainAsymptotic_of_eventually_f_le_upperScaledEndpoint
#print axioms Erdos390.WholePaper.mainNormalizedLimit_of_canonicalPostTangentContinuation
#print axioms Erdos390.WholePaper.mainAsymptotic_of_canonicalPostTangentContinuation
#print axioms Erdos390.WholePaper.mainNormalizedLimit_of_sharpSaiasDefect_and_selectorGeometryContinuation
#print axioms Erdos390.WholePaper.mainAsymptotic_of_sharpSaiasDefect_and_selectorGeometryContinuation

assert_no_sorry Erdos390.WholePaper.normalized_f_sub_two_mul_eq_div_secondOrderScale
assert_no_sorry Erdos390.WholePaper.eventually_normalized_f_sub_two_mul_le_upperScaledEndpoint_excess
assert_no_sorry Erdos390.WholePaper.mainNormalizedLimit_of_eventually_f_le_upperScaledEndpoint
assert_no_sorry Erdos390.WholePaper.mainAsymptotic_of_eventually_f_le_upperScaledEndpoint
assert_no_sorry Erdos390.WholePaper.mainNormalizedLimit_of_canonicalPostTangentContinuation
assert_no_sorry Erdos390.WholePaper.mainAsymptotic_of_canonicalPostTangentContinuation
assert_no_sorry Erdos390.WholePaper.mainNormalizedLimit_of_sharpSaiasDefect_and_selectorGeometryContinuation
assert_no_sorry Erdos390.WholePaper.mainAsymptotic_of_sharpSaiasDefect_and_selectorGeometryContinuation
