import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalFourFiveDeepDisplacementConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for deep frozen-coordinate displacement
-/

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms abs_normalizedLog_sub_le_of_div_le_and_abs_sub_le
#print axioms roughCanonicalFourFiveDeepUpperDisplacementConstant
#print axioms roughCanonicalFourFiveDeepHighDisplacementConstant
#print axioms roughCanonicalFourFiveDeepBroadDisplacementConstant
#print axioms roughCanonicalFourFiveDeepUpperDisplacementConstant_nonneg
#print axioms roughCanonicalFourFiveDeepHighDisplacementConstant_nonneg
#print axioms roughCanonicalFourFiveDeepBroadDisplacementConstant_pos
#print axioms roughCanonicalFourFiveDeepUpperFrozenDisplacement_le
#print axioms roughCanonicalFourFiveDeepHighFrozenDisplacement_le
#print axioms roughCanonicalFourFiveDeepBroadFrozenDisplacement_le
#print axioms RoughCanonicalFourFiveDeepFrozenDisplacementBoundsAt
#print axioms roughCanonicalFourFiveDeepFrozenDisplacementBoundsAt_of_scale
#print axioms RoughCanonicalFourFiveDeepFrozenDisplacementBoundsAt.upper_adapter_inputs
#print axioms RoughCanonicalFourFiveDeepFrozenDisplacementBoundsAt.high_adapter_inputs
#print axioms RoughCanonicalFourFiveDeepFrozenDisplacementBoundsAt.broad_adapter_inputs
#print axioms eventually_deepFrozenDisplacement_depth_le_half
#print axioms eventually_roughCanonicalFourFiveDeepFrozenDisplacementBoundsAt

assert_no_sorry abs_normalizedLog_sub_le_of_div_le_and_abs_sub_le
assert_no_sorry roughCanonicalFourFiveDeepUpperDisplacementConstant
assert_no_sorry roughCanonicalFourFiveDeepHighDisplacementConstant
assert_no_sorry roughCanonicalFourFiveDeepBroadDisplacementConstant
assert_no_sorry roughCanonicalFourFiveDeepUpperDisplacementConstant_nonneg
assert_no_sorry roughCanonicalFourFiveDeepHighDisplacementConstant_nonneg
assert_no_sorry roughCanonicalFourFiveDeepBroadDisplacementConstant_pos
assert_no_sorry roughCanonicalFourFiveDeepUpperFrozenDisplacement_le
assert_no_sorry roughCanonicalFourFiveDeepHighFrozenDisplacement_le
assert_no_sorry roughCanonicalFourFiveDeepBroadFrozenDisplacement_le
assert_no_sorry RoughCanonicalFourFiveDeepFrozenDisplacementBoundsAt
assert_no_sorry roughCanonicalFourFiveDeepFrozenDisplacementBoundsAt_of_scale
assert_no_sorry RoughCanonicalFourFiveDeepFrozenDisplacementBoundsAt.upper_adapter_inputs
assert_no_sorry RoughCanonicalFourFiveDeepFrozenDisplacementBoundsAt.high_adapter_inputs
assert_no_sorry RoughCanonicalFourFiveDeepFrozenDisplacementBoundsAt.broad_adapter_inputs
assert_no_sorry eventually_deepFrozenDisplacement_depth_le_half
assert_no_sorry eventually_roughCanonicalFourFiveDeepFrozenDisplacementBoundsAt

end Erdos390.WholePaper.BankPaperRealization
