import Erdos390.WholePaper.BankPaperCanonicalProposition87EndpointSlack
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for guarded P87 endpoint slack -/

#print axioms Erdos390.WholePaper.BankPaperCanonicalGuardedSmoothProtectedWindow
#print axioms Erdos390.WholePaper.frozenAmbientWeight_subtype_apply
#print axioms Erdos390.WholePaper.frozenAmbientWeight_subtypeRemainder_eq_preSelector
#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothProtectedWindow_of_subtypeBounds
#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothProtectedWindow_of_subtypeRemainder
#print axioms Erdos390.WholePaper.bankPaperProposition87AmbientActiveWeight_le_of_effectiveScoreBound
#print axioms Erdos390.WholePaper.bankPaperProposition87AmbientActiveWeight_endpoint_le_of_path
#print axioms Erdos390.WholePaper.eventually_bankPaperProposition87EndpointSlack_logReserve
#print axioms Erdos390.WholePaper.bankPaperProposition87AmbientActiveWeight_eq_zero_on_nonsmoothPool
#print axioms Erdos390.WholePaper.exists_bankPaperProposition87EndpointSelector_smoothSlackLayers
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedEndpointSlackConstruction_of_proposition87EndpointSelector
#print axioms Erdos390.WholePaper.BankPaperRealization.proposition87EndpointSelector_candidateSetEndpointInputs

assert_no_sorry Erdos390.WholePaper.BankPaperCanonicalGuardedSmoothProtectedWindow
assert_no_sorry Erdos390.WholePaper.frozenAmbientWeight_subtype_apply
assert_no_sorry Erdos390.WholePaper.frozenAmbientWeight_subtypeRemainder_eq_preSelector
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothProtectedWindow_of_subtypeBounds
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedSmoothProtectedWindow_of_subtypeRemainder
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87AmbientActiveWeight_le_of_effectiveScoreBound
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87AmbientActiveWeight_endpoint_le_of_path
assert_no_sorry Erdos390.WholePaper.eventually_bankPaperProposition87EndpointSlack_logReserve
assert_no_sorry Erdos390.WholePaper.bankPaperProposition87AmbientActiveWeight_eq_zero_on_nonsmoothPool
assert_no_sorry Erdos390.WholePaper.exists_bankPaperProposition87EndpointSelector_smoothSlackLayers
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedEndpointSlackConstruction_of_proposition87EndpointSelector
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.proposition87EndpointSelector_candidateSetEndpointInputs
