import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalCoreFirst
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for signed exceptional core-first cancellation -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSmoothParts
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSmoothFiber
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalExceptionalRawLowerSmoothParts
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalExceptionalRawLowerSmoothFiber
#print axioms Erdos390.WholePaper.BankPaperRealization.roughRawCandidateSet_pos_le_two_mul
#print axioms Erdos390.WholePaper.BankPaperRealization.completeSmoothPart_cast_lt_realExceptionalCutoff_of_rawLower
#print axioms Erdos390.WholePaper.BankPaperRealization.completeSmoothPart_lt_exceptionalCutoff_of_rawLower
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSmoothParts_subset_Icc_two_mul_cutoff
#print axioms Erdos390.WholePaper.BankPaperRealization.factorization_eq_completeSmoothPart_factorization_of_le
#print axioms Erdos390.WholePaper.BankPaperRealization.paperExceptionalSmoothFiber_eq_empty_of_not_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSmoothFiber_eq_empty_of_not_mem
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalCoreMass
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_paperExceptionalUpperFactors_factorization_eq_corePrefix
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_roughCanonicalExceptionalRawLower_factorization_eq_corePrefix
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalResidual_eq_coreFirst
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCoreCoefficient
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCoreCoefficient_mul_left
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCorePrefix
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCorePrefix_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughHeadPeriodicCorePrefix_le
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCoreMulPrefix
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCoreMulPrefix_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughHeadPeriodicCoreMulPrefix_le
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCoreDiscreteVariation
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicWeightedCoreSum
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_range_succ_zeroExtendedPeriodicCore_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicWeightedCoreSum_eq_abel
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughHeadPeriodicWeightedCoreSum_le_variation
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_Icc_mul_divInd_eq_quotientSum
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicValuationCoreSum
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicValuationCoreSum_eq_primePowerBlocks
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughHeadPeriodicValuationCoreSum_le
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_sum_factorization_mul_error_le
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_factorization_cutoffBand_le_four_mul_div_prime
#print axioms Erdos390.WholePaper.BankPaperRealization.weightedFactorizationSum_cutoffBand_le_eight_div_prime
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_sum_factorization_mul_cutoffBand_error_le
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDeepCoreSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalCutoffCoreSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDeepCoreSet_disjoint_cutoffCoreSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDeepCoreSet_union_cutoffCoreSet
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_exceptionalCorePrefix_eq_deep_add_cutoff
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalSignedExceptionalCoreChamberEstimate
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalSignedExceptionalResidual_le_coreFirstFinite
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalEndpointRatio
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperExceptionalCutoff_tendsto_atTop
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalEndpointRatio_tendsto_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_tangentPaperExceptionalCutoff_le_self_div_L_sq
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalSignedExceptionalCoreChamberEventually
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalCoreBoundConstant
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalCoreBoundConstant_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalSignedExceptionalResidualBound_of_coreChamber

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSmoothParts
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSmoothFiber
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalExceptionalRawLowerSmoothParts
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalExceptionalRawLowerSmoothFiber
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughRawCandidateSet_pos_le_two_mul
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeSmoothPart_cast_lt_realExceptionalCutoff_of_rawLower
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.completeSmoothPart_lt_exceptionalCutoff_of_rawLower
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSmoothParts_subset_Icc_two_mul_cutoff
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.factorization_eq_completeSmoothPart_factorization_of_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperExceptionalSmoothFiber_eq_empty_of_not_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalRawLowerSmoothFiber_eq_empty_of_not_mem
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalCoreMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_paperExceptionalUpperFactors_factorization_eq_corePrefix
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_roughCanonicalExceptionalRawLower_factorization_eq_corePrefix
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalResidual_eq_coreFirst
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCoreCoefficient
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCoreCoefficient_mul_left
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCorePrefix
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCorePrefix_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughHeadPeriodicCorePrefix_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCoreMulPrefix
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicCoreMulPrefix_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughHeadPeriodicCoreMulPrefix_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCoreDiscreteVariation
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicWeightedCoreSum
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_range_succ_zeroExtendedPeriodicCore_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicWeightedCoreSum_eq_abel
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughHeadPeriodicWeightedCoreSum_le_variation
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_Icc_mul_divInd_eq_quotientSum
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicValuationCoreSum
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadPeriodicValuationCoreSum_eq_primePowerBlocks
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughHeadPeriodicValuationCoreSum_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_sum_factorization_mul_error_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_factorization_cutoffBand_le_four_mul_div_prime
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.weightedFactorizationSum_cutoffBand_le_eight_div_prime
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_sum_factorization_mul_cutoffBand_error_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDeepCoreSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalCutoffCoreSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDeepCoreSet_disjoint_cutoffCoreSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalDeepCoreSet_union_cutoffCoreSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_exceptionalCorePrefix_eq_deep_add_cutoff
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalSignedExceptionalCoreChamberEstimate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalSignedExceptionalResidual_le_coreFirstFinite
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalEndpointRatio
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperExceptionalCutoff_tendsto_atTop
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalExceptionalEndpointRatio_tendsto_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_tangentPaperExceptionalCutoff_le_self_div_L_sq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalSignedExceptionalCoreChamberEventually
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalCoreBoundConstant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalSignedExceptionalCoreBoundConstant_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalSignedExceptionalResidualBound_of_coreChamber
