import Erdos390.WholePaper.BankPaperCanonicalNonsmoothSlackClosure
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_completeLabelMultiplicity_eq_zero_of_active
#print axioms Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_completeLabelMultiplicity_le_one
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedRow_subset_anchorRow_of_baseMultiplicity_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedRow_card_le_one_of_baseMultiplicity_zero
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalDiscrepancyIncrement_abs_le_two
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawWeightGuardBound
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawWeightGuardBound_nonneg
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadCompatibleBalancedRawWeight_abs_le_guardBound
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedGuardNumeratorConstant
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedGuardNumeratorConstant_pos
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalDiscrepancyIncrement_abs_le_fixed
#print axioms Erdos390.WholePaper.isCompleteRoughLabel_three_le_of_two_le
#print axioms Erdos390.WholePaper.eventually_roughCanonicalBalancedRawRowQuotaError_abs_le_unified_active
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeCorrectionDensity_eq_discrepancy_div
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawRowDiscrepancy_eq_quotaError
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedPostchargeRowDiscrepancy_abs_le_raw_add_guard
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool_linear_half_lower
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedGuardedPostchargeCorrectionDensity_abs_le_reserve
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalBalancedNonsmoothBounds
#print axioms Erdos390.WholePaper.BankPaperRealization.nonsmoothEndpointBounds_force_margin_inequalities
#print axioms Erdos390.WholePaper.BankPaperRealization.nonsmoothEndpointBounds_impossible_of_beta_le_sigma
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalBalancedNonsmoothBounds
#print axioms Erdos390.WholePaper.BankPaperRealization.RoughCanonicalBalancedNonsmoothBounds.to_actualEndpointBounds

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.paperFixedExceptionalFactors_completeLabelMultiplicity_eq_zero_of_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.prechargeBaseState_completeLabelMultiplicity_le_one
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedRow_subset_anchorRow_of_baseMultiplicity_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardDeletedRow_card_le_one_of_baseMultiplicity_zero
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalDiscrepancyIncrement_abs_le_two
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawWeightGuardBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedRawWeightGuardBound_nonneg
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadCompatibleBalancedRawWeight_abs_le_guardBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedGuardNumeratorConstant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedGuardNumeratorConstant_pos
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardLocalDiscrepancyIncrement_abs_le_fixed
assert_no_sorry Erdos390.WholePaper.isCompleteRoughLabel_three_le_of_two_le
assert_no_sorry Erdos390.WholePaper.eventually_roughCanonicalBalancedRawRowQuotaError_abs_le_unified_active
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedPostchargeCorrectionDensity_eq_discrepancy_div
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalRawRowDiscrepancy_eq_quotaError
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedPostchargeRowDiscrepancy_abs_le_raw_add_guard
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalGuardedBroadCorrectionPool_linear_half_lower
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBalancedGuardedPostchargeCorrectionDensity_abs_le_reserve
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalBalancedNonsmoothBounds
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.nonsmoothEndpointBounds_force_margin_inequalities
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.nonsmoothEndpointBounds_impossible_of_beta_le_sigma
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalBalancedNonsmoothBounds
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.RoughCanonicalBalancedNonsmoothBounds.to_actualEndpointBounds
