import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightOrdinaryLogLedgerConnector

/-! # Statement audit for the exact post-height ordinary-log ledger -/

namespace Erdos390.WholePaper

#check bankPaperCanonicalSelectorLogSupport
#check bankPaperCanonical_log_target_eq_sum_factorization_on_selectorLogSupport
#check bankPaperCanonical_log_candidate_eq_sum_factorization_on_selectorLogSupport
#check bankPaperCanonical_selectorLogDefect_eq_sum_log_mul_deficit
#check bankPaperCanonical_selectorWeightedResidual_eq_selectorLogDefect_div
#check bankPaperCanonicalSelector_ordinaryLogCompatible_of_selectorLog
#check sum_bankPaperCanonicalActiveSeedAmbientWeight_mul
#check bankPaperCanonicalActualFrozenLogMass_add_activeOrdinaryLog_eq
#check bankPaperCanonical_log_finset_prod_id
#check GuardedCentralAnchorCertificate.selectorTailTarget_log_charge
#check bankPaperCanonicalSectionNinePostHeight_activeSeed_ordinaryLogMoment_eq_logY_sub_Lambda0
#check bankPaperCanonicalSectionNinePostHeight_selectorLog_eq_target
#check bankPaperCanonicalSectionNinePostHeight_selectorLog_eq_target_of_prechargedTail
#check bankPaperCanonicalSectionNinePostHeight_initialSelector_ordinaryLogCompatible
#check bankPaperCanonicalSectionNinePostHeight_weightedActiveTarget_sub_primeLogMoment_eq_zero

end Erdos390.WholePaper
