import Erdos390.WholePaper.BankPaperPaths
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for actual full bank paths -/

#print axioms Erdos390.WholePaper.bankPaperPathComponentRequest_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateZeroValue_mem_componentOccurrences
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateOneValue_mem_componentOccurrences
#print axioms Erdos390.WholePaper.BankPaperRealization.pathComponentOccurrences_disjoint
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateZeroValue_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateOneValue_injective
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateZero_card
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateOne_card
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateZero_subset_componentCensus
#print axioms Erdos390.WholePaper.BankPaperRealization.pathStateOne_subset_componentCensus
#print axioms Erdos390.WholePaper.BankPaperRealization.pathComponentCensus_mem_factorInterval
#print axioms Erdos390.WholePaper.BankPaperRealization.pathComponent_completeRoughSignature_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.path_completeSignatureMultiplicity_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.realizedFullPathChange_eq_ordinary_add_bottom
#print axioms Erdos390.WholePaper.BankPaperRealization.realizedFullPathChange_eq_signedUnit

assert_no_sorry Erdos390.WholePaper.bankPaperPathComponentRequest_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateZeroValue_mem_componentOccurrences
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateOneValue_mem_componentOccurrences
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathComponentOccurrences_disjoint
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateZeroValue_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateOneValue_injective
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateZero_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateOne_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateZero_subset_componentCensus
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathStateOne_subset_componentCensus
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathComponentCensus_mem_factorInterval
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathComponent_completeRoughSignature_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.path_completeSignatureMultiplicity_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.realizedFullPathChange_eq_ordinary_add_bottom
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.realizedFullPathChange_eq_signedUnit
