import Erdos390.WholePaper.BankPaperPrechargeDivisibilityAlgebra
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.mul_dvd_of_factorization_split
#print axioms Erdos390.WholePaper.mul_dvd_of_factorization_split_with_donor
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.mul_prechargeBaseStateProduct_dvd_centralTailProduct

assert_no_sorry Erdos390.WholePaper.mul_dvd_of_factorization_split
assert_no_sorry Erdos390.WholePaper.mul_dvd_of_factorization_split_with_donor
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.mul_prechargeBaseStateProduct_dvd_centralTailProduct
