import Erdos390.WholePaper.BankPaperCanonicalBridgeRelevantGuardLedger
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the bridge-relevant guard ledger -/

#print axioms Erdos390.WholePaper.guardFinsetWithZeroEmbedding
#print axioms Erdos390.WholePaper.ledgerOfFinsetWithZero
#print axioms Erdos390.WholePaper.roughCanonicalBridgeRelevantGuardSet
#print axioms Erdos390.WholePaper.roughCanonicalBridgeRelevantLedgerFamily
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedger
#print axioms Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalBridgeGuardAgreement
#print axioms Erdos390.WholePaper.ledgerOfFinsetWithZero_guards
#print axioms Erdos390.WholePaper.roughCanonicalBridgeRelevantGuardSet_card_le
#print axioms Erdos390.WholePaper.roughCanonicalBridgeRelevantGuardSet_subset_anchors
#print axioms Erdos390.WholePaper.guardedCentralAnchor_mem_bridgeRelevant_of_smooth
#print axioms Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalBridgeRelevantGuardSet_iff_mem_guardSet
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantGuardSet_insert_zero_card_le_guardSlot
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedgerFamily_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedger_guards
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedger_agreement
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedgerFamily_agreement
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalBridgeRelevantLedger_agreement
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalBridgeRelevantLedgerFamily_agreement
#print axioms Erdos390.WholePaper.BankPaperRealization.rawCell_value_le_two_mul
#print axioms Erdos390.WholePaper.BankPaperRealization.rawCell_sdiff_roughCanonicalBridgeRelevantLedger_eq_fullGuard
#print axioms Erdos390.WholePaper.BankPaperRealization.structuredSample_value_mem_relevantLedger_iff_fullGuard
#print axioms Erdos390.WholePaper.BankPaperRealization.structuredActiveValues_sdiff_relevantLedger_eq_fullGuard
#print axioms Erdos390.WholePaper.BankPaperRealization.structuredSample_value_not_fullGuard_of_agreement
#print axioms Erdos390.WholePaper.BankPaperRealization.structuredSample_value_not_fullGuard_of_relevantLedger

assert_no_sorry Erdos390.WholePaper.guardFinsetWithZeroEmbedding
assert_no_sorry Erdos390.WholePaper.ledgerOfFinsetWithZero
assert_no_sorry Erdos390.WholePaper.roughCanonicalBridgeRelevantGuardSet
assert_no_sorry Erdos390.WholePaper.roughCanonicalBridgeRelevantLedgerFamily
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.BankPaperCanonicalBridgeGuardAgreement
assert_no_sorry Erdos390.WholePaper.ledgerOfFinsetWithZero_guards
assert_no_sorry Erdos390.WholePaper.roughCanonicalBridgeRelevantGuardSet_card_le
assert_no_sorry Erdos390.WholePaper.roughCanonicalBridgeRelevantGuardSet_subset_anchors
assert_no_sorry Erdos390.WholePaper.guardedCentralAnchor_mem_bridgeRelevant_of_smooth
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.mem_roughCanonicalBridgeRelevantGuardSet_iff_mem_guardSet
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantGuardSet_insert_zero_card_le_guardSlot
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedgerFamily_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedger_guards
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedger_agreement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalBridgeRelevantLedgerFamily_agreement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalBridgeRelevantLedger_agreement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalBridgeRelevantLedgerFamily_agreement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.rawCell_value_le_two_mul
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.rawCell_sdiff_roughCanonicalBridgeRelevantLedger_eq_fullGuard
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.structuredSample_value_mem_relevantLedger_iff_fullGuard
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.structuredActiveValues_sdiff_relevantLedger_eq_fullGuard
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.structuredSample_value_not_fullGuard_of_agreement
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.structuredSample_value_not_fullGuard_of_relevantLedger
