import Erdos390.WholePaper.BankPaperCanonicalGuardedPostchargeCorrectionRateClosure
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for guarded postcharge correction-rate closure -/

#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalUniformGuardedPostchargeCorrectionDensityConstant
#print axioms Erdos390.WholePaper.BankPaperRealization.roughCanonicalUniformGuardedPostchargeCorrectionDensityConstant_pos
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalUniformGuardedPostchargeCorrectionDensityBound
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_activeGuardedPostchargeCorrectionPool_factorization_le_four_mul_div_prime
#print axioms Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardedPostchargeRowCorrection_le_uniformDensity
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_abs_roughCanonicalAggregateGuardedPostchargeRowCorrection_le_strictScale
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_strictScale

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalUniformGuardedPostchargeCorrectionDensityConstant
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughCanonicalUniformGuardedPostchargeCorrectionDensityConstant_pos
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_roughCanonicalUniformGuardedPostchargeCorrectionDensityBound
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_activeGuardedPostchargeCorrectionPool_factorization_le_four_mul_div_prime
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.abs_roughCanonicalAggregateGuardedPostchargeRowCorrection_le_uniformDensity
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_abs_roughCanonicalAggregateGuardedPostchargeRowCorrection_le_strictScale
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_abs_roughCanonicalAggregateGuardedRawCorrectionValuationDefect_le_strictScale
