import Erdos390.WholePaper.BankPaperCanonicalSectionEightTopFrozenSourceConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the Section 8 frozen-top source

All public declarations in the isolated finite bridge are printed and
checked for proof placeholders.
-/

#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSmoothTopWeight
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedOutsideSelectorWithTop
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSmoothTopWeight_eq_rawWeight_of_mem_guardedSmoothRow_of_not_mem_broadPool
#print axioms Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_apply_of_mem_smoothRow
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_smoothRow_eq_frozenRaw_add_activeMass
#print axioms Erdos390.WholePaper.BankPaperRealization.roughHeadCompatibleRawWeight_split_protected_active_of_mem_guardedSmoothRow
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_roughHeadCompatibleRawWeight_split_protected_active_guardedSmoothRow
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_smoothRow_eq_balancedRaw
#print axioms Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_scaledSeed_smoothRow_eq_balancedRaw

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSmoothTopWeight
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedOutsideSelectorWithTop
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalSmoothTopWeight_eq_rawWeight_of_mem_guardedSmoothRow_of_not_mem_broadPool
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_apply_of_mem_smoothRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_smoothRow_eq_frozenRaw_add_activeMass
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.roughHeadCompatibleRawWeight_split_protected_active_of_mem_guardedSmoothRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_roughHeadCompatibleRawWeight_split_protected_active_guardedSmoothRow
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_smoothRow_eq_balancedRaw
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.sum_bankPaperCanonicalGlobalCorrectedSourceSelectorWithTop_scaledSeed_smoothRow_eq_balancedRaw
