import Erdos390.WholePaper.BankOrdinaryConcreteDemand

/-! # Assumption audit for concrete ordinary requests -/

#print axioms Erdos390.WholePaper.bankOrdinaryPaperRequest_component_spec
#print axioms Erdos390.WholePaper.bankOrdinaryPaperRequest_scale_le_yNat
#print axioms Erdos390.WholePaper.bankOrdinaryPoolDemand_eq
#print axioms Erdos390.WholePaper.bankOrdinaryPoolDemand_le_seventeen_beta
#print axioms Erdos390.WholePaper.bankOrdinaryPoolDemand_le_two_beta
#print axioms Erdos390.WholePaper.bankOrdinaryPoolDemand_scale_zero
#print axioms Erdos390.WholePaper.bankOrdinaryPoolDemand_zero_of_scale_gt_yNat
#print axioms Erdos390.WholePaper.yNat_div_bankOrdinaryWorstMarkerScale_tendsto_zero
#print axioms Erdos390.WholePaper.bankBottomPaperDemand_isLittleO_bankOrdinaryWorstMarkerScale
#print axioms Erdos390.WholePaper.bankBottomPaperDemand_div_bankOrdinaryWorstMarkerScale_tendsto_zero
#print axioms Erdos390.WholePaper.bankOrdinary_largeOrientationDemand_isLittleO
#print axioms Erdos390.WholePaper.bankOrdinary_smallOrientationDemand_isLittleO
#print axioms Erdos390.WholePaper.eventually_bankOrdinary_max_scale_log_le_five_yNat

assert_no_sorry Erdos390.WholePaper.bankOrdinaryPaperRequest_component_spec
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPaperRequest_scale_le_yNat
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPoolDemand_eq
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPoolDemand_le_seventeen_beta
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPoolDemand_le_two_beta
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPoolDemand_scale_zero
assert_no_sorry Erdos390.WholePaper.bankOrdinaryPoolDemand_zero_of_scale_gt_yNat
assert_no_sorry Erdos390.WholePaper.yNat_div_bankOrdinaryWorstMarkerScale_tendsto_zero
assert_no_sorry Erdos390.WholePaper.bankBottomPaperDemand_isLittleO_bankOrdinaryWorstMarkerScale
assert_no_sorry Erdos390.WholePaper.bankBottomPaperDemand_div_bankOrdinaryWorstMarkerScale_tendsto_zero
assert_no_sorry Erdos390.WholePaper.bankOrdinary_largeOrientationDemand_isLittleO
assert_no_sorry Erdos390.WholePaper.bankOrdinary_smallOrientationDemand_isLittleO
assert_no_sorry Erdos390.WholePaper.eventually_bankOrdinary_max_scale_log_le_five_yNat
