import Erdos390.WholePaper.BankPaperAnchorExactificationGuards
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for anchor/exactification bank guards -/

#print axioms Erdos390.WholePaper.BankPaperRealization.pathComponentCensus_subset_allComponentOccurrences
#print axioms Erdos390.WholePaper.BankPaperRealization.exactificationState_subset_allComponentOccurrences
#print axioms Erdos390.WholePaper.BankPaperRealization.disjoint_exactificationState_of_disjoint_allComponentOccurrences
#print axioms Erdos390.WholePaper.BankPaperRealization.disjoint_chosenExactificationBank_of_disjoint_states
#print axioms Erdos390.WholePaper.BankPaperRealization.disjoint_baseExactificationBank_of_disjoint_states
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_exactificationState
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_exactificationStates
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_baseExactificationBank
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_chosenExactificationBank
#print axioms Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchor_exactificationGuards
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_guardedCentralAnchor_exactificationGuards

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.pathComponentCensus_subset_allComponentOccurrences
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exactificationState_subset_allComponentOccurrences
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.disjoint_exactificationState_of_disjoint_allComponentOccurrences
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.disjoint_chosenExactificationBank_of_disjoint_states
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.disjoint_baseExactificationBank_of_disjoint_states
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_exactificationState
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_exactificationStates
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_baseExactificationBank
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchors_disjoint_chosenExactificationBank
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.guardedCentralAnchor_exactificationGuards
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_guardedCentralAnchor_exactificationGuards
