import Erdos390.WholePaper.BankPaperCanonicalArbitrarySourcePostHfitConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for arbitrary-source Post-Hfit production -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource
#print axioms BankPaperRealization.BankPaperCanonicalPostHfitGuardedSlackPackageOfSource
#print axioms BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_hpreUpper
#print axioms BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_hpreNonsmooth
#print axioms BankPaperRealization.exists_bankPaperCanonicalPostHfitGuardedSlackPackageOfSource_of_sourceState
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitStructuredPreSelector
#print axioms BankPaperRealization.BankPaperCanonicalTopFrozenRoundedPostHfitGuardedSlackPackage
#print axioms BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_hsourceNonsmooth
#print axioms BankPaperRealization.exists_bankPaperCanonicalTopFrozenRoundedPostHfitGuardedSlackPackage_of_sourceState

assert_no_sorry BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource
assert_no_sorry BankPaperRealization.BankPaperCanonicalPostHfitGuardedSlackPackageOfSource
assert_no_sorry BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_hpreUpper
assert_no_sorry BankPaperRealization.bankPaperCanonicalPostHfitStructuredPreSelectorOfSource_hpreNonsmooth
assert_no_sorry BankPaperRealization.exists_bankPaperCanonicalPostHfitGuardedSlackPackageOfSource_of_sourceState
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedPostHfitStructuredPreSelector
assert_no_sorry BankPaperRealization.BankPaperCanonicalTopFrozenRoundedPostHfitGuardedSlackPackage
assert_no_sorry BankPaperRealization.bankPaperCanonicalTopFrozenRoundedSourceSelector_hsourceNonsmooth
assert_no_sorry BankPaperRealization.exists_bankPaperCanonicalTopFrozenRoundedPostHfitGuardedSlackPackage_of_sourceState

end Erdos390.WholePaper
