import Erdos390.WholePaper.BankPaperExactificationState
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.BankPaperRealization.exactificationState_productChange
#print axioms Erdos390.WholePaper.BankPaperRealization.exactificationState_completeSignatureMultiplicity_eq
#print axioms Erdos390.WholePaper.BankPaperRealization.exactificationState_disjoint_of_slot_ne
#print axioms Erdos390.WholePaper.BankPaperRealization.exactificationState_subset_factorInterval
#print axioms Erdos390.WholePaper.BankPaperRealization.exactificationState_positive

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exactificationState_productChange
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exactificationState_completeSignatureMultiplicity_eq
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exactificationState_disjoint_of_slot_ne
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exactificationState_subset_factorInterval
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.exactificationState_positive
