import Erdos390.WholePaper.BankPaperCanonicalSignedExceptionalCoreFirst

/-! # Statement audit for signed exceptional core-first cancellation -/

namespace Erdos390.WholePaper

namespace BankPaperRealization

#check roughCanonicalExceptionalRawLowerSmoothParts
#check roughCanonicalExceptionalRawLowerSmoothFiber
#check mem_roughCanonicalExceptionalRawLowerSmoothParts
#check mem_roughCanonicalExceptionalRawLowerSmoothFiber
#check roughRawCandidateSet_pos_le_two_mul
#check completeSmoothPart_cast_lt_realExceptionalCutoff_of_rawLower
#check completeSmoothPart_lt_exceptionalCutoff_of_rawLower
#check roughCanonicalExceptionalRawLowerSmoothParts_subset_Icc_two_mul_cutoff
#check factorization_eq_completeSmoothPart_factorization_of_le
#check paperExceptionalSmoothFiber_eq_empty_of_not_mem
#check roughCanonicalExceptionalRawLowerSmoothFiber_eq_empty_of_not_mem
#check roughCanonicalSignedExceptionalCoreMass
#check sum_paperExceptionalUpperFactors_factorization_eq_corePrefix
#check sum_roughCanonicalExceptionalRawLower_factorization_eq_corePrefix
#check roughCanonicalSignedExceptionalResidual_eq_coreFirst
#check roughHeadPeriodicCoreCoefficient
#check roughHeadPeriodicCoreCoefficient_mul_left
#check roughHeadPeriodicCorePrefix
#check roughHeadPeriodicCorePrefix_eq
#check abs_roughHeadPeriodicCorePrefix_le
#check roughHeadPeriodicCoreMulPrefix
#check roughHeadPeriodicCoreMulPrefix_eq
#check abs_roughHeadPeriodicCoreMulPrefix_le
#check roughCoreDiscreteVariation
#check roughHeadPeriodicWeightedCoreSum
#check sum_range_succ_zeroExtendedPeriodicCore_eq
#check roughHeadPeriodicWeightedCoreSum_eq_abel
#check abs_roughHeadPeriodicWeightedCoreSum_le_variation
#check sum_Icc_mul_divInd_eq_quotientSum
#check roughHeadPeriodicValuationCoreSum
#check roughHeadPeriodicValuationCoreSum_eq_primePowerBlocks
#check abs_roughHeadPeriodicValuationCoreSum_le
#check abs_sum_factorization_mul_error_le
#check sum_factorization_cutoffBand_le_four_mul_div_prime
#check weightedFactorizationSum_cutoffBand_le_eight_div_prime
#check abs_sum_factorization_mul_cutoffBand_error_le
#check roughCanonicalExceptionalDeepCoreSet
#check roughCanonicalExceptionalCutoffCoreSet
#check roughCanonicalExceptionalDeepCoreSet_disjoint_cutoffCoreSet
#check roughCanonicalExceptionalDeepCoreSet_union_cutoffCoreSet
#check sum_exceptionalCorePrefix_eq_deep_add_cutoff
#check RoughCanonicalSignedExceptionalCoreChamberEstimate
#check abs_roughCanonicalSignedExceptionalResidual_le_coreFirstFinite
#check roughCanonicalExceptionalEndpointRatio
#check tangentPaperExceptionalCutoff_tendsto_atTop
#check roughCanonicalExceptionalEndpointRatio_tendsto_zero
#check eventually_tangentPaperExceptionalCutoff_le_self_div_L_sq
#check RoughCanonicalSignedExceptionalCoreChamberEventually
#check roughCanonicalSignedExceptionalCoreBoundConstant
#check roughCanonicalSignedExceptionalCoreBoundConstant_nonneg
#check eventually_roughCanonicalSignedExceptionalResidualBound_of_coreChamber

end BankPaperRealization

end Erdos390.WholePaper
