import Erdos390.WholePaper.BankPaperCanonicalSectionNinePostHeightPlacedMeasureConnector
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the post-height placed measure connector -/

namespace Erdos390.WholePaper

#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlacedPreSelector
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlacedPreSelector_eq_structuredPlacement
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlacedPreSelector_coordinateFit
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlaced_actualMeasure
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightActiveSeed_le_of_massAndCellDensity
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlacementCapacity_of_massAndCellDensity
#print axioms BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlaced_actualMeasure_and_feasible_of_massAndCellDensity

assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlacedPreSelector
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlacedPreSelector_eq_structuredPlacement
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlacedPreSelector_coordinateFit
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlaced_actualMeasure
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightActiveSeed_le_of_massAndCellDensity
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlacementCapacity_of_massAndCellDensity
assert_no_sorry BankPaperRealization.bankPaperCanonicalSectionNinePostHeightPlaced_actualMeasure_and_feasible_of_massAndCellDensity

end Erdos390.WholePaper
