import Erdos390.WholePaper.BankPaperFourFiveProductMeasureTelescope
import Mathlib.Util.AssertNoSorry

namespace Erdos390.WholePaper.BankPaperRealization

#print axioms fourFiveFiniteProductOne_sub
#print axioms fourFiveFiniteProductTwo_sub
#print axioms fourFiveFiniteProductThree_sub
#print axioms abs_fourFiveFiniteWeightedSum_le_mass_mul
#print axioms fourFiveRightDiscreteBVNorm_finiteWeightedFamily_le
#print axioms fourFiveRightDiscreteBVNorm_finiteWeightedFamily_le_mass_mul
#print axioms fourFiveReciprocalBVError_pos
#print axioms fourFiveActualReciprocalProductOne_sub_continuum
#print axioms fourFiveActualReciprocalProductTwo_sub_continuum
#print axioms fourFiveActualReciprocalProductThree_sub_continuum
#print axioms abs_fourFiveActualReciprocalProductOne_sub_continuum_le
#print axioms abs_fourFiveActualReciprocalProductTwo_sub_continuum_le
#print axioms abs_fourFiveActualReciprocalProductThree_sub_continuum_le

assert_no_sorry fourFiveFiniteProductOne_sub
assert_no_sorry fourFiveFiniteProductTwo_sub
assert_no_sorry fourFiveFiniteProductThree_sub
assert_no_sorry abs_fourFiveFiniteWeightedSum_le_mass_mul
assert_no_sorry fourFiveRightDiscreteBVNorm_finiteWeightedFamily_le
assert_no_sorry fourFiveRightDiscreteBVNorm_finiteWeightedFamily_le_mass_mul
assert_no_sorry fourFiveReciprocalBVError_pos
assert_no_sorry fourFiveActualReciprocalProductOne_sub_continuum
assert_no_sorry fourFiveActualReciprocalProductTwo_sub_continuum
assert_no_sorry fourFiveActualReciprocalProductThree_sub_continuum
assert_no_sorry abs_fourFiveActualReciprocalProductOne_sub_continuum_le
assert_no_sorry abs_fourFiveActualReciprocalProductTwo_sub_continuum_le
assert_no_sorry abs_fourFiveActualReciprocalProductThree_sub_continuum_le

end Erdos390.WholePaper.BankPaperRealization
