import Erdos390.WholePaper.BankPaperCanonicalSectionEightActiveMassScaleLowerConnector
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit for the guarded Section 8 active-mass lower connector
-/

#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedTailSmoothBaseDeletionCensus
#print axioms Erdos390.WholePaper.bankPaperCanonicalRawSmoothBase_sub_extendedGuardedSmoothBase_isLittleO
#print axioms Erdos390.WholePaper.bankPaperCanonicalExtendedGuardedSmoothBaseMass_paperScaleLower
#print axioms Erdos390.WholePaper.bankPaperCanonicalGuardedTailSmoothQ0Family_paperScaleLower

assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedTailSmoothBaseDeletionCensus
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalRawSmoothBase_sub_extendedGuardedSmoothBase_isLittleO
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalExtendedGuardedSmoothBaseMass_paperScaleLower
assert_no_sorry Erdos390.WholePaper.bankPaperCanonicalGuardedTailSmoothQ0Family_paperScaleLower
