import Erdos390.WholePaper.CanonicalCompleteRoughRows
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for canonical complete rough rows -/

#print axioms Erdos390.WholePaper.canonicalCompleteRoughRow_val
#print axioms Erdos390.WholePaper.canonicalCompleteRoughRowSignature_apply
#print axioms Erdos390.WholePaper.canonicalCompleteRoughCandidateValue_apply
#print axioms Erdos390.WholePaper.canonicalCompleteRoughRow_surjective
#print axioms Erdos390.WholePaper.canonicalCompleteRoughRow_label_pos
#print axioms Erdos390.WholePaper.canonicalCompleteRoughRowSignature_injective
#print axioms Erdos390.WholePaper.completeRoughSignature_eq_canonicalCompleteRoughRowSignature
#print axioms Erdos390.WholePaper.canonicalCompleteRoughCandidateValue_injective
#print axioms Erdos390.WholePaper.canonicalCompleteRoughCandidateValue_mem_factorInterval
#print axioms Erdos390.WholePaper.mem_completeRoughSubtypeRowFiber
#print axioms Erdos390.WholePaper.mem_completeRoughSubtypeRowFiber_iff_value_mem
#print axioms Erdos390.WholePaper.mem_canonicalCompleteRoughRowSet_iff
#print axioms Erdos390.WholePaper.canonicalCompleteRough_rowSet_eq_subtypeRowFiber
#print axioms Erdos390.WholePaper.sum_canonicalCompleteRoughRowSet_eq_sum_completeRoughRowFiber
#print axioms Erdos390.WholePaper.canonicalCompleteRough_rowSums_integer_iff_subtypeFiberSums_integer
#print axioms Erdos390.WholePaper.canonicalCompleteRough_rowSums_integer_of_subtypeFiberSums_integer
#print axioms Erdos390.WholePaper.canonicalCompleteRough_rowSums_integer_iff_rowFiberSums_integer
#print axioms Erdos390.WholePaper.canonicalCompleteRough_rowSums_integer_of_rowFiberSums_integer

assert_no_sorry Erdos390.WholePaper.canonicalCompleteRoughRow_val
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRoughRowSignature_apply
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRoughCandidateValue_apply
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRoughRow_surjective
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRoughRow_label_pos
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRoughRowSignature_injective
assert_no_sorry Erdos390.WholePaper.completeRoughSignature_eq_canonicalCompleteRoughRowSignature
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRoughCandidateValue_injective
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRoughCandidateValue_mem_factorInterval
assert_no_sorry Erdos390.WholePaper.mem_completeRoughSubtypeRowFiber
assert_no_sorry Erdos390.WholePaper.mem_completeRoughSubtypeRowFiber_iff_value_mem
assert_no_sorry Erdos390.WholePaper.mem_canonicalCompleteRoughRowSet_iff
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRough_rowSet_eq_subtypeRowFiber
assert_no_sorry Erdos390.WholePaper.sum_canonicalCompleteRoughRowSet_eq_sum_completeRoughRowFiber
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRough_rowSums_integer_iff_subtypeFiberSums_integer
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRough_rowSums_integer_of_subtypeFiberSums_integer
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRough_rowSums_integer_iff_rowFiberSums_integer
assert_no_sorry Erdos390.WholePaper.canonicalCompleteRough_rowSums_integer_of_rowFiberSums_integer
