import Erdos390.WholePaper.CentralAnchorGuardedCertificate
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.guardedCentralAnchorCertificate_of_changeCost
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.isCofactorChoice
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.anchors_eq
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.anchors_subset
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.anchors_prod
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.divisor_prime_support
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.divisor_reserve
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.divisor_dvd_tail
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.guarded_incident_cores

assert_no_sorry Erdos390.WholePaper.guardedCentralAnchorCertificate_of_changeCost
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.isCofactorChoice
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.anchors_eq
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.anchors_subset
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.anchors_prod
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.divisor_prime_support
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.divisor_reserve
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.divisor_dvd_tail
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.guarded_incident_cores
