import Erdos390.WholePaper.CentralAnchorCutoff
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the explicit cutoff scale separation -/

#print axioms Erdos390.WholePaper.centralAnchorCutoffThreshold_pos
#print axioms Erdos390.WholePaper.four_mul_succ_le_centralAnchorCutoff
#print axioms Erdos390.WholePaper.two_mul_add_one_lt_centralAnchorCutoff
#print axioms Erdos390.WholePaper.two_mul_lt_centralAnchorCutoff_sq
#print axioms Erdos390.WholePaper.centralAnchorCutoff_scaleSeparation
#print axioms Erdos390.WholePaper.two_le_centralAnchorCutoff
#print axioms Erdos390.WholePaper.eventually_centralAnchorCutoff_scaleSeparation
#print axioms Erdos390.WholePaper.eventually_two_mul_add_one_lt_centralAnchorCutoff
#print axioms Erdos390.WholePaper.eventually_two_mul_lt_centralAnchorCutoff_sq
#print axioms Erdos390.WholePaper.div_le_fixedPrefix_of_centralAnchorCutoff_lt

assert_no_sorry Erdos390.WholePaper.centralAnchorCutoffThreshold_pos
assert_no_sorry Erdos390.WholePaper.four_mul_succ_le_centralAnchorCutoff
assert_no_sorry Erdos390.WholePaper.two_mul_add_one_lt_centralAnchorCutoff
assert_no_sorry Erdos390.WholePaper.two_mul_lt_centralAnchorCutoff_sq
assert_no_sorry Erdos390.WholePaper.centralAnchorCutoff_scaleSeparation
assert_no_sorry Erdos390.WholePaper.two_le_centralAnchorCutoff
assert_no_sorry Erdos390.WholePaper.eventually_centralAnchorCutoff_scaleSeparation
assert_no_sorry Erdos390.WholePaper.eventually_two_mul_add_one_lt_centralAnchorCutoff
assert_no_sorry Erdos390.WholePaper.eventually_two_mul_lt_centralAnchorCutoff_sq
assert_no_sorry Erdos390.WholePaper.div_le_fixedPrefix_of_centralAnchorCutoff_lt
