import Erdos390.WholePaper.CentralAnchorGuardedChoice
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.guardedCentralCofactor_eq_of_not_mem
#print axioms Erdos390.WholePaper.guardedCentralCofactor_eq_three_of_mem_row_one
#print axioms Erdos390.WholePaper.guardedCentralCofactor_isChoice
#print axioms Erdos390.WholePaper.guardedCentralCofactor_ne_incidentCores
#print axioms Erdos390.WholePaper.guardedCentralCofactor_eq_off_changed
#print axioms Erdos390.WholePaper.guardedCentralCofactor_le_fixedPrefix
#print axioms Erdos390.WholePaper.guardedCentralAnchorDivisor_factorization_le_add_changed_cost

assert_no_sorry Erdos390.WholePaper.guardedCentralCofactor_eq_of_not_mem
assert_no_sorry Erdos390.WholePaper.guardedCentralCofactor_eq_three_of_mem_row_one
assert_no_sorry Erdos390.WholePaper.guardedCentralCofactor_isChoice
assert_no_sorry Erdos390.WholePaper.guardedCentralCofactor_ne_incidentCores
assert_no_sorry Erdos390.WholePaper.guardedCentralCofactor_eq_off_changed
assert_no_sorry Erdos390.WholePaper.guardedCentralCofactor_le_fixedPrefix
assert_no_sorry Erdos390.WholePaper.guardedCentralAnchorDivisor_factorization_le_add_changed_cost
