import Erdos390.WholePaper.CompleteRoughDecomposition
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for complete rough decomposition -/

#print axioms Erdos390.WholePaper.completeRoughLabel_pos
#print axioms Erdos390.WholePaper.completeRoughLabel_ne_zero
#print axioms Erdos390.WholePaper.completeRoughLabel_factorization_eq_filter_gt
#print axioms Erdos390.WholePaper.completeRoughLabel_factorization_apply
#print axioms Erdos390.WholePaper.completeRoughLabel_dvd
#print axioms Erdos390.WholePaper.completeRough_decomposition
#print axioms Erdos390.WholePaper.completeRoughLabel_mul_completeSmoothPart
#print axioms Erdos390.WholePaper.completeSmoothPart_factorization_eq_filter_le
#print axioms Erdos390.WholePaper.completeSmoothPart_factorization_apply
#print axioms Erdos390.WholePaper.completeRoughLabel_factorization_support
#print axioms Erdos390.WholePaper.completeSmoothPart_factorization_support
#print axioms Erdos390.WholePaper.prime_dvd_completeRoughLabel_gt
#print axioms Erdos390.WholePaper.completeSmoothPart_pos
#print axioms Erdos390.WholePaper.completeSmoothPart_mem_smoothNumbers
#print axioms Erdos390.WholePaper.completeRoughDecomposition_unique
#print axioms Erdos390.WholePaper.completeRoughLabel_eq_one_iff_mem_smoothNumbers
#print axioms Erdos390.WholePaper.completeRoughLabel_eq_one_iff_eq_zero_or_mem_smoothNumbers

assert_no_sorry Erdos390.WholePaper.completeRoughLabel_pos
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_ne_zero
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_factorization_eq_filter_gt
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_factorization_apply
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_dvd
assert_no_sorry Erdos390.WholePaper.completeRough_decomposition
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_mul_completeSmoothPart
assert_no_sorry Erdos390.WholePaper.completeSmoothPart_factorization_eq_filter_le
assert_no_sorry Erdos390.WholePaper.completeSmoothPart_factorization_apply
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_factorization_support
assert_no_sorry Erdos390.WholePaper.completeSmoothPart_factorization_support
assert_no_sorry Erdos390.WholePaper.prime_dvd_completeRoughLabel_gt
assert_no_sorry Erdos390.WholePaper.completeSmoothPart_pos
assert_no_sorry Erdos390.WholePaper.completeSmoothPart_mem_smoothNumbers
assert_no_sorry Erdos390.WholePaper.completeRoughDecomposition_unique
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_eq_one_iff_mem_smoothNumbers
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_eq_one_iff_eq_zero_or_mem_smoothNumbers
