import Erdos390.WholePaper.CompleteRoughRowPartition
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the complete rough-row partition -/

#print axioms Erdos390.WholePaper.mem_completeRoughLabelSet
#print axioms Erdos390.WholePaper.mem_completeRoughRowFiber
#print axioms Erdos390.WholePaper.mem_completeRoughLabelSet_iff_rowFiber_nonempty
#print axioms Erdos390.WholePaper.completeRoughRowFiber_subset
#print axioms Erdos390.WholePaper.completeRoughLabel_eq_of_mem_rowFiber
#print axioms Erdos390.WholePaper.completeRoughSignature_eq_label_factorization_of_mem_rowFiber
#print axioms Erdos390.WholePaper.completeRoughSignature_eq_of_mem_same_rowFiber
#print axioms Erdos390.WholePaper.completeRoughRowFibers_pairwiseDisjoint
#print axioms Erdos390.WholePaper.completeRoughLabelSet_biUnion_rowFibers
#print axioms Erdos390.WholePaper.sum_eq_sum_completeRoughRowFibers
#print axioms Erdos390.WholePaper.sum_factorization_eq_sum_completeRoughRowFibers
#print axioms Erdos390.WholePaper.factorization_eq_label_factorization_of_mem_rowFiber
#print axioms Erdos390.WholePaper.sum_factorization_eq_sum_rowCard_mul_labelFactorization

assert_no_sorry Erdos390.WholePaper.mem_completeRoughLabelSet
assert_no_sorry Erdos390.WholePaper.mem_completeRoughRowFiber
assert_no_sorry Erdos390.WholePaper.mem_completeRoughLabelSet_iff_rowFiber_nonempty
assert_no_sorry Erdos390.WholePaper.completeRoughRowFiber_subset
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_eq_of_mem_rowFiber
assert_no_sorry Erdos390.WholePaper.completeRoughSignature_eq_label_factorization_of_mem_rowFiber
assert_no_sorry Erdos390.WholePaper.completeRoughSignature_eq_of_mem_same_rowFiber
assert_no_sorry Erdos390.WholePaper.completeRoughRowFibers_pairwiseDisjoint
assert_no_sorry Erdos390.WholePaper.completeRoughLabelSet_biUnion_rowFibers
assert_no_sorry Erdos390.WholePaper.sum_eq_sum_completeRoughRowFibers
assert_no_sorry Erdos390.WholePaper.sum_factorization_eq_sum_completeRoughRowFibers
assert_no_sorry Erdos390.WholePaper.factorization_eq_label_factorization_of_mem_rowFiber
assert_no_sorry Erdos390.WholePaper.sum_factorization_eq_sum_rowCard_mul_labelFactorization
