import Erdos390.WholePaper.ExceptionalValuationSums
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the elementary finite valuation sums -/

#print axioms Erdos390.WholePaper.sum_factorization_Icc_eq_factorialFactorization
#print axioms Erdos390.WholePaper.sum_factorization_Icc_le_div_pred
#print axioms Erdos390.WholePaper.sum_factorization_Icc_cast_le_div_pred
#print axioms Erdos390.WholePaper.valuationPrefixReal_zero
#print axioms Erdos390.WholePaper.valuationPrefixReal_eq_factorialFactorization
#print axioms Erdos390.WholePaper.valuationPrefixReal_le_div_pred
#print axioms Erdos390.WholePaper.sum_range_succ_factorization_cast_eq_valuationPrefixReal
#print axioms Erdos390.WholePaper.weightedFactorizationSum_eq_abel
#print axioms Erdos390.WholePaper.weightedFactorizationSum_le_one_add_log_div_pred
#print axioms Erdos390.WholePaper.one_div_prime_pred_le_two_div_prime
#print axioms Erdos390.WholePaper.sum_factorization_Icc_cast_le_two_mul_div_prime
#print axioms Erdos390.WholePaper.weightedFactorizationSum_le_two_mul_one_add_log_div_prime

assert_no_sorry Erdos390.WholePaper.sum_factorization_Icc_eq_factorialFactorization
assert_no_sorry Erdos390.WholePaper.sum_factorization_Icc_le_div_pred
assert_no_sorry Erdos390.WholePaper.sum_factorization_Icc_cast_le_div_pred
assert_no_sorry Erdos390.WholePaper.valuationPrefixReal_zero
assert_no_sorry Erdos390.WholePaper.valuationPrefixReal_eq_factorialFactorization
assert_no_sorry Erdos390.WholePaper.valuationPrefixReal_le_div_pred
assert_no_sorry Erdos390.WholePaper.sum_range_succ_factorization_cast_eq_valuationPrefixReal
assert_no_sorry Erdos390.WholePaper.weightedFactorizationSum_eq_abel
assert_no_sorry Erdos390.WholePaper.weightedFactorizationSum_le_one_add_log_div_pred
assert_no_sorry Erdos390.WholePaper.one_div_prime_pred_le_two_div_prime
assert_no_sorry Erdos390.WholePaper.sum_factorization_Icc_cast_le_two_mul_div_prime
assert_no_sorry Erdos390.WholePaper.weightedFactorizationSum_le_two_mul_one_add_log_div_prime
