import Erdos390.WholePaper.FixedModulusReducedResidueCount
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.reducedResidueSegment_add
#print axioms Erdos390.WholePaper.reducedResidueSegment_disjoint
#print axioms Erdos390.WholePaper.reducedResidueSegment_card_add
#print axioms Erdos390.WholePaper.reducedResidueSegment_card_period
#print axioms Erdos390.WholePaper.reducedResidueSegment_card_fullBlocks
#print axioms Erdos390.WholePaper.reducedResidueSegment_card_eq_fullBlocks_add_remainder
#print axioms Erdos390.WholePaper.reducedResidueSegment_card_le_length
#print axioms Erdos390.WholePaper.reducedResidueIoc_eq_segment
#print axioms Erdos390.WholePaper.reducedResidueSegment_card_error_le_mod
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_error_le_mod
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_error_le_modulus
#print axioms Erdos390.WholePaper.coprimeMultipleIoc_card_eq_reducedResidueIoc
#print axioms Erdos390.WholePaper.quotientIocLength_sub_realLengthDiv_abs_lt_one
#print axioms Erdos390.WholePaper.coprimeMultipleIoc_card_error_le
#print axioms Erdos390.WholePaper.roughHeadFree_Ioc_card_error_le
#print axioms Erdos390.WholePaper.roughHeadCoprimeMultipleIoc_card_error_le
#print axioms Erdos390.WholePaper.prime_coprime_roughHeadModulus_of_cutoff_lt
#print axioms Erdos390.WholePaper.roughHeadPrimePowerMultipleIoc_card_error_le

assert_no_sorry Erdos390.WholePaper.reducedResidueSegment_add
assert_no_sorry Erdos390.WholePaper.reducedResidueSegment_disjoint
assert_no_sorry Erdos390.WholePaper.reducedResidueSegment_card_add
assert_no_sorry Erdos390.WholePaper.reducedResidueSegment_card_period
assert_no_sorry Erdos390.WholePaper.reducedResidueSegment_card_fullBlocks
assert_no_sorry Erdos390.WholePaper.reducedResidueSegment_card_eq_fullBlocks_add_remainder
assert_no_sorry Erdos390.WholePaper.reducedResidueSegment_card_le_length
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_eq_segment
assert_no_sorry Erdos390.WholePaper.reducedResidueSegment_card_error_le_mod
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_error_le_mod
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_error_le_modulus
assert_no_sorry Erdos390.WholePaper.coprimeMultipleIoc_card_eq_reducedResidueIoc
assert_no_sorry Erdos390.WholePaper.quotientIocLength_sub_realLengthDiv_abs_lt_one
assert_no_sorry Erdos390.WholePaper.coprimeMultipleIoc_card_error_le
assert_no_sorry Erdos390.WholePaper.roughHeadFree_Ioc_card_error_le
assert_no_sorry Erdos390.WholePaper.roughHeadCoprimeMultipleIoc_card_error_le
assert_no_sorry Erdos390.WholePaper.prime_coprime_roughHeadModulus_of_cutoff_lt
assert_no_sorry Erdos390.WholePaper.roughHeadPrimePowerMultipleIoc_card_error_le
