import Erdos390.WholePaper.FormalConjecturesBridge
import Mathlib.Util.AssertNoSorry

/-!
# Axiom audit: Formal Conjectures bridge for Erdős 390

The endpoint conversion, eventual bridge, fixed-constant asymptotic
equivalence, and both exact upstream conclusion shapes are checked for
hidden `sorry`.
-/

#print axioms Erdos390.WholePaper.FormalConjecturesBridge.fcAdmissible_to_isAdmissibleEndpoint
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.isAdmissibleEndpoint_to_exists_fcAdmissible
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.formalF_eq_wholePaper_f
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.eventually_formalF_eq_wholePaper_f
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.wholePaper_isEquivalent_fixedC0_of_mainAsymptotic
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.formalF_isEquivalent_fixedC0_of_mainAsymptotic
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.formalF_isEquivalent_fixedC0
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.formalF_theta
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.formalF_rhs
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.theta_of_eventuallyEq_formalF
#print axioms Erdos390.WholePaper.FormalConjecturesBridge.rhs_of_eventuallyEq_formalF

assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.fcAdmissible_to_isAdmissibleEndpoint
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.isAdmissibleEndpoint_to_exists_fcAdmissible
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.formalF_eq_wholePaper_f
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.eventually_formalF_eq_wholePaper_f
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.wholePaper_isEquivalent_fixedC0_of_mainAsymptotic
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.formalF_isEquivalent_fixedC0_of_mainAsymptotic
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.formalF_isEquivalent_fixedC0
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.formalF_theta
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.formalF_rhs
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.theta_of_eventuallyEq_formalF
assert_no_sorry Erdos390.WholePaper.FormalConjecturesBridge.rhs_of_eventuallyEq_formalF
