import Erdos390.WholePaper.GuardedUpperProductAssembly
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.guardedCentral_union_residual_prod
#print axioms Erdos390.WholePaper.hasComplementProduct_of_guardedCentral_residual
#print axioms Erdos390.WholePaper.isAdmissibleEndpoint_of_guardedCentral_residual
#print axioms Erdos390.WholePaper.GuardedCentralAnchorCertificate.isAdmissibleEndpoint_of_residual

assert_no_sorry Erdos390.WholePaper.guardedCentral_union_residual_prod
assert_no_sorry Erdos390.WholePaper.hasComplementProduct_of_guardedCentral_residual
assert_no_sorry Erdos390.WholePaper.isAdmissibleEndpoint_of_guardedCentral_residual
assert_no_sorry Erdos390.WholePaper.GuardedCentralAnchorCertificate.isAdmissibleEndpoint_of_residual
