import Erdos390.WholePaper.GuardedExactificationAlgebra
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for finite exactification algebra -/

#print axioms Erdos390.WholePaper.sum_integralSelection_eq_sum_mul
#print axioms Erdos390.WholePaper.selectedFactorSet_factorization
#print axioms Erdos390.WholePaper.selectedFactorSet_factorization_cast
#print axioms Erdos390.WholePaper.completeSignatureMultiplicity_selectedFactorSet
#print axioms Erdos390.WholePaper.integralSelection_filter_card_cast
#print axioms Erdos390.WholePaper.completeSignatureMultiplicity_selectedFactorSet_cast_eq
#print axioms Erdos390.WholePaper.chosenBankFactors_pairwiseDisjoint
#print axioms Erdos390.WholePaper.chosenBankFactors_prod_eq
#print axioms Erdos390.WholePaper.chosenBankFactors_factorization
#print axioms Erdos390.WholePaper.chosenBankFactors_factorization_sub_base
#print axioms Erdos390.WholePaper.completeSignatureMultiplicity_chosenBankFactors
#print axioms Erdos390.WholePaper.completeSignatureMultiplicity_bankState_invariant
#print axioms Erdos390.WholePaper.integralRoundingError_cast_eq
#print axioms Erdos390.WholePaper.roundingValuationError_eq_zero_of_complete_rows
#print axioms Erdos390.WholePaper.embeddedBankVector_subtype_neg_eq

assert_no_sorry Erdos390.WholePaper.sum_integralSelection_eq_sum_mul
assert_no_sorry Erdos390.WholePaper.selectedFactorSet_factorization
assert_no_sorry Erdos390.WholePaper.selectedFactorSet_factorization_cast
assert_no_sorry Erdos390.WholePaper.completeSignatureMultiplicity_selectedFactorSet
assert_no_sorry Erdos390.WholePaper.integralSelection_filter_card_cast
assert_no_sorry Erdos390.WholePaper.completeSignatureMultiplicity_selectedFactorSet_cast_eq
assert_no_sorry Erdos390.WholePaper.chosenBankFactors_pairwiseDisjoint
assert_no_sorry Erdos390.WholePaper.chosenBankFactors_prod_eq
assert_no_sorry Erdos390.WholePaper.chosenBankFactors_factorization
assert_no_sorry Erdos390.WholePaper.chosenBankFactors_factorization_sub_base
assert_no_sorry Erdos390.WholePaper.completeSignatureMultiplicity_chosenBankFactors
assert_no_sorry Erdos390.WholePaper.completeSignatureMultiplicity_bankState_invariant
assert_no_sorry Erdos390.WholePaper.integralRoundingError_cast_eq
assert_no_sorry Erdos390.WholePaper.roundingValuationError_eq_zero_of_complete_rows
assert_no_sorry Erdos390.WholePaper.embeddedBankVector_subtype_neg_eq
