import Erdos390.WholePaper.NaguraExplicitPsiBounds
import Mathlib.Util.AssertNoSorry

/-! Axiom and placeholder audit for the explicit Nagura `ψ` chain. -/

#print axioms Erdos390.WholePaper.log_factorial_le_stirling_elementary
#print axioms Erdos390.WholePaper.naguraChebyshevCombination_le_stirlingMajorant
#print axioms Erdos390.WholePaper.naguraMainCoefficient_lt_1_083
#print axioms Erdos390.WholePaper.naguraChebyshevCombination_lt_1_083_mul
#print axioms Erdos390.WholePaper.naguraWeightPrefix_nonneg
#print axioms Erdos390.WholePaper.first_sub_1806_le_nagura_weighted_sum
#print axioms Erdos390.WholePaper.psi_sub_psi_le_naguraChebyshevCombination
#print axioms Erdos390.WholePaper.psi_mul_1806_lt_1_086
#print axioms Erdos390.WholePaper.naguraLowerWeightPrefix_mem_unitInterval
#print axioms Erdos390.WholePaper.naguraLowerChebyshevCombination_le_psi
#print axioms Erdos390.WholePaper.naguraLowerMainCoefficient_gt_0_9209
#print axioms Erdos390.WholePaper.naguraLowerChebyshevCombination_gt_0_916_mul
#print axioms Erdos390.WholePaper.psi_mul_30_gt_0_916
#print axioms Erdos390.WholePaper.psi_gt_0_916_mul_sub_27_48
#print axioms Erdos390.WholePaper.psi_lt_1_086_mul_add_1961_316

assert_no_sorry Erdos390.WholePaper.log_factorial_le_stirling_elementary
assert_no_sorry Erdos390.WholePaper.naguraChebyshevCombination_le_stirlingMajorant
assert_no_sorry Erdos390.WholePaper.naguraMainCoefficient_lt_1_083
assert_no_sorry Erdos390.WholePaper.naguraChebyshevCombination_lt_1_083_mul
assert_no_sorry Erdos390.WholePaper.naguraWeightPrefix_nonneg
assert_no_sorry Erdos390.WholePaper.first_sub_1806_le_nagura_weighted_sum
assert_no_sorry Erdos390.WholePaper.psi_sub_psi_le_naguraChebyshevCombination
assert_no_sorry Erdos390.WholePaper.psi_mul_1806_lt_1_086
assert_no_sorry Erdos390.WholePaper.naguraLowerWeightPrefix_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.naguraLowerChebyshevCombination_le_psi
assert_no_sorry Erdos390.WholePaper.naguraLowerMainCoefficient_gt_0_9209
assert_no_sorry Erdos390.WholePaper.naguraLowerChebyshevCombination_gt_0_916_mul
assert_no_sorry Erdos390.WholePaper.psi_mul_30_gt_0_916
assert_no_sorry Erdos390.WholePaper.psi_gt_0_916_mul_sub_27_48
assert_no_sorry Erdos390.WholePaper.psi_lt_1_086_mul_add_1961_316
