import Erdos390.WholePaper.RoughSaiasFullyRealNaturalCells
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasFullyRealNaturalBuchstabCellRemainder_eq_continuous_add_fractional
#print axioms Erdos390.WholePaper.roughSaiasFullyRealNaturalBuchstabCellRemainder_eq_integral
#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_eq_selector_of_sq_le
#print axioms Erdos390.WholePaper.roughSaiasFullyRealNaturalBuchstabCellRemainder_eq_selectorRemainder
#print axioms Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_eq_naturalCellRemainders
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_naturalCells_sub_naturalTheta
#print axioms Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_abs_le_three_invLogSq_of_sq_le'
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_three_invLogSq_add_naturalThetaLedger

assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealNaturalBuchstabCellRemainder_eq_continuous_add_fractional
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealNaturalBuchstabCellRemainder_eq_integral
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_eq_selector_of_sq_le
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealNaturalBuchstabCellRemainder_eq_selectorRemainder
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_eq_naturalCellRemainders
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_naturalCells_sub_naturalTheta
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_abs_le_three_invLogSq_of_sq_le'
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_three_invLogSq_add_naturalThetaLedger
