import Erdos390.WholePaper.RoughSaiasFullyRealNormalForm
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.measurable_roughSaiasFullyRealFractionalWeight
#print axioms Erdos390.WholePaper.roughSaiasFullyRealFractionalWeight_mem_unitInterval
#print axioms Erdos390.WholePaper.roughSaiasFullyRealIntegrand_intervalIntegrable
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBaseFreeKernel_rpow_mul_jacobian
#print axioms Erdos390.WholePaper.roughSaiasFullyRealFractionalIntegral_eq_baseFree
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBaseFreeKernel_intervalIntegrable
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBaseFreeKernel_eq_zero_of_div_lt
#print axioms Erdos390.WholePaper.roughSaiasFullyReal_le_rpow_five
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBaseFreeIntegral_eq_realCap
#print axioms Erdos390.WholePaper.roughSaiasFullyRealG_eq_rho_sub_baseFree
#print axioms Erdos390.WholePaper.roughSaiasFullyRealG_eq_one_of_le_one
#print axioms Erdos390.WholePaper.roughSaiasFullyRealG_lipschitz_three
#print axioms Erdos390.WholePaper.roughSaiasFullyRealG_abs_le_sixteen
#print axioms Erdos390.WholePaper.roughSaiasFullyRealLambdaNormalForm_eq_floor_of_le_one
#print axioms Erdos390.WholePaper.roughSaiasFullyRealFractionalWeight_nat
#print axioms Erdos390.WholePaper.roughSaiasFullyRealG_nat
#print axioms Erdos390.WholePaper.roughSaiasFullyRealLambdaNormalForm_nat
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBaseFreeKernel_nat
#print axioms Erdos390.WholePaper.roughSaiasRealStieltjesFractionalCorrection_eq_fullyRealBaseFree_of_ne
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasFullyRealStieltjesFractionalCorrection
#print axioms Erdos390.WholePaper.integral_roughSaiasFullyRealStieltjesFractionalCorrection
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjes_eq_fullyRealNormalForm
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjes_eq_normalForm_via_fullyReal

assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasFullyRealFractionalWeight
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealFractionalWeight_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealIntegrand_intervalIntegrable
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBaseFreeKernel_rpow_mul_jacobian
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealFractionalIntegral_eq_baseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBaseFreeKernel_intervalIntegrable
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBaseFreeKernel_eq_zero_of_div_lt
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyReal_le_rpow_five
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBaseFreeIntegral_eq_realCap
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealG_eq_rho_sub_baseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealG_eq_one_of_le_one
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealG_lipschitz_three
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealG_abs_le_sixteen
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealLambdaNormalForm_eq_floor_of_le_one
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealFractionalWeight_nat
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealG_nat
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealLambdaNormalForm_nat
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBaseFreeKernel_nat
assert_no_sorry Erdos390.WholePaper.roughSaiasRealStieltjesFractionalCorrection_eq_fullyRealBaseFree_of_ne
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasFullyRealStieltjesFractionalCorrection
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasFullyRealStieltjesFractionalCorrection
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjes_eq_fullyRealNormalForm
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjes_eq_normalForm_via_fullyReal
