import Erdos390.WholePaper.RoughBalancedFriableResidualReduction
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughFriableCount_eq_main_add_residual
#print axioms Erdos390.WholePaper.roughFriableDickmanMain_zero
#print axioms Erdos390.WholePaper.roughFriableResidual_zero
#print axioms Erdos390.WholePaper.roughFriableResidual_eq_zero_of_le
#print axioms Erdos390.WholePaper.exists_uniform_roughFriableResidual_bound
#print axioms Erdos390.WholePaper.roughFriableResidual_reverseRecurrence
#print axioms Erdos390.WholePaper.roughFriableResidual_reverseRecurrence_all
#print axioms Erdos390.WholePaper.roughFriableResidual_difference_reverseRecurrence
#print axioms Erdos390.WholePaper.roughFriableResidual_difference_reverseRecurrence_all
#print axioms Erdos390.WholePaper.roughRho_abs_sub_le_abs_of_le_five
#print axioms Erdos390.WholePaper.roughBalancedFriableMain_abs_le
#print axioms Erdos390.WholePaper.roughFriableMain_abs_le_with_balanceError
#print axioms Erdos390.WholePaper.roughPhysicalFriableCombination_eq_main_add_residualTransition
#print axioms Erdos390.WholePaper.roughFriableResidual_localRegularity_initial
#print axioms Erdos390.WholePaper.exists_uniform_roughPhysicalFourTransition_reduction

assert_no_sorry Erdos390.WholePaper.roughFriableCount_eq_main_add_residual
assert_no_sorry Erdos390.WholePaper.roughFriableDickmanMain_zero
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_zero
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_eq_zero_of_le
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughFriableResidual_bound
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_reverseRecurrence
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_reverseRecurrence_all
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_difference_reverseRecurrence
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_difference_reverseRecurrence_all
assert_no_sorry Erdos390.WholePaper.roughRho_abs_sub_le_abs_of_le_five
assert_no_sorry Erdos390.WholePaper.roughBalancedFriableMain_abs_le
assert_no_sorry Erdos390.WholePaper.roughFriableMain_abs_le_with_balanceError
assert_no_sorry Erdos390.WholePaper.roughPhysicalFriableCombination_eq_main_add_residualTransition
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_localRegularity_initial
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughPhysicalFourTransition_reduction
