import Erdos390.WholePaper.RoughSaiasFunctionalBuchstab
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_div
#print axioms Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_buchstabProfile
#print axioms Erdos390.WholePaper.roughSaias_log_div_t_ratio_le
#print axioms Erdos390.WholePaper.measurable_uncurry_roughSaiasBuchstabDensityKernel
#print axioms Erdos390.WholePaper.exists_roughSaiasZeroExtendedRho_abs_bound_six
#print axioms Erdos390.WholePaper.roughSaiasFloorDensity_mem_unitInterval
#print axioms Erdos390.WholePaper.roughSaias_profile_coordinate_le_six
#print axioms Erdos390.WholePaper.roughSaias_inner_profile_coordinate_le_six
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasProfile_mul_floorDensity_six
#print axioms Erdos390.WholePaper.roughSaiasBuchstabDensityKernel_abs_le
#print axioms Erdos390.WholePaper.integrable_roughSaiasBuchstabDensityKernel
#print axioms Erdos390.WholePaper.roughSaiasBuchstabDensityFubini_of_compact
#print axioms Erdos390.WholePaper.roughSaiasStieltjesAtomPart_buchstab
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDensityPart_buchstab
#print axioms Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_buchstab
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_buchstab
#print axioms Erdos390.WholePaper.intervalIntegrable_roughSaiasLambdaStieltjesWithCutoff_buchstab
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDensityPart_buchstab_unconditional
#print axioms Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_buchstab_unconditional
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_buchstab_unconditional

assert_no_sorry Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_div
assert_no_sorry Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_buchstabProfile
assert_no_sorry Erdos390.WholePaper.roughSaias_log_div_t_ratio_le
assert_no_sorry Erdos390.WholePaper.measurable_uncurry_roughSaiasBuchstabDensityKernel
assert_no_sorry Erdos390.WholePaper.exists_roughSaiasZeroExtendedRho_abs_bound_six
assert_no_sorry Erdos390.WholePaper.roughSaiasFloorDensity_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.roughSaias_profile_coordinate_le_six
assert_no_sorry Erdos390.WholePaper.roughSaias_inner_profile_coordinate_le_six
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasProfile_mul_floorDensity_six
assert_no_sorry Erdos390.WholePaper.roughSaiasBuchstabDensityKernel_abs_le
assert_no_sorry Erdos390.WholePaper.integrable_roughSaiasBuchstabDensityKernel
assert_no_sorry Erdos390.WholePaper.roughSaiasBuchstabDensityFubini_of_compact
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesAtomPart_buchstab
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDensityPart_buchstab
assert_no_sorry Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_buchstab
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_buchstab
assert_no_sorry Erdos390.WholePaper.intervalIntegrable_roughSaiasLambdaStieltjesWithCutoff_buchstab
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDensityPart_buchstab_unconditional
assert_no_sorry Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_buchstab_unconditional
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_buchstab_unconditional
