import Erdos390.WholePaper.RoughSaiasEndpointApproximation
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasDickmanEndpointConstant_pos
#print axioms Erdos390.WholePaper.roughSaiasDickmanEndpoint_bound
#print axioms Erdos390.WholePaper.roughSaiasEndpointError_eq_friableCount_sub_lambdaNormalForm
#print axioms Erdos390.WholePaper.roughSaiasInvLogEndpointApproximationUpToFive
#print axioms Erdos390.WholePaper.roughSaiasLambdaNormalForm_endpoint_invLog_bound
#print axioms Erdos390.WholePaper.roughSaiasEndpointError_reverseRecurrence
#print axioms Erdos390.WholePaper.roughSaiasEndpointError_reverseRecurrence_top
#print axioms Erdos390.WholePaper.roughSaiasPrimeInvLogContraction_bound
#print axioms Erdos390.WholePaper.roughSaiasPrimeInvLogSqSum_contraction
#print axioms Erdos390.WholePaper.roughSaiasInvLogSqEndpointApproximationUpToFive_of_defect
#print axioms Erdos390.WholePaper.roughSaiasLambdaNormalForm_endpoint_invLogSq_bound_of_defect

assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanEndpointConstant_pos
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanEndpoint_bound
assert_no_sorry Erdos390.WholePaper.roughSaiasEndpointError_eq_friableCount_sub_lambdaNormalForm
assert_no_sorry Erdos390.WholePaper.roughSaiasInvLogEndpointApproximationUpToFive
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaNormalForm_endpoint_invLog_bound
assert_no_sorry Erdos390.WholePaper.roughSaiasEndpointError_reverseRecurrence
assert_no_sorry Erdos390.WholePaper.roughSaiasEndpointError_reverseRecurrence_top
assert_no_sorry Erdos390.WholePaper.roughSaiasPrimeInvLogContraction_bound
assert_no_sorry Erdos390.WholePaper.roughSaiasPrimeInvLogSqSum_contraction
assert_no_sorry Erdos390.WholePaper.roughSaiasInvLogSqEndpointApproximationUpToFive_of_defect
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaNormalForm_endpoint_invLogSq_bound_of_defect
