import Erdos390.WholePaper.RoughSaiasDickmanThetaFourth
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasDickmanThetaTransfer_abs_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasDickmanThetaTransfer_abs_le_invLogSq_fourthPower
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_eq_dickman_add_residual
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_dickman_add_residual
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_closedCore_add_residual

assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanThetaTransfer_abs_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanThetaTransfer_abs_le_invLogSq_fourthPower
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_eq_dickman_add_residual
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_dickman_add_residual
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_closedCore_add_residual
