import Erdos390.WholePaper.RoughSaiasSelectorLedgerBound
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientDrop_nonneg
#print axioms Erdos390.WholePaper.sum_roughSaiasNaturalQuotientDrop
#print axioms Erdos390.WholePaper.sum_mul_roughSaiasNaturalQuotientDrop
#print axioms Erdos390.WholePaper.sum_mul_roughSaiasNaturalQuotientDrop_le
#print axioms Erdos390.WholePaper.roughSaias_invLog_succ_sub_nonneg
#print axioms Erdos390.WholePaper.roughSaias_invLog_succ_sub_le
#print axioms Erdos390.WholePaper.roughSaiasSelectorCellLedger_le_drop_add_invSq
#print axioms Erdos390.WholePaper.sum_roughSaiasSelectorCellLedger_le
#print axioms Erdos390.WholePaper.abs_sum_roughSaiasFullyRealBuchstabCellRemainder_le_explicit
#print axioms Erdos390.WholePaper.abs_sum_roughSaiasFullyRealBuchstabCellRemainder_le_three_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasIntegerAbelConsistencyDefect_abs_le_three_invLogSq_of_sq_le

assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientDrop_nonneg
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasNaturalQuotientDrop
assert_no_sorry Erdos390.WholePaper.sum_mul_roughSaiasNaturalQuotientDrop
assert_no_sorry Erdos390.WholePaper.sum_mul_roughSaiasNaturalQuotientDrop_le
assert_no_sorry Erdos390.WholePaper.roughSaias_invLog_succ_sub_nonneg
assert_no_sorry Erdos390.WholePaper.roughSaias_invLog_succ_sub_le
assert_no_sorry Erdos390.WholePaper.roughSaiasSelectorCellLedger_le_drop_add_invSq
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasSelectorCellLedger_le
assert_no_sorry Erdos390.WholePaper.abs_sum_roughSaiasFullyRealBuchstabCellRemainder_le_explicit
assert_no_sorry Erdos390.WholePaper.abs_sum_roughSaiasFullyRealBuchstabCellRemainder_le_three_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasIntegerAbelConsistencyDefect_abs_le_three_invLogSq_of_sq_le
