import Erdos390.WholePaper.RoughSaiasWeightedTransition
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughFriableResidual_difference_abs_le_of_saiasEndpointApproximation
#print axioms Erdos390.WholePaper.roughPhysicalResidualTransition_abs_le_of_saiasEndpointApproximation
#print axioms Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_of_saiasEndpointApproximation
#print axioms Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_of_saiasPaperScale
#print axioms Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_two_mul_of_saiasPaperScale

assert_no_sorry Erdos390.WholePaper.roughFriableResidual_difference_abs_le_of_saiasEndpointApproximation
assert_no_sorry Erdos390.WholePaper.roughPhysicalResidualTransition_abs_le_of_saiasEndpointApproximation
assert_no_sorry Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_of_saiasEndpointApproximation
assert_no_sorry Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_of_saiasPaperScale
assert_no_sorry Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_two_mul_of_saiasPaperScale
