import Erdos390.WholePaper.RoughSaiasSharpCorrectionTarget
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasFullyRealCorrectionIntegrand
#print axioms Erdos390.WholePaper.roughSaiasSharpCorrectionObstruction
#print axioms Erdos390.WholePaper.roughSaiasDickmanContinuousPrimeDiscrepancy
#print axioms Erdos390.WholePaper.roughSaiasLocalNaturalPrimeCellDiscrepancy
#print axioms Erdos390.WholePaper.roughSaiasDualSpreadLocalNaturalPrimeCellDiscrepancy
#print axioms Erdos390.WholePaper.roughSaiasDualSpreadFullyRealNaturalCellRemainder
#print axioms Erdos390.WholePaper.roughSaiasFullyRealCorrectionIntegrand_eq
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_dickman_add_sharpCorrection
#print axioms Erdos390.WholePaper.roughSaiasDickmanContinuousPrimeDiscrepancy_eq_riemann_sub_theta
#print axioms Erdos390.WholePaper.roughSaiasSharpCorrectionObstruction_eq_naturalCells_sub_riemann_sub_residual
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_naturalCells_sub_localPrimeErrorResidual
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_sum_localNaturalPrimeCellDiscrepancy
#print axioms Erdos390.WholePaper.sum_roughSaiasLocalNaturalPrimeCellDiscrepancy_split
#print axioms Erdos390.WholePaper.sum_roughSaiasDualSpreadLocalNaturalPrimeCellDiscrepancy_eq
#print axioms Erdos390.WholePaper.sum_roughSaiasLocalNaturalPrimeCellDiscrepancy_eq_dualInvolution
#print axioms Erdos390.WholePaper.sum_roughSaiasDualSpreadFullyRealNaturalCellRemainder_eq
#print axioms Erdos390.WholePaper.sum_roughSaiasFullyRealNaturalCells_eq_dualInvolution
#print axioms Erdos390.WholePaper.sum_roughSaiasLocalNaturalPrimeCellDiscrepancy_eq_integral_sub_primeTheta
#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_succ_sub_abs_le_selectorCellLedger
#print axioms Erdos390.WholePaper.roughSaiasNatHyperbolaCoefficient_sub_succ_eq_selectorCellLedger
#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_succ_sub_abs_le_hyperbolaComponents
#print axioms Erdos390.WholePaper.sum_roughSaiasSelectorCellLedger_mul_fourth_le
#print axioms Erdos390.WholePaper.sum_roughSaiasNaturalThetaWeightVariation_mul_fourth_le_hyperbola
#print axioms Erdos390.WholePaper.sum_roughSaiasNaturalThetaWeightVariation_mul_fourth_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaPNTVariationLedger_fourth_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaPNTVariationLedger_fourth_le_upper_explicit
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaPNTVariationLedger_fourth_le_upper_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_upper_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_lowerNaturalCells_add_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_dualLowerNaturalCells_add_invLogSq
#print axioms Erdos390.WholePaper.abs_sum_roughSaiasLocalNaturalPrimeCellDiscrepancy_upper_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_lowerLocal_add_upperInvLogSq
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_canonicalLowerLocal_add_upperInvLogSq
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_upperInvLogSq_of_sqrt_succ_le
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_dualLower_add_upperInvLogSq
#print axioms Erdos390.WholePaper.roughSaiasDickmanContinuousPrimeDiscrepancy_abs_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_closed_add_sharpCorrection
#print axioms Erdos390.WholePaper.abs_sum_roughSaiasFullyRealNaturalCells_lower_le_forty_invLogSq
#print axioms Erdos390.WholePaper.abs_sum_roughSaiasDualSpreadFullyRealNaturalCellRemainder_le_forty_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasSharpDefectConstant
#print axioms Erdos390.WholePaper.roughSaiasSharpDefectCutoff
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_sharp_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasSharpReverseNormalFormDefectInvLogSqBound
#print axioms Erdos390.WholePaper.roughSaiasSharpEndpointApproximationUpToFive

assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealCorrectionIntegrand
assert_no_sorry Erdos390.WholePaper.roughSaiasSharpCorrectionObstruction
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanContinuousPrimeDiscrepancy
assert_no_sorry Erdos390.WholePaper.roughSaiasLocalNaturalPrimeCellDiscrepancy
assert_no_sorry Erdos390.WholePaper.roughSaiasDualSpreadLocalNaturalPrimeCellDiscrepancy
assert_no_sorry Erdos390.WholePaper.roughSaiasDualSpreadFullyRealNaturalCellRemainder
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealCorrectionIntegrand_eq
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_dickman_add_sharpCorrection
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanContinuousPrimeDiscrepancy_eq_riemann_sub_theta
assert_no_sorry Erdos390.WholePaper.roughSaiasSharpCorrectionObstruction_eq_naturalCells_sub_riemann_sub_residual
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_naturalCells_sub_localPrimeErrorResidual
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_sum_localNaturalPrimeCellDiscrepancy
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasLocalNaturalPrimeCellDiscrepancy_split
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasDualSpreadLocalNaturalPrimeCellDiscrepancy_eq
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasLocalNaturalPrimeCellDiscrepancy_eq_dualInvolution
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasDualSpreadFullyRealNaturalCellRemainder_eq
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasFullyRealNaturalCells_eq_dualInvolution
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasLocalNaturalPrimeCellDiscrepancy_eq_integral_sub_primeTheta
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_succ_sub_abs_le_selectorCellLedger
assert_no_sorry Erdos390.WholePaper.roughSaiasNatHyperbolaCoefficient_sub_succ_eq_selectorCellLedger
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_succ_sub_abs_le_hyperbolaComponents
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasSelectorCellLedger_mul_fourth_le
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasNaturalThetaWeightVariation_mul_fourth_le_hyperbola
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasNaturalThetaWeightVariation_mul_fourth_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaPNTVariationLedger_fourth_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaPNTVariationLedger_fourth_le_upper_explicit
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaPNTVariationLedger_fourth_le_upper_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_upper_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_lowerNaturalCells_add_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_dualLowerNaturalCells_add_invLogSq
assert_no_sorry Erdos390.WholePaper.abs_sum_roughSaiasLocalNaturalPrimeCellDiscrepancy_upper_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_lowerLocal_add_upperInvLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_canonicalLowerLocal_add_upperInvLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_upperInvLogSq_of_sqrt_succ_le
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_dualLower_add_upperInvLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanContinuousPrimeDiscrepancy_abs_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_closed_add_sharpCorrection
assert_no_sorry Erdos390.WholePaper.abs_sum_roughSaiasFullyRealNaturalCells_lower_le_forty_invLogSq
assert_no_sorry Erdos390.WholePaper.abs_sum_roughSaiasDualSpreadFullyRealNaturalCellRemainder_le_forty_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasSharpDefectConstant
assert_no_sorry Erdos390.WholePaper.roughSaiasSharpDefectCutoff
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_sharp_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasSharpReverseNormalFormDefectInvLogSqBound
assert_no_sorry Erdos390.WholePaper.roughSaiasSharpEndpointApproximationUpToFive
