import Erdos390.WholePaper.RoughSaiasSharpFixedHeadIntervalShift
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughFriableContinuousFixedDivisorDefect
#print axioms Erdos390.WholePaper.roughFriableMain_quotientFloor_stability
#print axioms Erdos390.WholePaper.roughFriableContinuousFixedDivisorDefect_sub_abs_le
#print axioms Erdos390.WholePaper.roughFriableDickmanMain_interval_fixedDivisorShift_abs_le
#print axioms Erdos390.WholePaper.roughSaiasIntervalFixedDivisorShiftBudget
#print axioms Erdos390.WholePaper.roughFriableInterval_fixedDivisorShift_abs_le_of_saiasEndpointApproximation
#print axioms Erdos390.WholePaper.roughSaiasSharpIntervalFixedDivisorBudget
#print axioms Erdos390.WholePaper.roughSaiasIntervalFixedDivisorShiftBudget_sharp_le
#print axioms Erdos390.WholePaper.roughFriableInterval_fixedDivisorShift_abs_le_sharp
#print axioms Erdos390.WholePaper.roughSmoothPhysicalBlock_fixedDivisorShift_abs_le_sharp
#print axioms Erdos390.WholePaper.roughSmoothPhysicalBlock_abs_le_rightEndpoint
#print axioms Erdos390.WholePaper.roughSmoothPhysicalBlock_fixedDivisorShift_abs_le_small
#print axioms Erdos390.WholePaper.roughCanonicalSharpFixedHeadShiftBudget
#print axioms Erdos390.WholePaper.roughCanonicalFixedHeadShiftLedger_le_sharpIntervalBudget
#print axioms Erdos390.WholePaper.roughCanonicalSharpFixedHeadShiftBudgetAllRows
#print axioms Erdos390.WholePaper.roughCanonicalFixedHeadShiftLedger_le_sharpIntervalBudget_allRows
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_three_mul_sharpAllowance

assert_no_sorry Erdos390.WholePaper.roughFriableContinuousFixedDivisorDefect
assert_no_sorry Erdos390.WholePaper.roughFriableMain_quotientFloor_stability
assert_no_sorry Erdos390.WholePaper.roughFriableContinuousFixedDivisorDefect_sub_abs_le
assert_no_sorry Erdos390.WholePaper.roughFriableDickmanMain_interval_fixedDivisorShift_abs_le
assert_no_sorry Erdos390.WholePaper.roughSaiasIntervalFixedDivisorShiftBudget
assert_no_sorry Erdos390.WholePaper.roughFriableInterval_fixedDivisorShift_abs_le_of_saiasEndpointApproximation
assert_no_sorry Erdos390.WholePaper.roughSaiasSharpIntervalFixedDivisorBudget
assert_no_sorry Erdos390.WholePaper.roughSaiasIntervalFixedDivisorShiftBudget_sharp_le
assert_no_sorry Erdos390.WholePaper.roughFriableInterval_fixedDivisorShift_abs_le_sharp
assert_no_sorry Erdos390.WholePaper.roughSmoothPhysicalBlock_fixedDivisorShift_abs_le_sharp
assert_no_sorry Erdos390.WholePaper.roughSmoothPhysicalBlock_abs_le_rightEndpoint
assert_no_sorry Erdos390.WholePaper.roughSmoothPhysicalBlock_fixedDivisorShift_abs_le_small
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpFixedHeadShiftBudget
assert_no_sorry Erdos390.WholePaper.roughCanonicalFixedHeadShiftLedger_le_sharpIntervalBudget
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpFixedHeadShiftBudgetAllRows
assert_no_sorry Erdos390.WholePaper.roughCanonicalFixedHeadShiftLedger_le_sharpIntervalBudget_allRows
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_three_mul_sharpAllowance
