import Erdos390.WholePaper.RoughSaiasQuotientBlocks
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasQuotientBlock
#print axioms Erdos390.WholePaper.roughSaiasQuotientValues
#print axioms Erdos390.WholePaper.natDiv_eq_iff_mul_bounds
#print axioms Erdos390.WholePaper.natDiv_eq_iff_mem_hyperbolaIoc
#print axioms Erdos390.WholePaper.mem_roughSaiasQuotientBlock
#print axioms Erdos390.WholePaper.natDiv_eq_of_between
#print axioms Erdos390.WholePaper.roughSaiasQuotientBlock_eq_hyperbola_filter
#print axioms Erdos390.WholePaper.roughSaiasQuotientBlock_subset_hyperbolaIoc
#print axioms Erdos390.WholePaper.roughSaiasQuotientBlock_card_le
#print axioms Erdos390.WholePaper.roughSaiasQuotientValues_subset_Iic
#print axioms Erdos390.WholePaper.roughSaiasQuotientValues_card_le
#print axioms Erdos390.WholePaper.roughSaiasDualQuotientInterval
#print axioms Erdos390.WholePaper.mem_roughSaiasDualQuotientInterval
#print axioms Erdos390.WholePaper.card_roughSaiasDualQuotientInterval
#print axioms Erdos390.WholePaper.natDiv_succ_lt_of_le_sqrt
#print axioms Erdos390.WholePaper.roughSaiasDualQuotientInterval_nonempty_of_le_sqrt
#print axioms Erdos390.WholePaper.le_of_mem_roughSaiasDualQuotientInterval_of_le_sqrt
#print axioms Erdos390.WholePaper.mem_div_Ioc_iff_exists_mem_roughSaiasDualQuotientInterval
#print axioms Erdos390.WholePaper.natDiv_le_self_of_mem_div_Ioc_of_le_sqrt_succ
#print axioms Erdos390.WholePaper.sum_Ico_sum_roughSaiasDualQuotientInterval
#print axioms Erdos390.WholePaper.sum_Ico_sum_roughSaiasDualQuotientInterval_involution
#print axioms Erdos390.WholePaper.sum_Ioc_eq_sum_roughSaiasQuotientBlocks
#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_diff_eq_on_quotientBlock
#print axioms Erdos390.WholePaper.roughSaiasStableQuotientEdges
#print axioms Erdos390.WholePaper.roughSaiasJumpQuotientEdges
#print axioms Erdos390.WholePaper.roughSaiasStableQuotientValues
#print axioms Erdos390.WholePaper.roughSaiasStableQuotientEdgeBlock
#print axioms Erdos390.WholePaper.mem_roughSaiasStableQuotientEdges
#print axioms Erdos390.WholePaper.mem_roughSaiasJumpQuotientEdges
#print axioms Erdos390.WholePaper.mem_roughSaiasStableQuotientEdgeBlock
#print axioms Erdos390.WholePaper.mem_roughSaiasStableQuotientEdgeBlock_iff_pair_mem
#print axioms Erdos390.WholePaper.sum_Ioc_eq_sum_stableQuotientEdges_add_jumpEdges
#print axioms Erdos390.WholePaper.roughSaiasStableQuotientEdges_eq_empty_of_le_sqrt_succ
#print axioms Erdos390.WholePaper.roughSaiasJumpQuotientEdges_eq_Ioc_of_le_sqrt_succ
#print axioms Erdos390.WholePaper.sum_roughSaiasStableQuotientEdges_eq_sum_edgeBlocks
#print axioms Erdos390.WholePaper.sum_stableNaturalThetaWeight_diff_mul_eq_baseFree_edgeBlocks
#print axioms Erdos390.WholePaper.sum_Ioc_naturalThetaWeight_diff_mul_eq_edgeBlocks_add_jumps
#print axioms Erdos390.WholePaper.sum_jumpQuotientEdges_succ_sub_eq_endpoints_sub_stable
#print axioms Erdos390.WholePaper.sum_jumpQuotientEdges_weighted_succ_sub_eq_endpoints_sub_residual_sub_stable
#print axioms Erdos390.WholePaper.roughSaiasPrimeLogError_succ_sub
#print axioms Erdos390.WholePaper.sum_jumpNaturalThetaWeight_diff_mul_primeLogError_eq_endpoints_sub_residual_sub_stable
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_eq_localPrimeErrorResidual

assert_no_sorry Erdos390.WholePaper.roughSaiasQuotientBlock
assert_no_sorry Erdos390.WholePaper.roughSaiasQuotientValues
assert_no_sorry Erdos390.WholePaper.natDiv_eq_iff_mul_bounds
assert_no_sorry Erdos390.WholePaper.natDiv_eq_iff_mem_hyperbolaIoc
assert_no_sorry Erdos390.WholePaper.mem_roughSaiasQuotientBlock
assert_no_sorry Erdos390.WholePaper.natDiv_eq_of_between
assert_no_sorry Erdos390.WholePaper.roughSaiasQuotientBlock_eq_hyperbola_filter
assert_no_sorry Erdos390.WholePaper.roughSaiasQuotientBlock_subset_hyperbolaIoc
assert_no_sorry Erdos390.WholePaper.roughSaiasQuotientBlock_card_le
assert_no_sorry Erdos390.WholePaper.roughSaiasQuotientValues_subset_Iic
assert_no_sorry Erdos390.WholePaper.roughSaiasQuotientValues_card_le
assert_no_sorry Erdos390.WholePaper.roughSaiasDualQuotientInterval
assert_no_sorry Erdos390.WholePaper.mem_roughSaiasDualQuotientInterval
assert_no_sorry Erdos390.WholePaper.card_roughSaiasDualQuotientInterval
assert_no_sorry Erdos390.WholePaper.natDiv_succ_lt_of_le_sqrt
assert_no_sorry Erdos390.WholePaper.roughSaiasDualQuotientInterval_nonempty_of_le_sqrt
assert_no_sorry Erdos390.WholePaper.le_of_mem_roughSaiasDualQuotientInterval_of_le_sqrt
assert_no_sorry Erdos390.WholePaper.mem_div_Ioc_iff_exists_mem_roughSaiasDualQuotientInterval
assert_no_sorry Erdos390.WholePaper.natDiv_le_self_of_mem_div_Ioc_of_le_sqrt_succ
assert_no_sorry Erdos390.WholePaper.sum_Ico_sum_roughSaiasDualQuotientInterval
assert_no_sorry Erdos390.WholePaper.sum_Ico_sum_roughSaiasDualQuotientInterval_involution
assert_no_sorry Erdos390.WholePaper.sum_Ioc_eq_sum_roughSaiasQuotientBlocks
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_diff_eq_on_quotientBlock
assert_no_sorry Erdos390.WholePaper.roughSaiasStableQuotientEdges
assert_no_sorry Erdos390.WholePaper.roughSaiasJumpQuotientEdges
assert_no_sorry Erdos390.WholePaper.roughSaiasStableQuotientValues
assert_no_sorry Erdos390.WholePaper.roughSaiasStableQuotientEdgeBlock
assert_no_sorry Erdos390.WholePaper.mem_roughSaiasStableQuotientEdges
assert_no_sorry Erdos390.WholePaper.mem_roughSaiasJumpQuotientEdges
assert_no_sorry Erdos390.WholePaper.mem_roughSaiasStableQuotientEdgeBlock
assert_no_sorry Erdos390.WholePaper.mem_roughSaiasStableQuotientEdgeBlock_iff_pair_mem
assert_no_sorry Erdos390.WholePaper.sum_Ioc_eq_sum_stableQuotientEdges_add_jumpEdges
assert_no_sorry Erdos390.WholePaper.roughSaiasStableQuotientEdges_eq_empty_of_le_sqrt_succ
assert_no_sorry Erdos390.WholePaper.roughSaiasJumpQuotientEdges_eq_Ioc_of_le_sqrt_succ
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasStableQuotientEdges_eq_sum_edgeBlocks
assert_no_sorry Erdos390.WholePaper.sum_stableNaturalThetaWeight_diff_mul_eq_baseFree_edgeBlocks
assert_no_sorry Erdos390.WholePaper.sum_Ioc_naturalThetaWeight_diff_mul_eq_edgeBlocks_add_jumps
assert_no_sorry Erdos390.WholePaper.sum_jumpQuotientEdges_succ_sub_eq_endpoints_sub_stable
assert_no_sorry Erdos390.WholePaper.sum_jumpQuotientEdges_weighted_succ_sub_eq_endpoints_sub_residual_sub_stable
assert_no_sorry Erdos390.WholePaper.roughSaiasPrimeLogError_succ_sub
assert_no_sorry Erdos390.WholePaper.sum_jumpNaturalThetaWeight_diff_mul_primeLogError_eq_endpoints_sub_residual_sub_stable
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_eq_localPrimeErrorResidual
