import Erdos390.WholePaper.RoughSaiasUnconditionalDownstream
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughFriableResidual_difference_abs_le_of_saiasEndpointApproximation_unconditional
#print axioms Erdos390.WholePaper.roughPhysicalResidualTransition_abs_le_of_saiasEndpointApproximation_unconditional
#print axioms Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_of_saiasEndpointApproximation_unconditional
#print axioms Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_of_saiasPaperScale_unconditional
#print axioms Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_two_mul_of_saiasPaperScale_unconditional
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_saiasPaperScale_unconditional
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_literalSaiasPaperScale_unconditional
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_literalSaiasAndHeadLedger_unconditional
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_three_mul_paperAllowance_unconditional
#print axioms Erdos390.WholePaper.bankPaper_activeRoughRowQuota_and_isAdmissibleEndpoint_of_canonicalSaiasHandoff_unconditional

assert_no_sorry Erdos390.WholePaper.roughFriableResidual_difference_abs_le_of_saiasEndpointApproximation_unconditional
assert_no_sorry Erdos390.WholePaper.roughPhysicalResidualTransition_abs_le_of_saiasEndpointApproximation_unconditional
assert_no_sorry Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_of_saiasEndpointApproximation_unconditional
assert_no_sorry Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_of_saiasPaperScale_unconditional
assert_no_sorry Erdos390.WholePaper.roughPhysicalFriableCombination_abs_le_two_mul_of_saiasPaperScale_unconditional
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_saiasPaperScale_unconditional
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_literalSaiasPaperScale_unconditional
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_literalSaiasAndHeadLedger_unconditional
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_three_mul_paperAllowance_unconditional
assert_no_sorry Erdos390.WholePaper.bankPaper_activeRoughRowQuota_and_isAdmissibleEndpoint_of_canonicalSaiasHandoff_unconditional
