import Erdos390.WholePaper.RoughSaiasNormalization
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_of_lt_one
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_of_one_le
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_one
#print axioms Erdos390.WholePaper.measurable_roughSaiasDickmanDerivative
#print axioms Erdos390.WholePaper.continuous_roughSaiasBaseRpow
#print axioms Erdos390.WholePaper.measurable_roughSaiasFractionalWeight
#print axioms Erdos390.WholePaper.roughSaiasFractionalWeight_mem_unitInterval
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_abs_le_one
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_translate_intervalIntegrable
#print axioms Erdos390.WholePaper.roughSaiasIntegrand_intervalIntegrable
#print axioms Erdos390.WholePaper.roughSaiasG_eq_moving
#print axioms Erdos390.WholePaper.roughSaiasG_eq_one_of_le_one
#print axioms Erdos390.WholePaper.roughSaiasLambdaNormalForm_nat
#print axioms Erdos390.WholePaper.roughSaiasLambdaNormalForm_eq_floor
#print axioms Erdos390.WholePaper.roughSaiasLambdaNormalForm_eq_friableCount_initial
#print axioms Erdos390.WholePaper.roughRho_antitoneOn_zero_five
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_antitoneOn_left
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_monotoneOn_right
#print axioms Erdos390.WholePaper.eVariationOn_neg_real
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_eVariationOn_le_two
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_boundedVariationOn
#print axioms Erdos390.WholePaper.roughSaiasDickmanDerivative_translation_le_two
#print axioms Erdos390.WholePaper.roughSaiasG_lipschitz_three
#print axioms Erdos390.WholePaper.roughSaiasGMoving_lipschitz_three
#print axioms Erdos390.WholePaper.roughSaiasFractionalWeight_le_rpow_neg
#print axioms Erdos390.WholePaper.roughSaias_integral_rpow_neg
#print axioms Erdos390.WholePaper.roughSaias_integral_rpow_neg_le_inv_log
#print axioms Erdos390.WholePaper.roughSaiasG_sub_rho_abs_le_inv_log
#print axioms Erdos390.WholePaper.roughSaiasG_sub_rho_lipschitz_four
#print axioms Erdos390.WholePaper.roughSaiasNaturalMain_eq_lambdaNormalForm
#print axioms Erdos390.WholePaper.roughSaiasEndpointError_initial
#print axioms Erdos390.WholePaper.roughFriableResidual_eq_saiasError_add_correction
#print axioms Erdos390.WholePaper.roughSaiasDickmanCorrection_difference_abs_le
#print axioms Erdos390.WholePaper.roughFriableResidual_difference_eq_saias
#print axioms Erdos390.WholePaper.roughFriablePrimeTransitionLedger_eq_saias
#print axioms Erdos390.WholePaper.roughFriablePrimeTransitionLedger_le_of_saiasEndpointApproximation

assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_of_lt_one
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_of_one_le
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_one
assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasDickmanDerivative
assert_no_sorry Erdos390.WholePaper.continuous_roughSaiasBaseRpow
assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasFractionalWeight
assert_no_sorry Erdos390.WholePaper.roughSaiasFractionalWeight_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_abs_le_one
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_translate_intervalIntegrable
assert_no_sorry Erdos390.WholePaper.roughSaiasIntegrand_intervalIntegrable
assert_no_sorry Erdos390.WholePaper.roughSaiasG_eq_moving
assert_no_sorry Erdos390.WholePaper.roughSaiasG_eq_one_of_le_one
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaNormalForm_nat
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaNormalForm_eq_floor
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaNormalForm_eq_friableCount_initial
assert_no_sorry Erdos390.WholePaper.roughRho_antitoneOn_zero_five
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_antitoneOn_left
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_monotoneOn_right
assert_no_sorry Erdos390.WholePaper.eVariationOn_neg_real
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_eVariationOn_le_two
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_boundedVariationOn
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanDerivative_translation_le_two
assert_no_sorry Erdos390.WholePaper.roughSaiasG_lipschitz_three
assert_no_sorry Erdos390.WholePaper.roughSaiasGMoving_lipschitz_three
assert_no_sorry Erdos390.WholePaper.roughSaiasFractionalWeight_le_rpow_neg
assert_no_sorry Erdos390.WholePaper.roughSaias_integral_rpow_neg
assert_no_sorry Erdos390.WholePaper.roughSaias_integral_rpow_neg_le_inv_log
assert_no_sorry Erdos390.WholePaper.roughSaiasG_sub_rho_abs_le_inv_log
assert_no_sorry Erdos390.WholePaper.roughSaiasG_sub_rho_lipschitz_four
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalMain_eq_lambdaNormalForm
assert_no_sorry Erdos390.WholePaper.roughSaiasEndpointError_initial
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_eq_saiasError_add_correction
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanCorrection_difference_abs_le
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_difference_eq_saias
assert_no_sorry Erdos390.WholePaper.roughFriablePrimeTransitionLedger_eq_saias
assert_no_sorry Erdos390.WholePaper.roughFriablePrimeTransitionLedger_le_of_saiasEndpointApproximation
