import Erdos390.WholePaper.RoughSaiasRiemannAbsorption
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.exists_roughSaiasRiemannAbsorptionCutoff
#print axioms Erdos390.WholePaper.roughSaiasRiemannAbsorptionCutoff
#print axioms Erdos390.WholePaper.roughSaiasRiemannAbsorptionCutoff_spec
#print axioms Erdos390.WholePaper.roughSaiasDickmanRiemannEnvelope_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasDickmanBuchstabBlockRemainder_abs_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_closed_add_obstruction

assert_no_sorry Erdos390.WholePaper.exists_roughSaiasRiemannAbsorptionCutoff
assert_no_sorry Erdos390.WholePaper.roughSaiasRiemannAbsorptionCutoff
assert_no_sorry Erdos390.WholePaper.roughSaiasRiemannAbsorptionCutoff_spec
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanRiemannEnvelope_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanBuchstabBlockRemainder_abs_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_closed_add_obstruction
