import Erdos390.WholePaper.RoughSaiasSignedFractionalAbel
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasRealQuotient_sub_fract_eq_natQuotient
#print axioms Erdos390.WholePaper.roughSaiasSignedPrimeFloorCorrection_eq_fractional
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_continuous_add_signedFloor
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_continuous_add_fractional
#print axioms Erdos390.WholePaper.roughSaiasPrimeThetaWeightedInterval_eq_continuousSum
#print axioms Erdos390.WholePaper.roughSaiasReverseContinuousNormalFormDefect_eq_abel_sub_theta
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_signedAbelCenter_sub_theta
#print axioms Erdos390.WholePaper.roughSaiasThetaErrorTransfer_eq_finiteAbel
#print axioms Erdos390.WholePaper.roughSaiasNormalFormThetaWeight_eq_natural_add_fractional
#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_diff_eq_paired
#print axioms Erdos390.WholePaper.roughSaiasPrimeThetaWeightedInterval_eq_naturalSum
#print axioms Erdos390.WholePaper.roughSaiasPrimeThetaWeightedInterval_eq_fractionalSum
#print axioms Erdos390.WholePaper.roughSaiasIntegerAbelMain_normalForm_eq_natural_add_fractional
#print axioms Erdos390.WholePaper.roughSaiasSignedAbelCenter_eq_natural_add_fractionalTheta
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_naturalAbel_sub_theta
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_eq_finiteAbel
#print axioms Erdos390.WholePaper.roughSaiasThetaErrorTransfer_abs_le_pntLedger
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_pntLedger
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_sub_naturalAbel_abs_le
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_sub_signedAbelCenter_abs_le
#print axioms Erdos390.WholePaper.roughSaiasThetaFourthPowerConstant_pos
#print axioms Erdos390.WholePaper.roughSaiasThetaFourthPower_bound
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_sub_signedAbelCenter_abs_le_fourthPower
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_sub_naturalAbel_abs_le_fourthPower

assert_no_sorry Erdos390.WholePaper.roughSaiasRealQuotient_sub_fract_eq_natQuotient
assert_no_sorry Erdos390.WholePaper.roughSaiasSignedPrimeFloorCorrection_eq_fractional
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_continuous_add_signedFloor
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_continuous_add_fractional
assert_no_sorry Erdos390.WholePaper.roughSaiasPrimeThetaWeightedInterval_eq_continuousSum
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseContinuousNormalFormDefect_eq_abel_sub_theta
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_signedAbelCenter_sub_theta
assert_no_sorry Erdos390.WholePaper.roughSaiasThetaErrorTransfer_eq_finiteAbel
assert_no_sorry Erdos390.WholePaper.roughSaiasNormalFormThetaWeight_eq_natural_add_fractional
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_diff_eq_paired
assert_no_sorry Erdos390.WholePaper.roughSaiasPrimeThetaWeightedInterval_eq_naturalSum
assert_no_sorry Erdos390.WholePaper.roughSaiasPrimeThetaWeightedInterval_eq_fractionalSum
assert_no_sorry Erdos390.WholePaper.roughSaiasIntegerAbelMain_normalForm_eq_natural_add_fractional
assert_no_sorry Erdos390.WholePaper.roughSaiasSignedAbelCenter_eq_natural_add_fractionalTheta
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_naturalAbel_sub_theta
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_eq_finiteAbel
assert_no_sorry Erdos390.WholePaper.roughSaiasThetaErrorTransfer_abs_le_pntLedger
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_pntLedger
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_sub_naturalAbel_abs_le
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_sub_signedAbelCenter_abs_le
assert_no_sorry Erdos390.WholePaper.roughSaiasThetaFourthPowerConstant_pos
assert_no_sorry Erdos390.WholePaper.roughSaiasThetaFourthPower_bound
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_sub_signedAbelCenter_abs_le_fourthPower
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_sub_naturalAbel_abs_le_fourthPower
