import Erdos390.WholePaper.RoughSaiasCorrectionObstruction
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasDickmanBuchstabBlockRemainder_abs_le
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_eq_closedPieces_add_obstruction
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_closed_add_riemann_add_obstruction

assert_no_sorry Erdos390.WholePaper.roughSaiasDickmanBuchstabBlockRemainder_abs_le
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_eq_closedPieces_add_obstruction
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_closed_add_riemann_add_obstruction
