import Erdos390.WholePaper.RoughSaiasContinuousBuchstab
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasZeroExtendedRho_of_neg
#print axioms Erdos390.WholePaper.roughSaiasZeroExtendedRho_of_nonneg
#print axioms Erdos390.WholePaper.roughSaiasZeroExtendedRho_zero
#print axioms Erdos390.WholePaper.measurable_roughSaiasZeroExtendedRho
#print axioms Erdos390.WholePaper.roughSaiasZeroExtendedRho_mem_unitInterval
#print axioms Erdos390.WholePaper.roughSaiasZeroExtendedRho_abs_le_one
#print axioms Erdos390.WholePaper.measurable_roughSaiasStieltjesDickmanProfile
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_eq_zero_of_lt
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_self
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_one
#print axioms Erdos390.WholePaper.roughSaiasStieltjesCoordinate_eq_log_div
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_div_eq_test
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_eq_mul_test
#print axioms Erdos390.WholePaper.roughSaiasStieltjesTest_self
#print axioms Erdos390.WholePaper.measurable_roughSaiasFloorDensity
#print axioms Erdos390.WholePaper.roughSaiasStieltjesAtomPart_zero
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDensityPart_zero
#print axioms Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_zero
#print axioms Erdos390.WholePaper.roughSaiasStieltjesAtomPart_add
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDensityPart_add
#print axioms Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_add
#print axioms Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_congr
#print axioms Erdos390.WholePaper.roughSaiasStieltjesAtomPart_eq_of_cutoff
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDensityPart_eq_of_cutoff
#print axioms Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_eq_of_cutoff
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_eq_of_le
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_eq_canonical
#print axioms Erdos390.WholePaper.roughSaiasStieltjesAtomPart_profile_nat
#print axioms Erdos390.WholePaper.roughSaiasStieltjesTest_sum_eq_endpoint_sub_integral
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_nat_eq_test_sub_density
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_nat_eq_abel_ledger
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjes_nat
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_eq_mul_antiderivative
#print axioms Erdos390.WholePaper.roughSaiasContinuousBuchstabProfile_eq_mul_dickmanWeight
#print axioms Erdos390.WholePaper.roughSaiasContinuousBuchstabProfile_eq_zero_of_lt
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_eq_first_of_one_le_ratio
#print axioms Erdos390.WholePaper.intervalIntegrable_roughSaiasContinuousBuchstabProfile_to_birth
#print axioms Erdos390.WholePaper.intervalIntegrable_roughSaiasContinuousBuchstabProfile_from_birth
#print axioms Erdos390.WholePaper.roughSaiasContinuousBuchstabProfile_integral_from_birth_eq_zero
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab_active
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab_birth
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab_inactive
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab_cross_birth
#print axioms Erdos390.WholePaper.intervalIntegrable_roughSaiasContinuousBuchstabProfile
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab

assert_no_sorry Erdos390.WholePaper.roughSaiasZeroExtendedRho_of_neg
assert_no_sorry Erdos390.WholePaper.roughSaiasZeroExtendedRho_of_nonneg
assert_no_sorry Erdos390.WholePaper.roughSaiasZeroExtendedRho_zero
assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasZeroExtendedRho
assert_no_sorry Erdos390.WholePaper.roughSaiasZeroExtendedRho_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.roughSaiasZeroExtendedRho_abs_le_one
assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasStieltjesDickmanProfile
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_eq_zero_of_lt
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_self
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_one
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesCoordinate_eq_log_div
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_div_eq_test
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_eq_mul_test
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesTest_self
assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasFloorDensity
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesAtomPart_zero
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDensityPart_zero
assert_no_sorry Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_zero
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesAtomPart_add
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDensityPart_add
assert_no_sorry Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_add
assert_no_sorry Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_congr
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesAtomPart_eq_of_cutoff
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDensityPart_eq_of_cutoff
assert_no_sorry Erdos390.WholePaper.roughSaiasFiniteStieltjesFunctional_eq_of_cutoff
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_eq_of_le
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_eq_canonical
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesAtomPart_profile_nat
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesTest_sum_eq_endpoint_sub_integral
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_nat_eq_test_sub_density
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_nat_eq_abel_ledger
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjes_nat
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_eq_mul_antiderivative
assert_no_sorry Erdos390.WholePaper.roughSaiasContinuousBuchstabProfile_eq_mul_dickmanWeight
assert_no_sorry Erdos390.WholePaper.roughSaiasContinuousBuchstabProfile_eq_zero_of_lt
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_eq_first_of_one_le_ratio
assert_no_sorry Erdos390.WholePaper.intervalIntegrable_roughSaiasContinuousBuchstabProfile_to_birth
assert_no_sorry Erdos390.WholePaper.intervalIntegrable_roughSaiasContinuousBuchstabProfile_from_birth
assert_no_sorry Erdos390.WholePaper.roughSaiasContinuousBuchstabProfile_integral_from_birth_eq_zero
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab_active
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab_birth
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab_inactive
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab_cross_birth
assert_no_sorry Erdos390.WholePaper.intervalIntegrable_roughSaiasContinuousBuchstabProfile
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDickmanProfile_buchstab
