import Erdos390.WholePaper.RoughSaiasRealStieltjesNormalForm
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasRealStieltjesFloorCorrection_eq_smooth_sub_fractional
#print axioms Erdos390.WholePaper.roughSaiasRealStieltjesDerivativeFloor_add_density
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesTestRightDerivative
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesDerivative_mul_floor
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesProfile_mul_floorDensity
#print axioms Erdos390.WholePaper.roughSaiasStieltjesAtomPart_ceil_profile_eq_floor_test
#print axioms Erdos390.WholePaper.roughSaiasStieltjesTest_floor_sum_eq_endpoint_sub_integral
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDensityPart_ceil_profile_eq_realCap
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjes_eq_floor_add_floorCorrection
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasRealRhoCoordinateRightDerivative
#print axioms Erdos390.WholePaper.integral_roughSaiasRealRhoCoordinateRightDerivative
#print axioms Erdos390.WholePaper.integral_roughSaiasRealStieltjesSmoothCorrection
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesSmoothCorrection
#print axioms Erdos390.WholePaper.roughSaiasRealStieltjesFractionalCorrection_eq_baseFree_of_ne
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesFractionalCorrection
#print axioms Erdos390.WholePaper.integral_roughSaiasRealStieltjesFractionalCorrection
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjes_eq_normalForm

assert_no_sorry Erdos390.WholePaper.roughSaiasRealStieltjesFloorCorrection_eq_smooth_sub_fractional
assert_no_sorry Erdos390.WholePaper.roughSaiasRealStieltjesDerivativeFloor_add_density
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesTestRightDerivative
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesDerivative_mul_floor
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesProfile_mul_floorDensity
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesAtomPart_ceil_profile_eq_floor_test
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesTest_floor_sum_eq_endpoint_sub_integral
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDensityPart_ceil_profile_eq_realCap
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjes_eq_floor_add_floorCorrection
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasRealRhoCoordinateRightDerivative
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasRealRhoCoordinateRightDerivative
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasRealStieltjesSmoothCorrection
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesSmoothCorrection
assert_no_sorry Erdos390.WholePaper.roughSaiasRealStieltjesFractionalCorrection_eq_baseFree_of_ne
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasRealStieltjesFractionalCorrection
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasRealStieltjesFractionalCorrection
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjes_eq_normalForm
