import Erdos390.WholePaper.RoughSaiasFullyRealBuchstabCells
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasFullyRealBuchstabNormalIntegrand_eq_selector
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBuchstabNormalIntegrand_eq_selector_on_cell
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_inner_eq_fullyReal
#print axioms Erdos390.WholePaper.roughSaiasNaturalMain_buchstab_fullyReal
#print axioms Erdos390.WholePaper.intervalIntegrable_roughSaiasFullyRealBuchstabNormalIntegrand
#print axioms Erdos390.WholePaper.integral_roughSaiasFullyRealBuchstab_eq_sum_cells
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBuchstabNormalIntegrand_nat
#print axioms Erdos390.WholePaper.roughSaiasNormalFormThetaWeight_eq_selector_of_sq_le
#print axioms Erdos390.WholePaper.roughSaiasFullyReal_cell_integrand_sub_sample
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBuchstabCellRemainder_eq_selector
#print axioms Erdos390.WholePaper.roughSaiasRealQuotientSelector_cell_sub_right_abs_le
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBuchstabCellRemainder_abs_le_selectorLedger
#print axioms Erdos390.WholePaper.abs_sum_roughSaiasFullyRealBuchstabCellRemainder_le_selectorLedger
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBuchstabCellRemainder_eq_drifts
#print axioms Erdos390.WholePaper.integral_roughSaiasFullyRealBuchstab_cell_eq_sample_add_remainder
#print axioms Erdos390.WholePaper.roughSaiasNaturalMain_buchstab_sum_cells
#print axioms Erdos390.WholePaper.roughSaiasIntegerAbelConsistencyDefect_eq_cellRemainders
#print axioms Erdos390.WholePaper.roughSaiasSignedAbelCenter_eq_cellRemainders_add_signedFloor
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_cells_add_floor_sub_theta

assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBuchstabNormalIntegrand_eq_selector
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBuchstabNormalIntegrand_eq_selector_on_cell
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_inner_eq_fullyReal
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalMain_buchstab_fullyReal
assert_no_sorry Erdos390.WholePaper.intervalIntegrable_roughSaiasFullyRealBuchstabNormalIntegrand
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasFullyRealBuchstab_eq_sum_cells
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBuchstabNormalIntegrand_nat
assert_no_sorry Erdos390.WholePaper.roughSaiasNormalFormThetaWeight_eq_selector_of_sq_le
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyReal_cell_integrand_sub_sample
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBuchstabCellRemainder_eq_selector
assert_no_sorry Erdos390.WholePaper.roughSaiasRealQuotientSelector_cell_sub_right_abs_le
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBuchstabCellRemainder_abs_le_selectorLedger
assert_no_sorry Erdos390.WholePaper.abs_sum_roughSaiasFullyRealBuchstabCellRemainder_le_selectorLedger
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBuchstabCellRemainder_eq_drifts
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasFullyRealBuchstab_cell_eq_sample_add_remainder
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalMain_buchstab_sum_cells
assert_no_sorry Erdos390.WholePaper.roughSaiasIntegerAbelConsistencyDefect_eq_cellRemainders
assert_no_sorry Erdos390.WholePaper.roughSaiasSignedAbelCenter_eq_cellRemainders_add_signedFloor
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_eq_cells_add_floor_sub_theta
