import Erdos390.WholePaper.RoughFixedHeadFriableShift
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughRhoFloorKernel_stability
#print axioms Erdos390.WholePaper.roughFriableMain_fixedDivisorShift
#print axioms Erdos390.WholePaper.exists_uniform_roughFixedHead_friableCount_shift_bound
#print axioms Erdos390.WholePaper.roughSmoothPhysicalBlock_eq_friableEndpoints
#print axioms Erdos390.WholePaper.exists_uniform_roughFixedHead_smoothPhysicalBlock_shift_bound
#print axioms Erdos390.WholePaper.roughHead_moebius_inv_sum_eq_density
#print axioms Erdos390.WholePaper.exists_uniform_roughHeadFree_smoothPhysicalBlock_density_bound

assert_no_sorry Erdos390.WholePaper.roughRhoFloorKernel_stability
assert_no_sorry Erdos390.WholePaper.roughFriableMain_fixedDivisorShift
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughFixedHead_friableCount_shift_bound
assert_no_sorry Erdos390.WholePaper.roughSmoothPhysicalBlock_eq_friableEndpoints
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughFixedHead_smoothPhysicalBlock_shift_bound
assert_no_sorry Erdos390.WholePaper.roughHead_moebius_inv_sum_eq_density
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughHeadFree_smoothPhysicalBlock_density_bound
