import Erdos390.WholePaper.RoughSaiasCellTransitionSplit
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.le_roughSaiasSelectorTransition
#print axioms Erdos390.WholePaper.roughSaiasSelectorTransition_sq_ge
#print axioms Erdos390.WholePaper.roughSaiasSelectorTransition_le
#print axioms Erdos390.WholePaper.sum_roughSaiasFullyRealNaturalCells_split
#print axioms Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_eq_splitCells
#print axioms Erdos390.WholePaper.abs_sum_roughSaiasFullyRealNaturalCells_upper_le_three_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_abs_le_lowerCells_add_three
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_lowerCells_closedCore_residual
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_canonicalLowerCells_closedCore_residual

assert_no_sorry Erdos390.WholePaper.le_roughSaiasSelectorTransition
assert_no_sorry Erdos390.WholePaper.roughSaiasSelectorTransition_sq_ge
assert_no_sorry Erdos390.WholePaper.roughSaiasSelectorTransition_le
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasFullyRealNaturalCells_split
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_eq_splitCells
assert_no_sorry Erdos390.WholePaper.abs_sum_roughSaiasFullyRealNaturalCells_upper_le_three_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_abs_le_lowerCells_add_three
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_lowerCells_closedCore_residual
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_self_abs_le_canonicalLowerCells_closedCore_residual
