import Erdos390.WholePaper.RoughSaiasStieltjesNormalForm
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasNatFloor_cast_eq_sub_fract
#print axioms Erdos390.WholePaper.roughSaiasStieltjesFloorCorrection_eq_smooth_sub_fractional
#print axioms Erdos390.WholePaper.roughSaiasStieltjesDerivativeFloor_add_density
#print axioms Erdos390.WholePaper.roughSaiasPositiveIncrement_prefix
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasStieltjesDerivative_mul_floor
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasStieltjesProfile_mul_floorDensity
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_nat_eq_add_floorCorrection
#print axioms Erdos390.WholePaper.hasDerivWithinAt_roughSaiasRhoCoordinate_right
#print axioms Erdos390.WholePaper.continuousOn_roughSaiasRhoCoordinate
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasRhoCoordinateRightDerivative
#print axioms Erdos390.WholePaper.integral_roughSaiasRhoCoordinateRightDerivative
#print axioms Erdos390.WholePaper.integral_roughSaiasStieltjesSmoothCorrection
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasStieltjesSmoothCorrection
#print axioms Erdos390.WholePaper.roughSaias_natCast_le_rpow_five
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_eq_natCap
#print axioms Erdos390.WholePaper.roughSaiasStieltjesFractionalCorrection_eq_baseFree_of_ne
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasStieltjesFractionalCorrection
#print axioms Erdos390.WholePaper.integral_roughSaiasStieltjesFractionalCorrection
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_nat_eq_normalForm
#print axioms Erdos390.WholePaper.roughSaiasLambdaStieltjes_nat_eq_normalForm

assert_no_sorry Erdos390.WholePaper.roughSaiasNatFloor_cast_eq_sub_fract
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesFloorCorrection_eq_smooth_sub_fractional
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesDerivativeFloor_add_density
assert_no_sorry Erdos390.WholePaper.roughSaiasPositiveIncrement_prefix
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasStieltjesDerivative_mul_floor
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasStieltjesProfile_mul_floorDensity
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_nat_eq_add_floorCorrection
assert_no_sorry Erdos390.WholePaper.hasDerivWithinAt_roughSaiasRhoCoordinate_right
assert_no_sorry Erdos390.WholePaper.continuousOn_roughSaiasRhoCoordinate
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasRhoCoordinateRightDerivative
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasRhoCoordinateRightDerivative
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasStieltjesSmoothCorrection
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasStieltjesSmoothCorrection
assert_no_sorry Erdos390.WholePaper.roughSaias_natCast_le_rpow_five
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_eq_natCap
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesFractionalCorrection_eq_baseFree_of_ne
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasStieltjesFractionalCorrection
assert_no_sorry Erdos390.WholePaper.integral_roughSaiasStieltjesFractionalCorrection
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjesWithCutoff_nat_eq_normalForm
assert_no_sorry Erdos390.WholePaper.roughSaiasLambdaStieltjes_nat_eq_normalForm
