import Erdos390.WholePaper.RoughFriableFaceInduction
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughReversePrimeInterval_prime
#print axioms Erdos390.WholePaper.roughReversePrimeInterval_gt_left
#print axioms Erdos390.WholePaper.roughReversePrimeInterval_le_right
#print axioms Erdos390.WholePaper.roughFriableReverseMainDefect_eq_continuous_add_floor
#print axioms Erdos390.WholePaper.roughFriableReverseFloorDiscrepancy_abs_le_card
#print axioms Erdos390.WholePaper.roughFriableReverseFloorDiscrepancy_abs_le_endpointScale
#print axioms Erdos390.WholePaper.roughFriableReverseFloorTerm_abs_le_three
#print axioms Erdos390.WholePaper.roughFriableReverseFloorDiscrepancy_difference_abs_le_endpointScale
#print axioms Erdos390.WholePaper.exists_uniform_roughFriableReverseContinuousDefect_bound
#print axioms Erdos390.WholePaper.exists_uniform_roughFriableReverseMainDefect_bound
#print axioms Erdos390.WholePaper.roughFriablePrimeTransitionLedger_eq_residualDifference
#print axioms Erdos390.WholePaper.roughFriablePrimeTransitionLedger_eq_continuous_floor_lower
#print axioms Erdos390.WholePaper.exists_uniform_roughFriablePrimeTransitionLedger_broad_bound
#print axioms Erdos390.WholePaper.exists_uniform_roughFriablePrimeTransitionLedger_wideGap_bound
#print axioms Erdos390.WholePaper.roughReverseQuotient_log_le_lowerFace
#print axioms Erdos390.WholePaper.roughFriableResidual_localRegularity_initial_all
#print axioms Erdos390.WholePaper.roughFriableResidual_faceRegularity_one
#print axioms Erdos390.WholePaper.roughFriableResidual_faceRegularity_step
#print axioms Erdos390.WholePaper.roughFriableResidual_faceRegularity_one_to_five
#print axioms Erdos390.WholePaper.roughFriableResidual_localRegularity_of_primeTransition

assert_no_sorry Erdos390.WholePaper.roughReversePrimeInterval_prime
assert_no_sorry Erdos390.WholePaper.roughReversePrimeInterval_gt_left
assert_no_sorry Erdos390.WholePaper.roughReversePrimeInterval_le_right
assert_no_sorry Erdos390.WholePaper.roughFriableReverseMainDefect_eq_continuous_add_floor
assert_no_sorry Erdos390.WholePaper.roughFriableReverseFloorDiscrepancy_abs_le_card
assert_no_sorry Erdos390.WholePaper.roughFriableReverseFloorDiscrepancy_abs_le_endpointScale
assert_no_sorry Erdos390.WholePaper.roughFriableReverseFloorTerm_abs_le_three
assert_no_sorry Erdos390.WholePaper.roughFriableReverseFloorDiscrepancy_difference_abs_le_endpointScale
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughFriableReverseContinuousDefect_bound
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughFriableReverseMainDefect_bound
assert_no_sorry Erdos390.WholePaper.roughFriablePrimeTransitionLedger_eq_residualDifference
assert_no_sorry Erdos390.WholePaper.roughFriablePrimeTransitionLedger_eq_continuous_floor_lower
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughFriablePrimeTransitionLedger_broad_bound
assert_no_sorry Erdos390.WholePaper.exists_uniform_roughFriablePrimeTransitionLedger_wideGap_bound
assert_no_sorry Erdos390.WholePaper.roughReverseQuotient_log_le_lowerFace
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_localRegularity_initial_all
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_faceRegularity_one
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_faceRegularity_step
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_faceRegularity_one_to_five
assert_no_sorry Erdos390.WholePaper.roughFriableResidual_localRegularity_of_primeTransition
