import Erdos390.WholePaper.RoughSaiasCanonicalRowBridge
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughUpperCompleteRoughRowTarget
#print axioms Erdos390.WholePaper.roughPhysicalLowerFriableMass
#print axioms Erdos390.WholePaper.IsCompleteRoughLabel
#print axioms Erdos390.WholePaper.roughCanonicalFixedHeadShiftLedger
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError
#print axioms Erdos390.WholePaper.isCompleteRoughLabel_of_canonicalCompleteRoughRow
#print axioms Erdos390.WholePaper.completeRoughLabel_mul_eq_of_isCompleteRoughLabel_of_smooth
#print axioms Erdos390.WholePaper.isCompleteRoughLabel_coprime_roughHeadModulus
#print axioms Erdos390.WholePaper.sum_canonicalCompleteRoughRowSet_rawWeight_eq_rawRowMass
#print axioms Erdos390.WholePaper.completeRoughRowFiber_Ioc_card_eq_smoothInterval
#print axioms Erdos390.WholePaper.completeRoughRowFiber_headFreeIoc_card_eq_headFreeSmoothInterval
#print axioms Erdos390.WholePaper.roughUpperCompleteRoughRowTarget_eq_friableEndpoints
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawRowMass_eq_headFreeRowCards
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawRowMass_eq_headFreeSmoothPhysicalBlock
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawRowMass_eq_headDivisorShift
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawRowMass_sub_densityPhysicalBlock_abs_le
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawRowMass_sub_densityLower_abs_le
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_eq_target_sub_rawRowMass
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_eq_physicalFriableCombination
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_sub_physicalFriableCombination_abs
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_saiasPaperScale
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_literalSaiasPaperScale
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_literalSaiasAndHeadLedger
#print axioms Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_three_mul_paperAllowance

assert_no_sorry Erdos390.WholePaper.roughUpperCompleteRoughRowTarget
assert_no_sorry Erdos390.WholePaper.roughPhysicalLowerFriableMass
assert_no_sorry Erdos390.WholePaper.IsCompleteRoughLabel
assert_no_sorry Erdos390.WholePaper.roughCanonicalFixedHeadShiftLedger
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError
assert_no_sorry Erdos390.WholePaper.isCompleteRoughLabel_of_canonicalCompleteRoughRow
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_mul_eq_of_isCompleteRoughLabel_of_smooth
assert_no_sorry Erdos390.WholePaper.isCompleteRoughLabel_coprime_roughHeadModulus
assert_no_sorry Erdos390.WholePaper.sum_canonicalCompleteRoughRowSet_rawWeight_eq_rawRowMass
assert_no_sorry Erdos390.WholePaper.completeRoughRowFiber_Ioc_card_eq_smoothInterval
assert_no_sorry Erdos390.WholePaper.completeRoughRowFiber_headFreeIoc_card_eq_headFreeSmoothInterval
assert_no_sorry Erdos390.WholePaper.roughUpperCompleteRoughRowTarget_eq_friableEndpoints
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawRowMass_eq_headFreeRowCards
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawRowMass_eq_headFreeSmoothPhysicalBlock
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawRowMass_eq_headDivisorShift
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawRowMass_sub_densityPhysicalBlock_abs_le
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawRowMass_sub_densityLower_abs_le
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_eq_target_sub_rawRowMass
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_eq_physicalFriableCombination
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_sub_physicalFriableCombination_abs
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_saiasPaperScale
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_literalSaiasPaperScale
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_of_literalSaiasAndHeadLedger
assert_no_sorry Erdos390.WholePaper.roughCanonicalRawRowQuotaError_abs_le_three_mul_paperAllowance
