import Erdos390.WholePaper.RoughTransitionBalancedBlock
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughBalancedBlock_centered_identity
#print axioms Erdos390.WholePaper.roughBalancedBlock_model_abs_le
#print axioms Erdos390.WholePaper.roughBalancedBlock_logDisplacementMoment
#print axioms Erdos390.WholePaper.roughBalancedBlock_logModel_abs_le
#print axioms Erdos390.WholePaper.roughBalancedBlock_observed_abs_le
#print axioms Erdos390.WholePaper.roughPhysicalBalancedAlpha_normalization
#print axioms Erdos390.WholePaper.roughPhysicalBlock_firstMoment_eq_zero
#print axioms Erdos390.WholePaper.roughPhysicalBalancedAlpha_firstMoment_eq_zero
#print axioms Erdos390.WholePaper.roughPhysicalBlockEndpoint_nonneg
#print axioms Erdos390.WholePaper.roughPhysicalBlock_transitionComplete_abs_le

assert_no_sorry Erdos390.WholePaper.roughBalancedBlock_centered_identity
assert_no_sorry Erdos390.WholePaper.roughBalancedBlock_model_abs_le
assert_no_sorry Erdos390.WholePaper.roughBalancedBlock_logDisplacementMoment
assert_no_sorry Erdos390.WholePaper.roughBalancedBlock_logModel_abs_le
assert_no_sorry Erdos390.WholePaper.roughBalancedBlock_observed_abs_le
assert_no_sorry Erdos390.WholePaper.roughPhysicalBalancedAlpha_normalization
assert_no_sorry Erdos390.WholePaper.roughPhysicalBlock_firstMoment_eq_zero
assert_no_sorry Erdos390.WholePaper.roughPhysicalBalancedAlpha_firstMoment_eq_zero
assert_no_sorry Erdos390.WholePaper.roughPhysicalBlockEndpoint_nonneg
assert_no_sorry Erdos390.WholePaper.roughPhysicalBlock_transitionComplete_abs_le
