import Erdos390.WholePaper.RoughSaiasNaturalThetaLedgerBound
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_abs_le_sixteen
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaPNTLedger_le_endpoint_add_variation
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaPNTEndpointEnvelope_fourth_le
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaPNTEndpointEnvelope_fourth_le_invLogSq
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_endpoint_add_variation
#print axioms Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_endpoint_add_variation_fourthPower
#print axioms Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_cells_endpoint_variation

assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_abs_le_sixteen
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaPNTLedger_le_endpoint_add_variation
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaPNTEndpointEnvelope_fourth_le
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaPNTEndpointEnvelope_fourth_le_invLogSq
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_endpoint_add_variation
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalThetaErrorTransfer_abs_le_endpoint_add_variation_fourthPower
assert_no_sorry Erdos390.WholePaper.roughSaiasReverseNormalFormDefect_abs_le_cells_endpoint_variation
