import Erdos390.WholePaper.RoughHeadCompatibleFinitePoint
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughHighLowerBlock_disjoint_roughBroadLowerBlock
#print axioms Erdos390.WholePaper.roughRawCandidateSet_eq_Ioc
#print axioms Erdos390.WholePaper.roughUpperBlock_disjoint_rawCandidateSet
#print axioms Erdos390.WholePaper.roughUpperBlock_card
#print axioms Erdos390.WholePaper.roughHighLowerBlock_card
#print axioms Erdos390.WholePaper.roughBroadLowerBlock_card
#print axioms Erdos390.WholePaper.roughHeadZeroPattern_modulus
#print axioms Erdos390.WholePaper.roughHeadZeroPattern_factor
#print axioms Erdos390.WholePaper.roughHeadModulus_pos
#print axioms Erdos390.WholePaper.roughHeadDensity_pos
#print axioms Erdos390.WholePaper.roughHeadBalancedAlpha_length_normalization
#print axioms Erdos390.WholePaper.roughHeadBalancedAlpha_card_normalization
#print axioms Erdos390.WholePaper.mem_roughHeadFree
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawWeight_eq_zero_of_not_mem
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawWeight_eq_zero_of_not_mem_Ioc
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawWeight_mem_unitInterval
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawPoint_apply
#print axioms Erdos390.WholePaper.roughHeadCompatibleRawPoint_mem_unitInterval
#print axioms Erdos390.WholePaper.sum_roughHeadCompatibleRawWeight
#print axioms Erdos390.WholePaper.sum_roughHeadCompatibleRawWeight_Ioc
#print axioms Erdos390.WholePaper.sum_roughHeadCompatibleRawRowMass
#print axioms Erdos390.WholePaper.roughHeadFree_card_eq_moebiusDivisorCounts
#print axioms Erdos390.WholePaper.roughHeadModulus_mem_smoothNumbers
#print axioms Erdos390.WholePaper.roughHeadFreeSmoothInterval_card_eq_divisorShift
#print axioms Erdos390.WholePaper.roughHeadFreeSmoothInterval_card_real_eq_divisorShift
#print axioms Erdos390.WholePaper.roughHeadFreeSmoothPhysicalBlock_eq_divisorShift

assert_no_sorry Erdos390.WholePaper.roughHighLowerBlock_disjoint_roughBroadLowerBlock
assert_no_sorry Erdos390.WholePaper.roughRawCandidateSet_eq_Ioc
assert_no_sorry Erdos390.WholePaper.roughUpperBlock_disjoint_rawCandidateSet
assert_no_sorry Erdos390.WholePaper.roughUpperBlock_card
assert_no_sorry Erdos390.WholePaper.roughHighLowerBlock_card
assert_no_sorry Erdos390.WholePaper.roughBroadLowerBlock_card
assert_no_sorry Erdos390.WholePaper.roughHeadZeroPattern_modulus
assert_no_sorry Erdos390.WholePaper.roughHeadZeroPattern_factor
assert_no_sorry Erdos390.WholePaper.roughHeadModulus_pos
assert_no_sorry Erdos390.WholePaper.roughHeadDensity_pos
assert_no_sorry Erdos390.WholePaper.roughHeadBalancedAlpha_length_normalization
assert_no_sorry Erdos390.WholePaper.roughHeadBalancedAlpha_card_normalization
assert_no_sorry Erdos390.WholePaper.mem_roughHeadFree
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawWeight_eq_zero_of_not_mem
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawWeight_eq_zero_of_not_mem_Ioc
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawWeight_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawPoint_apply
assert_no_sorry Erdos390.WholePaper.roughHeadCompatibleRawPoint_mem_unitInterval
assert_no_sorry Erdos390.WholePaper.sum_roughHeadCompatibleRawWeight
assert_no_sorry Erdos390.WholePaper.sum_roughHeadCompatibleRawWeight_Ioc
assert_no_sorry Erdos390.WholePaper.sum_roughHeadCompatibleRawRowMass
assert_no_sorry Erdos390.WholePaper.roughHeadFree_card_eq_moebiusDivisorCounts
assert_no_sorry Erdos390.WholePaper.roughHeadModulus_mem_smoothNumbers
assert_no_sorry Erdos390.WholePaper.roughHeadFreeSmoothInterval_card_eq_divisorShift
assert_no_sorry Erdos390.WholePaper.roughHeadFreeSmoothInterval_card_real_eq_divisorShift
assert_no_sorry Erdos390.WholePaper.roughHeadFreeSmoothPhysicalBlock_eq_divisorShift
