import Erdos390.WholePaper.RoughSaiasBaseChange
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_eq_sub_div
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_succ_le
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_sub_succ
#print axioms Erdos390.WholePaper.one_le_roughSaiasBaseFreeDickmanCoordinate_of_le_div
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_eq_sawtooth_mul_scaled
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_succ_sub
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_succ_sub
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_eq_zero_of_div_lt
#print axioms Erdos390.WholePaper.roughSaiasNatQuotientLogRatio_succ_le
#print axioms Erdos390.WholePaper.roughSaiasNatQuotient_div_succ_lt_rpow_five
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_succ_tail_eq_zero
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_rpow_mul_jacobian
#print axioms Erdos390.WholePaper.roughSaiasFractionalIntegral_eq_baseFree
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_intervalIntegrable
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_succ_sub
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_succ_sub_factored
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_succ_sub_eq_common
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_succ_sub_eq_translation
#print axioms Erdos390.WholePaper.roughSaiasG_at_natQuotient_eq_baseFree
#print axioms Erdos390.WholePaper.roughSaiasG_at_natQuotient_succ_sub_eq_common
#print axioms Erdos390.WholePaper.roughSaiasNaturalMain_eq_rho_sub_baseFree
#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_eq_baseFree
#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_diff_eq_baseFree
#print axioms Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_diff_eq_baseFree_on_block
#print axioms Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_eq_baseFree
#print axioms Erdos390.WholePaper.roughSaiasSignedAbelCenter_eq_baseFree_add_fractionalTheta

assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_eq_zero_of_div_lt
assert_no_sorry Erdos390.WholePaper.roughSaiasNatQuotientLogRatio_succ_le
assert_no_sorry Erdos390.WholePaper.roughSaiasNatQuotient_div_succ_lt_rpow_five
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_succ_tail_eq_zero
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_eq_sub_div
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_succ_le
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_sub_succ
assert_no_sorry Erdos390.WholePaper.one_le_roughSaiasBaseFreeDickmanCoordinate_of_le_div
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_eq_sawtooth_mul_scaled
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_succ_sub
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_succ_sub
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_rpow_mul_jacobian
assert_no_sorry Erdos390.WholePaper.roughSaiasFractionalIntegral_eq_baseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalKernel_intervalIntegrable
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_succ_sub
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_succ_sub_factored
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_succ_sub_eq_common
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_succ_sub_eq_translation
assert_no_sorry Erdos390.WholePaper.roughSaiasG_at_natQuotient_eq_baseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasG_at_natQuotient_succ_sub_eq_common
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalMain_eq_rho_sub_baseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_eq_baseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_diff_eq_baseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalQuotientThetaWeight_diff_eq_baseFree_on_block
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalIntegerAbelConsistencyDefect_eq_baseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasSignedAbelCenter_eq_baseFree_add_fractionalTheta
