import Erdos390.WholePaper.RoughSaiasSharpCanonicalRowPaperScale
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughHeadDensity_le_one
#print axioms Erdos390.WholePaper.roughHeadBalancedAlpha_abs_le_of_tail_lower
#print axioms Erdos390.WholePaper.roughHeadBalancedAlpha_succ_abs_le
#print axioms Erdos390.WholePaper.roughBalancedAlphaConstant
#print axioms Erdos390.WholePaper.roughBalancedAlphaConstant_nonneg
#print axioms Erdos390.WholePaper.roughCanonicalSharpMainRowScaleConstant
#print axioms Erdos390.WholePaper.roughCanonicalSharpTransitionRowScaleConstant
#print axioms Erdos390.WholePaper.roughCanonicalSharpHeadDivisorRowScaleConstant
#print axioms Erdos390.WholePaper.roughCanonicalSharpHeadRowScaleConstant
#print axioms Erdos390.WholePaper.roughCanonicalSharpUnifiedRowScaleConstant
#print axioms Erdos390.WholePaper.roughNatQuotient_sub_realQuotient_abs_lt_one
#print axioms Erdos390.WholePaper.roughRealQuotient_lt_natQuotient_add_one
#print axioms Erdos390.WholePaper.roughQuotientGap_cast_le
#print axioms Erdos390.WholePaper.roughTwoQuotient_le_three_halfQuotient
#print axioms Erdos390.WholePaper.roughUpperQuotient_le_three_centralQuotient
#print axioms Erdos390.WholePaper.roughLowerEndpoint_mul_logRatio_le_gap
#print axioms Erdos390.WholePaper.roughUpperEndpoint_mul_logRatio_le_three_gap
#print axioms Erdos390.WholePaper.roughDickmanUpperWeightedDisplacement_le_three_gap
#print axioms Erdos390.WholePaper.roughDickmanLowerWeightedDisplacement_le_gap
#print axioms Erdos390.WholePaper.roughTail_div_row_cast_le
#print axioms Erdos390.WholePaper.roughRowScale_elementary
#print axioms Erdos390.WholePaper.roughBalancedCanonicalContinuousFirstMoment_eq_zero
#print axioms Erdos390.WholePaper.roughBalancedCanonicalNaturalFirstMoment_abs_le
#print axioms Erdos390.WholePaper.sum_abs_roughPhysicalBlockCoefficient_le
#print axioms Erdos390.WholePaper.roughPhysicalDickmanDisplacementSum_le_three_gaps
#print axioms Erdos390.WholePaper.roughCanonicalBalancedDickmanTransitionLedger_le
#print axioms Erdos390.WholePaper.roughCanonicalBalancedSaiasTransitionBudget_le
#print axioms Erdos390.WholePaper.roughCanonicalBalancedSharpFixedHeadBudget_le
#print axioms Erdos390.WholePaper.roughCanonicalSharpMainRowScaleConstant_nonneg
#print axioms Erdos390.WholePaper.roughCanonicalSharpTransitionRowScaleConstant_nonneg
#print axioms Erdos390.WholePaper.roughCanonicalSharpHeadDivisorRowScaleConstant_nonneg
#print axioms Erdos390.WholePaper.roughCanonicalSharpHeadRowScaleConstant_nonneg
#print axioms Erdos390.WholePaper.roughCanonicalSharpUnifiedRowScaleConstant_nonneg
#print axioms Erdos390.WholePaper.roughCanonicalBalancedRawRowQuotaError_abs_le_unified

assert_no_sorry Erdos390.WholePaper.roughHeadDensity_le_one
assert_no_sorry Erdos390.WholePaper.roughHeadBalancedAlpha_abs_le_of_tail_lower
assert_no_sorry Erdos390.WholePaper.roughHeadBalancedAlpha_succ_abs_le
assert_no_sorry Erdos390.WholePaper.roughBalancedAlphaConstant
assert_no_sorry Erdos390.WholePaper.roughBalancedAlphaConstant_nonneg
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpMainRowScaleConstant
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpTransitionRowScaleConstant
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpHeadDivisorRowScaleConstant
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpHeadRowScaleConstant
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpUnifiedRowScaleConstant
assert_no_sorry Erdos390.WholePaper.roughNatQuotient_sub_realQuotient_abs_lt_one
assert_no_sorry Erdos390.WholePaper.roughRealQuotient_lt_natQuotient_add_one
assert_no_sorry Erdos390.WholePaper.roughQuotientGap_cast_le
assert_no_sorry Erdos390.WholePaper.roughTwoQuotient_le_three_halfQuotient
assert_no_sorry Erdos390.WholePaper.roughUpperQuotient_le_three_centralQuotient
assert_no_sorry Erdos390.WholePaper.roughLowerEndpoint_mul_logRatio_le_gap
assert_no_sorry Erdos390.WholePaper.roughUpperEndpoint_mul_logRatio_le_three_gap
assert_no_sorry Erdos390.WholePaper.roughDickmanUpperWeightedDisplacement_le_three_gap
assert_no_sorry Erdos390.WholePaper.roughDickmanLowerWeightedDisplacement_le_gap
assert_no_sorry Erdos390.WholePaper.roughTail_div_row_cast_le
assert_no_sorry Erdos390.WholePaper.roughRowScale_elementary
assert_no_sorry Erdos390.WholePaper.roughBalancedCanonicalContinuousFirstMoment_eq_zero
assert_no_sorry Erdos390.WholePaper.roughBalancedCanonicalNaturalFirstMoment_abs_le
assert_no_sorry Erdos390.WholePaper.sum_abs_roughPhysicalBlockCoefficient_le
assert_no_sorry Erdos390.WholePaper.roughPhysicalDickmanDisplacementSum_le_three_gaps
assert_no_sorry Erdos390.WholePaper.roughCanonicalBalancedDickmanTransitionLedger_le
assert_no_sorry Erdos390.WholePaper.roughCanonicalBalancedSaiasTransitionBudget_le
assert_no_sorry Erdos390.WholePaper.roughCanonicalBalancedSharpFixedHeadBudget_le
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpMainRowScaleConstant_nonneg
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpTransitionRowScaleConstant_nonneg
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpHeadDivisorRowScaleConstant_nonneg
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpHeadRowScaleConstant_nonneg
assert_no_sorry Erdos390.WholePaper.roughCanonicalSharpUnifiedRowScaleConstant_nonneg
assert_no_sorry Erdos390.WholePaper.roughCanonicalBalancedRawRowQuotaError_abs_le_unified
