import Erdos390.WholePaper.RoughSaiasSharpVariation
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_eq_neg_rho_div_log_sub
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_abs_le_inv_log
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_nonpos_of_active
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_antitone_base
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_eq_zero_of_div_lt
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_succ_le_of_active
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_le_of_quotient_le_of_active
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_succ_le_of_active
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_quotient_succ_sub_eq_common
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_hyperbola_succ_sub_eq_common
#print axioms Erdos390.WholePaper.roughSaiasHyperbolaFractionalTransition_intervalIntegrable
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_sum_abs_succ_sub_eq
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_sum_abs_succ_sub_le_inv_log
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_sum_abs_succ_sub_le_two_inv_log_of_cutoff
#print axioms Erdos390.WholePaper.roughSaiasNaturalHyperbolaSupport_antitone
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_natHyperbola_le_five
#print axioms Erdos390.WholePaper.roughSaiasNat_le_rpow_five
#print axioms Erdos390.WholePaper.roughSaiasNatHyperbolaLogRatio_le_five
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_hyperbola_succ_sub_eq_firstCap
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_sum_abs_succ_sub_le_two_inv_log
#print axioms Erdos390.WholePaper.roughSaiasNatHyperbolaLogRatio_succ_le
#print axioms Erdos390.WholePaper.sum_abs_rho_natHyperbolaLogRatio_succ_sub_le_one
#print axioms Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_hyperbola_sum_abs_succ_sub_le_two_inv_log
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_sum_abs_succ_sub_eq
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_sum_abs_succ_sub_le_inv_log
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_sum_abs_succ_sub_le_inv_log_of_last_active
#print axioms Erdos390.WholePaper.roughSaiasScaledDickmanKernel_sum_abs_succ_sub_le_two_inv_log_of_cutoff
#print axioms Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCoordinate
#print axioms Erdos390.WholePaper.roughSaiasFullyRealHyperbolaScaledDickmanKernel
#print axioms Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCellKernelOscillation
#print axioms Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCellFractionalOscillation
#print axioms Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCellFractionalOscillationLedger
#print axioms Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCoordinate_le_five
#print axioms Erdos390.WholePaper.roughSaiasFullyRealBaseFreeFractionalIntegral_hyperbola_cell_abs_sub_le
#print axioms Erdos390.WholePaper.sum_roughSaiasFullyRealHyperbolaCellFractionalOscillationLedger_le_two_inv_log

assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_eq_neg_rho_div_log_sub
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_abs_le_inv_log
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_nonpos_of_active
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_antitone_base
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_eq_zero_of_div_lt
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_succ_le_of_active
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_le_of_quotient_le_of_active
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_succ_le_of_active
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_quotient_succ_sub_eq_common
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_hyperbola_succ_sub_eq_common
assert_no_sorry Erdos390.WholePaper.roughSaiasHyperbolaFractionalTransition_intervalIntegrable
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_sum_abs_succ_sub_eq
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_sum_abs_succ_sub_le_inv_log
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_sum_abs_succ_sub_le_two_inv_log_of_cutoff
assert_no_sorry Erdos390.WholePaper.roughSaiasNaturalHyperbolaSupport_antitone
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeDickmanCoordinate_natHyperbola_le_five
assert_no_sorry Erdos390.WholePaper.roughSaiasNat_le_rpow_five
assert_no_sorry Erdos390.WholePaper.roughSaiasNatHyperbolaLogRatio_le_five
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_hyperbola_succ_sub_eq_firstCap
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_hyperbola_sum_abs_succ_sub_le_two_inv_log
assert_no_sorry Erdos390.WholePaper.roughSaiasNatHyperbolaLogRatio_succ_le
assert_no_sorry Erdos390.WholePaper.sum_abs_rho_natHyperbolaLogRatio_succ_sub_le_one
assert_no_sorry Erdos390.WholePaper.roughSaiasBaseFreeFractionalIntegral_hyperbola_sum_abs_succ_sub_le_two_inv_log
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_sum_abs_succ_sub_eq
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_sum_abs_succ_sub_le_inv_log
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_sum_abs_succ_sub_le_inv_log_of_last_active
assert_no_sorry Erdos390.WholePaper.roughSaiasScaledDickmanKernel_sum_abs_succ_sub_le_two_inv_log_of_cutoff
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCoordinate
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealHyperbolaScaledDickmanKernel
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCellKernelOscillation
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCellFractionalOscillation
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCellFractionalOscillationLedger
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealHyperbolaCoordinate_le_five
assert_no_sorry Erdos390.WholePaper.roughSaiasFullyRealBaseFreeFractionalIntegral_hyperbola_cell_abs_sub_le
assert_no_sorry Erdos390.WholePaper.sum_roughSaiasFullyRealHyperbolaCellFractionalOscillationLedger_le_two_inv_log
