import Erdos390.WholePaper.RoughSaiasRealBaseChange
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasRealBaseFreeFractionalKernel_rpow_mul_jacobian
#print axioms Erdos390.WholePaper.roughSaiasFractionalIntegral_eq_realBaseFree
#print axioms Erdos390.WholePaper.roughSaiasRealBaseFreeFractionalKernel_intervalIntegrable
#print axioms Erdos390.WholePaper.roughSaiasRealBaseFreeFractionalKernel_eq_zero_of_div_lt
#print axioms Erdos390.WholePaper.roughSaiasReal_le_rpow_five
#print axioms Erdos390.WholePaper.roughSaiasRealBaseFreeFractionalIntegral_eq_realCap
#print axioms Erdos390.WholePaper.roughSaiasG_at_realEndpoint_eq_realBaseFree

assert_no_sorry Erdos390.WholePaper.roughSaiasRealBaseFreeFractionalKernel_rpow_mul_jacobian
assert_no_sorry Erdos390.WholePaper.roughSaiasFractionalIntegral_eq_realBaseFree
assert_no_sorry Erdos390.WholePaper.roughSaiasRealBaseFreeFractionalKernel_intervalIntegrable
assert_no_sorry Erdos390.WholePaper.roughSaiasRealBaseFreeFractionalKernel_eq_zero_of_div_lt
assert_no_sorry Erdos390.WholePaper.roughSaiasReal_le_rpow_five
assert_no_sorry Erdos390.WholePaper.roughSaiasRealBaseFreeFractionalIntegral_eq_realCap
assert_no_sorry Erdos390.WholePaper.roughSaiasG_at_realEndpoint_eq_realBaseFree
