import Erdos390.WholePaper.RoughSaiasStieltjesKernel
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_of_le_one
#print axioms Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_of_one_lt
#print axioms Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_one
#print axioms Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_eq_roughSaias
#print axioms Erdos390.WholePaper.measurable_roughSaiasOpenFaceDickmanDerivative
#print axioms Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_abs_le_one
#print axioms Erdos390.WholePaper.roughSaiasOpenFace_convolution_eq_rightLimit
#print axioms Erdos390.WholePaper.roughSaiasStieltjesCoordinate_mem
#print axioms Erdos390.WholePaper.continuousOn_roughSaiasStieltjesTest
#print axioms Erdos390.WholePaper.hasDerivWithinAt_roughSaiasStieltjesTest_right
#print axioms Erdos390.WholePaper.roughSaiasStieltjesTest_hasRightDerivOn
#print axioms Erdos390.WholePaper.measurable_roughSaiasStieltjesCoordinate
#print axioms Erdos390.WholePaper.measurable_roughSaiasStieltjesTestRightDerivative
#print axioms Erdos390.WholePaper.roughSaiasStieltjesTestRightDerivative_abs_le
#print axioms Erdos390.WholePaper.integrableOn_roughSaiasStieltjesTestRightDerivative

assert_no_sorry Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_of_le_one
assert_no_sorry Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_of_one_lt
assert_no_sorry Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_one
assert_no_sorry Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_eq_roughSaias
assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasOpenFaceDickmanDerivative
assert_no_sorry Erdos390.WholePaper.roughSaiasOpenFaceDickmanDerivative_abs_le_one
assert_no_sorry Erdos390.WholePaper.roughSaiasOpenFace_convolution_eq_rightLimit
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesCoordinate_mem
assert_no_sorry Erdos390.WholePaper.continuousOn_roughSaiasStieltjesTest
assert_no_sorry Erdos390.WholePaper.hasDerivWithinAt_roughSaiasStieltjesTest_right
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesTest_hasRightDerivOn
assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasStieltjesCoordinate
assert_no_sorry Erdos390.WholePaper.measurable_roughSaiasStieltjesTestRightDerivative
assert_no_sorry Erdos390.WholePaper.roughSaiasStieltjesTestRightDerivative_abs_le
assert_no_sorry Erdos390.WholePaper.integrableOn_roughSaiasStieltjesTestRightDerivative
