import Erdos390.WholePaper.SafeShortIntervalPrimeCounting
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for safe moving short-interval prime counting -/

#print axioms Erdos390.WholePaper.SafePrimeCounting.movingEndpoint_log_ratio_tendsto_one
#print axioms Erdos390.WholePaper.SafePrimeCounting.theta_movingEndpoint_error_normalized_tendsto_zero
#print axioms Erdos390.WholePaper.SafePrimeCounting.theta_shortMovingInterval_normalized_tendsto
#print axioms Erdos390.WholePaper.SafePrimeCounting.theta_natCast_sub_eq_sum_prime_Ioc
#print axioms Erdos390.WholePaper.SafePrimeCounting.prime_Ioc_log_weight_bounds
#print axioms Erdos390.WholePaper.SafePrimeCounting.prime_Ioc_card_eq_primeCounting_sub
#print axioms Erdos390.WholePaper.SafePrimeCounting.prime_Ioc_shortMovingInterval_normalized_tendsto
#print axioms Erdos390.WholePaper.SafePrimeCounting.primeCounting_sub_shortMovingInterval_normalized_tendsto

assert_no_sorry Erdos390.WholePaper.SafePrimeCounting.movingEndpoint_log_ratio_tendsto_one
assert_no_sorry Erdos390.WholePaper.SafePrimeCounting.theta_movingEndpoint_error_normalized_tendsto_zero
assert_no_sorry Erdos390.WholePaper.SafePrimeCounting.theta_shortMovingInterval_normalized_tendsto
assert_no_sorry Erdos390.WholePaper.SafePrimeCounting.theta_natCast_sub_eq_sum_prime_Ioc
assert_no_sorry Erdos390.WholePaper.SafePrimeCounting.prime_Ioc_log_weight_bounds
assert_no_sorry Erdos390.WholePaper.SafePrimeCounting.prime_Ioc_card_eq_primeCounting_sub
assert_no_sorry Erdos390.WholePaper.SafePrimeCounting.prime_Ioc_shortMovingInterval_normalized_tendsto
assert_no_sorry Erdos390.WholePaper.SafePrimeCounting.primeCounting_sub_shortMovingInterval_normalized_tendsto
