import Erdos390.WholePaper.StationaryPrefixValuationAsymptotic
import Mathlib.Util.AssertNoSorry

/-! Transitive axiom and sorry audit for the actual prefix-product valuation. -/

#print axioms Erdos390.WholePaper.stationaryPrefixCofactorProduct_factorization
#print axioms Erdos390.WholePaper.stationaryPrefixCofactorProduct_factorization_normalized_tendsto
#print axioms Erdos390.WholePaper.stationaryPrefixCofactorProductUpTo_factorization_normalized_tendsto
#print axioms Erdos390.WholePaper.eventually_stationaryPrefixCofactorProductUpTo_factorization_le_real
#print axioms Erdos390.WholePaper.eventually_stationaryPrefixCofactorProductUpTo_factorization_le_nat
#print axioms Erdos390.WholePaper.eventually_stationaryPrefixCofactorProductUpTo_factorization_le_on_primesUpTo
#print axioms Erdos390.WholePaper.exists_stationaryPrefixParts_with_valuation_capacity

assert_no_sorry Erdos390.WholePaper.stationaryPrefixCofactorProduct_factorization
assert_no_sorry Erdos390.WholePaper.stationaryPrefixCofactorProduct_factorization_normalized_tendsto
assert_no_sorry Erdos390.WholePaper.stationaryPrefixCofactorProductUpTo_factorization_normalized_tendsto
assert_no_sorry Erdos390.WholePaper.eventually_stationaryPrefixCofactorProductUpTo_factorization_le_real
assert_no_sorry Erdos390.WholePaper.eventually_stationaryPrefixCofactorProductUpTo_factorization_le_nat
assert_no_sorry Erdos390.WholePaper.eventually_stationaryPrefixCofactorProductUpTo_factorization_le_on_primesUpTo
assert_no_sorry Erdos390.WholePaper.exists_stationaryPrefixParts_with_valuation_capacity
