import Erdos390.WholePaper.StationaryPrefixCentralCofactorChoice
import Mathlib.Util.AssertNoSorry

/-! Transitive axiom audit for the actual product and capacity layer. -/

#print axioms Erdos390.WholePaper.stationaryPrefixMarkedTriple_marker_mem_largeCentralPrimes
#print axioms Erdos390.WholePaper.stationaryPrefixMarkedTriples_prod_cofactor
#print axioms Erdos390.WholePaper.exists_stationaryPrefixMarkedTriple_of_mem_largeCentralPrimes
#print axioms Erdos390.WholePaper.largeCentralCofactorProduct_factorization_eq_sum
#print axioms Erdos390.WholePaper.largeCentralCofactorProduct_stationaryPrefixCofactorChoice
#print axioms Erdos390.WholePaper.fullCentralAnchors_prod_stationaryPrefixCofactorChoice
#print axioms Erdos390.WholePaper.eventually_stationaryPrefixCofactorChoice_certificate
#print axioms Erdos390.WholePaper.eventually_stationaryPrefixCofactorChoice_factorization_le_on_primesUpTo

assert_no_sorry Erdos390.WholePaper.stationaryPrefixMarkedTriple_marker_mem_largeCentralPrimes
assert_no_sorry Erdos390.WholePaper.stationaryPrefixMarkedTriples_prod_cofactor
assert_no_sorry Erdos390.WholePaper.exists_stationaryPrefixMarkedTriple_of_mem_largeCentralPrimes
assert_no_sorry Erdos390.WholePaper.largeCentralCofactorProduct_factorization_eq_sum
assert_no_sorry Erdos390.WholePaper.largeCentralCofactorProduct_stationaryPrefixCofactorChoice
assert_no_sorry Erdos390.WholePaper.fullCentralAnchors_prod_stationaryPrefixCofactorChoice
assert_no_sorry Erdos390.WholePaper.eventually_stationaryPrefixCofactorChoice_certificate
assert_no_sorry Erdos390.WholePaper.eventually_stationaryPrefixCofactorChoice_factorization_le_on_primesUpTo
