import Erdos390.WholePaper.TangentCollisionCounting
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for tangent collision counting -/

#print axioms Erdos390.WholePaper.tangentFiniteUniformMeasure_apply
#print axioms Erdos390.WholePaper.tangentUniformMultiplierMeasure_eq_uniformOfFintype
#print axioms Erdos390.WholePaper.tangentUniformMultiplierRestriction_map_eq_uniformOfFintype
#print axioms Erdos390.WholePaper.tangentUniformMultiplierRestrictionMeasure_apply
#print axioms Erdos390.WholePaper.tangentCollisionProbability_eq_configurationCount_div
#print axioms Erdos390.WholePaper.tangentCollisionOn_iff_exists_endpointEquation
#print axioms Erdos390.WholePaper.card_tangentCollisionConfigurations_le_fourEndpointEquations
#print axioms Erdos390.WholePaper.card_tangentEndpointEquationConfigurations_le_solutions
#print axioms Erdos390.WholePaper.card_tangentEndpointEquationSolutions_same_le
#print axioms Erdos390.WholePaper.card_tangentEndpointEquationSolutions_coprime_le
#print axioms Erdos390.WholePaper.card_tangentEndpointEquationSolutions_prime_le_budget
#print axioms Erdos390.WholePaper.tangentEndpointEquationBudget_comm
#print axioms Erdos390.WholePaper.tangentOrderedPairEndpointBudget_comm
#print axioms Erdos390.WholePaper.card_tangentCollisionConfigurations_le_endpointBudget
#print axioms Erdos390.WholePaper.tangentCollisionProbability_le_endpointBudget_div_lowerChoiceCount
#print axioms Erdos390.WholePaper.tangentCollisionLowerChoiceCount_pair
#print axioms Erdos390.WholePaper.tangentCollisionChoiceCount_pair
#print axioms Erdos390.WholePaper.tangentCollisionEndpointBudget_pair
#print axioms Erdos390.WholePaper.tangentRequestCollisionMass_eq_sum_otherRequests
#print axioms Erdos390.WholePaper.tangentRequestCollisionMass_le_loadBudget
#print axioms Erdos390.WholePaper.tangentRequestCollisionMass_le_fullLoadBudget
#print axioms Erdos390.WholePaper.tangentRequestCollisionMass_le_sum_endpointBudgetQuotients
#print axioms Erdos390.WholePaper.tangentCleanMultiplierLists_endpoint_le_broadUpper
#print axioms Erdos390.WholePaper.tangentCleanRequestCollisionMass_le_sum_endpointBudgetQuotients
#print axioms Erdos390.WholePaper.tangentCleanRequestCollisionMass_le_eighth_of_exactCounting
#print axioms Erdos390.WholePaper.tangentCleanCommonMultiplier_collisionFree_of_exactCounting
#print axioms Erdos390.WholePaper.tangentCleanRequestCollisionMass_le_loadBudget
#print axioms Erdos390.WholePaper.tangentCleanRequestCollisionMass_le_eighth_of_counting
#print axioms Erdos390.WholePaper.tangentCleanCommonMultiplier_collisionFree_of_counting

assert_no_sorry Erdos390.WholePaper.tangentFiniteUniformMeasure_apply
assert_no_sorry Erdos390.WholePaper.tangentUniformMultiplierMeasure_eq_uniformOfFintype
assert_no_sorry Erdos390.WholePaper.tangentUniformMultiplierRestriction_map_eq_uniformOfFintype
assert_no_sorry Erdos390.WholePaper.tangentUniformMultiplierRestrictionMeasure_apply
assert_no_sorry Erdos390.WholePaper.tangentCollisionProbability_eq_configurationCount_div
assert_no_sorry Erdos390.WholePaper.tangentCollisionOn_iff_exists_endpointEquation
assert_no_sorry Erdos390.WholePaper.card_tangentCollisionConfigurations_le_fourEndpointEquations
assert_no_sorry Erdos390.WholePaper.card_tangentEndpointEquationConfigurations_le_solutions
assert_no_sorry Erdos390.WholePaper.card_tangentEndpointEquationSolutions_same_le
assert_no_sorry Erdos390.WholePaper.card_tangentEndpointEquationSolutions_coprime_le
assert_no_sorry Erdos390.WholePaper.card_tangentEndpointEquationSolutions_prime_le_budget
assert_no_sorry Erdos390.WholePaper.tangentEndpointEquationBudget_comm
assert_no_sorry Erdos390.WholePaper.tangentOrderedPairEndpointBudget_comm
assert_no_sorry Erdos390.WholePaper.card_tangentCollisionConfigurations_le_endpointBudget
assert_no_sorry Erdos390.WholePaper.tangentCollisionProbability_le_endpointBudget_div_lowerChoiceCount
assert_no_sorry Erdos390.WholePaper.tangentCollisionLowerChoiceCount_pair
assert_no_sorry Erdos390.WholePaper.tangentCollisionChoiceCount_pair
assert_no_sorry Erdos390.WholePaper.tangentCollisionEndpointBudget_pair
assert_no_sorry Erdos390.WholePaper.tangentRequestCollisionMass_eq_sum_otherRequests
assert_no_sorry Erdos390.WholePaper.tangentRequestCollisionMass_le_loadBudget
assert_no_sorry Erdos390.WholePaper.tangentRequestCollisionMass_le_fullLoadBudget
assert_no_sorry Erdos390.WholePaper.tangentRequestCollisionMass_le_sum_endpointBudgetQuotients
assert_no_sorry Erdos390.WholePaper.tangentCleanMultiplierLists_endpoint_le_broadUpper
assert_no_sorry Erdos390.WholePaper.tangentCleanRequestCollisionMass_le_sum_endpointBudgetQuotients
assert_no_sorry Erdos390.WholePaper.tangentCleanRequestCollisionMass_le_eighth_of_exactCounting
assert_no_sorry Erdos390.WholePaper.tangentCleanCommonMultiplier_collisionFree_of_exactCounting
assert_no_sorry Erdos390.WholePaper.tangentCleanRequestCollisionMass_le_loadBudget
assert_no_sorry Erdos390.WholePaper.tangentCleanRequestCollisionMass_le_eighth_of_counting
assert_no_sorry Erdos390.WholePaper.tangentCleanCommonMultiplier_collisionFree_of_counting
