import Erdos390.WholePaper.TangentBalancedProductFlow
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the balanced product transport -/

#print axioms Erdos390.WholePaper.tangentPositiveMass
#print axioms Erdos390.WholePaper.tangentNegativeMass
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow
#print axioms Erdos390.WholePaper.tangentPositiveMass_nonneg
#print axioms Erdos390.WholePaper.tangentNegativeMass_nonneg
#print axioms Erdos390.WholePaper.tangentPositiveMass_eq_negativeMass
#print axioms Erdos390.WholePaper.tangentPositiveMass_add_negativeMass
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_nonneg
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_eq_zero_of_positiveMass_eq_zero
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_self
#print axioms Erdos390.WholePaper.tangentBalanced_eq_zero_of_positiveMass_eq_zero
#print axioms Erdos390.WholePaper.sum_tangentBalancedProductFlow_out
#print axioms Erdos390.WholePaper.sum_tangentBalancedProductFlow_in
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_divergence_eq
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_traffic_eq_positiveMass
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_traffic_eq_half_sum_abs
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_incident_eq_abs
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_positive_endpoints_ne

assert_no_sorry Erdos390.WholePaper.tangentPositiveMass
assert_no_sorry Erdos390.WholePaper.tangentNegativeMass
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow
assert_no_sorry Erdos390.WholePaper.tangentPositiveMass_nonneg
assert_no_sorry Erdos390.WholePaper.tangentNegativeMass_nonneg
assert_no_sorry Erdos390.WholePaper.tangentPositiveMass_eq_negativeMass
assert_no_sorry Erdos390.WholePaper.tangentPositiveMass_add_negativeMass
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_nonneg
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_eq_zero_of_positiveMass_eq_zero
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_self
assert_no_sorry Erdos390.WholePaper.tangentBalanced_eq_zero_of_positiveMass_eq_zero
assert_no_sorry Erdos390.WholePaper.sum_tangentBalancedProductFlow_out
assert_no_sorry Erdos390.WholePaper.sum_tangentBalancedProductFlow_in
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_divergence_eq
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_traffic_eq_positiveMass
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_traffic_eq_half_sum_abs
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_incident_eq_abs
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_positive_endpoints_ne
