import Erdos390.WholePaper.TangentCleanListCardinalityBridge
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the tangent clean-list cardinality bridge -/

#print axioms Erdos390.WholePaper.tangentHeadCoprimeCandidates
#print axioms Erdos390.WholePaper.tangentHeadCoprimeCandidates_eq_reducedResidueIoc
#print axioms Erdos390.WholePaper.card_tangentHeadCoprimeCandidates_add_headBad
#print axioms Erdos390.WholePaper.tangentCleanCommonMultiplierList_card_lower_of_headCandidate
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperCleanCommonMultiplierList_card_lower_of_headCandidate
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperCleanCommonMultiplierList_card_lower_of_abstractSelberg

assert_no_sorry Erdos390.WholePaper.tangentHeadCoprimeCandidates
assert_no_sorry Erdos390.WholePaper.tangentHeadCoprimeCandidates_eq_reducedResidueIoc
assert_no_sorry Erdos390.WholePaper.card_tangentHeadCoprimeCandidates_add_headBad
assert_no_sorry Erdos390.WholePaper.tangentCleanCommonMultiplierList_card_lower_of_headCandidate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperCleanCommonMultiplierList_card_lower_of_headCandidate
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperCleanCommonMultiplierList_card_lower_of_abstractSelberg
