import Erdos390.WholePaper.TangentDistributedFlowCensus
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the distributed tangent census -/

#print axioms Erdos390.WholePaper.tangentDistributedTotalTrafficLedger
#print axioms Erdos390.WholePaper.tangentDistributedLabelIncidentLedger
#print axioms Erdos390.WholePaper.tangentDistributedSupportCount
#print axioms Erdos390.WholePaper.tangentDistributedResidualCollisionUpper
#print axioms Erdos390.WholePaper.TangentSameOrAdjacentRatioCell
#print axioms Erdos390.WholePaper.TangentFlowRespectsRatioCells
#print axioms Erdos390.WholePaper.TangentRatioCellGeometry
#print axioms Erdos390.WholePaper.tangentRatioCellPrefixMass
#print axioms Erdos390.WholePaper.tangentRatioCellTailPointwiseUpper
#print axioms Erdos390.WholePaper.tangentRatioCellCutTraffic
#print axioms Erdos390.WholePaper.tangentRatioCellCard
#print axioms Erdos390.WholePaper.tangentRatioCellLeftPrefixMass
#print axioms Erdos390.WholePaper.tangentRatioCellUniformPortLoad
#print axioms Erdos390.WholePaper.tangentRatioCellPointwisePortUpper
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryDivergence
#print axioms Erdos390.WholePaper.tangentRatioCellInternalResidual
#print axioms Erdos390.WholePaper.tangentPositiveEdge_sameOrAdjacentRatioCell
#print axioms Erdos390.WholePaper.tangentPositiveEdge_locality_of_ratioCells
#print axioms Erdos390.WholePaper.tangentRatioCellCutTraffic_nonneg
#print axioms Erdos390.WholePaper.tangentRatioCellUniformPortLoad_nonneg
#print axioms Erdos390.WholePaper.tangentRatioCellPrefixMass_add_tail_eq_bandSum
#print axioms Erdos390.WholePaper.abs_tangentRatioCellPrefixMass_le_tailPointwiseUpper
#print axioms Erdos390.WholePaper.tangentRatioCellUniformPortLoad_le_pointwisePortUpper
#print axioms Erdos390.WholePaper.abs_tangentRatioCellBoundaryDivergence_le_portLoad
#print axioms Erdos390.WholePaper.abs_internalResidual_add_portLoad_le
#print axioms Erdos390.WholePaper.card_tangentPositiveFlowEdges_le_distributedSupportCount
#print axioms Erdos390.WholePaper.tangentDistributedPositiveEdge_labels_ne
#print axioms Erdos390.WholePaper.tangentDistributedPositiveEdge_locality
#print axioms Erdos390.WholePaper.sum_tangentDistributedPositiveEdges_le_trafficLedger
#print axioms Erdos390.WholePaper.sum_tangentPositiveFlowEdges_mul_eq_full_of_nonneg
#print axioms Erdos390.WholePaper.tangentDistributedPositiveEdges_boundary_eq_residual
#print axioms Erdos390.WholePaper.tangentDistributedPositiveEdges_factorizationBoundary_eq_residual
#print axioms Erdos390.WholePaper.tangentDistributedSplitRequest_factorizationBoundary_eq_residual
#print axioms Erdos390.WholePaper.tangentDistributedLabelIncidentLedger_at_label
#print axioms Erdos390.WholePaper.tangentDistributedLabelIncidentLedger_mul_le
#print axioms Erdos390.WholePaper.tangentDistributedWeightedIncident_le
#print axioms Erdos390.WholePaper.tangentDistributedIncidentTraffic_le_ledger
#print axioms Erdos390.WholePaper.tangentDistributedTotalRequestCount_le
#print axioms Erdos390.WholePaper.tangentDistributedLabelRequestLoad_le
#print axioms Erdos390.WholePaper.tangentDistributedWeightedLabelCensusUpper_le
#print axioms Erdos390.WholePaper.tangentDistributedWeightedLabelRequestLoad_le
#print axioms Erdos390.WholePaper.tangentDistributedPaperMainBudget
#print axioms Erdos390.WholePaper.tangentDistributedPaperErrorBudget
#print axioms Erdos390.WholePaper.tangentDistributedPaperCeilingBudget
#print axioms Erdos390.WholePaper.tangentDistributedResidualCollisionUpper_le_paperBudgets
#print axioms Erdos390.WholePaper.tangentDistributedResidualCollisionUpper_le_of_paperSmallness
#print axioms Erdos390.WholePaper.tangentDistributedRequest_census_small_of_paperBounds
#print axioms Erdos390.WholePaper.tangentDistributedCollisionCensusBudget_le_eighth_of_paperBounds
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperDistributedSplitEndpointsDistinct_of_residualCensus

assert_no_sorry Erdos390.WholePaper.tangentDistributedTotalTrafficLedger
assert_no_sorry Erdos390.WholePaper.tangentDistributedLabelIncidentLedger
assert_no_sorry Erdos390.WholePaper.tangentDistributedSupportCount
assert_no_sorry Erdos390.WholePaper.tangentDistributedResidualCollisionUpper
assert_no_sorry Erdos390.WholePaper.TangentSameOrAdjacentRatioCell
assert_no_sorry Erdos390.WholePaper.TangentFlowRespectsRatioCells
assert_no_sorry Erdos390.WholePaper.TangentRatioCellGeometry
assert_no_sorry Erdos390.WholePaper.tangentRatioCellPrefixMass
assert_no_sorry Erdos390.WholePaper.tangentRatioCellTailPointwiseUpper
assert_no_sorry Erdos390.WholePaper.tangentRatioCellCutTraffic
assert_no_sorry Erdos390.WholePaper.tangentRatioCellCard
assert_no_sorry Erdos390.WholePaper.tangentRatioCellLeftPrefixMass
assert_no_sorry Erdos390.WholePaper.tangentRatioCellUniformPortLoad
assert_no_sorry Erdos390.WholePaper.tangentRatioCellPointwisePortUpper
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryDivergence
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalResidual
assert_no_sorry Erdos390.WholePaper.tangentPositiveEdge_sameOrAdjacentRatioCell
assert_no_sorry Erdos390.WholePaper.tangentPositiveEdge_locality_of_ratioCells
assert_no_sorry Erdos390.WholePaper.tangentRatioCellCutTraffic_nonneg
assert_no_sorry Erdos390.WholePaper.tangentRatioCellUniformPortLoad_nonneg
assert_no_sorry Erdos390.WholePaper.tangentRatioCellPrefixMass_add_tail_eq_bandSum
assert_no_sorry Erdos390.WholePaper.abs_tangentRatioCellPrefixMass_le_tailPointwiseUpper
assert_no_sorry Erdos390.WholePaper.tangentRatioCellUniformPortLoad_le_pointwisePortUpper
assert_no_sorry Erdos390.WholePaper.abs_tangentRatioCellBoundaryDivergence_le_portLoad
assert_no_sorry Erdos390.WholePaper.abs_internalResidual_add_portLoad_le
assert_no_sorry Erdos390.WholePaper.card_tangentPositiveFlowEdges_le_distributedSupportCount
assert_no_sorry Erdos390.WholePaper.tangentDistributedPositiveEdge_labels_ne
assert_no_sorry Erdos390.WholePaper.tangentDistributedPositiveEdge_locality
assert_no_sorry Erdos390.WholePaper.sum_tangentDistributedPositiveEdges_le_trafficLedger
assert_no_sorry Erdos390.WholePaper.sum_tangentPositiveFlowEdges_mul_eq_full_of_nonneg
assert_no_sorry Erdos390.WholePaper.tangentDistributedPositiveEdges_boundary_eq_residual
assert_no_sorry Erdos390.WholePaper.tangentDistributedPositiveEdges_factorizationBoundary_eq_residual
assert_no_sorry Erdos390.WholePaper.tangentDistributedSplitRequest_factorizationBoundary_eq_residual
assert_no_sorry Erdos390.WholePaper.tangentDistributedLabelIncidentLedger_at_label
assert_no_sorry Erdos390.WholePaper.tangentDistributedLabelIncidentLedger_mul_le
assert_no_sorry Erdos390.WholePaper.tangentDistributedWeightedIncident_le
assert_no_sorry Erdos390.WholePaper.tangentDistributedIncidentTraffic_le_ledger
assert_no_sorry Erdos390.WholePaper.tangentDistributedTotalRequestCount_le
assert_no_sorry Erdos390.WholePaper.tangentDistributedLabelRequestLoad_le
assert_no_sorry Erdos390.WholePaper.tangentDistributedWeightedLabelCensusUpper_le
assert_no_sorry Erdos390.WholePaper.tangentDistributedWeightedLabelRequestLoad_le
assert_no_sorry Erdos390.WholePaper.tangentDistributedPaperMainBudget
assert_no_sorry Erdos390.WholePaper.tangentDistributedPaperErrorBudget
assert_no_sorry Erdos390.WholePaper.tangentDistributedPaperCeilingBudget
assert_no_sorry Erdos390.WholePaper.tangentDistributedResidualCollisionUpper_le_paperBudgets
assert_no_sorry Erdos390.WholePaper.tangentDistributedResidualCollisionUpper_le_of_paperSmallness
assert_no_sorry Erdos390.WholePaper.tangentDistributedRequest_census_small_of_paperBounds
assert_no_sorry Erdos390.WholePaper.tangentDistributedCollisionCensusBudget_le_eighth_of_paperBounds
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperDistributedSplitEndpointsDistinct_of_residualCensus
