import Erdos390.WholePaper.TangentLLLNumerics
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.one_sub_sum_le_prod_one_sub
#print axioms Erdos390.WholePaper.half_le_prod_one_sub_two_mul
#print axioms Erdos390.WholePaper.probability_le_two_mul_probability_mul_neighborProduct
#print axioms Erdos390.WholePaper.probability_le_two_mul_probability_mul_neighborProduct_of_requestMass

assert_no_sorry Erdos390.WholePaper.one_sub_sum_le_prod_one_sub
assert_no_sorry Erdos390.WholePaper.half_le_prod_one_sub_two_mul
assert_no_sorry Erdos390.WholePaper.probability_le_two_mul_probability_mul_neighborProduct
assert_no_sorry Erdos390.WholePaper.probability_le_two_mul_probability_mul_neighborProduct_of_requestMass
