import Erdos390.WholePaper.TangentPaperCleanListAbsorption
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the literal paper-scale tangent absorption

All 17 public theorems are printed and checked for `sorry`.
-/

#print axioms Erdos390.WholePaper.tangentPaperHeadGap_pos
#print axioms Erdos390.WholePaper.tangentPaperCleanListDensity_pos
#print axioms Erdos390.WholePaper.tangentPaperExceptionalCutoff_cast_ge
#print axioms Erdos390.WholePaper.tangentPaperExceptionalCutoff_cast_lt_add_one
#print axioms Erdos390.WholePaper.tangentPaperExceptionalCutoff_le_roughScale_implies_real
#print axioms Erdos390.WholePaper.tangentPaperExceptionalCutoff_pos
#print axioms Erdos390.WholePaper.tangentPaperExceptionalCutoff_log_le
#print axioms Erdos390.WholePaper.tangentCanonicalExceptionalLengthSum_le_harmonic
#print axioms Erdos390.WholePaper.tangentCanonicalExceptionalLengthSum_normalized_le_harmonic
#print axioms Erdos390.WholePaper.tangentPaper_yNat_div_self_tendsto_zero
#print axioms Erdos390.WholePaper.tangentPaperSharpDeletion_mul_yNat_div_self_tendsto_zero
#print axioms Erdos390.WholePaper.eventually_tangentCanonicalExceptionalMain_normalized_le_paperGap
#print axioms Erdos390.WholePaper.eventually_tangentCanonicalExceptionalRemainder_normalized_le_paperGap
#print axioms Erdos390.WholePaper.tangentRoughHeadCandidateMain_normalized_ge_three_quarters
#print axioms Erdos390.WholePaper.eventually_tangentRoughHeadCandidateMain_normalized_ge_three_quarters
#print axioms Erdos390.WholePaper.eventually_tangentPaper_candidateFloor_absorbs_canonicalLosses
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_tangentPaperCleanCommonMultiplierList_card_lower_absorbed

assert_no_sorry Erdos390.WholePaper.tangentPaperHeadGap_pos
assert_no_sorry Erdos390.WholePaper.tangentPaperCleanListDensity_pos
assert_no_sorry Erdos390.WholePaper.tangentPaperExceptionalCutoff_cast_ge
assert_no_sorry Erdos390.WholePaper.tangentPaperExceptionalCutoff_cast_lt_add_one
assert_no_sorry Erdos390.WholePaper.tangentPaperExceptionalCutoff_le_roughScale_implies_real
assert_no_sorry Erdos390.WholePaper.tangentPaperExceptionalCutoff_pos
assert_no_sorry Erdos390.WholePaper.tangentPaperExceptionalCutoff_log_le
assert_no_sorry Erdos390.WholePaper.tangentCanonicalExceptionalLengthSum_le_harmonic
assert_no_sorry Erdos390.WholePaper.tangentCanonicalExceptionalLengthSum_normalized_le_harmonic
assert_no_sorry Erdos390.WholePaper.tangentPaper_yNat_div_self_tendsto_zero
assert_no_sorry Erdos390.WholePaper.tangentPaperSharpDeletion_mul_yNat_div_self_tendsto_zero
assert_no_sorry Erdos390.WholePaper.eventually_tangentCanonicalExceptionalMain_normalized_le_paperGap
assert_no_sorry Erdos390.WholePaper.eventually_tangentCanonicalExceptionalRemainder_normalized_le_paperGap
assert_no_sorry Erdos390.WholePaper.tangentRoughHeadCandidateMain_normalized_ge_three_quarters
assert_no_sorry Erdos390.WholePaper.eventually_tangentRoughHeadCandidateMain_normalized_ge_three_quarters
assert_no_sorry Erdos390.WholePaper.eventually_tangentPaper_candidateFloor_absorbs_canonicalLosses
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_tangentPaperCleanCommonMultiplierList_card_lower_absorbed
