import Erdos390.WholePaper.TangentExceptionalSelbergReduction
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the exceptional-row Selberg reduction -/

#print axioms Erdos390.WholePaper.tangentReciprocalArithmeticFunction_isMultiplicative
#print axioms Erdos390.WholePaper.tangentReciprocalArithmeticFunction_apply_of_pos
#print axioms Erdos390.WholePaper.roughHeadModulus_squarefree
#print axioms Erdos390.WholePaper.completeRoughLabel_coprime_roughHeadModulus
#print axioms Erdos390.WholePaper.tangentIntervalReciprocalSieve_siftedSum
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_le_abstractSelberg
#print axioms Erdos390.WholePaper.Ioc_filter_dvd_card_eq_div_sub_div
#print axioms Erdos390.WholePaper.tangentIntervalReciprocalSieve_multSum
#print axioms Erdos390.WholePaper.tangentIntervalReciprocalSieve_rem_abs_lt_one
#print axioms Erdos390.WholePaper.tangentIntervalReciprocalSieve_rem_abs_lt_one_total
#print axioms Erdos390.WholePaper.tangentIntervalReciprocalSieve_errSum_le_l1
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_le_abstractSelberg_l1
#print axioms Erdos390.WholePaper.tangentRoughDecompositionIndex_injective
#print axioms Erdos390.WholePaper.card_tangentExceptionalSmoothIndices_le_div
#print axioms Erdos390.WholePaper.tangentExceptional_l1_accumulation_eq
#print axioms Erdos390.WholePaper.tangentExceptional_l1_accumulation_le_div
#print axioms Erdos390.WholePaper.tangentExceptional_l1_accumulation_le_of_bound
#print axioms Erdos390.WholePaper.tangentRoughDecompositionIndex_mem_exceptionalSievePairs
#print axioms Erdos390.WholePaper.card_tangentExceptionalMultipliers_le_sieveSum
#print axioms Erdos390.WholePaper.tangentExceptionalMultipliers_card_cast_le_abstractSelbergMajorant
#print axioms Erdos390.WholePaper.tangentExceptionalMultipliers_card_cast_le_abstractSelbergL1Majorant
#print axioms Erdos390.WholePaper.tangentExceptionalMultipliers_card_le_abstractSelbergNatMajorant
#print axioms Erdos390.WholePaper.tangentCommonMultiplier_abstractSelberg_finite_deletion_ledger
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperCommonMultiplier_abstractSelberg_sharp_ledger
#print axioms Erdos390.WholePaper.tangentExceptional_y_pow_four
#print axioms Erdos390.WholePaper.tangentExceptional_yNat_pow_four_le
#print axioms Erdos390.WholePaper.tangentExceptional_deltaStar_remainder_exponent
#print axioms Erdos390.WholePaper.tangentExceptional_remainderPower_tendsto_zero

assert_no_sorry Erdos390.WholePaper.tangentReciprocalArithmeticFunction_isMultiplicative
assert_no_sorry Erdos390.WholePaper.tangentReciprocalArithmeticFunction_apply_of_pos
assert_no_sorry Erdos390.WholePaper.roughHeadModulus_squarefree
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_coprime_roughHeadModulus
assert_no_sorry Erdos390.WholePaper.tangentIntervalReciprocalSieve_siftedSum
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_le_abstractSelberg
assert_no_sorry Erdos390.WholePaper.Ioc_filter_dvd_card_eq_div_sub_div
assert_no_sorry Erdos390.WholePaper.tangentIntervalReciprocalSieve_multSum
assert_no_sorry Erdos390.WholePaper.tangentIntervalReciprocalSieve_rem_abs_lt_one
assert_no_sorry Erdos390.WholePaper.tangentIntervalReciprocalSieve_rem_abs_lt_one_total
assert_no_sorry Erdos390.WholePaper.tangentIntervalReciprocalSieve_errSum_le_l1
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_le_abstractSelberg_l1
assert_no_sorry Erdos390.WholePaper.tangentRoughDecompositionIndex_injective
assert_no_sorry Erdos390.WholePaper.card_tangentExceptionalSmoothIndices_le_div
assert_no_sorry Erdos390.WholePaper.tangentExceptional_l1_accumulation_eq
assert_no_sorry Erdos390.WholePaper.tangentExceptional_l1_accumulation_le_div
assert_no_sorry Erdos390.WholePaper.tangentExceptional_l1_accumulation_le_of_bound
assert_no_sorry Erdos390.WholePaper.tangentRoughDecompositionIndex_mem_exceptionalSievePairs
assert_no_sorry Erdos390.WholePaper.card_tangentExceptionalMultipliers_le_sieveSum
assert_no_sorry Erdos390.WholePaper.tangentExceptionalMultipliers_card_cast_le_abstractSelbergMajorant
assert_no_sorry Erdos390.WholePaper.tangentExceptionalMultipliers_card_cast_le_abstractSelbergL1Majorant
assert_no_sorry Erdos390.WholePaper.tangentExceptionalMultipliers_card_le_abstractSelbergNatMajorant
assert_no_sorry Erdos390.WholePaper.tangentCommonMultiplier_abstractSelberg_finite_deletion_ledger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperCommonMultiplier_abstractSelberg_sharp_ledger
assert_no_sorry Erdos390.WholePaper.tangentExceptional_y_pow_four
assert_no_sorry Erdos390.WholePaper.tangentExceptional_yNat_pow_four_le
assert_no_sorry Erdos390.WholePaper.tangentExceptional_deltaStar_remainder_exponent
assert_no_sorry Erdos390.WholePaper.tangentExceptional_remainderPower_tendsto_zero
