import Erdos390.WholePaper.TangentRatioCellEarthmover
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the explicit ratio-cell earthmover -/

#print axioms Erdos390.WholePaper.tangentRatioCellUniformWeight
#print axioms Erdos390.WholePaper.tangentRatioCellCard_at_vertex_pos
#print axioms Erdos390.WholePaper.tangentRatioCellCard_at_vertex_ne_zero
#print axioms Erdos390.WholePaper.tangentRatioCellUniformWeight_eq_zero_of_card_eq_zero
#print axioms Erdos390.WholePaper.tangentRatioCellUniformWeight_nonneg
#print axioms Erdos390.WholePaper.sum_tangentRatioCellUniformWeight
#print axioms Erdos390.WholePaper.tangentRatioCellUniformWeight_at_vertex
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_nonneg
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_eq_zero_of_left_empty
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_eq_zero_of_right_empty
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_self
#print axioms Erdos390.WholePaper.sum_tangentRatioCellBoundaryCutFlow_out
#print axioms Erdos390.WholePaper.sum_tangentRatioCellBoundaryCutFlow_in
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_divergence
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_divergence_of_mem_left
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_divergence_of_mem_right
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_traffic
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_incident
#print axioms Erdos390.WholePaper.tangentFlowDivergence_finset_sum
#print axioms Erdos390.WholePaper.tangentFlowTraffic_finset_sum
#print axioms Erdos390.WholePaper.tangentVertexIncident_finset_sum
#print axioms Erdos390.WholePaper.tangentRatioCellCanonicalCutTraffic
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow_nonneg
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow_self
#print axioms Erdos390.WholePaper.tangentRatioCellPrefixMass_lastCell
#print axioms Erdos390.WholePaper.sum_tangentRatioCell_eq_prefix_sub_left
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow_divergence_cutSum
#print axioms Erdos390.WholePaper.sum_prefix_mul_leftUniformWeight
#print axioms Erdos390.WholePaper.sum_prefix_mul_rightUniformWeight
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow_divergence_eq
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow_traffic_eq
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow_incident_cutSum
#print axioms Erdos390.WholePaper.sum_abs_prefix_mul_leftUniformWeight
#print axioms Erdos390.WholePaper.sum_abs_prefix_mul_rightUniformWeight
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow_incident_eq_portLoad
#print axioms Erdos390.WholePaper.tangentRatioCellMaskedInternalResidual
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_nonneg
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_self
#print axioms Erdos390.WholePaper.sum_tangentRatioCellBoundaryDivergence_eq_prefix_sub_left
#print axioms Erdos390.WholePaper.sum_tangentRatioCellMaskedInternalResidual_eq_zero
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_divergence_cutSum
#print axioms Erdos390.WholePaper.sum_tangentRatioCellMaskedInternalResidual_at_vertex
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_divergence_eq
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_incident_cutSum
#print axioms Erdos390.WholePaper.sum_abs_tangentRatioCellMaskedInternalResidual_at_vertex
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_incident_eq_abs
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_traffic_cutSum
#print axioms Erdos390.WholePaper.sum_abs_tangentRatioCellMaskedInternalResidual_partition
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_traffic_eq
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_positive_cells
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_respectsRatioCells
#print axioms Erdos390.WholePaper.tangentRatioCellBoundaryFlow_respectsRatioCells
#print axioms Erdos390.WholePaper.tangentBalancedProductFlow_masked_positive_cells
#print axioms Erdos390.WholePaper.tangentRatioCellInternalFlow_respectsRatioCells
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow
#print axioms Erdos390.WholePaper.tangentFlowDivergence_add
#print axioms Erdos390.WholePaper.tangentFlowTraffic_add
#print axioms Erdos390.WholePaper.tangentVertexIncident_add
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_nonneg
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_self
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_positive_endpoints_ne
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_respectsRatioCells
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_divergence_eq
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_incident_eq
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_incident_le
#print axioms Erdos390.WholePaper.sum_tangentVertexIncident_eq_two_traffic
#print axioms Erdos390.WholePaper.sum_tangentRatioCellUniformPortLoad_eq_two_cutTraffic
#print axioms Erdos390.WholePaper.sum_abs_tangentRatioCellInternalResidual_le
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_traffic_eq
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_traffic_le
#print axioms Erdos390.WholePaper.sum_union_le_add_sum_of_nonneg_real
#print axioms Erdos390.WholePaper.sum_source_filter_eq_outgoing
#print axioms Erdos390.WholePaper.sum_target_filter_eq_incoming
#print axioms Erdos390.WholePaper.tangentIncidentPositiveFlowMass_le_vertexIncident
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_positiveIncident_le
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_positiveEdge_locality
#print axioms Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_spec
#print axioms Erdos390.WholePaper.tangentRatioCellCanonicalCutTraffic_le_prefixUpper

assert_no_sorry Erdos390.WholePaper.tangentRatioCellUniformWeight
assert_no_sorry Erdos390.WholePaper.tangentRatioCellCard_at_vertex_pos
assert_no_sorry Erdos390.WholePaper.tangentRatioCellCard_at_vertex_ne_zero
assert_no_sorry Erdos390.WholePaper.tangentRatioCellUniformWeight_eq_zero_of_card_eq_zero
assert_no_sorry Erdos390.WholePaper.tangentRatioCellUniformWeight_nonneg
assert_no_sorry Erdos390.WholePaper.sum_tangentRatioCellUniformWeight
assert_no_sorry Erdos390.WholePaper.tangentRatioCellUniformWeight_at_vertex
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_nonneg
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_eq_zero_of_left_empty
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_eq_zero_of_right_empty
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_self
assert_no_sorry Erdos390.WholePaper.sum_tangentRatioCellBoundaryCutFlow_out
assert_no_sorry Erdos390.WholePaper.sum_tangentRatioCellBoundaryCutFlow_in
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_divergence
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_divergence_of_mem_left
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_divergence_of_mem_right
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_traffic
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_incident
assert_no_sorry Erdos390.WholePaper.tangentFlowDivergence_finset_sum
assert_no_sorry Erdos390.WholePaper.tangentFlowTraffic_finset_sum
assert_no_sorry Erdos390.WholePaper.tangentVertexIncident_finset_sum
assert_no_sorry Erdos390.WholePaper.tangentRatioCellCanonicalCutTraffic
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow_nonneg
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow_self
assert_no_sorry Erdos390.WholePaper.tangentRatioCellPrefixMass_lastCell
assert_no_sorry Erdos390.WholePaper.sum_tangentRatioCell_eq_prefix_sub_left
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow_divergence_cutSum
assert_no_sorry Erdos390.WholePaper.sum_prefix_mul_leftUniformWeight
assert_no_sorry Erdos390.WholePaper.sum_prefix_mul_rightUniformWeight
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow_divergence_eq
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow_traffic_eq
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow_incident_cutSum
assert_no_sorry Erdos390.WholePaper.sum_abs_prefix_mul_leftUniformWeight
assert_no_sorry Erdos390.WholePaper.sum_abs_prefix_mul_rightUniformWeight
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow_incident_eq_portLoad
assert_no_sorry Erdos390.WholePaper.tangentRatioCellMaskedInternalResidual
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_nonneg
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_self
assert_no_sorry Erdos390.WholePaper.sum_tangentRatioCellBoundaryDivergence_eq_prefix_sub_left
assert_no_sorry Erdos390.WholePaper.sum_tangentRatioCellMaskedInternalResidual_eq_zero
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_divergence_cutSum
assert_no_sorry Erdos390.WholePaper.sum_tangentRatioCellMaskedInternalResidual_at_vertex
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_divergence_eq
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_incident_cutSum
assert_no_sorry Erdos390.WholePaper.sum_abs_tangentRatioCellMaskedInternalResidual_at_vertex
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_incident_eq_abs
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_traffic_cutSum
assert_no_sorry Erdos390.WholePaper.sum_abs_tangentRatioCellMaskedInternalResidual_partition
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_traffic_eq
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_positive_cells
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryCutFlow_respectsRatioCells
assert_no_sorry Erdos390.WholePaper.tangentRatioCellBoundaryFlow_respectsRatioCells
assert_no_sorry Erdos390.WholePaper.tangentBalancedProductFlow_masked_positive_cells
assert_no_sorry Erdos390.WholePaper.tangentRatioCellInternalFlow_respectsRatioCells
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow
assert_no_sorry Erdos390.WholePaper.tangentFlowDivergence_add
assert_no_sorry Erdos390.WholePaper.tangentFlowTraffic_add
assert_no_sorry Erdos390.WholePaper.tangentVertexIncident_add
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_nonneg
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_self
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_positive_endpoints_ne
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_respectsRatioCells
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_divergence_eq
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_incident_eq
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_incident_le
assert_no_sorry Erdos390.WholePaper.sum_tangentVertexIncident_eq_two_traffic
assert_no_sorry Erdos390.WholePaper.sum_tangentRatioCellUniformPortLoad_eq_two_cutTraffic
assert_no_sorry Erdos390.WholePaper.sum_abs_tangentRatioCellInternalResidual_le
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_traffic_eq
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_traffic_le
assert_no_sorry Erdos390.WholePaper.sum_union_le_add_sum_of_nonneg_real
assert_no_sorry Erdos390.WholePaper.sum_source_filter_eq_outgoing
assert_no_sorry Erdos390.WholePaper.sum_target_filter_eq_incoming
assert_no_sorry Erdos390.WholePaper.tangentIncidentPositiveFlowMass_le_vertexIncident
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_positiveIncident_le
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_positiveEdge_locality
assert_no_sorry Erdos390.WholePaper.tangentRatioCellEarthmoverFlow_spec
assert_no_sorry Erdos390.WholePaper.tangentRatioCellCanonicalCutTraffic_le_prefixUpper
