import Erdos390.WholePaper.TangentExceptionalLambdaSquareSieve
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the concrete finite Lambda-squared sieve -/

#print axioms Erdos390.WholePaper.mem_tangentSelbergLambdaSupport
#print axioms Erdos390.WholePaper.tangentSelbergLambdaSupport_pos
#print axioms Erdos390.WholePaper.one_mem_tangentSelbergLambdaSupport
#print axioms Erdos390.WholePaper.sum_tangentSelbergLambdaSquareCoefficient_divisors
#print axioms Erdos390.WholePaper.tangentSelbergLambdaSquareCoefficient_isUpperMoebius
#print axioms Erdos390.WholePaper.tangentSelbergLambdaSquareCoefficient_eq_zero_of_level_sq_lt
#print axioms Erdos390.WholePaper.tangentSelbergLambdaSquareCoefficient_divisorMoment
#print axioms Erdos390.WholePaper.tangentSelbergLambdaSquare_mainQuadraticIdentity
#print axioms Erdos390.WholePaper.tangentIntervalReciprocalSieve_lambdaSquare_mainSum
#print axioms Erdos390.WholePaper.tangent_reciprocal_lcm_eq_totient_commonDivisorSum
#print axioms Erdos390.WholePaper.tangent_reciprocal_lcm_eq_totient_modulusSum
#print axioms Erdos390.WholePaper.tangentSelbergLambdaSquare_quadraticDiagonalization
#print axioms Erdos390.WholePaper.tangentSelberg_moebius_diagonal_constraint
#print axioms Erdos390.WholePaper.tangent_sum_moebius_quotients_over_divisors
#print axioms Erdos390.WholePaper.tangentSelberg_upper_moebius_inversion
#print axioms Erdos390.WholePaper.tangentSelbergDensitySum_pos
#print axioms Erdos390.WholePaper.tangentSelbergDensitySum_inv_le_quadratic
#print axioms Erdos390.WholePaper.tangentSelbergLambdaSquareCoefficient_l1_le
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_le_lambdaSquare
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_le_lambdaSquare_of_bounds
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_le_lambdaSquare_paperShape
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambda_div
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambda_diagonalTransform_of_mem
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambda_diagonalTransform
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambda_quadratic_eq_invDensity
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambda_one
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambdaSquareCoefficient_isUpperMoebius
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_le_canonicalLambdaSquare
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_le_canonicalLambdaSquare_density
#print axioms Erdos390.WholePaper.reducedResidueIoc_card_le_canonicalLambdaSquare_paperShape

assert_no_sorry Erdos390.WholePaper.mem_tangentSelbergLambdaSupport
assert_no_sorry Erdos390.WholePaper.tangentSelbergLambdaSupport_pos
assert_no_sorry Erdos390.WholePaper.one_mem_tangentSelbergLambdaSupport
assert_no_sorry Erdos390.WholePaper.sum_tangentSelbergLambdaSquareCoefficient_divisors
assert_no_sorry Erdos390.WholePaper.tangentSelbergLambdaSquareCoefficient_isUpperMoebius
assert_no_sorry Erdos390.WholePaper.tangentSelbergLambdaSquareCoefficient_eq_zero_of_level_sq_lt
assert_no_sorry Erdos390.WholePaper.tangentSelbergLambdaSquareCoefficient_divisorMoment
assert_no_sorry Erdos390.WholePaper.tangentSelbergLambdaSquare_mainQuadraticIdentity
assert_no_sorry Erdos390.WholePaper.tangentIntervalReciprocalSieve_lambdaSquare_mainSum
assert_no_sorry Erdos390.WholePaper.tangent_reciprocal_lcm_eq_totient_commonDivisorSum
assert_no_sorry Erdos390.WholePaper.tangent_reciprocal_lcm_eq_totient_modulusSum
assert_no_sorry Erdos390.WholePaper.tangentSelbergLambdaSquare_quadraticDiagonalization
assert_no_sorry Erdos390.WholePaper.tangentSelberg_moebius_diagonal_constraint
assert_no_sorry Erdos390.WholePaper.tangent_sum_moebius_quotients_over_divisors
assert_no_sorry Erdos390.WholePaper.tangentSelberg_upper_moebius_inversion
assert_no_sorry Erdos390.WholePaper.tangentSelbergDensitySum_pos
assert_no_sorry Erdos390.WholePaper.tangentSelbergDensitySum_inv_le_quadratic
assert_no_sorry Erdos390.WholePaper.tangentSelbergLambdaSquareCoefficient_l1_le
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_le_lambdaSquare
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_le_lambdaSquare_of_bounds
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_le_lambdaSquare_paperShape
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambda_div
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambda_diagonalTransform_of_mem
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambda_diagonalTransform
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambda_quadratic_eq_invDensity
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambda_one
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambdaSquareCoefficient_isUpperMoebius
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_le_canonicalLambdaSquare
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_le_canonicalLambdaSquare_density
assert_no_sorry Erdos390.WholePaper.reducedResidueIoc_card_le_canonicalLambdaSquare_paperShape
