import Erdos390.WholePaper.TangentCollisionLocalLemma
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the tangent collision experiment -/

#print axioms Erdos390.WholePaper.tangentUniformMultiplierMeasure_isProbability
#print axioms Erdos390.WholePaper.tangentUniformMultiplierCoordinates_iIndep
#print axioms Erdos390.WholePaper.tangentCollisionSupport_subset_union
#print axioms Erdos390.WholePaper.tangentCollisionEvent_eq_preimage
#print axioms Erdos390.WholePaper.avoidTangentCollisionEvents_eq_preimage
#print axioms Erdos390.WholePaper.tangentCollisionEvent_independent_of_nonNeighbors
#print axioms Erdos390.WholePaper.tangentCollisionProbability_le_eighth_of_requestMass
#print axioms Erdos390.WholePaper.tangentCollisionNeighborhoodMass_le_quarter_of_requestMass
#print axioms Erdos390.WholePaper.tangentCollisionLLLNumerics_of_requestMass
#print axioms Erdos390.WholePaper.tangentCollisionFreeOutcome_of_requestMass
#print axioms Erdos390.WholePaper.tangentEndpointsDistinct_of_avoidsCollisions
#print axioms Erdos390.WholePaper.tangentEndpointsDistinct_of_requestMass
#print axioms Erdos390.WholePaper.tangentCleanCommonMultiplier_collisionFree_of_requestMass
#print axioms Erdos390.WholePaper.tangentSplitEndpointsDistinct_of_cleanRequestMass

assert_no_sorry Erdos390.WholePaper.tangentUniformMultiplierMeasure_isProbability
assert_no_sorry Erdos390.WholePaper.tangentUniformMultiplierCoordinates_iIndep
assert_no_sorry Erdos390.WholePaper.tangentCollisionSupport_subset_union
assert_no_sorry Erdos390.WholePaper.tangentCollisionEvent_eq_preimage
assert_no_sorry Erdos390.WholePaper.avoidTangentCollisionEvents_eq_preimage
assert_no_sorry Erdos390.WholePaper.tangentCollisionEvent_independent_of_nonNeighbors
assert_no_sorry Erdos390.WholePaper.tangentCollisionProbability_le_eighth_of_requestMass
assert_no_sorry Erdos390.WholePaper.tangentCollisionNeighborhoodMass_le_quarter_of_requestMass
assert_no_sorry Erdos390.WholePaper.tangentCollisionLLLNumerics_of_requestMass
assert_no_sorry Erdos390.WholePaper.tangentCollisionFreeOutcome_of_requestMass
assert_no_sorry Erdos390.WholePaper.tangentEndpointsDistinct_of_avoidsCollisions
assert_no_sorry Erdos390.WholePaper.tangentEndpointsDistinct_of_requestMass
assert_no_sorry Erdos390.WholePaper.tangentCleanCommonMultiplier_collisionFree_of_requestMass
assert_no_sorry Erdos390.WholePaper.tangentSplitEndpointsDistinct_of_cleanRequestMass
