import Erdos390.WholePaper.TangentStarTransport
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for exact finite star transport -/

#print axioms Erdos390.WholePaper.tangentStarFlow_nonneg
#print axioms Erdos390.WholePaper.tangentStarFlow_self
#print axioms Erdos390.WholePaper.tangentStarFlow_to_pivot
#print axioms Erdos390.WholePaper.tangentStarFlow_from_pivot
#print axioms Erdos390.WholePaper.tangentStarFlow_pos_incident_pivot
#print axioms Erdos390.WholePaper.tangentStarFlow_sum_out_of_ne
#print axioms Erdos390.WholePaper.tangentStarFlow_sum_in_of_ne
#print axioms Erdos390.WholePaper.tangentStarFlow_divergence_of_ne
#print axioms Erdos390.WholePaper.tangentStarFlow_sum_out_pivot
#print axioms Erdos390.WholePaper.tangentStarFlow_sum_in_pivot
#print axioms Erdos390.WholePaper.tangentStarFlow_divergence_pivot
#print axioms Erdos390.WholePaper.tangentStarFlow_divergence_eq
#print axioms Erdos390.WholePaper.tangentStarFlow_traffic_eq_sum_erase_abs
#print axioms Erdos390.WholePaper.tangentStarFlow_traffic_le_sum_abs
#print axioms Erdos390.WholePaper.tangentFlow_weightedBoundary_eq_divergence
#print axioms Erdos390.WholePaper.tangentStarFlow_weightedBoundary_eq_residual
#print axioms Erdos390.WholePaper.tangentStarFlow_pairBoundary_eq_residual
#print axioms Erdos390.WholePaper.tangentStarFlow_residualVector
#print axioms Erdos390.WholePaper.tangentStarFlow_factorizationBoundary_eq_residual

assert_no_sorry Erdos390.WholePaper.tangentStarFlow_nonneg
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_self
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_to_pivot
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_from_pivot
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_pos_incident_pivot
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_sum_out_of_ne
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_sum_in_of_ne
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_divergence_of_ne
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_sum_out_pivot
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_sum_in_pivot
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_divergence_pivot
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_divergence_eq
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_traffic_eq_sum_erase_abs
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_traffic_le_sum_abs
assert_no_sorry Erdos390.WholePaper.tangentFlow_weightedBoundary_eq_divergence
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_weightedBoundary_eq_residual
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_pairBoundary_eq_residual
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_residualVector
assert_no_sorry Erdos390.WholePaper.tangentStarFlow_factorizationBoundary_eq_residual
