import Erdos390.WholePaper.TangentExceptionalCanonicalBounds
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the canonical Lambda-squared analytic bounds

All 44 public theorems in `TangentExceptionalCanonicalBounds` are printed
and checked for `sorry`; the upstream uniform reciprocal-prime quadrature
bound used in the fixed Mertens loss is checked explicitly as well.
-/

#print axioms Erdos390.Full.PrimeBandQuadrature.fullReciprocalSumUniform_bound
#print axioms Erdos390.WholePaper.tangentReciprocalTotientArithmeticFunction_isMultiplicative
#print axioms Erdos390.WholePaper.tangentReciprocalTotientArithmeticFunction_apply_of_pos
#print axioms Erdos390.WholePaper.tangentReciprocalTotientArithmeticFunction_apply_prime
#print axioms Erdos390.WholePaper.tangentSigmaTotientRatioArithmeticFunction_isMultiplicative
#print axioms Erdos390.WholePaper.tangentSigmaTotientRatioArithmeticFunction_apply_of_pos
#print axioms Erdos390.WholePaper.tangentSquarefreeFourOverPrimeArithmeticFunction_isMultiplicative
#print axioms Erdos390.WholePaper.tangentSquarefreeFourOverPrimeArithmeticFunction_nonneg
#print axioms Erdos390.WholePaper.tangentSquarefreeFourOverPrimeArithmeticFunction_apply_prime
#print axioms Erdos390.WholePaper.tangentSquarefreeFourOverPrimeArithmeticFunction_eq_zero_of_not_squarefree
#print axioms Erdos390.WholePaper.tangentSquarefreeFourOverSquareArithmeticFunction_isMultiplicative
#print axioms Erdos390.WholePaper.tangentSquarefreeFourOverSquareArithmeticFunction_nonneg
#print axioms Erdos390.WholePaper.tangentSquarefreeFourOverSquareArithmeticFunction_apply_prime
#print axioms Erdos390.WholePaper.tangentSelbergFullDensitySum_eq_primeProduct
#print axioms Erdos390.WholePaper.tangentSelbergDensitySum_eq_reciprocalTotient
#print axioms Erdos390.WholePaper.sum_powerset_sum_mul_prod_le
#print axioms Erdos390.WholePaper.tangentSelbergFullLogMoment_le
#print axioms Erdos390.WholePaper.roughHeadModulus_primeFactors
#print axioms Erdos390.WholePaper.wholePaper_primesUpTo_eq_full_primesUpTo
#print axioms Erdos390.WholePaper.roughHead_primeFactor_logMoment_le_fullPrimeSums
#print axioms Erdos390.WholePaper.eventually_fullPrimeMoment_le_nine_fifths_log
#print axioms Erdos390.WholePaper.eventually_roughHead_fullLogMoment_le_nine_fifths
#print axioms Erdos390.WholePaper.tangentSelbergMertensBase_ge_cutoff
#print axioms Erdos390.WholePaper.tangentSelbergMertensBase_ge_two
#print axioms Erdos390.WholePaper.tangentSelbergMertensLoss_nonneg
#print axioms Erdos390.WholePaper.fullReciprocalSum_ge_logLog_sub_tangentSelbergMertensLoss
#print axioms Erdos390.WholePaper.exp_fullReciprocalSum_le_roughHeadFullDensity
#print axioms Erdos390.WholePaper.roughHeadFullDensity_ge_exp_neg_loss_mul_log
#print axioms Erdos390.WholePaper.tangentSelbergFullDensitySum_le_density_add_logTail
#print axioms Erdos390.WholePaper.eventually_roughHead_density_ge_one_tenth_fullDensity
#print axioms Erdos390.WholePaper.tangentSigmaTotientRatio_le_fourConvolution_of_squarefree
#print axioms Erdos390.WholePaper.tangent_fourOverPrime_convolution_nonneg
#print axioms Erdos390.WholePaper.roughHead_fourOverSquareEulerProduct_le_exp_four
#print axioms Erdos390.WholePaper.sum_fourOverSquare_le_exp_four
#print axioms Erdos390.WholePaper.tangentSelbergSigmaTotientMean_le
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambda_abs_le
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambda_l1_le_sigmaTotientMean
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambda_l1_le_exp_four_mul_level_div_density
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalMainConstant_pos
#print axioms Erdos390.WholePaper.tangentSelbergCanonicalLambdaConstant_pos
#print axioms Erdos390.WholePaper.eventually_tangentSelbergCanonical_coefficientBounds
#print axioms Erdos390.WholePaper.eventually_tangentSelbergCanonical_invDensity_le
#print axioms Erdos390.WholePaper.eventually_tangentSelbergCanonical_l1_le
#print axioms Erdos390.WholePaper.exists_tangentSelbergCanonical_coefficientBounds_cutoff
#print axioms Erdos390.WholePaper.eventually_reducedResidueIoc_card_le_canonicalLambdaSquare_roughHead

assert_no_sorry Erdos390.Full.PrimeBandQuadrature.fullReciprocalSumUniform_bound
assert_no_sorry Erdos390.WholePaper.tangentReciprocalTotientArithmeticFunction_isMultiplicative
assert_no_sorry Erdos390.WholePaper.tangentReciprocalTotientArithmeticFunction_apply_of_pos
assert_no_sorry Erdos390.WholePaper.tangentReciprocalTotientArithmeticFunction_apply_prime
assert_no_sorry Erdos390.WholePaper.tangentSigmaTotientRatioArithmeticFunction_isMultiplicative
assert_no_sorry Erdos390.WholePaper.tangentSigmaTotientRatioArithmeticFunction_apply_of_pos
assert_no_sorry Erdos390.WholePaper.tangentSquarefreeFourOverPrimeArithmeticFunction_isMultiplicative
assert_no_sorry Erdos390.WholePaper.tangentSquarefreeFourOverPrimeArithmeticFunction_nonneg
assert_no_sorry Erdos390.WholePaper.tangentSquarefreeFourOverPrimeArithmeticFunction_apply_prime
assert_no_sorry Erdos390.WholePaper.tangentSquarefreeFourOverPrimeArithmeticFunction_eq_zero_of_not_squarefree
assert_no_sorry Erdos390.WholePaper.tangentSquarefreeFourOverSquareArithmeticFunction_isMultiplicative
assert_no_sorry Erdos390.WholePaper.tangentSquarefreeFourOverSquareArithmeticFunction_nonneg
assert_no_sorry Erdos390.WholePaper.tangentSquarefreeFourOverSquareArithmeticFunction_apply_prime
assert_no_sorry Erdos390.WholePaper.tangentSelbergFullDensitySum_eq_primeProduct
assert_no_sorry Erdos390.WholePaper.tangentSelbergDensitySum_eq_reciprocalTotient
assert_no_sorry Erdos390.WholePaper.sum_powerset_sum_mul_prod_le
assert_no_sorry Erdos390.WholePaper.tangentSelbergFullLogMoment_le
assert_no_sorry Erdos390.WholePaper.roughHeadModulus_primeFactors
assert_no_sorry Erdos390.WholePaper.wholePaper_primesUpTo_eq_full_primesUpTo
assert_no_sorry Erdos390.WholePaper.roughHead_primeFactor_logMoment_le_fullPrimeSums
assert_no_sorry Erdos390.WholePaper.eventually_fullPrimeMoment_le_nine_fifths_log
assert_no_sorry Erdos390.WholePaper.eventually_roughHead_fullLogMoment_le_nine_fifths
assert_no_sorry Erdos390.WholePaper.tangentSelbergMertensBase_ge_cutoff
assert_no_sorry Erdos390.WholePaper.tangentSelbergMertensBase_ge_two
assert_no_sorry Erdos390.WholePaper.tangentSelbergMertensLoss_nonneg
assert_no_sorry Erdos390.WholePaper.fullReciprocalSum_ge_logLog_sub_tangentSelbergMertensLoss
assert_no_sorry Erdos390.WholePaper.exp_fullReciprocalSum_le_roughHeadFullDensity
assert_no_sorry Erdos390.WholePaper.roughHeadFullDensity_ge_exp_neg_loss_mul_log
assert_no_sorry Erdos390.WholePaper.tangentSelbergFullDensitySum_le_density_add_logTail
assert_no_sorry Erdos390.WholePaper.eventually_roughHead_density_ge_one_tenth_fullDensity
assert_no_sorry Erdos390.WholePaper.tangentSigmaTotientRatio_le_fourConvolution_of_squarefree
assert_no_sorry Erdos390.WholePaper.tangent_fourOverPrime_convolution_nonneg
assert_no_sorry Erdos390.WholePaper.roughHead_fourOverSquareEulerProduct_le_exp_four
assert_no_sorry Erdos390.WholePaper.sum_fourOverSquare_le_exp_four
assert_no_sorry Erdos390.WholePaper.tangentSelbergSigmaTotientMean_le
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambda_abs_le
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambda_l1_le_sigmaTotientMean
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambda_l1_le_exp_four_mul_level_div_density
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalMainConstant_pos
assert_no_sorry Erdos390.WholePaper.tangentSelbergCanonicalLambdaConstant_pos
assert_no_sorry Erdos390.WholePaper.eventually_tangentSelbergCanonical_coefficientBounds
assert_no_sorry Erdos390.WholePaper.eventually_tangentSelbergCanonical_invDensity_le
assert_no_sorry Erdos390.WholePaper.eventually_tangentSelbergCanonical_l1_le
assert_no_sorry Erdos390.WholePaper.exists_tangentSelbergCanonical_coefficientBounds_cutoff
assert_no_sorry Erdos390.WholePaper.eventually_reducedResidueIoc_card_le_canonicalLambdaSquare_roughHead
