import Erdos390.WholePaper.TangentStarSplitRequestBridge
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the star-to-split-request bridge -/

#print axioms Erdos390.WholePaper.tangentStarPositiveEdges
#print axioms Erdos390.WholePaper.tangentStarEdgeSource
#print axioms Erdos390.WholePaper.tangentStarEdgeTarget
#print axioms Erdos390.WholePaper.tangentStarEdgeFlow
#print axioms Erdos390.WholePaper.tangentStarResidualL1
#print axioms Erdos390.WholePaper.tangentStarResidualL1IncidentTraffic
#print axioms Erdos390.WholePaper.tangentStarLabelIncidentTraffic
#print axioms Erdos390.WholePaper.tangentStarSupportCount
#print axioms Erdos390.WholePaper.mem_tangentStarPositiveEdges
#print axioms Erdos390.WholePaper.tangentStarEdgeFlow_nonneg
#print axioms Erdos390.WholePaper.tangentStarPositiveEdge_labels_ne
#print axioms Erdos390.WholePaper.sum_tangentStarPositiveEdges_eq_traffic
#print axioms Erdos390.WholePaper.sum_tangentStarPositiveEdges_eq_sum_erase_abs
#print axioms Erdos390.WholePaper.sum_tangentStarPositiveEdges_le_residualL1
#print axioms Erdos390.WholePaper.tangentStarIncidentFlowMass_le_residualL1
#print axioms Erdos390.WholePaper.card_tangentStarPositiveEdges_le_supportCount
#print axioms Erdos390.WholePaper.sum_tangentStarPositiveEdges_mul_eq_full
#print axioms Erdos390.WholePaper.tangentStarPositiveEdges_factorizationBoundary_eq_residual
#print axioms Erdos390.WholePaper.tangentStarSplitRequest_factorizationBoundary_eq_residual
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperStarSplitEndpointsDistinct_of_residualL1Census

assert_no_sorry Erdos390.WholePaper.tangentStarPositiveEdges
assert_no_sorry Erdos390.WholePaper.tangentStarEdgeSource
assert_no_sorry Erdos390.WholePaper.tangentStarEdgeTarget
assert_no_sorry Erdos390.WholePaper.tangentStarEdgeFlow
assert_no_sorry Erdos390.WholePaper.tangentStarResidualL1
assert_no_sorry Erdos390.WholePaper.tangentStarResidualL1IncidentTraffic
assert_no_sorry Erdos390.WholePaper.tangentStarLabelIncidentTraffic
assert_no_sorry Erdos390.WholePaper.tangentStarSupportCount
assert_no_sorry Erdos390.WholePaper.mem_tangentStarPositiveEdges
assert_no_sorry Erdos390.WholePaper.tangentStarEdgeFlow_nonneg
assert_no_sorry Erdos390.WholePaper.tangentStarPositiveEdge_labels_ne
assert_no_sorry Erdos390.WholePaper.sum_tangentStarPositiveEdges_eq_traffic
assert_no_sorry Erdos390.WholePaper.sum_tangentStarPositiveEdges_eq_sum_erase_abs
assert_no_sorry Erdos390.WholePaper.sum_tangentStarPositiveEdges_le_residualL1
assert_no_sorry Erdos390.WholePaper.tangentStarIncidentFlowMass_le_residualL1
assert_no_sorry Erdos390.WholePaper.card_tangentStarPositiveEdges_le_supportCount
assert_no_sorry Erdos390.WholePaper.sum_tangentStarPositiveEdges_mul_eq_full
assert_no_sorry Erdos390.WholePaper.tangentStarPositiveEdges_factorizationBoundary_eq_residual
assert_no_sorry Erdos390.WholePaper.tangentStarSplitRequest_factorizationBoundary_eq_residual
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperStarSplitEndpointsDistinct_of_residualL1Census
