import Erdos390.WholePaper.FiniteAsymmetricLocalLemma
import Erdos390.WholePaper.TangentLLLNumerics
import Erdos390.WholePaper.TangentCollisionFreeFeasibility
import Erdos390.WholePaper.TangentCommonMultiplierLists
import Mathlib.Probability.Distributions.Uniform
import Mathlib.Probability.Independence.Basic
import Mathlib.Tactic

/-!
# The finite collision experiment for tangent requests

This file instantiates the finite asymmetric local lemma with the literal
random experiment used in Section 9.  Every request independently chooses a
uniform element of its own nonempty finite multiplier list.  Bad events are
indexed by two-element sets of requests and say that the two resulting
two-element endpoint sets intersect.  Two bad events are declared dependent
exactly when their request supports intersect.

The paper-facing input is the per-request collision estimate

`sum_{E containing r} P(E) <= 1 / 8`.

It implies, inside this file, both `P(E) <= 1 / 8` and the factor-two
neighborhood estimate `sum_{F in Gamma(E)} P(F) <= 1 / 4`.  Thus the literal
choice `x_E = 2 * P(E)` satisfies the numerical local-lemma inequality via
`TangentLLLNumerics`.  Independence is not assumed: it is derived from the
finite product measure and disjoint coordinate supports.

The last theorem specializes the construction to the actual clean common
lists already defined in `TangentCommonMultiplierLists`.  The two remaining
paper inputs are deliberately visible there: nonemptiness of every clean list
and the `1 / 8` collision-mass estimate.  Those are the analytic common-list
cardinality and collision-count estimates, not another local-lemma premise.
-/

open MeasureTheory Set ProbabilityTheory
open scoped BigOperators ENNReal

namespace Erdos390.WholePaper

noncomputable section

/-! ## The finite product experiment -/

/-- The choices available to one request are the elements of its own finite
multiplier list.  Using the subtype makes list membership part of the sample
space rather than a conclusion that has to be recovered from a null-set
argument. -/
abbrev TangentMultiplierChoice {Request : Type*}
    (lists : Request → Finset ℕ) (request : Request) :=
  ↑(lists request)

/-- A complete outcome chooses one listed multiplier for every request. -/
abbrev TangentMultiplierOutcome {Request : Type*}
    (lists : Request → Finset ℕ) :=
  ∀ request, TangentMultiplierChoice lists request

/-- The product of the uniform measures on all request lists. -/
def tangentUniformMultiplierMeasure
    {Request : Type*} [Fintype Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty) :
    Measure (TangentMultiplierOutcome lists) := by
  letI : ∀ request, Nonempty (TangentMultiplierChoice lists request) :=
    fun request ↦ Finset.nonempty_coe_sort.mpr (hlist request)
  exact Measure.pi fun request ↦
    (PMF.uniformOfFintype
      (TangentMultiplierChoice lists request)).toMeasure

theorem tangentUniformMultiplierMeasure_isProbability
    {Request : Type*} [Fintype Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty) :
    IsProbabilityMeasure (tangentUniformMultiplierMeasure lists hlist) := by
  unfold tangentUniformMultiplierMeasure
  infer_instance

/-- The coordinate choices in the preceding product experiment are mutually
independent. -/
theorem tangentUniformMultiplierCoordinates_iIndep
    {Request : Type*} [Fintype Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty) :
    iIndepFun
      (fun request (outcome : TangentMultiplierOutcome lists) ↦
        outcome request)
      (tangentUniformMultiplierMeasure lists hlist) := by
  unfold tangentUniformMultiplierMeasure
  letI : ∀ request, Nonempty (TangentMultiplierChoice lists request) :=
    fun request ↦ Finset.nonempty_coe_sort.mpr (hlist request)
  exact iIndepFun_pi fun _request ↦ measurable_id.aemeasurable

/-! ## Collision events and their supports -/

/-- Bad events are indexed by unordered two-element sets of requests. -/
abbrev TangentCollisionIndex (Request : Type*) :=
  {support : Finset Request // support.card = 2}

/-- The two numerical endpoints generated by one request. -/
def tangentRequestEndpointSet {Request : Type*}
    (source target : Request → ℕ) (multiplier : Request → ℕ)
    (request : Request) : Finset ℕ :=
  {source request * multiplier request,
    target request * multiplier request}

/-- Endpoint set for one coordinate of a restricted outcome. -/
def tangentRestrictedEndpointSet
    {Request : Type*} {lists : Request → Finset ℕ}
    (source target : Request → ℕ)
    (support : Finset Request)
    (outcome : ∀ request : ↑support,
      TangentMultiplierChoice lists request.1)
    (request : ↑support) : Finset ℕ :=
  {source request.1 * (outcome request).1,
    target request.1 * (outcome request).1}

/-- A collision on a two-request support: the two endpoint sets intersect.
The existential form is convenient for restriction to coordinate cylinders
and is equivalent to one of the four endpoint equalities. -/
def tangentCollisionOn
    {Request : Type*} {lists : Request → Finset ℕ}
    (source target : Request → ℕ)
    (collision : TangentCollisionIndex Request)
    (outcome : ∀ request : ↑collision.1,
      TangentMultiplierChoice lists request.1) : Prop :=
  ∃ r s : ↑collision.1, r ≠ s ∧
    ¬Disjoint
      (tangentRestrictedEndpointSet source target collision.1 outcome r)
      (tangentRestrictedEndpointSet source target collision.1 outcome s)

/-- The collision cylinder in the full product sample space. -/
def tangentCollisionEvent
    {Request : Type*} {lists : Request → Finset ℕ}
    (source target : Request → ℕ)
    (collision : TangentCollisionIndex Request) :
    Set (TangentMultiplierOutcome lists) :=
  {outcome | tangentCollisionOn source target collision
    (fun request ↦ outcome request.1)}

/-- Dependency neighborhood of a collision event.  Self-dependency is
excluded, and every other two-request event is adjacent exactly when the two
supports share a request. -/
def tangentCollisionNeighbors
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (collision : TangentCollisionIndex Request) :
    Finset (TangentCollisionIndex Request) :=
  Finset.univ.filter fun other ↦
    other ≠ collision ∧ ¬Disjoint collision.1 other.1

/-- All collision events incident to one fixed request. -/
def tangentIncidentCollisions
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (request : Request) : Finset (TangentCollisionIndex Request) :=
  Finset.univ.filter fun collision ↦ request ∈ collision.1

/-- The union of the request supports used by a finite family of collision
events. -/
def tangentCollisionSupportUnion
    {Request : Type*} [DecidableEq Request]
    (collisions : Finset (TangentCollisionIndex Request)) : Finset Request :=
  collisions.biUnion fun collision ↦ collision.1

theorem tangentCollisionSupport_subset_union
    {Request : Type*} [DecidableEq Request]
    {collisions : Finset (TangentCollisionIndex Request)}
    {collision : TangentCollisionIndex Request}
    (hcollision : collision ∈ collisions) :
    collision.1 ⊆ tangentCollisionSupportUnion collisions := by
  exact Finset.subset_biUnion_of_mem
    (fun event : TangentCollisionIndex Request ↦ event.1) hcollision

/-- Restrict an assignment on a larger finite coordinate set to a smaller
one. -/
def tangentRestrictMultiplierOutcome
    {Request : Type*} {lists : Request → Finset ℕ}
    {small large : Finset Request} (hsubset : small ⊆ large)
    (outcome : ∀ request : ↑large,
      TangentMultiplierChoice lists request.1) :
    ∀ request : ↑small, TangentMultiplierChoice lists request.1 :=
  fun request ↦ outcome ⟨request.1, hsubset request.2⟩

/-- Configurations on the union support which avoid every collision in a
finite family. -/
def tangentAvoidCollisionConfigurations
    {Request : Type*} [DecidableEq Request]
    {lists : Request → Finset ℕ}
    (source target : Request → ℕ)
    (collisions : Finset (TangentCollisionIndex Request)) :
    Set (∀ request : ↑(tangentCollisionSupportUnion collisions),
      TangentMultiplierChoice lists request.1) :=
  {outcome | ∀ collision, ∀ hcollision : collision ∈ collisions,
    ¬tangentCollisionOn source target collision
      (tangentRestrictMultiplierOutcome
        (tangentCollisionSupport_subset_union hcollision) outcome)}

theorem tangentCollisionEvent_eq_preimage
    {Request : Type*} {lists : Request → Finset ℕ}
    (source target : Request → ℕ)
    (collision : TangentCollisionIndex Request) :
    tangentCollisionEvent (lists := lists) source target collision =
      (fun (outcome : TangentMultiplierOutcome lists)
          (request : ↑collision.1) ↦ outcome request.1) ⁻¹'
        {restricted : ∀ request : ↑collision.1,
            TangentMultiplierChoice lists request.1 |
          tangentCollisionOn (lists := lists) source target collision
            restricted} :=
  rfl

theorem avoidTangentCollisionEvents_eq_preimage
    {Request : Type*} [DecidableEq Request]
    {lists : Request → Finset ℕ}
    (source target : Request → ℕ)
    (collisions : Finset (TangentCollisionIndex Request)) :
    avoidEvents (tangentCollisionEvent (lists := lists) source target)
        collisions =
      (fun outcome
          (request : ↑(tangentCollisionSupportUnion collisions)) ↦
        outcome request.1) ⁻¹'
          tangentAvoidCollisionConfigurations
            (lists := lists) source target collisions := by
  ext outcome
  simp only [avoidEvents, Set.mem_iInter, Set.mem_compl_iff,
    Set.mem_preimage, tangentAvoidCollisionConfigurations]
  constructor
  · intro havoid collision hcollision
    have h := havoid collision hcollision
    simpa only [tangentCollisionEvent, tangentRestrictMultiplierOutcome]
      using h
  · intro havoid collision hcollision
    have h := havoid collision hcollision
    simpa only [tangentCollisionEvent, tangentRestrictMultiplierOutcome]
      using h

/-! ## Product-space dependency factorization -/

/-- Events on a two-request support are independent of simultaneous
avoidance of any finite family of events whose union support is disjoint from
that pair.  The support disjointness is derived from the declared dependency
graph; the measure factorization itself comes from `iIndepFun_pi`. -/
theorem tangentCollisionEvent_independent_of_nonNeighbors
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty)
    (source target : Request → ℕ)
    (collision : TangentCollisionIndex Request)
    (collisions : Finset (TangentCollisionIndex Request))
    (hcollision : collision ∉ collisions)
    (hdisjoint : Disjoint collisions
      (tangentCollisionNeighbors collision)) :
    let μ := tangentUniformMultiplierMeasure lists hlist
    μ.real (tangentCollisionEvent source target collision ∩
        avoidEvents (tangentCollisionEvent source target) collisions) =
      μ.real (tangentCollisionEvent source target collision) *
        μ.real (avoidEvents
          (tangentCollisionEvent source target) collisions) := by
  let μ := tangentUniformMultiplierMeasure lists hlist
  let unionSupport := tangentCollisionSupportUnion collisions
  let leftRestriction :=
    fun (outcome : TangentMultiplierOutcome lists)
        (request : ↑collision.1) ↦ outcome request.1
  let rightRestriction :=
    fun (outcome : TangentMultiplierOutcome lists)
        (request : ↑unionSupport) ↦ outcome request.1
  have hsupportDisjoint : Disjoint collision.1 unionSupport := by
    rw [Finset.disjoint_left]
    intro request hrequestCollision hrequestUnion
    obtain ⟨other, hother, hrequestOther⟩ :=
      Finset.mem_biUnion.mp hrequestUnion
    have hotherNe : other ≠ collision := by
      intro heq
      subst other
      exact hcollision hother
    have hoverlap : ¬Disjoint collision.1 other.1 :=
      Finset.not_disjoint_iff.mpr
        ⟨request, hrequestCollision, hrequestOther⟩
    have hotherNeighbor : other ∈ tangentCollisionNeighbors collision := by
      exact Finset.mem_filter.mpr
        ⟨Finset.mem_univ other, hotherNe, hoverlap⟩
    exact Finset.disjoint_left.mp hdisjoint hother hotherNeighbor
  have hcoordinateMeasurable :
      ∀ request,
        Measurable (fun outcome : TangentMultiplierOutcome lists ↦
          outcome request) :=
    fun request ↦ measurable_pi_apply request
  have hindepFun : IndepFun leftRestriction rightRestriction μ := by
    dsimp only [leftRestriction, rightRestriction, unionSupport, μ]
    exact (tangentUniformMultiplierCoordinates_iIndep lists hlist).indepFun_finset
      collision.1 (tangentCollisionSupportUnion collisions)
      hsupportDisjoint hcoordinateMeasurable
  have hleftMeasurable : Measurable leftRestriction := by
    dsimp only [leftRestriction]
    exact measurable_pi_iff.mpr fun request ↦
      measurable_pi_apply request.1
  have hrightMeasurable : Measurable rightRestriction := by
    dsimp only [rightRestriction, unionSupport]
    exact measurable_pi_iff.mpr fun request ↦
      measurable_pi_apply request.1
  let collisionConfigurations :
      Set (∀ request : ↑collision.1,
        TangentMultiplierChoice lists request.1) :=
    {restricted | tangentCollisionOn source target collision restricted}
  let safeConfigurations :
      Set (∀ request : ↑unionSupport,
        TangentMultiplierChoice lists request.1) :=
    tangentAvoidCollisionConfigurations source target collisions
  letI : IsProbabilityMeasure μ :=
    tangentUniformMultiplierMeasure_isProbability lists hlist
  have hindepSet : IndepSet
      (leftRestriction ⁻¹' collisionConfigurations)
      (rightRestriction ⁻¹' safeConfigurations) μ :=
    ((indepFun_iff_indepSet_preimage hleftMeasurable hrightMeasurable).mp
      hindepFun) collisionConfigurations safeConfigurations
        (Set.toFinite _).measurableSet (Set.toFinite _).measurableSet
  have hmeasure := hindepSet.measure_inter_eq_mul
  have hevent :
      tangentCollisionEvent source target collision =
        leftRestriction ⁻¹' collisionConfigurations := by
    rfl
  have havoid :
      avoidEvents (tangentCollisionEvent source target) collisions =
        rightRestriction ⁻¹' safeConfigurations := by
    dsimp only [rightRestriction, safeConfigurations, unionSupport]
    exact avoidTangentCollisionEvents_eq_preimage source target collisions
  rw [← hevent, ← havoid] at hmeasure
  simpa only [Measure.real, ENNReal.toReal_mul] using
    congrArg ENNReal.toReal hmeasure

/-! ## The literal `1/8`, factor-two, and factor-four bookkeeping -/

/-- Probability of one actual collision event in the uniform product
experiment. -/
def tangentCollisionProbability
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty)
    (source target : Request → ℕ)
    (collision : TangentCollisionIndex Request) : ℝ :=
  (tangentUniformMultiplierMeasure lists hlist).real
    (tangentCollisionEvent source target collision)

/-- Total collision probability incident to one request.  This is exactly
the quantity bounded by `B_coll` in Section 9. -/
def tangentRequestCollisionMass
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty)
    (source target : Request → ℕ) (request : Request) : ℝ :=
  ∑ collision ∈ tangentIncidentCollisions request,
    tangentCollisionProbability lists hlist source target collision

private theorem sum_union_le_add_sum_of_nonneg
    {α : Type*} [DecidableEq α]
    (s t : Finset α) (f : α → ℝ) (hf : ∀ a, 0 ≤ f a) :
    ∑ a ∈ s ∪ t, f a ≤ (∑ a ∈ s, f a) + ∑ a ∈ t, f a := by
  calc
    (∑ a ∈ s ∪ t, f a) =
        ∑ a ∈ s ∪ (t \ s), f a := by
          rw [Finset.union_sdiff_self_eq_union]
    _ = (∑ a ∈ s, f a) + ∑ a ∈ t \ s, f a := by
      rw [Finset.sum_union Finset.disjoint_sdiff]
    _ ≤ (∑ a ∈ s, f a) + ∑ a ∈ t, f a := by
      exact add_le_add (le_refl _)
        (Finset.sum_le_sum_of_subset_of_nonneg Finset.sdiff_subset
          (fun a _ha _hnew ↦ hf a))

private theorem sum_biUnion_le_sum_sum_of_nonneg
    {ι α : Type*} [DecidableEq ι] [DecidableEq α]
    (s : Finset ι) (t : ι → Finset α) (f : α → ℝ)
    (hf : ∀ a, 0 ≤ f a) :
    ∑ a ∈ s.biUnion t, f a ≤
      ∑ i ∈ s, ∑ a ∈ t i, f a := by
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih =>
      rw [Finset.biUnion_insert, Finset.sum_insert hi]
      exact (sum_union_le_add_sum_of_nonneg
        (t i) (s.biUnion t) f hf).trans
          (add_le_add (le_refl _) ih)

/-- A two-request event is itself bounded by either one of its incident
request masses, hence by the paper's literal `1/8`. -/
theorem tangentCollisionProbability_le_eighth_of_requestMass
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty)
    (source target : Request → ℕ)
    (hrequestMass : ∀ request,
      tangentRequestCollisionMass lists hlist source target request ≤ 1 / 8)
    (collision : TangentCollisionIndex Request) :
    tangentCollisionProbability lists hlist source target collision ≤ 1 / 8 := by
  have hnonempty : collision.1.Nonempty := by
    rw [← Finset.card_pos, collision.2]
    norm_num
  obtain ⟨request, hrequest⟩ := hnonempty
  have hincident : collision ∈ tangentIncidentCollisions request := by
    exact Finset.mem_filter.mpr
      ⟨Finset.mem_univ collision, hrequest⟩
  calc
    tangentCollisionProbability lists hlist source target collision ≤
        ∑ event ∈ tangentIncidentCollisions request,
          tangentCollisionProbability lists hlist source target event := by
      exact Finset.single_le_sum
        (fun event _hevent ↦ measureReal_nonneg) hincident
    _ = tangentRequestCollisionMass lists hlist source target request := rfl
    _ ≤ 1 / 8 := hrequestMass request

/-- The dependency neighborhood of a two-request event is covered by the
incident collision families of its two requests.  Summing the two `1/8`
bounds gives the literal factor-two estimate `1/4`. -/
theorem tangentCollisionNeighborhoodMass_le_quarter_of_requestMass
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty)
    (source target : Request → ℕ)
    (hrequestMass : ∀ request,
      tangentRequestCollisionMass lists hlist source target request ≤ 1 / 8)
    (collision : TangentCollisionIndex Request) :
    ∑ other ∈ tangentCollisionNeighbors collision,
        tangentCollisionProbability lists hlist source target other ≤
      1 / 4 := by
  let probability :=
    tangentCollisionProbability lists hlist source target
  have hprobabilityNonneg : ∀ event, 0 ≤ probability event :=
    fun _event ↦ measureReal_nonneg
  have hneighborSubset : tangentCollisionNeighbors collision ⊆
      collision.1.biUnion tangentIncidentCollisions := by
    intro other hother
    have hotherData := Finset.mem_filter.mp hother
    obtain ⟨request, hrequestCollision, hrequestOther⟩ :=
      Finset.not_disjoint_iff.mp hotherData.2.2
    exact Finset.mem_biUnion.mpr
      ⟨request, hrequestCollision, Finset.mem_filter.mpr
        ⟨Finset.mem_univ other, hrequestOther⟩⟩
  calc
    (∑ other ∈ tangentCollisionNeighbors collision, probability other) ≤
        ∑ other ∈ collision.1.biUnion tangentIncidentCollisions,
          probability other := by
      exact Finset.sum_le_sum_of_subset_of_nonneg hneighborSubset
        (fun event _hevent _hnew ↦ hprobabilityNonneg event)
    _ ≤ ∑ request ∈ collision.1,
        ∑ other ∈ tangentIncidentCollisions request,
          probability other :=
      sum_biUnion_le_sum_sum_of_nonneg collision.1
        tangentIncidentCollisions probability hprobabilityNonneg
    _ = ∑ request ∈ collision.1,
        tangentRequestCollisionMass lists hlist source target request := rfl
    _ ≤ ∑ _request ∈ collision.1, (1 / 8 : ℝ) := by
      exact Finset.sum_le_sum fun request _hrequest ↦ hrequestMass request
    _ = 1 / 4 := by
      norm_num [collision.2, Finset.sum_const]

/-- With `x_E = 2 P(E)`, the `1/8` request-mass estimate gives the complete
asymmetric-LLL numerical inequality.  This is the factor-four line of the
paper: the doubled mass in a dependency neighborhood is at most `1/2`. -/
theorem tangentCollisionLLLNumerics_of_requestMass
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty)
    (source target : Request → ℕ)
    (hrequestMass : ∀ request,
      tangentRequestCollisionMass lists hlist source target request ≤ 1 / 8)
    (collision : TangentCollisionIndex Request) :
    tangentCollisionProbability lists hlist source target collision ≤
      (2 * tangentCollisionProbability lists hlist source target collision) *
        ∏ other ∈ tangentCollisionNeighbors collision,
          (1 - 2 *
            tangentCollisionProbability lists hlist source target other) := by
  exact probability_le_two_mul_probability_mul_neighborProduct_of_requestMass
    (tangentCollisionNeighbors collision)
    (tangentCollisionProbability lists hlist source target) collision
    (fun _event _hevent ↦ measureReal_nonneg) (1 / 8 : ℝ) (by norm_num)
    (by
      have hquarter :=
        tangentCollisionNeighborhoodMass_le_quarter_of_requestMass
          lists hlist source target hrequestMass collision
      nlinarith)

/-! ## The collision-free outcome -/

/-- Finite product-space specialization of the local lemma used in Section
9.  It constructs an outcome avoiding every collision event; neither
collision-free existence nor the local-lemma conclusion is an input. -/
theorem tangentCollisionFreeOutcome_of_requestMass
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty)
    (source target : Request → ℕ)
    (hrequestMass : ∀ request,
      tangentRequestCollisionMass lists hlist source target request ≤ 1 / 8) :
    ∃ outcome : TangentMultiplierOutcome lists,
      ∀ collision : TangentCollisionIndex Request,
        outcome ∉ tangentCollisionEvent source target collision := by
  let μ := tangentUniformMultiplierMeasure lists hlist
  let event := tangentCollisionEvent (lists := lists) source target
  let probability :=
    tangentCollisionProbability lists hlist source target
  let x := fun collision : TangentCollisionIndex Request ↦
    2 * probability collision
  letI : IsProbabilityMeasure μ :=
    tangentUniformMultiplierMeasure_isProbability lists hlist
  apply finiteAsymmetricLocalLemma μ event tangentCollisionNeighbors x
  · intro collision
    exact (Set.toFinite (event collision)).measurableSet
  · intro collision
    have heventBound :=
      tangentCollisionProbability_le_eighth_of_requestMass
        lists hlist source target hrequestMass collision
    constructor
    · dsimp only [x, probability]
      exact mul_nonneg (by norm_num) measureReal_nonneg
    · dsimp only [x, probability]
      linarith
  · intro collision collisions hcollision hdisjoint
    dsimp only [μ, event]
    exact tangentCollisionEvent_independent_of_nonNeighbors
      lists hlist source target collision collisions
        hcollision hdisjoint
  · intro collision
    dsimp only [μ, event, x, probability]
    exact tangentCollisionLLLNumerics_of_requestMass
      lists hlist source target hrequestMass collision

/-- Avoidance of all two-request collision events gives the deterministic
endpoint-distinctness structure consumed by the tangent feasibility layer.
The only extra facts needed are that the two labels of one request differ
and that its selected multiplier is nonzero. -/
theorem tangentEndpointsDistinct_of_avoidsCollisions
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    {lists : Request → Finset ℕ}
    (source target : Request → ℕ)
    (outcome : TangentMultiplierOutcome lists)
    (hsourceTarget : ∀ request, source request ≠ target request)
    (hmultiplier : ∀ request, (outcome request).1 ≠ 0)
    (havoid : ∀ collision : TangentCollisionIndex Request,
      outcome ∉ tangentCollisionEvent source target collision) :
    TangentEndpointsDistinct Finset.univ source target
      (fun request ↦ (outcome request).1) := by
  have hpairwise : ∀ r s : Request, r ≠ s →
      Disjoint
        (tangentRequestEndpointSet source target
          (fun request ↦ (outcome request).1) r)
        (tangentRequestEndpointSet source target
          (fun request ↦ (outcome request).1) s) := by
    intro r s hrs
    by_contra hoverlap
    let collision : TangentCollisionIndex Request :=
      ⟨{r, s}, by simp [hrs]⟩
    have hr : r ∈ collision.1 := by simp [collision]
    have hs : s ∈ collision.1 := by simp [collision]
    apply havoid collision
    change tangentCollisionOn source target collision
      (fun request ↦ outcome request.1)
    refine ⟨⟨r, hr⟩, ⟨s, hs⟩, ?_, ?_⟩
    · intro heq
      exact hrs (congrArg Subtype.val heq)
    · simpa only [tangentRestrictedEndpointSet,
        tangentRequestEndpointSet] using hoverlap
  refine ⟨?_, ?_, ?_⟩
  · intro r _hr s _hs heq
    by_contra hrs
    change source r * (outcome r).1 =
      source s * (outcome s).1 at heq
    have hdisjoint := hpairwise r s hrs
    have hleft : source r * (outcome r).1 ∈
        tangentRequestEndpointSet source target
          (fun request ↦ (outcome request).1) r := by
      simp [tangentRequestEndpointSet]
    have hright : source r * (outcome r).1 ∈
        tangentRequestEndpointSet source target
          (fun request ↦ (outcome request).1) s := by
      simp [tangentRequestEndpointSet, heq]
    exact Finset.disjoint_left.mp hdisjoint hleft hright
  · intro r _hr s _hs heq
    by_contra hrs
    change target r * (outcome r).1 =
      target s * (outcome s).1 at heq
    have hdisjoint := hpairwise r s hrs
    have hleft : target r * (outcome r).1 ∈
        tangentRequestEndpointSet source target
          (fun request ↦ (outcome request).1) r := by
      simp [tangentRequestEndpointSet]
    have hright : target r * (outcome r).1 ∈
        tangentRequestEndpointSet source target
          (fun request ↦ (outcome request).1) s := by
      simp [tangentRequestEndpointSet, heq]
    exact Finset.disjoint_left.mp hdisjoint hleft hright
  · intro r _hr s _hs
    by_cases hrs : r = s
    · subst s
      intro heq
      exact hsourceTarget r (mul_right_cancel₀ (hmultiplier r) heq)
    · intro heq
      have hdisjoint := hpairwise r s hrs
      have hleft : source r * (outcome r).1 ∈
          tangentRequestEndpointSet source target
            (fun request ↦ (outcome request).1) r := by
        simp [tangentRequestEndpointSet]
      have hright : source r * (outcome r).1 ∈
          tangentRequestEndpointSet source target
            (fun request ↦ (outcome request).1) s := by
        rw [heq]
        simp [tangentRequestEndpointSet]
      exact Finset.disjoint_left.mp hdisjoint hleft hright

/-- Paper-facing deterministic output of the finite collision experiment. -/
theorem tangentEndpointsDistinct_of_requestMass
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (lists : Request → Finset ℕ)
    (hlist : ∀ request, (lists request).Nonempty)
    (source target : Request → ℕ)
    (hsourceTarget : ∀ request, source request ≠ target request)
    (hpositive : ∀ request, ∀ multiplier ∈ lists request,
      multiplier ≠ 0)
    (hrequestMass : ∀ request,
      tangentRequestCollisionMass lists hlist source target request ≤ 1 / 8) :
    ∃ outcome : TangentMultiplierOutcome lists,
      TangentEndpointsDistinct Finset.univ source target
        (fun request ↦ (outcome request).1) := by
  obtain ⟨outcome, havoid⟩ := tangentCollisionFreeOutcome_of_requestMass
    lists hlist source target hrequestMass
  exact ⟨outcome,
    tangentEndpointsDistinct_of_avoidsCollisions source target outcome
      hsourceTarget (fun request ↦
        hpositive request (outcome request).1 (outcome request).2) havoid⟩

/-! ## Specialization to the literal clean common lists -/

/-- The actual request-indexed family of clean common lists from Section 9.
The list is indexed by the unordered label pair in paper order
`(max source target, min source target)`; the directed orientation remains
separate and is used only by the signed tangent update. -/
def tangentCleanMultiplierLists
    {Request : Type*}
    (n K h Phead X0 y : ℕ) (source target : Request → ℕ)
    (dedicatedRows numericalGuards : Finset ℕ) :
    Request → Finset ℕ :=
  fun request ↦ tangentCleanCommonMultiplierList
    n K h Phead X0 y
      (max (source request) (target request))
      (min (source request) (target request))
      dedicatedRows numericalGuards

/-- Applying the finite collision experiment to the literal clean lists
produces actual numerical multipliers, proves their list membership, and
supplies `TangentEndpointsDistinct`.  The visible hypotheses are exactly the
two estimates not yet proved by the current common-list API: list
nonemptiness and per-request collision mass at most `1/8`. -/
theorem tangentCleanCommonMultiplier_collisionFree_of_requestMass
    {Request : Type*} [Fintype Request] [DecidableEq Request]
    (n K h Phead X0 y : ℕ) (source target : Request → ℕ)
    (dedicatedRows numericalGuards : Finset ℕ)
    (hsourceTarget : ∀ request, source request ≠ target request)
    (hlist : ∀ request,
      (tangentCleanMultiplierLists n K h Phead X0 y source target
        dedicatedRows numericalGuards request).Nonempty)
    (hrequestMass : ∀ request,
      tangentRequestCollisionMass
        (tangentCleanMultiplierLists n K h Phead X0 y source target
          dedicatedRows numericalGuards)
        hlist source target request ≤ 1 / 8) :
    ∃ multiplier : Request → ℕ,
      (∀ request,
        multiplier request ∈
          tangentCleanCommonMultiplierList
            n K h Phead X0 y
              (max (source request) (target request))
              (min (source request) (target request))
              dedicatedRows numericalGuards) ∧
      TangentEndpointsDistinct Finset.univ source target multiplier := by
  let lists := tangentCleanMultiplierLists
    n K h Phead X0 y source target dedicatedRows numericalGuards
  obtain ⟨outcome, hdistinct⟩ := tangentEndpointsDistinct_of_requestMass
    lists hlist source target hsourceTarget
    (by
      intro request multiplier hmultiplier
      change multiplier ∈ tangentCleanCommonMultiplierList
        n K h Phead X0 y
          (max (source request) (target request))
          (min (source request) (target request))
          dedicatedRows numericalGuards at hmultiplier
      have hbounds := mem_tangentCleanCommonMultiplierList.mp hmultiplier
      exact (lt_of_le_of_lt (Nat.zero_le _) hbounds.1.1).ne')
    hrequestMass
  refine ⟨fun request ↦ (outcome request).1, ?_, hdistinct⟩
  intro request
  simpa only [lists, tangentCleanMultiplierLists] using
    (outcome request).2

/-! ## The literal split-request specialization -/

/-- Clean multiplier lists indexed by the actual `Fin`-split requests of the
tangent flow. -/
def tangentSplitCleanMultiplierLists
    {E : Type*} (edges : Finset E) (source target : E → ℕ)
    (L sigma : ℝ) (flow : E → ℝ)
    (n K h Phead X0 y : ℕ)
    (dedicatedRows numericalGuards : Finset ℕ) :
    TangentSplitRequest edges L sigma flow → Finset ℕ :=
  tangentCleanMultiplierLists n K h Phead X0 y
    (tangentSplitRequestSource source)
    (tangentSplitRequestTarget target)
      dedicatedRows numericalGuards

/-- Direct bridge from the actual split-request family to the endpoint
certificate consumed by `tangentSplitUpdate_feasible_and_margin`. -/
theorem tangentSplitEndpointsDistinct_of_cleanRequestMass
    {E : Type*} [DecidableEq E] (edges : Finset E)
    (source target : E → ℕ) (L sigma : ℝ) (flow : E → ℝ)
    (n K h Phead X0 y : ℕ)
    (dedicatedRows numericalGuards : Finset ℕ)
    (hsourceTarget : ∀ request : TangentSplitRequest edges L sigma flow,
      tangentSplitRequestSource source request ≠
        tangentSplitRequestTarget target request)
    (hlist : ∀ request : TangentSplitRequest edges L sigma flow,
      (tangentSplitCleanMultiplierLists edges source target L sigma flow
        n K h Phead X0 y dedicatedRows numericalGuards request).Nonempty)
    (hrequestMass : ∀ request : TangentSplitRequest edges L sigma flow,
      tangentRequestCollisionMass
        (tangentSplitCleanMultiplierLists edges source target L sigma flow
          n K h Phead X0 y dedicatedRows numericalGuards)
        hlist (tangentSplitRequestSource source)
          (tangentSplitRequestTarget target) request ≤ 1 / 8) :
    ∃ multiplier : TangentSplitRequest edges L sigma flow → ℕ,
      (∀ request,
        multiplier request ∈
          tangentSplitCleanMultiplierLists edges source target L sigma flow
            n K h Phead X0 y dedicatedRows numericalGuards request) ∧
      TangentEndpointsDistinct
        (tangentSplitRequests edges L sigma flow)
        (tangentSplitRequestSource source)
        (tangentSplitRequestTarget target) multiplier := by
  obtain ⟨multiplier, hmem, hdistinct⟩ :=
    tangentCleanCommonMultiplier_collisionFree_of_requestMass
      n K h Phead X0 y
      (tangentSplitRequestSource source)
      (tangentSplitRequestTarget target)
      dedicatedRows numericalGuards hsourceTarget hlist hrequestMass
  refine ⟨multiplier, ?_, ?_⟩
  · intro request
    simpa only [tangentSplitCleanMultiplierLists,
      tangentCleanMultiplierLists] using hmem request
  · simpa only [tangentSplitRequests] using hdistinct

end

end Erdos390.WholePaper
