import Erdos390.WholePaper.TangentCommonMultiplierLists
import Mathlib.Util.AssertNoSorry

#print axioms Erdos390.WholePaper.mem_tangentCommonMultiplierInterval
#print axioms Erdos390.WholePaper.card_tangentCommonMultiplierInterval
#print axioms Erdos390.WholePaper.mem_tangentCleanCommonMultiplierList
#print axioms Erdos390.WholePaper.tangentCommonMultiplierInterval_endpoints
#print axioms Erdos390.WholePaper.completeRoughSignature_small_left_mul
#print axioms Erdos390.WholePaper.completeRoughLabel_small_left_mul
#print axioms Erdos390.WholePaper.tangentCleanCommonMultiplier_mem_certificate
#print axioms Erdos390.WholePaper.card_tangentLabelGuardDeletedMultipliers_le
#print axioms Erdos390.WholePaper.card_tangentEndpointGuardDeletedMultipliers_le
#print axioms Erdos390.WholePaper.tangentCommonMultiplierBadSet_subset_interval
#print axioms Erdos390.WholePaper.tangentCleanCommonMultiplierList_eq_sdiff_badSet
#print axioms Erdos390.WholePaper.card_tangentCleanCommonMultiplierList
#print axioms Erdos390.WholePaper.card_tangentCommonMultiplierBadSet_le
#print axioms Erdos390.WholePaper.tangentCommonMultiplier_finite_deletion_ledger

assert_no_sorry Erdos390.WholePaper.mem_tangentCommonMultiplierInterval
assert_no_sorry Erdos390.WholePaper.card_tangentCommonMultiplierInterval
assert_no_sorry Erdos390.WholePaper.mem_tangentCleanCommonMultiplierList
assert_no_sorry Erdos390.WholePaper.tangentCommonMultiplierInterval_endpoints
assert_no_sorry Erdos390.WholePaper.completeRoughSignature_small_left_mul
assert_no_sorry Erdos390.WholePaper.completeRoughLabel_small_left_mul
assert_no_sorry Erdos390.WholePaper.tangentCleanCommonMultiplier_mem_certificate
assert_no_sorry Erdos390.WholePaper.card_tangentLabelGuardDeletedMultipliers_le
assert_no_sorry Erdos390.WholePaper.card_tangentEndpointGuardDeletedMultipliers_le
assert_no_sorry Erdos390.WholePaper.tangentCommonMultiplierBadSet_subset_interval
assert_no_sorry Erdos390.WholePaper.tangentCleanCommonMultiplierList_eq_sdiff_badSet
assert_no_sorry Erdos390.WholePaper.card_tangentCleanCommonMultiplierList
assert_no_sorry Erdos390.WholePaper.card_tangentCommonMultiplierBadSet_le
assert_no_sorry Erdos390.WholePaper.tangentCommonMultiplier_finite_deletion_ledger
