import Erdos390.WholePaper.TangentPaperNumericalGuards
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for the literal Section 9 guard family -/

#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperBankRows_card_eq_componentCount
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperBankRows_card_le_anchorMarkerBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperDedicatedRows_card
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperDedicatedRows_subset_bankRows
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentDedicatedRowMultipliers_tangentPaperDedicatedRows
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperNumericalGuardSet_card_le
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperNumericalGuardSet_card_le_anchorMarkerBudget
#print axioms Erdos390.WholePaper.mediumPrime_not_dvd_guardedLargeCentralAnchor
#print axioms Erdos390.WholePaper.guardedCentralAnchors_pairPrimeDivisors_subset
#print axioms Erdos390.WholePaper.card_guardedCentralAnchors_pairPrimeDivisors_le_two
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperPairNumericalGuards_subset_anchor_states
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperPairNumericalGuards_card_le_componentCount
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperPairNumericalGuards_card_le_anchorMarkerBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentLabelGuardDeletedMultipliers_numericalGuardSet_eq_pair_left
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentLabelGuardDeletedMultipliers_numericalGuardSet_eq_pair_right
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentEndpointGuardDeletedMultipliers_numericalGuardSet_eq_pair
#print axioms Erdos390.WholePaper.BankPaperRealization.card_tangentEndpointGuardDeletedMultipliers_numericalGuardSet_le
#print axioms Erdos390.WholePaper.BankPaperRealization.card_tangentEndpointGuardDeletedMultipliers_numericalGuardSet_le_budget
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperCommonMultiplier_finite_deletion_ledger

assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperBankRows_card_eq_componentCount
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperBankRows_card_le_anchorMarkerBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperDedicatedRows_card
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperDedicatedRows_subset_bankRows
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentDedicatedRowMultipliers_tangentPaperDedicatedRows
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperNumericalGuardSet_card_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperNumericalGuardSet_card_le_anchorMarkerBudget
assert_no_sorry Erdos390.WholePaper.mediumPrime_not_dvd_guardedLargeCentralAnchor
assert_no_sorry Erdos390.WholePaper.guardedCentralAnchors_pairPrimeDivisors_subset
assert_no_sorry Erdos390.WholePaper.card_guardedCentralAnchors_pairPrimeDivisors_le_two
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperPairNumericalGuards_subset_anchor_states
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperPairNumericalGuards_card_le_componentCount
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperPairNumericalGuards_card_le_anchorMarkerBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentLabelGuardDeletedMultipliers_numericalGuardSet_eq_pair_left
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentLabelGuardDeletedMultipliers_numericalGuardSet_eq_pair_right
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentEndpointGuardDeletedMultipliers_numericalGuardSet_eq_pair
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.card_tangentEndpointGuardDeletedMultipliers_numericalGuardSet_le
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.card_tangentEndpointGuardDeletedMultipliers_numericalGuardSet_le_budget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperCommonMultiplier_finite_deletion_ledger
