import Erdos390.WholePaper.TangentSplitRequestLoads
import Mathlib.Util.AssertNoSorry

/-! # Axiom audit for actual tangent split-request loads -/

#print axioms Erdos390.WholePaper.tangentIncidentSplitRequestEquiv
#print axioms Erdos390.WholePaper.tangentSplitTotalRequestCount_eq_requestTotal
#print axioms Erdos390.WholePaper.tangentSplitRequestLabelLoad_eq_incidentRequestCount
#print axioms Erdos390.WholePaper.tangentSupportDegree_le_edges_card
#print axioms Erdos390.WholePaper.tangentIncidentFlowMass_le_totalFlowMass
#print axioms Erdos390.WholePaper.tangentPositiveFlowEdges
#print axioms Erdos390.WholePaper.mem_tangentPositiveFlowEdges
#print axioms Erdos390.WholePaper.sum_tangentPositiveFlowEdges_eq_traffic
#print axioms Erdos390.WholePaper.tangentSplitTotalRequestUpper
#print axioms Erdos390.WholePaper.tangentSplitLabelRequestUpper
#print axioms Erdos390.WholePaper.cast_tangentSplitTotalRequestCount_le_upper
#print axioms Erdos390.WholePaper.cast_tangentSplitRequestLabelLoad_le_upper
#print axioms Erdos390.WholePaper.cast_tangentSplitRequestLabelLoad_le_totalFlowMass
#print axioms Erdos390.WholePaper.cast_tangentPositiveFlowTotalRequestCount_le_traffic
#print axioms Erdos390.WholePaper.cast_tangentPositiveFlowRequestLabelLoad_le_traffic
#print axioms Erdos390.WholePaper.tangentSplitNormalizedTotalRequestUpper
#print axioms Erdos390.WholePaper.tangentSplitNormalizedLabelRequestUpper
#print axioms Erdos390.WholePaper.tangentSplitNormalizedTotalRequestCount_le_upper
#print axioms Erdos390.WholePaper.tangentSplitNormalizedRequestLabelLoad_le_upper
#print axioms Erdos390.WholePaper.tangentSplitCensusTotalRequestUpper
#print axioms Erdos390.WholePaper.tangentSplitCensusLabelRequestUpper
#print axioms Erdos390.WholePaper.cast_tangentSplitTotalRequestCount_le_census
#print axioms Erdos390.WholePaper.cast_tangentSplitRequestLabelLoad_le_census
#print axioms Erdos390.WholePaper.tangentSplitNormalizedTotalRequestCount_le_census
#print axioms Erdos390.WholePaper.tangentSplitNormalizedRequestLabelLoad_le_census
#print axioms Erdos390.WholePaper.tangentSplitNormalizedCollisionFlowBudget
#print axioms Erdos390.WholePaper.tangentSplitNormalizedCollisionCensusBudget
#print axioms Erdos390.WholePaper.tangentSplitNormalizedCollisionFlowBudget_le_censusBudget
#print axioms Erdos390.WholePaper.tangentSplitRequestCollisionMass_le_normalizedFlowBudget
#print axioms Erdos390.WholePaper.tangentSplitRequestCollisionMass_le_normalizedCensusBudget
#print axioms Erdos390.WholePaper.tangentCleanSplitRequestCollisionMass_le_normalizedFlowBudget
#print axioms Erdos390.WholePaper.tangentCleanSplitRequestCollisionMass_le_eighth_of_flowBudget
#print axioms Erdos390.WholePaper.tangentCleanSplitRequestCollisionMass_le_eighth_of_censusBudget
#print axioms Erdos390.WholePaper.tangentSplitEndpointsDistinct_of_normalizedFlowBudget
#print axioms Erdos390.WholePaper.tangentSplitEndpointsDistinct_of_normalizedCensusBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperSplitRequest_sharp_finite_deletion_ledger
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperSplitEndpointsDistinct_of_normalizedFlowBudget
#print axioms Erdos390.WholePaper.BankPaperRealization.tangentPaperSplitEndpointsDistinct_of_normalizedCensusBudget

assert_no_sorry Erdos390.WholePaper.tangentIncidentSplitRequestEquiv
assert_no_sorry Erdos390.WholePaper.tangentSplitTotalRequestCount_eq_requestTotal
assert_no_sorry Erdos390.WholePaper.tangentSplitRequestLabelLoad_eq_incidentRequestCount
assert_no_sorry Erdos390.WholePaper.tangentSupportDegree_le_edges_card
assert_no_sorry Erdos390.WholePaper.tangentIncidentFlowMass_le_totalFlowMass
assert_no_sorry Erdos390.WholePaper.tangentPositiveFlowEdges
assert_no_sorry Erdos390.WholePaper.mem_tangentPositiveFlowEdges
assert_no_sorry Erdos390.WholePaper.sum_tangentPositiveFlowEdges_eq_traffic
assert_no_sorry Erdos390.WholePaper.tangentSplitTotalRequestUpper
assert_no_sorry Erdos390.WholePaper.tangentSplitLabelRequestUpper
assert_no_sorry Erdos390.WholePaper.cast_tangentSplitTotalRequestCount_le_upper
assert_no_sorry Erdos390.WholePaper.cast_tangentSplitRequestLabelLoad_le_upper
assert_no_sorry Erdos390.WholePaper.cast_tangentSplitRequestLabelLoad_le_totalFlowMass
assert_no_sorry Erdos390.WholePaper.cast_tangentPositiveFlowTotalRequestCount_le_traffic
assert_no_sorry Erdos390.WholePaper.cast_tangentPositiveFlowRequestLabelLoad_le_traffic
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedTotalRequestUpper
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedLabelRequestUpper
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedTotalRequestCount_le_upper
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedRequestLabelLoad_le_upper
assert_no_sorry Erdos390.WholePaper.tangentSplitCensusTotalRequestUpper
assert_no_sorry Erdos390.WholePaper.tangentSplitCensusLabelRequestUpper
assert_no_sorry Erdos390.WholePaper.cast_tangentSplitTotalRequestCount_le_census
assert_no_sorry Erdos390.WholePaper.cast_tangentSplitRequestLabelLoad_le_census
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedTotalRequestCount_le_census
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedRequestLabelLoad_le_census
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedCollisionFlowBudget
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedCollisionCensusBudget
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedCollisionFlowBudget_le_censusBudget
assert_no_sorry Erdos390.WholePaper.tangentSplitRequestCollisionMass_le_normalizedFlowBudget
assert_no_sorry Erdos390.WholePaper.tangentSplitRequestCollisionMass_le_normalizedCensusBudget
assert_no_sorry Erdos390.WholePaper.tangentCleanSplitRequestCollisionMass_le_normalizedFlowBudget
assert_no_sorry Erdos390.WholePaper.tangentCleanSplitRequestCollisionMass_le_eighth_of_flowBudget
assert_no_sorry Erdos390.WholePaper.tangentCleanSplitRequestCollisionMass_le_eighth_of_censusBudget
assert_no_sorry Erdos390.WholePaper.tangentSplitEndpointsDistinct_of_normalizedFlowBudget
assert_no_sorry Erdos390.WholePaper.tangentSplitEndpointsDistinct_of_normalizedCensusBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperSplitRequest_sharp_finite_deletion_ledger
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperSplitEndpointsDistinct_of_normalizedFlowBudget
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.tangentPaperSplitEndpointsDistinct_of_normalizedCensusBudget
