import Erdos390.WholePaper.TangentPairArithmetic
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for tangent pair arithmetic -/

#print axioms Erdos390.WholePaper.tangentDensityDisjointCoefficient
#print axioms Erdos390.WholePaper.tangentDensitySharedCoefficient
#print axioms Erdos390.WholePaper.tangentDensityDisjointCoefficient_nonneg
#print axioms Erdos390.WholePaper.tangentDensitySharedCoefficient_nonneg
#print axioms Erdos390.WholePaper.tangentBroadUpper_le_two_mul
#print axioms Erdos390.WholePaper.cast_tangentEndpointEquationBudget_le_of_ne
#print axioms Erdos390.WholePaper.cast_tangentEndpointEquationBudget_le_of_eq
#print axioms Erdos390.WholePaper.tangentOrderedPairEndpointBudget_div_le_charges_of_equationBounds
#print axioms Erdos390.WholePaper.tangentEndpointLowerScale_of_maxLower
#print axioms Erdos390.WholePaper.tangentOrderedPairEndpointBudget_div_le_densityCoefficients
#print axioms Erdos390.WholePaper.tangentDensityCollisionBudget_le_eighth
#print axioms Erdos390.WholePaper.tangentSplitNormalizedCollisionCensusBudget_le_eighth_of_density

assert_no_sorry Erdos390.WholePaper.tangentDensityDisjointCoefficient
assert_no_sorry Erdos390.WholePaper.tangentDensitySharedCoefficient
assert_no_sorry Erdos390.WholePaper.tangentDensityDisjointCoefficient_nonneg
assert_no_sorry Erdos390.WholePaper.tangentDensitySharedCoefficient_nonneg
assert_no_sorry Erdos390.WholePaper.tangentBroadUpper_le_two_mul
assert_no_sorry Erdos390.WholePaper.cast_tangentEndpointEquationBudget_le_of_ne
assert_no_sorry Erdos390.WholePaper.cast_tangentEndpointEquationBudget_le_of_eq
assert_no_sorry Erdos390.WholePaper.tangentOrderedPairEndpointBudget_div_le_charges_of_equationBounds
assert_no_sorry Erdos390.WholePaper.tangentEndpointLowerScale_of_maxLower
assert_no_sorry Erdos390.WholePaper.tangentOrderedPairEndpointBudget_div_le_densityCoefficients
assert_no_sorry Erdos390.WholePaper.tangentDensityCollisionBudget_le_eighth
assert_no_sorry Erdos390.WholePaper.tangentSplitNormalizedCollisionCensusBudget_le_eighth_of_density
