import Erdos390.WholePaper.TangentCanonicalCleanListLower
import Mathlib.Util.AssertNoSorry

/-! # Assumption audit for the canonical tangent clean-list lower bound -/

#print axioms Erdos390.WholePaper.tangentRoughHeadCandidateLower_le_card
#print axioms Erdos390.WholePaper.eventually_tangentExceptionalMultipliers_card_cast_le_canonicalUpper
#print axioms Erdos390.WholePaper.eventually_tangentExceptionalMultipliers_card_le_canonicalNatUpper
#print axioms Erdos390.WholePaper.tangentCanonicalExceptionalRemainder_normalized_le
#print axioms Erdos390.WholePaper.tangentEffectiveLowerCard_scale
#print axioms Erdos390.WholePaper.eventually_tangentExceptionalMultipliers_card_le_canonicalNatUpper_yNat
#print axioms Erdos390.WholePaper.eventually_tangentCleanCommonMultiplierList_card_lower_canonical
#print axioms Erdos390.WholePaper.BankPaperRealization.eventually_tangentPaperCleanCommonMultiplierList_card_lower_canonical

assert_no_sorry Erdos390.WholePaper.tangentRoughHeadCandidateLower_le_card
assert_no_sorry Erdos390.WholePaper.eventually_tangentExceptionalMultipliers_card_cast_le_canonicalUpper
assert_no_sorry Erdos390.WholePaper.eventually_tangentExceptionalMultipliers_card_le_canonicalNatUpper
assert_no_sorry Erdos390.WholePaper.tangentCanonicalExceptionalRemainder_normalized_le
assert_no_sorry Erdos390.WholePaper.tangentEffectiveLowerCard_scale
assert_no_sorry Erdos390.WholePaper.eventually_tangentExceptionalMultipliers_card_le_canonicalNatUpper_yNat
assert_no_sorry Erdos390.WholePaper.eventually_tangentCleanCommonMultiplierList_card_lower_canonical
assert_no_sorry Erdos390.WholePaper.BankPaperRealization.eventually_tangentPaperCleanCommonMultiplierList_card_lower_canonical
